### PR TITLE
config: Make remote-write required for Agent mode

### LINKED ISSUE #9611: Agent: Add validation that fails agent if no remote write is configured.
cc @rfratto

### PR DESCRIPTION
**Pull request by ArthurSens**
Makes remote-write a requirement for Prometheus running in Agent mode.

Expected behaviors:
* Prometheus will hard fail if started in agent mode without remote-write configuration
* Prometheus is able to run with an invalid remote-write URL. (Will log errors)
* Prometheus won't crash if reload is triggered without remote-write configuration, but won't reload(Will log error)
* Promtool is able to check config files in agent mode if `--agent` flag is passed.

Fixes #9611

### CODE REVIEW

**Comment by ArthurSens** [comment]
I think I just need to add a test for this and it should be good to go 🙂

File: cmd/promtool/main.go [hunk 1]
```diff
@@ -56,6 +56,8 @@ import (
 	"github.com/prometheus/prometheus/scrape"
 )
 
+var agentMode bool
```
Comment (roidelapluie) [inline cmd/promtool/main.go:59]: The global variable does not seem to be useful.

File: cmd/prometheus/main.go [hunk 2]
```diff
@@ -1162,7 +1162,7 @@ func reloadConfig(filename string, expandExternalLabels bool, enableExemplarStor
 		}
 	}()
 
-	conf, err := config.LoadFile(filename, expandExternalLabels, logger)
+	conf, err := config.LoadFile(filename, expandExternalLabels, logger, agentMode)
```
Comment (roidelapluie) [inline cmd/prometheus/main.go:1165]: can we have agent mode in second position?

File: config/config.go [hunk 3]
```diff
@@ -108,6 +108,11 @@ func LoadFile(filename string, expandExternalLabels bool, logger log.Logger) (*C
 	if err != nil {
 		return nil, errors.Wrapf(err, "parsing YAML file %s", filename)
 	}
+
+	if agentMode && len(cfg.RemoteWriteConfigs) == 0 {
+		return nil, errors.New("remote-write required in agent mode")
+	}
```
Comment (roidelapluie) [inline config/config.go:114]: We can also error if rule_files or alerting is set.

**Review by roidelapluie — COMMENTED** [review]
Thanks Arthur :)

File: documentation/examples/prometheus-agent.yml [hunk 4]
```diff
@@ -0,0 +1,22 @@
+# my global config
+global:
+  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
+  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
```
Comment (ArthurSens) [inline documentation/examples/prometheus-agent.yml:4]: Hmmm, since there is no rule evaluation, should `evaluation_interval` also be a reason for failure? 🤔

Comment (roidelapluie) [reply documentation/examples/prometheus-agent.yml:4]: I don't think we should go that far

**Comment by roidelapluie** [comment]
Thank you.

I think we should have actionnable error messages:

`field alerting not allowed in agent mode`
`field remote_read not allowed in agent mode`
`field rule_files is not allowed in agent mode`

and

`at least one remote_write target must be specified in agent mode`

**Comment by ArthurSens** [comment]
I think I've addressed everything! Thanks for the review, by the way. 

This is the first time I'm getting my head around the agent so your hints regarding all other requirements besides the remote-write were very much appreciated :)

**Review by roidelapluie — APPROVED** [review]
