### PR TITLE
Fix 'chunks.HeadReadWriter: maxt of the files are not set' error

### LINKED ISSUE #7753: Compaction failing with "reload blocks: head truncate failed: truncate chunks.HeadReadWriter: maxt of the files are not set" after running out of disk.
**What did you do?**
Prometheus' PV ran out of disk. Since expanding the volume it has not been able to compact and has caused the WAL to grown significantly. 

**What did you expect to see?**
Compaction succeed.

**What did you see instead? Under which circumstances?**
```
level=info ts=2020-08-05T19:53:11.276Z caller=compact.go:495 component=tsdb msg="write block" mint=1596196800000 maxt=1596204000000 ulid=01EF02VSNNYSFMVJMD6ANFZNBE duration=1m30.807383762s
level=info ts=2020-08-05T19:53:27.859Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=4.785877467s
level=error ts=2020-08-05T19:53:27.859Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: truncate chunks.HeadReadWriter: maxt of the files are not set"
```

**Environment**

* System information:

`Linux 4.14.177-139.254.amzn2.x86_64 x86_64`

* Prometheus version:

```
/bin $ prometheus --version
prometheus, version 2.19.3 (branch: HEAD, revision: 657ba532e42f1db8d7c77bf802378643da0d3118)
  build user:       root@b99e50bced7c
  build date:       20200724-12:20:53
  go version:       go1.14.6
```
* Alertmanager version:

	insert output of `alertmanager --version` here (if relevant to the issue)

* Prometheus configuration file:
```
insert configuration here
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
level=info ts=2020-08-05T19:53:11.276Z caller=compact.go:495 component=tsdb msg="write block" mint=1596196800000 maxt=1596204000000 ulid=01EF02VSNNYSFMVJMD6ANFZNBE duration=1m30.807383762s
level=info ts=2020-08-05T19:53:27.859Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=4.785877467s
level=error ts=2020-08-05T19:53:27.859Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: truncate chunks.HeadReadWriter: maxt of the files are not set"
level=info ts=2020-08-05T19:54:45.604Z caller=compact.go:495 component=tsdb msg="write block" mint=1596204000000 maxt=1596211200000 ulid=01EF02Z3GVGXY4WWSD90RPD30Y duration=1m16.745163355s
level=info ts=2020-08-05T19:55:01.976Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=4.669319115s
level=error ts=2020-08-05T19:55:01.976Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: truncate chunks.HeadReadWriter: maxt of the files are not set"
level=info ts=2020-08-05T19:56:18.381Z caller=compact.go:495 component=tsdb msg="write block" mint=1596211200000 maxt=1596218400000 ulid=01EF0320D86GV9KY6R8DN9B2T8 duration=1m14.404863455s
level=info ts=2020-08-05T19:56:34.955Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=4.796791613s
level=error ts=2020-08-05T19:56:34.955Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: truncate chunks.HeadReadWriter: maxt of the files are not set"
level=info ts=2020-08-05T19:58:00.875Z caller=compact.go:495 component=tsdb msg="write block" mint=1596218400000 maxt=1596225600000 ulid=01EF034X5B6YNJ8KYPYBT92N6Z duration=1m21.919280529s
level=info ts=2020-08-05T19:58:17.466Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=4.826867639s
level=error ts=2020-08-05T19:58:17.467Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: truncate chunks.HeadReadWriter: maxt of the files are not set"
level=info ts=2020-08-05T19:59:47.263Z caller=compact.go:495 component=tsdb msg="write block" mint=1596225600000 maxt=1596232800000 ulid=01EF03855V6EB9SRKPT9ZKA114 duration=1m21.796447323s
level=info ts=2020-08-05T20:00:04.567Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=5.810357915s
level=error ts=2020-08-05T20:00:04.567Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: truncate chunks.HeadReadWriter: maxt of the files are not set"
level=info ts=2020-08-05T20:01:49.119Z caller=compact.go:495 component=tsdb msg="write block" mint=1596232800000 maxt=1596240000000 ulid=01EF03BNJQ20845XTE8QAPM4WT duration=1m28.551811148s
level=info ts=2020-08-05T20:02:07.764Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=7.103617979s
level=error ts=2020-08-05T20:02:07.764Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: truncate chunks.HeadReadWriter: maxt of the files are not set"
level=info ts=2020-08-05T20:03:58.841Z caller=compact.go:495 component=tsdb msg="write block" mint=1596240000000 maxt=1596247200000 ulid=01EF03FXGMDJ9T6GV5TFMWFFYB duration=1m19.076524283s
level=info ts=2020-08-05T20:04:14.610Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=4.551891356s
level=error ts=2020-08-05T20:04:14.611Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: truncate chunks.HeadReadWriter: maxt of the files are not set"
level=info ts=2020-08-05T20:06:41.295Z caller=compact.go:495 component=tsdb msg="write block" mint=1596247200000 maxt=1596254400000 ulid=01EF03MMQKVRMNG2505F06C88P duration=1m26.683850992s
level=info ts=2020-08-05T20:06:55.990Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=4.351650424s
level=error ts=2020-08-05T20:06:55.991Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: truncate chunks.HeadReadWriter: maxt of the files are not set"
level=info ts=2020-08-05T20:09:21.571Z caller=compact.go:495 component=tsdb msg="write block" mint=1596254400000 maxt=1596261600000 ulid=01EF03SJAQC1HZP5WJZ1FYVTTJ duration=1m25.580728185s
level=info ts=2020-08-05T20:09:37.774Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=5.485501226s
level=error ts=2020-08-05T20:09:37.774Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: truncate chunks.HeadReadWriter: maxt of the files are not set"
level=info ts=2020-08-05T20:12:02.702Z caller=compact.go:495 component=tsdb msg="write block" mint=1596261600000 maxt=1596268800000 ulid=01EF03YGAE4E61JQ8CWBVNRKE4 duration=1m24.927457486s
level=info ts=2020-08-05T20:12:17.560Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=4.70238568s
level=error ts=2020-08-05T20:12:17.561Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: truncate chunks.HeadReadWriter: maxt of the files are not set"
level=info ts=2020-08-05T20:14:43.687Z caller=compact.go:495 component=tsdb msg="write block" mint=1596268800000 maxt=1596276000000 ulid=01EF043CBS1FQ3DWHNVGZ37BNH duration=1m26.125940478s
level=info ts=2020-08-05T20:14:58.537Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=4.900787405s
level=error ts=2020-08-05T20:14:58.537Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: truncate chunks.HeadReadWriter: maxt of the files are not set"
level=info ts=2020-08-05T20:17:25.782Z caller=compact.go:495 component=tsdb msg="write block" mint=1596276000000 maxt=1596283200000 ulid=01EF0489J980MBBTW109395NYX duration=1m27.244860734s
level=info ts=2020-08-05T20:17:40.586Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=4.463465401s
level=error ts=2020-08-05T20:17:40.586Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: truncate chunks.HeadReadWriter: maxt of the files are not set"
level=info ts=2020-08-05T20:20:06.587Z caller=compact.go:495 component=tsdb msg="write block" mint=1596283200000 maxt=1596290400000 ulid=01EF04D7TAJNV35XQ8N655RA17 duration=1m26.00074054s
level=info ts=2020-08-05T20:20:21.863Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=5.335014992s
level=error ts=2020-08-05T20:20:21.863Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: truncate chunks.HeadReadWriter: maxt of the files are not set"
level=info ts=2020-08-05T20:22:50.355Z caller=compact.go:495 component=tsdb msg="write block" mint=1596290400000 maxt=1596297600000 ulid=01EF04J5A7D7WWR124EA86GM02 duration=1m28.491722267s
level=info ts=2020-08-05T20:23:05.451Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=5.172110543s
level=error ts=2020-08-05T20:23:05.452Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: truncate chunks.HeadReadWriter: maxt of the files are not set"
level=info ts=2020-08-05T20:25:30.067Z caller=compact.go:495 component=tsdb msg="write block" mint=1596297600000 maxt=1596304800000 ulid=01EF04Q52C25V2N46J8CTJK9BB duration=1m24.614694146s
level=info ts=2020-08-05T20:25:45.291Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=5.161502783s
level=error ts=2020-08-05T20:25:45.291Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: truncate chunks.HeadReadWriter: maxt of the files are not set"
level=info ts=2020-08-05T20:28:10.767Z caller=compact.go:495 component=tsdb msg="write block" mint=1596304800000 maxt=1596312000000 ulid=01EF04W15CWJ319FJ6R8HQ41P3 duration=1m25.474890938s
level=info ts=2020-08-05T20:28:25.206Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=4.765624789s
level=error ts=2020-08-05T20:28:25.207Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: truncate chunks.HeadReadWriter: maxt of the files are not set"
level=info ts=2020-08-05T20:30:48.342Z caller=compact.go:495 component=tsdb msg="write block" mint=1596312000000 maxt=1596319200000 ulid=01EF050XAQS7ES5THEAGZ20FNW duration=1m23.135141138s
level=info ts=2020-08-05T20:31:02.121Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=4.353567157s
level=error ts=2020-08-05T20:31:02.121Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: truncate chunks.HeadReadWriter: maxt of the files are not set"
level=info ts=2020-08-05T20:33:26.382Z caller=compact.go:495 component=tsdb msg="write block" mint=1596319200000 maxt=1596326400000 ulid=01EF055PJ90EDPJEGVBQ09W3JN duration=1m24.260670992s
level=info ts=2020-08-05T20:33:40.691Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=4.819558846s
level=error ts=2020-08-05T20:33:40.691Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: truncate chunks.HeadReadWriter: maxt of the files are not set"
level=info ts=2020-08-05T20:36:04.345Z caller=compact.go:495 component=tsdb msg="write block" mint=1596326400000 maxt=1596333600000 ulid=01EF05AHDK1X7DH4X2VVCM74X1 duration=1m23.653743418s
level=info ts=2020-08-05T20:36:18.018Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=4.374772607s
level=error ts=2020-08-05T20:36:18.018Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: truncate chunks.HeadReadWriter: maxt of the files are not set"
level=info ts=2020-08-05T20:38:41.409Z caller=compact.go:495 component=tsdb msg="write block" mint=1596333600000 maxt=1596340800000 ulid=01EF05FB22X6QWB0R1Z50JAQ2P duration=1m23.390583285s
level=info ts=2020-08-05T20:38:54.579Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=4.342844915s
level=error ts=2020-08-05T20:38:54.579Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: truncate chunks.HeadReadWriter: maxt of the files are not set"
level=info ts=2020-08-05T20:41:20.470Z caller=compact.go:495 component=tsdb msg="write block" mint=1596340800000 maxt=1596348000000 ulid=01EF05M3YMM2HRKPVA26YDDQSV duration=1m25.890907622s
level=info ts=2020-08-05T20:41:34.144Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=4.689668197s
level=error ts=2020-08-05T20:41:34.144Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: truncate chunks.HeadReadWriter: maxt of the files are not set"
level=info ts=2020-08-05T20:43:56.460Z caller=compact.go:495 component=tsdb msg="write block" mint=1596348000000 maxt=1596355200000 ulid=01EF05RZS0XVEKE90ZRK8EM5EZ duration=1m22.315554241s
level=info ts=2020-08-05T20:44:10.135Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=4.314395882s
level=error ts=2020-08-05T20:44:10.135Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: truncate chunks.HeadReadWriter: maxt of the files are not set"
level=info ts=2020-08-05T20:46:33.892Z caller=compact.go:495 component=tsdb msg="write block" mint=1596355200000 maxt=1596362400000 ulid=01EF05XR3QN9RSQ4K1QTMBXK18 duration=1m23.756389586s
level=info ts=2020-08-05T20:46:47.173Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=4.426261455s
level=error ts=2020-08-05T20:46:47.174Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: truncate chunks.HeadReadWriter: maxt of the files are not set"
level=info ts=2020-08-05T20:49:10.190Z caller=compact.go:495 component=tsdb msg="write block" mint=1596362400000 maxt=1596369600000 ulid=01EF062HF6VPRHC0CGQ933EWZX duration=1m23.01603619s
level=info ts=2020-08-05T20:49:23.327Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=4.466244161s
level=error ts=2020-08-05T20:49:23.327Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: truncate chunks.HeadReadWriter: maxt of the files are not set"
level=info ts=2020-08-05T20:51:45.058Z caller=compact.go:495 component=tsdb msg="write block" mint=1596369600000 maxt=1596376800000 ulid=01EF0679YZA6HWVAD25H22KMMA duration=1m21.730924824s
level=info ts=2020-08-05T20:51:59.968Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=6.3762643s
level=error ts=2020-08-05T20:51:59.968Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: truncate chunks.HeadReadWriter: maxt of the files are not set"
level=info ts=2020-08-05T20:54:02.927Z caller=compact.go:495 component=tsdb msg="write block" mint=1596376800000 maxt=1596384000000 ulid=01EF06C2Y08JN84H73CXRRBWQ0 duration=1m2.958514367s
level=info ts=2020-08-05T20:54:14.951Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=4.283839042s
level=error ts=2020-08-05T20:54:14.951Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: truncate chunks.HeadReadWriter: maxt of the files are not set"
level=info ts=2020-08-05T20:56:29.503Z caller=compact.go:495 component=tsdb msg="write block" mint=1596384000000 maxt=1596391200000 ulid=01EF06G6R8DBDWXM086GCK6V3Q duration=1m14.551482023s
level=info ts=2020-08-05T20:56:42.732Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=5.485278728s
level=error ts=2020-08-05T20:56:42.732Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: truncate chunks.HeadReadWriter: maxt of the files are not set"
level=info ts=2020-08-05T20:58:51.266Z caller=compact.go:495 component=tsdb msg="write block" mint=1596391200000 maxt=1596398400000 ulid=01EF06MQ2CKZ6ZTZB2BZ57FS1N duration=1m8.533207287s
level=info ts=2020-08-05T20:59:03.297Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=4.909989808s
level=error ts=2020-08-05T20:59:03.297Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: truncate chunks.HeadReadWriter: maxt of the files are not set"
level=info ts=2020-08-05T21:01:04.725Z caller=compact.go:495 component=tsdb msg="write block" mint=1596398400000 maxt=1596405600000 ulid=01EF06S0B15X4ASAR4JP26A76T duration=1m1.427704891s
level=info ts=2020-08-05T21:01:14.821Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=3.329620898s
level=error ts=2020-08-05T21:01:14.822Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: truncate chunks.HeadReadWriter: maxt of the files are not set"
level=info ts=2020-08-05T21:03:07.290Z caller=compact.go:495 component=tsdb msg="write block" mint=1596405600000 maxt=1596412800000 ulid=01EF06X0S604AGNF1G6D55DV2H duration=52.468210404s
level=info ts=2020-08-05T21:03:17.397Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=3.349731258s
level=error ts=2020-08-05T21:03:17.397Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: truncate chunks.HeadReadWriter: maxt of the files are not set"
level=info ts=2020-08-05T21:05:10.813Z caller=compact.go:495 component=tsdb msg="write block" mint=1596412800000 maxt=1596420000000 ulid=01EF070RFPFVWWMJMK3WYYD4EC duration=53.414916043s
level=info ts=2020-08-05T21:05:21.051Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=3.463317683s
level=error ts=2020-08-05T21:05:21.051Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: truncate chunks.HeadReadWriter: maxt of the files are not set"
level=info ts=2020-08-05T21:07:14.085Z caller=compact.go:495 component=tsdb msg="write block" mint=1596420000000 maxt=1596427200000 ulid=01EF074H7VV7S5NB0EY9GKZ2W7 duration=53.033248323s
level=info ts=2020-08-05T21:07:23.682Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=3.166190023s
level=error ts=2020-08-05T21:07:23.682Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: truncate chunks.HeadReadWriter: maxt of the files are not set"
level=info ts=2020-08-05T21:09:14.721Z caller=compact.go:495 component=tsdb msg="write block" mint=1596427200000 maxt=1596434400000 ulid=01EF0789034QSG8PNKP4NYZ5W9 duration=51.038772579s
level=info ts=2020-08-05T21:09:24.386Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=3.586369126s
level=error ts=2020-08-05T21:09:24.386Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: truncate chunks.HeadReadWriter: maxt of the files are not set"
level=info ts=2020-08-05T21:11:15.077Z caller=compact.go:495 component=tsdb msg="write block" mint=1596434400000 maxt=1596441600000 ulid=01EF07BYW21KS133N265YP5GTT duration=50.690633246s
level=info ts=2020-08-05T21:11:24.561Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=3.174515689s
level=error ts=2020-08-05T21:11:24.561Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: truncate chunks.HeadReadWriter: maxt of the files are not set"
level=info ts=2020-08-05T21:13:17.288Z caller=compact.go:495 component=tsdb msg="write block" mint=1596441600000 maxt=1596448800000 ulid=01EF07FM7HDTTV8B8XY60AQW25 duration=52.726657288s
level=info ts=2020-08-05T21:13:26.921Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=3.348811831s
level=error ts=2020-08-05T21:13:26.921Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: truncate chunks.HeadReadWriter: maxt of the files are not set"
level=info ts=2020-08-05T21:15:17.942Z caller=compact.go:495 component=tsdb msg="write block" mint=1596448800000 maxt=1596456000000 ulid=01EF07KBQ9VG5HD5FEX9DASYJQ duration=51.02108194s
level=info ts=2020-08-05T21:15:27.674Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=3.412658147s
level=error ts=2020-08-05T21:15:27.675Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: truncate chunks.HeadReadWriter: maxt of the files are not set"
level=info ts=2020-08-05T21:17:18.198Z caller=compact.go:495 component=tsdb msg="write block" mint=1596456000000 maxt=1596463200000 ulid=01EF07Q1MV23KX5Z9KS3B0W5QS duration=50.523420352s
level=info ts=2020-08-05T21:17:27.814Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=3.414549426s
level=error ts=2020-08-05T21:17:27.815Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: truncate chunks.HeadReadWriter: maxt of the files are not set"
level=info ts=2020-08-05T21:19:18.861Z caller=compact.go:495 component=tsdb msg="write block" mint=1596463200000 maxt=1596470400000 ulid=01EF07TPZ77DA16YKN1S17V4FY duration=51.046696109s
level=info ts=2020-08-05T21:19:28.100Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=3.337859437s
level=error ts=2020-08-05T21:19:28.100Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: truncate chunks.HeadReadWriter: maxt of the files are not set"
level=info ts=2020-08-05T21:21:19.232Z caller=compact.go:495 component=tsdb msg="write block" mint=1596470400000 maxt=1596477600000 ulid=01EF07YCE4ADNQ9Z6718HDCBGP duration=51.132148899s
level=info ts=2020-08-05T21:21:28.810Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=3.63978473s
level=error ts=2020-08-05T21:21:28.811Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: truncate chunks.HeadReadWriter: maxt of the files are not set"
level=info ts=2020-08-05T21:23:23.197Z caller=compact.go:495 component=tsdb msg="write block" mint=1596477600000 maxt=1596484800000 ulid=01EF0822ABRYBN6HAM2RCZXQTA duration=54.385914353s
level=info ts=2020-08-05T21:23:31.843Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=3.156516596s
level=error ts=2020-08-05T21:23:31.843Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: truncate chunks.HeadReadWriter: maxt of the files are not set"
level=info ts=2020-08-05T21:25:26.184Z caller=compact.go:495 component=tsdb msg="write block" mint=1596484800000 maxt=1596492000000 ulid=01EF085TF32RRA33VZDQRCHX6B duration=54.340616074s
level=info ts=2020-08-05T21:25:36.279Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=4.0670259s
level=error ts=2020-08-05T21:25:36.279Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: truncate chunks.HeadReadWriter: maxt of the files are not set"
level=info ts=2020-08-05T21:27:29.041Z caller=compact.go:495 component=tsdb msg="write block" mint=1596492000000 maxt=1596499200000 ulid=01EF089KZR0GWWHB6B265F4A60 duration=52.761459808s
level=info ts=2020-08-05T21:27:38.147Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=3.429389761s
level=error ts=2020-08-05T21:27:38.148Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: truncate chunks.HeadReadWriter: maxt of the files are not set"
level=info ts=2020-08-05T21:29:30.059Z caller=compact.go:495 component=tsdb msg="write block" mint=1596499200000 maxt=1596506400000 ulid=01EF08DB04PSXCXGGGHH0BHDED duration=51.911512545s
level=info ts=2020-08-05T21:29:38.662Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=3.011488749s
level=error ts=2020-08-05T21:29:38.662Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: truncate chunks.HeadReadWriter: maxt of the files are not set"
level=info ts=2020-08-05T21:31:30.184Z caller=compact.go:495 component=tsdb msg="write block" mint=1596506400000 maxt=1596513600000 ulid=01EF08H0P66PEJGF18VJYCDTD5 duration=51.522153391s
level=info ts=2020-08-05T21:31:38.678Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=3.227830337s
level=error ts=2020-08-05T21:31:38.678Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: truncate chunks.HeadReadWriter: maxt of the files are not set"
level=info ts=2020-08-05T21:33:29.360Z caller=compact.go:495 component=tsdb msg="write block" mint=1596513600000 maxt=1596520800000 ulid=01EF08MNWPFH3GRFYFMPR9QDE8 duration=50.681218737s
level=info ts=2020-08-05T21:33:37.852Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=3.028051369s
level=error ts=2020-08-05T21:33:37.852Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: truncate chunks.HeadReadWriter: maxt of the files are not set"
level=info ts=2020-08-05T21:35:28.945Z caller=compact.go:495 component=tsdb msg="write block" mint=1596520800000 maxt=1596528000000 ulid=01EF08RA8W2N592XA5HAR9T423 duration=51.093393706s
level=info ts=2020-08-05T21:35:37.657Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=3.321986775s
level=error ts=2020-08-05T21:35:37.657Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: truncate chunks.HeadReadWriter: maxt of the files are not set"
level=info ts=2020-08-05T21:37:29.454Z caller=compact.go:495 component=tsdb msg="write block" mint=1596528000000 maxt=1596535200000 ulid=01EF08VZ8T8RB0X518F8B1WY8J duration=51.795859078s
level=info ts=2020-08-05T21:37:38.002Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=3.285070713s
level=error ts=2020-08-05T21:37:38.002Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: truncate chunks.HeadReadWriter: maxt of the files are not set"
level=info ts=2020-08-05T21:39:39.924Z caller=compact.go:495 component=tsdb msg="write block" mint=1596535200000 maxt=1596542400000 ulid=01EF08ZMSJ9PBW8CTA1TVDX65G duration=1m1.92181733s
level=info ts=2020-08-05T21:39:48.594Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=3.869542462s
level=error ts=2020-08-05T21:39:48.594Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: truncate chunks.HeadReadWriter: maxt of the files are not set"
level=info ts=2020-08-05T21:41:56.719Z caller=compact.go:495 component=tsdb msg="write block" mint=1596542400000 maxt=1596549600000 ulid=01EF093MAJQ2RRW9RP8R23P75Z duration=1m8.124144047s
level=info ts=2020-08-05T21:42:05.563Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=4.34962086s
level=error ts=2020-08-05T21:42:05.563Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: truncate chunks.HeadReadWriter: maxt of the files are not set"
level=info ts=2020-08-05T21:44:06.355Z caller=compact.go:495 component=tsdb msg="write block" mint=1596549600000 maxt=1596556800000 ulid=01EF097T2WGSJ9H63FZGQT5DXB duration=1m0.791448198s
level=info ts=2020-08-05T21:44:13.982Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=3.658911319s
level=error ts=2020-08-05T21:44:13.982Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: truncate chunks.HeadReadWriter: maxt of the files are not set"
level=info ts=2020-08-05T21:46:29.542Z caller=compact.go:495 component=tsdb msg="write block" mint=1596556800000 maxt=1596564000000 ulid=01EF09BQFZ0X0HBPPAXX8WWAD7 duration=1m15.559808163s
level=info ts=2020-08-05T21:46:38.204Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=4.989997902s
level=error ts=2020-08-05T21:46:38.204Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: truncate chunks.HeadReadWriter: maxt of the files are not set"
level=info ts=2020-08-05T21:48:17.372Z caller=compact.go:495 component=tsdb msg="write block" mint=1596564000000 maxt=1596571200000 ulid=01EF09G4AWM2DT8NFVXRD39EE9 duration=39.167862899s
level=info ts=2020-08-05T21:48:22.129Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=1.74352872s
level=error ts=2020-08-05T21:48:22.129Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: truncate chunks.HeadReadWriter: maxt of the files are not set"
level=info ts=2020-08-05T21:50:00.971Z caller=compact.go:495 component=tsdb msg="write block" mint=1596571200000 maxt=1596578400000 ulid=01EF09K9TH7ZXEQMJQKEMAH84D duration=38.841413089s
level=info ts=2020-08-05T21:50:05.324Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=1.639332386s
level=error ts=2020-08-05T21:50:05.324Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: truncate chunks.HeadReadWriter: maxt of the files are not set"
level=info ts=2020-08-05T21:51:43.612Z caller=compact.go:495 component=tsdb msg="write block" mint=1596578400000 maxt=1596585600000 ulid=01EF09PEKCNRRNSS9DXC4QD32Y duration=38.287732487s
level=info ts=2020-08-05T21:51:47.827Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=1.537108584s
level=error ts=2020-08-05T21:51:47.828Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: truncate chunks.HeadReadWriter: maxt of the files are not set"
level=info ts=2020-08-05T21:53:25.289Z caller=compact.go:495 component=tsdb msg="write block" mint=1596585600000 maxt=1596592800000 ulid=01EF09SJPM9WN0Z548Y0SQP188 duration=37.461825256s
level=info ts=2020-08-05T21:53:29.692Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=1.9546845s
level=error ts=2020-08-05T21:53:29.693Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: truncate chunks.HeadReadWriter: maxt of the files are not set"
level=info ts=2020-08-05T21:55:06.291Z caller=compact.go:495 component=tsdb msg="write block" mint=1596592800000 maxt=1596600000000 ulid=01EF09WP5XV1N7JDB13G5GACTP duration=36.597921464s
level=info ts=2020-08-05T21:55:10.551Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=1.634177947s
level=error ts=2020-08-05T21:55:10.552Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: truncate chunks.HeadReadWriter: maxt of the files are not set"
level=info ts=2020-08-05T21:56:46.473Z caller=compact.go:495 component=tsdb msg="write block" mint=1596600000000 maxt=1596607200000 ulid=01EF09ZRNRDY3C3KYVAWGYC49T duration=35.921223676s
level=info ts=2020-08-05T21:56:50.798Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=1.978500191s
level=error ts=2020-08-05T21:56:50.798Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: truncate chunks.HeadReadWriter: maxt of the files are not set"
level=info ts=2020-08-05T21:57:57.908Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=881.792176ms
level=error ts=2020-08-05T21:57:57.908Z caller=db.go:675 component=tsdb msg="compaction failed" err="head truncate failed (in compact): truncate chunks.HeadReadWriter: maxt of the files are not set"
level=info ts=2020-08-05T21:59:05.129Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=923.515212ms
level=error ts=2020-08-05T21:59:05.129Z caller=db.go:675 component=tsdb msg="compaction failed" err="head truncate failed (in compact): truncate chunks.HeadReadWriter: maxt of the files are not set"
level=info ts=2020-08-05T22:00:12.637Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=942.508602ms
level=error ts=2020-08-05T22:00:12.637Z caller=db.go:675 component=tsdb msg="compaction failed" err="head truncate failed (in compact): truncate chunks.HeadReadWriter: maxt of the files are not set"
level=info ts=2020-08-05T22:01:19.900Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=958.200014ms
level=error ts=2020-08-05T22:01:19.900Z caller=db.go:675 component=tsdb msg="compaction failed" err="head truncate failed (in compact): truncate chunks.HeadReadWriter: maxt of the files are not set"
level=info ts=2020-08-05T22:02:27.001Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=940.483145ms
level=error ts=2020-08-05T22:02:27.001Z caller=db.go:675 component=tsdb msg="compaction failed" err="head truncate failed (in compact): truncate chunks.HeadReadWriter: maxt of the files are not set"
level=info ts=2020-08-05T22:03:58.155Z caller=compact.go:495 component=tsdb msg="write block" mint=1596643200000 maxt=1596650400000 ulid=01EF0AD2WSBH7ZJ4CGFC5QXRT1 duration=31.153624855s
level=info ts=2020-08-05T22:04:01.788Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=1.544027198s
level=error ts=2020-08-05T22:04:01.789Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: truncate chunks.HeadReadWriter: maxt of the files are not set"
level=info ts=2020-08-05T22:05:32.128Z caller=compact.go:495 component=tsdb msg="write block" mint=1596650400000 maxt=1596657600000 ulid=01EF0AFZEXD1CE2H1DAGBBNBX0 duration=30.338982416s
level=info ts=2020-08-05T22:05:35.410Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=1.254804731s
level=error ts=2020-08-05T22:05:35.410Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: truncate chunks.HeadReadWriter: maxt of the files are not set"
level=info ts=2020-08-05T23:00:39.972Z caller=compact.go:495 component=tsdb msg="write block" mint=1596657600000 maxt=1596664800000 ulid=01EF0DMMCBTC20S55VNHCFEXBP duration=39.960603554s
level=info ts=2020-08-05T23:00:44.197Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=2.010689705s
level=error ts=2020-08-05T23:00:44.197Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: truncate chunks.HeadReadWriter: maxt of the files are not set"
level=info ts=2020-08-06T01:00:32.979Z caller=compact.go:495 component=tsdb msg="write block" mint=1596664800000 maxt=1596672000000 ulid=01EF0MGBMCF27JRRDTS24RD4V9 duration=32.96750581s
level=info ts=2020-08-06T01:00:36.286Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=1.295094636s
level=error ts=2020-08-06T01:00:36.286Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: truncate chunks.HeadReadWriter: maxt of the files are not set"
level=info ts=2020-08-06T03:00:32.641Z caller=compact.go:495 component=tsdb msg="write block" mint=1596672000000 maxt=1596679200000 ulid=01EF0VC2WCYFTZFP5K7VHDJTQ6 duration=32.6294486s
level=info ts=2020-08-06T03:00:35.630Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=1.19888433s
level=error ts=2020-08-06T03:00:35.630Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: truncate chunks.HeadReadWriter: maxt of the files are not set"
level=info ts=2020-08-06T05:00:31.876Z caller=compact.go:495 component=tsdb msg="write block" mint=1596679200000 maxt=1596686400000 ulid=01EF127T4BDP1M95DXNZK3GYZC duration=31.865363489s
level=info ts=2020-08-06T05:00:35.164Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=1.258602008s
level=error ts=2020-08-06T05:00:35.164Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: truncate chunks.HeadReadWriter: maxt of the files are not set"
level=info ts=2020-08-06T07:00:32.606Z caller=compact.go:495 component=tsdb msg="write block" mint=1596686400000 maxt=1596693600000 ulid=01EF193HCBMJ01736PA2X6NX49 duration=32.594766481s
level=info ts=2020-08-06T07:00:35.954Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=1.349864616s
level=error ts=2020-08-06T07:00:35.955Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: truncate chunks.HeadReadWriter: maxt of the files are not set"
level=info ts=2020-08-06T09:00:32.406Z caller=compact.go:495 component=tsdb msg="write block" mint=1596693600000 maxt=1596700800000 ulid=01EF1FZ8MA7NKP4VM8X85DQSST duration=32.395919607s
level=info ts=2020-08-06T09:00:35.556Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=1.33599727s
level=error ts=2020-08-06T09:00:35.556Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: truncate chunks.HeadReadWriter: maxt of the files are not set"
level=info ts=2020-08-06T11:00:32.718Z caller=compact.go:495 component=tsdb msg="write block" mint=1596700800000 maxt=1596708000000 ulid=01EF1PTZWCHAYXWQYNSWNE39HF duration=32.706716531s
level=info ts=2020-08-06T11:00:35.782Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=1.224633923s
level=error ts=2020-08-06T11:00:35.782Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: truncate chunks.HeadReadWriter: maxt of the files are not set"
level=info ts=2020-08-06T13:00:33.993Z caller=compact.go:495 component=tsdb msg="write block" mint=1596708000000 maxt=1596715200000 ulid=01EF1XPQ4DQ6MBTW124H8DMG6F duration=33.980051969s
level=info ts=2020-08-06T13:00:37.226Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=1.306963996s
level=error ts=2020-08-06T13:00:37.226Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: truncate chunks.HeadReadWriter: maxt of the files are not set"
```

### PR DESCRIPTION
**Pull request by codesome**
Fixes #7753

This is in addition to #7855. While #7855 is an enhancement, this PR would fix #7753 entirely.

### CODE REVIEW

**Comment by codesome** [comment]
cc @roidelapluie, ideally should go in 2.21

**Comment by roidelapluie** [comment]
Will that fix the TSDB errors in place or just prevent further issues?

**Comment by roidelapluie** [comment]
Should we have a test for this?

**Comment by codesome** [comment]
It will fix the `chunks.HeadReadWriter: maxt of the files are not set` errors

**Comment by roidelapluie** [comment]
> It will fix the `chunks.HeadReadWriter: maxt of the files are not set` errors

The people experiencing the bug, do they need to delete their chuncks_head?

**Comment by codesome** [comment]
> Should we have a test for this?

Adding

**Comment by codesome** [comment]
> The people experiencing the bug, do they need to delete their chuncks_head?

Nope, just upgrade

**Comment by codesome** [comment]
I have added the test for this

File: tsdb/head.go [hunk 1]
```diff
@@ -652,7 +652,7 @@ func (h *Head) Init(minValidTime int64) error {
 		}
 		// If this fails, data will be recovered from WAL.
 		// Hence we wont lose any data (given WAL is not corrupt).
-		h.removeCorruptedMmappedChunks(err)
+		mmappedChunks = h.removeCorruptedMmappedChunks(err)
```
Comment (bwplotka) [inline tsdb/head.go:655]: The main fix is here as far as I can see (:

File: tsdb/chunks/head_chunks.go [hunk 2]
```diff
@@ -539,9 +539,7 @@ func (cdm *ChunkDiskMapper) IterateAllChunks(f func(seriesRef, chunkRef uint64,
 	defer cdm.writePathMtx.Unlock()
 
 	defer func() {
-		if err == nil {
-			cdm.fileMaxtSet = true
-		}
+		cdm.fileMaxtSet = true
```
Comment (bwplotka) [inline tsdb/chunks/head_chunks.go:542]: Can you elaborate why this is changed? Not sure

**Review by bwplotka — APPROVED** [review]
LGTM, but curious about this defer change can you explain? :thinking: 
Why we have this var then if it's always set to true

**Comment by codesome** [comment]
> Why we have this var then if it's always set to true

To make sure `IterateAllChunks` is called _at least once_

File: tsdb/head.go (hunk 1 above)
Comment (codesome) [reply tsdb/head.go:655]: While this is a needed fix, it is fine if we missed updating this map, as samples will be recovered from the WAL if no m-mapped chunks.

File: tsdb/chunks/head_chunks.go (hunk 2 above)
Comment (codesome) [reply tsdb/chunks/head_chunks.go:542]: We only want to make sure that `IterateAllChunks` was called at least once. Errors are fine here as the `Head` recovers from it (either calls repair on this or skips m-mapped chunks as there is data in WAL).

Head skipping m-map chunks and going with WAL is a possibility in case of non-corruption errors and we should be able to run compaction in that case. `Truncate()` on m-mapped chunk fails during compaction if this is not set to true in case of error.

**Comment by bwplotka** [comment]
Even if it's error?

**Comment by codesome** [comment]
> Even if it's error?

Yes. Head will initiate repair/truncate from the point error/corruption occured, so, maxt of files is set till the relevant place even in case of error.

**Comment by roidelapluie** [comment]
Thanks!
