### PR TITLE
fix(scaleway-sd): use public IPs if no private IP present

### LINKED ISSUE #13940: discovery(scaleway): instances without private IPs are not added to the target lists
### What did you do?

We are using Scaleway instances with routed IPs. Due to how routed IPs work, [those instances have no private IPs](https://www.scaleway.com/en/docs/compute/instances/api-cli/using-routed-ips/#routed-ips-overview).
The documentation says that the Scaleway SD uses the public IPv4 address by default. We have relabelled the instances to use their public IPv4 instead.

### What did you expect to see?

We expect our instances with routed IPs to show up in Scaleway's service discovery with their public IP as addresses.

### What did you see instead? Under which circumstances?

Instances with routed IPs (and therefor no private IPs) are not listed at all.

### System information

Linux 5.15.150.1-microsoft-standard-WSL2 x86_64

### Prometheus version

```text
prometheus, version 2.51.2 (branch: main, revision: b938bbc11169dc224c103bec32a55daad0f3f34e)
  build user:       root@desktop
  build date:       20240416-17:19:29
  go version:       go1.22.0
  platform:         linux/amd64
  tags:             netgo,builtinassets,stringlabels
```

### Prometheus configuration file

```yaml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: scaleway
    scaleway_sd_configs:
      - role: instance
        project_id: 11111111-1111-1111-1111-111111111111
        access_key: SCWXXXXXXXXXXXXXXXXX
        secret_key: 11111111-1111-1111-1111-111111111111

    relabel_configs:
      - source_labels: [ __meta_scaleway_instance_public_ipv4 ]
        replacement: "${1}:9090"
        target_label: __address__
```

### Alertmanager version

_No response_

### Alertmanager configuration file

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by Heyoxe**
In the Scaleway service discovery, use the instance's public IP if no private IP is available.

Fixes #13940 

@bboreham

### CODE REVIEW

**Review by bboreham — APPROVED** [review]
Lgtm

File: discovery/scaleway/instance.go [hunk 1]
```diff
@@ -174,20 +174,24 @@ func (d *instanceDiscovery) refresh(ctx context.Context) ([]*targetgroup.Group,
...
+			addr = net.JoinHostPort(server.PublicIP.Address.String(), strconv.FormatUint(uint64(d.port), 10))
 		}
 
 		if server.PrivateIP != nil {
 			labels[instancePrivateIPv4Label] = model.LabelValue(*server.PrivateIP)
+			addr = net.JoinHostPort(*server.PrivateIP, strconv.FormatUint(uint64(d.port), 10))
+		}
 
-			addr := net.JoinHostPort(*server.PrivateIP, strconv.FormatUint(uint64(d.port), 10))
+		if addr != "" {
```
Comment (machine424) [inline discovery/scaleway/instance.go:193]: Thanks.

I'm not familiar with the API, but is it possible for the pointers to be not nil but point to the empty string? If that is possible, then this changes the behavior a little bit, as it would have been possible, before, for `model.AddressLabel` to be set to `""` but now we completely skip setting that label if it's the case, I'm not sure if it's ok.

Adding a test for this would be great especially to enforce the use case and avoid regressions.

I think we'll need to adjust the doc now https://github.com/prometheus/prometheus/blob/b938bbc11169dc224c103bec32a55daad0f3f34e/docs/configuration/configuration.md?plain=1#L2952 to inform that we try other addresses.

**Review by machine424 — CHANGES_REQUESTED** [review]

File: discovery/scaleway/instance.go (hunk 1 above)
Comment (machine424) [reply discovery/scaleway/instance.go]: I think so. Yes, add the case to TestScalewayInstanceRefresh should do it.

**Review by bboreham — APPROVED** [review]
lgtm again
