### PR TITLE
Close DB in Agent tests

### LINKED ISSUE #9621: Tests are failing on windows
```
== RUN   TestCommit
    db_test.go:78: 
        	Error Trace:	db_test.go:78
        	            				testing.go:912
        	            				testing.go:1049
        	            				testing.go:1253
        	Error:      	Received unexpected error:
        	            	remove C:\Users\circleci\AppData\Local\Temp\TestCommit4080017690\wal\00000000: The process cannot access the file because it is being used by another process.
```

This seems new since the CircleCI incident. maybe they upgraded the windows version?

### PR DESCRIPTION
**Pull request by LeviHarrison**
The DB wasn't being closed in most of the tests in `agent/db_test.go`, causing an error when removing the data directory.

Fixes #9621

### CODE REVIEW

File: tsdb/agent/db_test.go [hunk 1]
```diff
@@ -45,10 +45,10 @@ func TestUnsupported(t *testing.T) {
 	logger := log.NewNopLogger()
 
 	s, err := Open(logger, prometheus.DefaultRegisterer, nil, promAgentDir, opts)
-	if err != nil {
-		t.Fatalf("unable to create storage for the agent: %v", err)
-	}
-	defer s.Close()
+	require.NoError(t, err)
```
Comment (LeviHarrison) [inline tsdb/agent/db_test.go:48]: It can be assumed that this error was because the storage couldn't be created, so I went ahead and simplified the error checks.

**Comment by LeviHarrison** [comment]
I've been able to squash most of the errors but there are still two remaining.

**Comment by roidelapluie** [comment]
cc @rfratto for awareness

File: tsdb/agent/db_test.go [hunk 2]
```diff
@@ -109,15 +110,16 @@ func TestCommit(t *testing.T) {
...
 
-	s, err = Open(logger, nil, remoteStorage, promAgentDir, opts)
-	if err != nil {
-		t.Fatalf("unable to create storage for the agent: %v", err)
-	}
+	s1, err := Open(logger, nil, remoteStorage, promAgentDir, opts)
+	require.NoError(t, err)
+	defer func() {
+		require.NoError(t, s1.Close())
+	}()
```
Comment (rfratto) [inline tsdb/agent/db_test.go:117]: I'm not actually sure why the tests here were re-opening the WAL (they came from grafana#22 and I didn't notice that this was happening initially). I ran into this in #9623 and removed the duplicate opens. 

Doing the same here might help remove the need for the `defer func()`, maybe?

Comment (rfratto) [reply tsdb/agent/db_test.go:117]: (that is, I think a lot of the problem is that these tests are opening the DB twice when they don't need to)

Comment (rfratto) [reply tsdb/agent/db_test.go:117]: @spaparaju Do you happen to remember why the tests were doing this?

Comment (spaparaju) [reply tsdb/agent/db_test.go:117]: @rfratto I see some disconnect here. Currently at the Prometheus main branch, I could not see the agent tests (`/tsdb/agent/storage_test.go` file is missing) that I included as part of these two PRs ([first](https://github.com/grafana/prometheus/pull/22/files), [second](https://github.com/grafana/prometheus/pull/24/files)).

**Comment by roidelapluie** [comment]
pushed another fix attempt

File: tsdb/agent/db_test.go [hunk 3]
```diff
@@ -108,16 +102,20 @@ func TestCommit(t *testing.T) {
...
 
 	var dec record.Decoder
 
 	if err == nil {
-		sr, err := wal.NewSegmentsReader(s.wal.Dir())
+		sr, err := wal.NewSegmentsReader(s1.wal.Dir())
```
Comment (codesome) [inline tsdb/agent/db_test.go:118]: This seems to be missing a Close()

File: tsdb/agent/db_test.go [hunk 4]
```diff
@@ -72,22 +66,22 @@ func TestCommit(t *testing.T) {
...
+	promAgentDir := t.TempDir()
 
 	lbls := labelsForTest(t.Name(), numSeries)
 	opts := DefaultOptions()
 	logger := log.NewNopLogger()
 	reg := prometheus.NewRegistry()
 	remoteStorage := remote.NewStorage(log.With(logger, "component", "remote"), reg, startTime, promAgentDir, time.Second*30, nil)
+	defer func() {
+		require.NoError(t, remoteStorage.Close())
+	}()
```
Comment (codesome) [inline tsdb/agent/db_test.go:78]: The panic is happening here because we are overwriting `remoteStorage` below, hence the double close. It will be safer to do something like this here
```go
	defer func(rs <thetype>) {
		require.NoError(t, rs.Close())
	}(remoteStorage)
```

File: tsdb/agent/db_test.go [hunk 5]
```diff
@@ -161,22 +159,22 @@ func TestRollback(t *testing.T) {
...
```
Comment (codesome) [inline tsdb/agent/db_test.go:171]: Same comment about `remoteStorage` being overwritten, hence pass `remoteStorage` as an argument to this function.

**Comment by codesome** [comment]
I attempted another fix and rebased and removed the build flags introduced in https://github.com/prometheus/prometheus/pull/9645

**Comment by roidelapluie** [comment]
Is it the same recipe  that needs to be applied to Prometheus' wal_test.go?

**Comment by codesome** [comment]
@roidelapluie not sure I understand what you mean

**Comment by roidelapluie** [comment]
> @roidelapluie not sure I understand what you mean

tsdb/wal_test.go is also excluded in windows.

**Comment by codesome** [comment]
> > @roidelapluie not sure I understand what you mean
> 
> tsdb/wal_test.go is also excluded in windows.

Ah okay, I was looking at tsdb/wal/wal_test.go :P. Yeah possible that it is the same thing, but would leave that out of this PR for now. Agent is based on tsdb/wal/wal.go and not tsdb/wal.go. The latter seems to contain some WAL repair for ealier 2.x versions.

**Review by codesome — APPROVED** [review]
Windows is :green_circle:, will merge on all :green_circle:!

**Comment by LeviHarrison** [comment]
@codesome thanks for picking this up! I've been a bit busy lately.
