### PR TITLE
Limit number of merics in prometheus UI

### LINKED ISSUE #2119: Limit number of metrics displayed in prometheus UI
IMO it's too easy to crash the browser by entering a expression returning too many elements. It should be straight forward to only display the first X elements a query returns and print a warning.
X should be really high so the limit only kicks in in cases where displaying the data would takes several gigs of memory.

### LINKED ISSUE #3321: Autocomplete on /graph interface slow with large numbers of metricnames
**What did you do?**
I have a cluster which returns ~150k names from `/api/v1/label/__name__/values`. This takes a decent amount of time for the browser to load, but then when you go to type it is slow to the point of unusable. For me at least (in both chrome and firefox) after I finish typing 2 characters it immediately pegs a CPU core for ~2m or so, rending the browser useless.

**What did you expect to see?**
I expect it to keep up :) A great example is from the grafana guys. They recently added ace editor support for promql (https://github.com/grafana/grafana/pull/9118) and that javascript typeahead doesn't have problems with my 150k names

### PR DESCRIPTION
**Pull request by vn-ki**
Closes #2119 
Closes #3321

Displays only first 10000 series in the UI.
If there are more than 10000 series, show a warning.

Display only the first 100 metrics in the typeahead. I chose 100 because it did not make sense to scroll beyond that in a suggestion box and can be changed in case more is required.

Make the typeahead scrollable for easy navigation of suggestions. 

Ping: @simonpasquier @codesome 

Signed-off-by: Vishnunarayan K I <appukuttancr@gmail.com>

### CODE REVIEW

File: web/ui/static/js/graph/index.js [hunk 1]
```diff
@@ -1143,6 +1145,25 @@ function escapeHTML(string) {
   });
 }
 
+function limitMetrics(result) {
+  var MAX_METRICS_NUM = 10;
```
Comment (brian-brazil) [inline web/ui/static/js/graph/index.js]: Is this the right value?

I'd suggest going with 10k, which is still a reasonable number of metrics to have.

Comment (vn-ki) [reply web/ui/static/js/graph/index.js]: @brian-brazil Done.

**Comment by codesome** [comment]
Gave a quick run. The warning doesn't go away when I query something later which fetches fewer metrics.

**Comment by vn-ki** [comment]
@codesome Fixed.

File: web/ui/static/js/graph/index.js [hunk 2]
```diff
@@ -1143,6 +1145,26 @@ function escapeHTML(string) {
...
 
+function limitMetrics(result) {
+  var MAX_METRICS_NUM = 10000;
+  var message = "<strong>Warning!</strong> Fetched " +
+    result.length + " metrics, but displaying only first " +
+    MAX_METRICS_NUM + " ones.";
+
+  if ($("#max-metrics-warning")[0]) {
+    // If message already exists
+    $("#max-metrics-warning").remove();
```
Comment (codesome) [inline web/ui/static/js/graph/index.js]: From a UX perspective, I think this should be done when you submit a query.

Comment (vn-ki) [reply web/ui/static/js/graph/index.js]: Done

Comment (vn-ki) [reply web/ui/static/js/graph/index.js]: Please don't merge it yet. I'm refactoring it a bit.

Comment (vn-ki) [reply web/ui/static/js/graph/index.js]: Done

File: web/ui/static/js/graph/index.js [hunk 3]
```diff
@@ -887,6 +903,20 @@ Prometheus.Graph.prototype.formatKMBT = function(y) {
   }
 }
 
+Prometheus.Graph.prototype.limitMetrics = function (result) {
+  var self = this;
+  var MAX_METRICS_NUM = 10000;
+  var message = "<strong>Warning!</strong> Fetched " +
+    result.length + " metrics, but displaying only first " +
+    MAX_METRICS_NUM + " ones.";
```
Comment (codesome) [inline web/ui/static/js/graph/index.js]:
```suggestion
    MAX_METRICS_NUM + ".";
```

File: web/ui/static/js/graph/index.js [hunk 4]
```diff
@@ -803,6 +817,7 @@ Prometheus.Graph.prototype.handleConsoleResponse = function(data, textStatus) {
       tBody.append("<tr><td colspan='2'><i>no data</i></td></tr>");
       return;
     }
+    data.result = self.limitMetrics(data.result);
```
Comment (juliusv) [inline web/ui/static/js/graph/index.js]: Could we change the wording from "metrics" to "series" here, since "metrics" often in most Prometheus contexts refers to a metric name or all series belonging to a given metric name. Same below in the error message.

File: web/ui/static/js/graph/index.js [hunk 5]
```diff
@@ -286,7 +287,7 @@ Prometheus.Graph.prototype.initTypeahead = function(self) {
   self.expr.typeahead({
     autoSelect: false,
     source: source,
-    items: "all",
+    items: 100,
```
Comment (juliusv) [inline web/ui/static/js/graph/index.js]: Can we make this limit higher, like 1000? When exploring metrics, I often just type e.g. `node_` in the expression input to see what exists with that prefix. But on [http://demo.robustperception.io:9090/graph?g0.range_input=1h&g0.expr=count(count%20by(__name__)%20(%7B__name__%3D~%22node_.*%22%7D))&g0.tab=1](the RobustPerception demo server), this already returns 169 different metric names. It would be possible to use the dropdown selector for some of these use cases, but that is more cumbersome.

**Comment by vn-ki** [comment]
Done @codesome @juliusv

File: web/ui/static/js/graph/index.js [hunk 6]
```diff
@@ -887,6 +903,20 @@ Prometheus.Graph.prototype.formatKMBT = function(y) {
   }
 }
 
+Prometheus.Graph.prototype.limitSeries = function (result) {
+  var self = this;
+  var MAX_METRICS_NUM = 10000;
```
Comment (juliusv) [inline web/ui/static/js/graph/index.js]: This is still "metrics" rather than "series".

File: web/ui/static/js/graph/index.js [hunk 7]
```diff
@@ -887,6 +903,20 @@ Prometheus.Graph.prototype.formatKMBT = function(y) {
   }
 }
 
+Prometheus.Graph.prototype.limitSeries = function (result) {
```
Comment (juliusv) [inline web/ui/static/js/graph/index.js]: Mini style nit: `function (result)` -> `function(result)`

Comment (vn-ki) [reply web/ui/static/js/graph/index.js]: @juliusv Done

**Comment by juliusv** [comment]
:+1: thanks!
