### PR TITLE
remote write handler: reject samples with future timestamps

### LINKED ISSUE #12006: Error "out of bounds" may disable all jobs when invalid metrics are received by remote-write
### What did you do?

Prometheus 2.39 running with `--web.enable-remote-write-receiver` to receive remote-written metrics from some other Prometheus instances and OpenTelemetry collectors in the same network.

### What did you expect to see?

If a remote machine sends invalid metrics (perhaps with grossly incorrect timestamps?), these samples should just be dropped, in the same way out of order samples are (normally) dropped by the scraper. Other jobs and sources should be unaffected.

### What did you see instead? Under which circumstances?

In some circumstances it may happen that the logs are flooded with errors like:

```
ts=2023-02-20T08:53:21.719Z caller=scrape.go:1294 level=warn component="scrape manager" scrape_pool=blackbox target=<redacted> msg="Appending scrape report failed" err="out of bounds"
ts=2023-02-20T08:53:22.795Z caller=manager.go:683 level=warn component="rule manager" <redacted> msg="Rule evaluation result discarded" err="out of bounds" sample=<redacted> => 1 @[1676883202753]"
```

At the same time,
* the `/targets` page shows most targets across all jobs down with "out of bounds" error;
* a `count(up) by (job)` query will show that most targets have completely vanished.

This is different from https://github.com/prometheus/prometheus/issues/10900 in various ways:
1) there isn't any log line containing both "Out of order sample from remote write" and "out of bounds";
2) the local clock was in sync;
3) deleting the database didn't help;
4) the error vanishes the moment the `--web.enable-remote-write-receiver` option is removed.

### System information

```
$ uname -a
Linux <redacted> 4.18.0-425.10.1.el8_7.x86_64 #1 SMP Wed Dec 14 16:00:01 EST 2022 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/*release* | head -n5
NAME="Red Hat Enterprise Linux"
VERSION="8.7 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.7"
```

### Prometheus version

```text
$ prometheus --version
prometheus, version 2.39.1 (branch: HEAD, revision: dcd6af9e0d56165c6f5c64ebbc1fae798d24933a)
  build user:       root@273d60c69592
  build date:       20221007-15:57:09
  go version:       go1.19.2
  platform:         linux/amd64
```

### Prometheus configuration file

`/etc/systemd/system/prometheus.service` includes

```
ExecStart=/usr/local/bin/prometheus \
<redacted>
  --web.enable-lifecycle \
  --web.enable-admin-api \
  --web.enable-remote-write-receiver
```

### LINKED ISSUE #13573: Wrong timestamp can break entire tsdb
### What did you do?

It looks like we found some kind of critical vulnerability related to timestamp. One of the servers sent the metric through the Prometheus agent with an incorrect timestamp **timestamp=4039374839932** (Wednesday, January 1, 2098 4:33:59 AM) . This happened because the ntp service displayed the wrong time (in fact it was a CMOS battery issue). Therefore, the agent sent the metric with this timestamp. Because of this, there was an "out of bounds" error in the logs. It looks like there is no way to block metrics with the wrong timestamp and the only thing left is to delete the entire tsdb. Deleting via curl or promtool is not helped.
Steps how we fixed it:
1. Stop prometheus
2. Add this config to prometheus.yml
`storage:
  tsdb:
    out_of_order_time_window: 75y`
3. Start prometheus
4. Check logs, find broken metrics in prometheus logs
5. Stop prometheus, fix metrics
6. Delete out_of_order_time_window parameter
7. Drop entire tsdb and start prometheus

### What did you expect to see?

Somehow block these metrics (with incorrect timestamp) or delete it via promtool/curl. After this, such metrics will not hit and break the entire database.

### What did you see instead? Under which circumstances?

1. Error "out of bound" for all targets, for instance:
`ts=2024-02-12T15:41:56.168Z caller=scrape.go:1350 level=warn component="scrape manager" scrape_pool=http-targets target=http://mydb-test-gc1:9104/metrics msg="Appending scrape report failed" err="out of bounds"`
2 Error
`msg="Error on ingesting samples that are too old or are too far into the future"`
3 Current max timestamp is equal to wrong timestamp (approx)
image

### System information

Linux 5.14.0-331.el9.x86_64 x86_64

### Prometheus version

```text
prometheus, version 2.47.0 (branch: HEAD, revision: efa34a5840661c29c2e362efa76bc3a70dccb335)
  build user:       root@409eb5e6b30c
  build date:       20230906-10:20:07
  go version:       go1.21.0
  platform:         linux/amd64
  tags:             netgo,builtinassets,stringlabels
```

### Prometheus configuration file

```yaml
# my global config
global:
  scrape_interval:    15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 60s # Evaluate rules every 15 seconds. The default is every 1 minute.
  scrape_timeout: 10s
  external_labels:
    prometheus: main
  # scrape_timeout is set to the global default (10s).
# Alertmanager configuration
alerting:
  alert_relabel_configs:
    - source_labels: [prometheus]
      regex: (.*)
      target_label: prometheus
  alertmanagers:
  - static_configs:
      - targets: ['*****:9093']
      - targets: ['*****:9093']
      - targets: ['*****:9093']

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "/etc/prometheus/rules/*.rule"

#Write to VictoriaMetrics
remote_write:
  - url: https://<victoria_metrics1>/api/v1/write
    basic_auth:
      username: *****
      password: *****
    queue_config:
      capacity: 50000
      max_samples_per_send: 25000
      max_shards: 35
    metadata_config:
      send_interval: 45s
      max_samples_per_send: 25000
  - url: https://<victoria_metrics2>/api/v1/write
    basic_auth:
      username: ******
      password: ******
    queue_config:
      capacity: 50000
      max_samples_per_send: 25000
      max_shards: 35
    metadata_config:
      send_interval: 45s
      max_samples_per_send: 25000

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'http-targets'
    scrape_interval: 20s
    scrape_timeout: 10s
    scheme: http
    http_sd_configs:
      - url: "*****"
        basic_auth:
          username: *****
          password: *****
    relabel_configs:
      - source_labels: [__app_name]
        target_label: job
        regex: (^\S+$)
      - source_labels: [__metrics_path]
        target_label: __metrics_path__
        regex: (^\S+$)
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: "monitoring_agent_check_errors"
        action: drop
  - job_name: ... # other scrape jobs, nothing interesting here
 

Also command line flags:
            "Cmd": [
                "--config.file=/etc/prometheus/prometheus.yml",
                "--storage.tsdb.path=/prometheus",
                "--storage.tsdb.retention=90d",
                "--storage.tsdb.retention.size=6000GB",
                "--web.listen-address=0.0.0.0:9090",
                "--log.level=info",
                "--web.enable-admin-api",
                "--web.enable-lifecycle",
                "--web.external-url=https://******",
                "--web.console.libraries=/usr/share/prometheus/console_libraries",
                "--web.console.templates=/usr/share/prometheus/consoles",
                "--web.enable-remote-write-receiver"
```

### Alertmanager version

_No response_

### Alertmanager configuration file

_No response_

### Logs

```text
Errors regarding wrong timestamp

2024-02-12T15:35:09.472954+00:00 my-host docker/prometheus/a731f7ee2b1a/prom/prometheus:v2.47.0[3286185]: ts=2024-02-12T15:35:09.472Z caller=write_handler.go:132 level=error component=web msg="Out of order sample from remote write" err="duplicate sample for timestamp" series="{__name__=\"scrape_samples_scraped\", city=\"Johannesburg\", state=\"maintenance\", country=\"South Africa\", env=\"prod\", hostname=\"broken-host\", instance=\"127.0.0.1:35807\", job=\"prometheus\", prometheus_agent=\"true\", role=\"edge\", "}" timestamp=4039374839411
```

### PR DESCRIPTION
**Pull request by jkroepke**
- Fixes #13573 
- Fixes #12006

Based on the [comment](https://github.com/prometheus/prometheus/issues/13573#issuecomment-2145808011), I started to implement a potential solution for #13573. The alternative solution would a check in `storage.Appendable` implementation.

I added 2 tests to cover that issue, which both are green now.

### CODE REVIEW

File: storage/remote/write_handler.go [hunk 1]
```diff
@@ -124,7 +129,13 @@ func (h *writeHandler) write(ctx context.Context, req *prompb.WriteRequest) (err
 		}
 		var ref storage.SeriesRef
 		for _, s := range ts.Samples {
-			ref, err = app.Append(ref, labels, s.Timestamp, s.Value)
+			// check, if the histogram timestamp is in the past
+			if s.Timestamp <= currentTimestamp {
+				ref, err = app.Append(ref, labels, s.Timestamp, s.Value)
+			} else {
+				err = storage.ErrOutOfBounds
+			}
```
Comment (bboreham) [inline storage/remote/write_handler.go:137]: I think I would do this differently, to avoid logging a confusing message:
```suggestion
			if s.Timestamp > currentTimestamp {
				level.Error(h.logger).Log("msg", "Sample with future timestamp from remote write", "series", labels.String(), "timestamp", s.Timestamp)
				return storage.ErrOutOfBounds
			}
			ref, err = app.Append(ref, labels, s.Timestamp, s.Value)
```

**Review by bboreham — COMMENTED** [review]
This implementation seems fragile to server clock drift - if the receiver goes a few milliseconds behind the sender, all sends will fail.  Or did I miss something?

Perhaps the same approach used for scraping, where a 10-minute difference is allowed, would work?
https://github.com/prometheus/prometheus/blob/7aacef9b42a275f7ad8f60a707abb6de2a5d1448/scrape/scrape.go#L648

**Comment by jkroepke** [comment]
> Perhaps the same approach used for scraping, where a 10-minute difference is allowed, would work?

I think, a 10 minutes time drift should never happens. I think, 2 minutes are enough. Classical NTP checks have 0.5 seconds time drift as warning and 1 seconds time drift as critical .

If Prometheus and TSDB depends on time, clients should be in sync. I personally think seconds for clock skew situation would be way enough. 

As I know, 30 seconds are used for clock skew at OIDC, too.

---

Anyways, for consistency, I will change the check to +10 minutes. 

https://github.com/prometheus/prometheus/blob/7aacef9b42a275f7ad8f60a707abb6de2a5d1448/scrape/scrape.go#L648

The and I think the times can be discussed in a follow-up issue. (both for scrape and remote write)

**Comment by bboreham** [comment]
> I think, a 10 minutes time drift should never happens. 

Totally agree with you in principle, however I see data from hundreds of thousands of servers at $dayjob, and I assure you people have all kinds of wacky times.

Anyway, agreed on consistency and making that change in a different PR.

**Comment by jkroepke** [comment]
> Anyway, agreed on consistency and making that change in a different PR.

Sound like an config option for me.

**Review by machine424 — COMMENTED** [review]
Just some nits.
Shouldn't we do the same for exemplars?

File: storage/remote/write_handler.go [hunk 2]
```diff
@@ -115,6 +120,12 @@ func (h *writeHandler) write(ctx context.Context, req *prompb.WriteRequest) (err
 
 	b := labels.NewScratchBuilder(0)
 	var exemplarErr error
+
+	timeLimitApp := &timeLimitAppender{
+		Appender: app,
```
Comment (machine424) [inline storage/remote/write_handler.go:125]: nitty nit: we can initialize the appender directly here and use timeLimitApp everywhere.

File: storage/remote/write_handler.go [hunk 3]
```diff
@@ -140,7 +151,7 @@ func (h *writeHandler) write(ctx context.Context, req *prompb.WriteRequest) (err
 		for _, ep := range ts.Exemplars {
 			e := exemplarProtoToExemplar(&b, ep)
 
-			_, exemplarErr = app.AppendExemplar(0, labels, e)
+			_, exemplarErr = timeLimitApp.AppendExemplar(0, labels, e)
```
Comment (machine424) [inline storage/remote/write_handler.go:154]: we could need to override `AppendExemplar` for timeLimitAppender, but let's wait for the feature's GA, the test should fail by then anyway.

**Review by machine424 — APPROVED** [review]
Thanks.

File: storage/remote/write_handler.go [hunk 4]
```diff
@@ -115,6 +120,12 @@ func (h *writeHandler) write(ctx context.Context, req *prompb.WriteRequest) (err
 
 	b := labels.NewScratchBuilder(0)
 	var exemplarErr error
+
+	timeLimitApp := &timeLimitAppender{
```
Comment (bwplotka) [inline storage/remote/write_handler.go:124]: One alternative is to create this once on NewWriteHandler and implement it so it's always `maxAheadTime` from now. We would kind of save some lines to understand/read here, plus a few small allocations. Not a blocker.  🤗

**Review by bwplotka — APPROVED** [review]
Small suggestion, otherwise LGTM, thanks!

File: storage/remote/write_handler.go (hunk 4 above)
Comment (jkroepke) [reply storage/remote/write_handler.go]: hmm. in the current design, `timestamp.FromTime(time.Now().Add(maxAheadTime))` is calculated once per request. If it's get initialized `NewWriteHandler`, it needs to be calculated for each condition? Or did I miss something?

**Comment by jkroepke** [comment]
Thanks for all the reviewer. I apply the code suggestion. I hope, everything is fine.

File: storage/remote/write_handler.go [hunk 5]
```diff
@@ -149,13 +159,15 @@ func (h *writeHandler) write(ctx context.Context, req *prompb.WriteRequest) (err
 		}
 
 		for _, hp := range ts.Histograms {
+			// check, if the histogram timestamp is in the past
```
Comment (machine424) [inline storage/remote/write_handler.go:162]: I think this is a leftover.

**Review by machine424 — APPROVED** [review]
Thanks for your patience.

File: storage/remote/write_handler.go [hunk 6]
```diff
@@ -104,17 +109,22 @@ func (h *writeHandler) write(ctx context.Context, req *prompb.WriteRequest) (err
...
+			_ = timeLimitApp.Rollback()
 			return
 		}
-		err = app.Commit()
+		err = timeLimitApp.Commit()
 	}()
 
 	b := labels.NewScratchBuilder(0)
 	var exemplarErr error
+
```
Comment (machine424) [inline storage/remote/write_handler.go:127]: I hope that writing an entire `req.Timeseries` doesn't take more than 10 minutes in any environment.
Let's see.

**Comment by jkroepke** [comment]
How we can continue? After Prometheus release, is there a merge window time?

**Review by bboreham — APPROVED** [review]
