### PR TITLE
Kubernetes SD: Refactor to handle missing Kubernetes events

### LINKED ISSUE #1316: Kubernetes discovery misses some changes
When bringing up a local cluster for integration tests, sometimes Prometheus (using the example Kubernetes configuration) does not pick up a service that requests to be scraped using the `prometheus.io/scrape` annotation.

In this situation, sending a SIGHUP to the Prometheus process seems to "fix" this:

```
mr@ip-10-33-34-50 ~/k8s (git)-[master] % kubectl-local --namespace=kube-system exec -ti deploymentrc-2964570028-e8nbh -- wget -q -O - "http://localhost:9090/api/v1/query?query=haproxy_backend_up&time=$(date -u +%s)"
{"status":"success","data":{"resultType":"vector","result":[]}}
mr@ip-10-33-34-50 ~/k8s (git)-[master] % kubectl-local --namespace=kube-system exec -ti deploymentrc-2964570028-e8nbh -- pkill -HUP prometheus
mr@ip-10-33-34-50 ~/k8s (git)-[master] % kubectl-local --namespace=kube-system exec -ti deploymentrc-2964570028-e8nbh -- wget -q -O - "http://localhost:9090/api/v1/query?query=haproxy_backend_up&time=$(date -u +%s)"
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"__name__":"haproxy_backend_up","backend":"default-web-80","instance":"172.17.128.7:9101","job":"kubernetes-services","kubernetes_name":"ingress-controller","kubernetes_namespace":"ingress-internal","kubernetes_role":"service"},"value":[1452788773,"1"]},{"metric":{"__name__":"haproxy_backend_up","backend":"deny","instance":"172.17.128.7:9101","job":"kubernetes-services","kubernetes_name":"ingress-controller","kubernetes_namespace":"ingress-internal","kubernetes_role":"service"},"value":[1452788773,"1"]},{"metric":{"__name__":"haproxy_backend_up","backend":"kube-system-kibana-logging-5601","instance":"172.17.128.7:9101","job":"kubernetes-services","kubernetes_name":"ingress-controller","kubernetes_namespace":"ingress-internal","kubernetes_role":"service"},"value":[1452788773,"1"]},{"metric":{"__name__":"haproxy_backend_up","backend":"kube-system-prometheus-9090","instance":"172.17.128.7:9101","job":"kubernetes-services","kubernetes_name":"ingress-controller","kubernetes_namespace":"ingress-internal","kubernetes_role":"service"},"value":[1452788773,"1"]},{"metric":{"__name__":"haproxy_backend_up","backend":"stats","instance":"172.17.128.7:9101","job":"kubernetes-services","kubernetes_name":"ingress-controller","kubernetes_namespace":"ingress-internal","kubernetes_role":"service"},"value":[1452788773,"1"]}]}}
mr@ip-10-33-34-50 ~/k8s (git)-[master] % kubectl-local --namespace=kube-system logs deploymentrc-2964570028-e8nbh
prometheus, version 0.16.1 (branch: HEAD, revision: 968ee35)
  build user:       @84057be02ab6
  build date:       20160111-15:47:17
  go version:       1.5.1
time="2016-01-14T16:08:50Z" level=info msg="Loading configuration file /etc/prometheus/prometheus.yml" source="main.go:196"
time="2016-01-14T16:08:50Z" level=info msg="Loading series map and head chunks..." source="storage.go:262"
time="2016-01-14T16:08:50Z" level=info msg="0 series loaded." source="storage.go:267"
time="2016-01-14T16:08:50Z" level=info msg="Starting target manager..." source="targetmanager.go:114"
time="2016-01-14T16:08:50Z" level=info msg="Listening on :9090" source="web.go:223"
time="2016-01-14T16:09:00Z" level=error msg="Unable to list Kubernetes nodes: Unable to query any masters" source="discovery.go:113"
time="2016-01-14T16:09:10Z" level=error msg="Unable to list Kubernetes nodes: Unable to query any masters" source="discovery.go:113"
time="2016-01-14T16:09:20Z" level=error msg="Failed to watch service endpoints: Unable to query any masters" source="discovery.go:551"
time="2016-01-14T16:09:20Z" level=error msg="Failed to watch service endpoints: Unable to query any masters" source="discovery.go:551"
time="2016-01-14T16:09:30Z" level=error msg="Failed to watch nodes: Unable to query any masters" source="discovery.go:365"
time="2016-01-14T16:09:30Z" level=error msg="Failed to watch nodes: Unable to query any masters" source="discovery.go:365"
time="2016-01-14T16:09:40Z" level=error msg="Failed to watch services: Unable to query any masters" source="discovery.go:407"
time="2016-01-14T16:09:40Z" level=error msg="Failed to watch services: Unable to query any masters" source="discovery.go:407"
time="2016-01-14T16:09:50Z" level=error msg="Failed to watch service endpoints: Unable to query any masters" source="discovery.go:551"
time="2016-01-14T16:09:50Z" level=error msg="Failed to watch service endpoints: Unable to query any masters" source="discovery.go:551"
time="2016-01-14T16:10:00Z" level=error msg="Failed to watch nodes: Unable to query any masters" source="discovery.go:365"
time="2016-01-14T16:10:00Z" level=error msg="Failed to watch nodes: Unable to query any masters" source="discovery.go:365"
time="2016-01-14T16:10:10Z" level=error msg="Failed to watch services: Unable to query any masters" source="discovery.go:407"
time="2016-01-14T16:10:10Z" level=error msg="Failed to watch services: Unable to query any masters" source="discovery.go:407"
time="2016-01-14T16:10:20Z" level=error msg="Failed to watch service endpoints: Unable to query any masters" source="discovery.go:551"
time="2016-01-14T16:10:20Z" level=error msg="Failed to watch service endpoints: Unable to query any masters" source="discovery.go:551"
time="2016-01-14T16:10:30Z" level=error msg="Failed to watch nodes: Unable to query any masters" source="discovery.go:365"
time="2016-01-14T16:10:30Z" level=error msg="Failed to watch nodes: Unable to query any masters" source="discovery.go:365"
time="2016-01-14T16:10:40Z" level=error msg="Failed to watch services: Unable to query any masters" source="discovery.go:407"
time="2016-01-14T16:10:40Z" level=error msg="Failed to watch services: Unable to query any masters" source="discovery.go:407"
time="2016-01-14T16:13:50Z" level=info msg="Checkpointing in-memory metrics and chunks..." source="persistence.go:539"
time="2016-01-14T16:13:50Z" level=info msg="Done checkpointing in-memory metrics and chunks in 178.226463ms." source="persistence.go:563"
time="2016-01-14T16:18:50Z" level=info msg="Checkpointing in-memory metrics and chunks..." source="persistence.go:539"
time="2016-01-14T16:18:50Z" level=info msg="Done checkpointing in-memory metrics and chunks in 167.210103ms." source="persistence.go:563"
time="2016-01-14T16:23:50Z" level=info msg="Checkpointing in-memory metrics and chunks..." source="persistence.go:539"
time="2016-01-14T16:23:50Z" level=info msg="Done checkpointing in-memory metrics and chunks in 144.101098ms." source="persistence.go:563"
time="2016-01-14T16:26:10Z" level=info msg="Loading configuration file /etc/prometheus/prometheus.yml" source="main.go:196"
time="2016-01-14T16:26:10Z" level=info msg="Stopping target manager..." source="targetmanager.go:203"
time="2016-01-14T16:26:10Z" level=info msg="Target manager stopped." source="targetmanager.go:216"
time="2016-01-14T16:26:10Z" level=info msg="Starting target manager..." source="targetmanager.go:114"
```

Of note may be that during the bring-up of this cluster, several components are dumped in pretty much at once, in parallel, and in no particular order. Prometheus and the to-be-scraped HAProxy exporter may come up in either order or at the same time. Once in about 5 times it gets into the situation above, which may or may not be a race condition …

There's also a bunch of errors about being unable to query any masters, but they also happen when everything works out just fine.

@jimmidyson any idea what's up with that?

### PR DESCRIPTION
**Pull request by jimmidyson**
Fixes #1316

@matthiasr If you could try this out that would be awesome.

### CODE REVIEW

**Comment by matthiasr** [comment]
Wow, that was quick :smile: I'll give this a spin as soon as possible.

**Comment by fabxc** [comment]
Wow, quick indeed. Thanks a lot!
Will review as soon as I find time.

File: retrieval/discovery/kubernetes/discovery.go [hunk 1]
```diff
@@ -392,62 +405,144 @@ func (kd *Discovery) watchNodes(events chan interface{}, done <-chan struct{}, r
...
+		for _, ns := range services {
+			for _, service := range ns {
+				events <- &serviceEvent{added, service}
+			}
+		}
+
+		var wg sync.WaitGroup
+		wg.Add(2)
+
+		go kd.watchServices(resourceVersion, events, done, &wg)
```
Comment (fabxc) [inline retrieval/discovery/kubernetes/discovery.go]: The `wg` is not really a relevant parameter to that function. Something like this would be more idiomatic I'd say.

```
go func() {
    kd.watchServices(resourceVersion, events, done)
    wg.Done()
}()
```

**Comment by fabxc** [comment]
:+1:

File: retrieval/discovery/kubernetes/discovery.go (hunk 1 above)
Comment (jimmidyson) [inline retrieval/discovery/kubernetes/discovery.go]: Thanks for tip! Always learning ;)

Updated.

**Comment by jimmidyson** [comment]
I'd really appreciate it if @matthiasr could test this before merging just to confirm the fix. Seems to work for me, but always good to have a second/third/fourth opinion.

**Comment by matthiasr** [comment]
Yep I haven't forgotten. I'll try to get this done today.

**Comment by matthiasr** [comment]
So, uhm, I've caught up to master and that seems to already have fixed the issue :open_mouth: after running my cluster test several times in a row it hasn't failed yet. I'll test this branch anyway.

**Comment by matthiasr** [comment]
I've also tested this branch and I can confirm that it's functionally not a regression, but it seems #1316 was already fixed by upgrading to master.

**Comment by fabxc** [comment]
From the comments I infer that this is still a preferable refactoring? @jimmidyson

**Comment by jimmidyson** [comment]
@matthiasr I'm happily surprised it was fixed on master without this PR :)

@fabxc Yes this is still a "better" refactoring than before, safer in a few ways IMO.
