### PR TITLE
API: Fix global URL when external address has no port

### LINKED ISSUE #8358: React UI version of Status -> Targets shows spurious ': address <host>: missing port in address' for localhost targets when behind an Apache reverse proxy
**What did you do?**

We have our Prometheus instance behind a HTTPS Apache reverse proxy. Since the switch to the new React UI in 2.23.0, the /targets URL (from Status -> Targets) will show an error for all targets of ': address <our-host>: missing port in address' for most targets it reports. It appears that this warning shows up only for targets where the endpoint is 'localhost' or '127.0.0.1', except for the scrape of Prometheus itself on 'http://localhost:9090/metrics'.

I am running 2.24.0 (and before it 2.23.0) in setups that aren't behind an Apache reverse proxy and those instances don't show this problem.

**Environment**

* System information:

	Linux 4.15.0-117-generic x86_64

* Prometheus version:

	prometheus, version 2.24.0 (branch: HEAD, revision: 02e92236a8bad3503ff5eec3e04ac205a3b8e4fe)
  build user:       root@d9f90f0b1f76
  build date:       20210106-13:48:37
  go version:       go1.15.6
  platform:         linux/amd64

Our Prometheus configuration is relatively large and I expect it to not be relevant. However, some of our command line flags are probably relevant here, so:

    prometheus --config.file=/etc/prometheus/prometheus.yml [tsdb settings etc] --web.external-url=https://csmetrics.cs.toronto.edu/prometheus/ --web.route-prefix=/ --web.listen-address=127.0.0.1:9090

### PR DESCRIPTION
**Pull request by roidelapluie**
fix #8358 

Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

### CODE REVIEW

File: web/api/v1/api.go [hunk 1]
```diff
@@ -780,9 +784,16 @@ func getGlobalURL(u *url.URL, opts GlobalURLOptions) (*url.URL, error) {
...
-					return u, err
+					if strings.HasSuffix(err.Error(), "missing port in address") {
+						host = opts.Host
+					} else {
+						return u, err
+					}
+				}
+				u.Host = host
+				if port != "" {
+					u.Host += ":" + port
```
Comment (juliusv) [inline web/api/v1/api.go:795]: You probably want to use https://golang.org/pkg/net/?m=all#JoinHostPort here so that IPv6 addresses are handled correctly as well? And then add test cases below where the global URL contains a IPv6 addresses (with and without port).

Comment (roidelapluie) [reply web/api/v1/api.go:795]: Indeed  . I did think about then forget :) Thanks, will update the PR

Comment (roidelapluie) [reply web/api/v1/api.go:795]: @juliusv it turns out that in a URL, there should be [] for IPv6. Therefore, we are already covered.

Adding JoinHostPort  creates a URL like `[[::1]]:80` which is not valid, therefore the current approach is correct.

**Comment by roidelapluie** [comment]
Thanks, I have addressed your comment.
In the future we might want to refactor that in the react ui.

**Comment by roidelapluie** [comment]
@juliusv friendly pre release ping :)

**Comment by juliusv** [comment]
:+1: Thanks :)
