### PR TITLE
[BUGFIX] UI :Suppress duration unit autocomplete when unit already present in query selector

### LINKED ISSUE #15452: Auto-complete keeps inserting a 'd' when trying to change rate duration
### What did you do?

1. Graph a rate `rate(foo_count[5m])`
2. Attempt to graph a different duration
3. 'd' is always inserted by autocomplete

### What did you expect to see?

A rate with say 1 or 10 minute buckets not an error.

Ideally the autocomplete would see that my expression would be more valid if it did nothing rather than creating a broken duration.

### What did you see instead? Under which circumstances?

An error message unless I also press escape first, then enter.

[prom_bug.webm](https://github.com/user-attachments/assets/8bc4dc1d-c1f0-409e-96cd-65638aa72d67)

### System information

Chrome on linux 129.0.6668.70 (Official Build) (64-bit) 

### Prometheus version

```text
{"version":"3.0.0","revision":"c5d009d57fcccb7247e1191a0b10d74b06295388","branch":"HEAD","buildUser":"root@aa286d0eb00a","buildDate":"20241114-16:40:43","goVersion":"go1.23.3"}
```

### Prometheus configuration file

_No response_

### Alertmanager version

_No response_

### Alertmanager configuration file

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by adity-a34**
Suppress duration unit autocomplete when unit is already present after digit (e.g. `rate(foo[5m])`, `rate(foo[5ms])`).

- Prevents duplicate duration unit suggestions in query editor.
- Adds tests for no-suggestion scenarios.

#### Which issue(s) does the PR fix:
Fixes #15452

#### Does this PR introduce a user-facing change?
```release-notes
[BUGFIX] The query editor no longer suggests a duration unit if one is already present after a number.
```

Resulting behavior:

https://github.com/user-attachments/assets/921a9696-cab0-4f33-9ce8-9757521d626b

### CODE REVIEW

File: web/ui/module/codemirror-promql/src/complete/hybrid.ts [hunk 1]
```diff
@@ -166,6 +166,25 @@ function arrayToCompletionResult(data: Completion[], from: number, to: number, i
   } as CompletionResult;
 }
 
+const durationUnitLabels = durationTerms
+  .map((term) => term.label)
+  .filter((label): label is string => typeof label === 'string')
```
Comment (Nexucis) [inline web/ui/module/codemirror-promql/src/complete/hybrid.ts]: `durationTerms` contains only a string, so this is not needed.

File: web/ui/module/codemirror-promql/src/complete/hybrid.ts [hunk 2]
```diff
@@ -166,6 +166,25 @@ function arrayToCompletionResult(data: Completion[], from: number, to: number, i
...
+  .sort((a, b) => b.length - a.length);
```
Comment (Nexucis) [inline web/ui/module/codemirror-promql/src/complete/hybrid.ts]: I would assume you don't need to sort the list since this is already sorted. So I would say this is not needed as well

File: web/ui/module/codemirror-promql/src/complete/hybrid.ts [hunk 3]
```diff
@@ -166,6 +166,25 @@ function arrayToCompletionResult(data: Completion[], from: number, to: number, i
...
+
+const durationWithUnitRegexp = new RegExp(`^\\d+(?:${durationUnitLabels.map((label) => escapeRegExp(label)).join('|')})$`);
```
Comment (Nexucis) [inline web/ui/module/codemirror-promql/src/complete/hybrid.ts]: I would say we can simplify this thing by a single const

```typescript
const durationWithUnitRegexp = new RegExp(`^\\d+(?:${durationTerms.map((term) => term.label).map((label) => escapeRegExp(label)).join('|')})$`);
```

And it will be nice to put in comment the expected result and have a test actually.

File: web/ui/module/codemirror-promql/src/complete/hybrid.ts [hunk 4]
```diff
@@ -166,6 +166,25 @@ function arrayToCompletionResult(data: Completion[], from: number, to: number, i
...
+
+function escapeRegExp(value: string): string {
+  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
+}
+
+function hasCompleteDurationUnit(state: EditorState, node: SyntaxNode): boolean {
```
Comment (Nexucis) [inline web/ui/module/codemirror-promql/src/complete/hybrid.ts:174]: Can you add a comment to explain the purpose of this function. Which is basically the purpose of the PR.

Comment (ADITYATIWARI342005) [reply web/ui/module/codemirror-promql/src/complete/hybrid.ts]: I'll add a comment that explains the function's purpose.

**Comment by adity-a34** [comment]
I have added the tests for the regex
image

**Comment by adity-a34** [comment]
Hi @Nexucis 
Thank you for the review given earlier, It helped in making the necessary optimisations, 
Can you please review the latest changes made ?

File: web/ui/module/codemirror-promql/src/complete/hybrid.test.ts [hunk 5]
```diff
@@ -630,6 +642,32 @@ describe('analyzeCompletion test', () => {
...
+describe('durationWithUnitRegexp test', () => {
+  it('should match complete durations with units', () => {
+    const testCases = [
+      { input: '5m', expected: true },
+      { input: '30s', expected: true },
+      { input: '1h', expected: true },
+      { input: '500ms', expected: true },
+      { input: '2d', expected: true },
+      { input: '1w', expected: true },
+      { input: '1y', expected: true },
```
Comment (Nexucis) [inline web/ui/module/codemirror-promql/src/complete/hybrid.test.ts:654]: I am curious about what would happen if you have the duration `1d2h` for example. Does the test still work ?

File: web/ui/module/codemirror-promql/src/complete/hybrid.ts [hunk 6]
```diff
@@ -166,6 +166,22 @@ function arrayToCompletionResult(data: Completion[], from: number, to: number, i
   } as CompletionResult;
 }
 
+// Matches complete duration with units (e.g., 5m, 30s, 1h, 500ms)
+export const durationWithUnitRegexp = new RegExp(`^\\d+(?:${durationTerms.map((term) => escapeRegExp(term.label)).join('|')})$`);
+
+function escapeRegExp(value: string): string {
```
Comment (juliusv) [inline web/ui/module/codemirror-promql/src/complete/hybrid.ts]: Can we use `RegExp.escape()` (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/escape) here? Or actually, since we know that every duration term is only a single letter, maybe we are ok without explicit escaping in the first place?

**Comment by adity-a34** [comment]
> I am curious about what would happen if you have the duration `1d2h` for example. Does the test still work ?

@Nexucis I have kept the tests simpler. 
Do you want me to make it more diverse?
Please tell me, and I will try to make it more accurate.

**Comment by Nexucis** [comment]
> Do you want me to make it more diverse?

Yes that would be great. I have already tested manually if it still works, and this is the case. So I am expecting the tests will be fine as well.

**Comment by adity-a34** [comment]
Hi @juliusv,
Could you please confirm if using `declare global { ... }` for the `RegExpConstructor` type augmentation is permitted under our repository’s TypeScript practices?
I added this to ensure the RegExp.escape polyfill works cleanly with TS and satisfies both compatibility and future ES2024 standards.
Let me know if you prefer this handled differently!

**Comment by adity-a34** [comment]
@Nexucis @juliusv 
I have made the changes as suggested... Please let me know if anything is misaligned or remaining from the expected/optimal implementation.

**Review by Nexucis — APPROVED** [review]
looks good to me.
Thank you @ADITYATIWARI342005

I will let a bit of time for @juliusv if he want to add more comments and then we will merge it.

File: web/ui/module/codemirror-promql/src/complete/hybrid.ts [hunk 7]
```diff
@@ -166,6 +166,32 @@ function arrayToCompletionResult(data: Completion[], from: number, to: number, i
...
 
+// Polyfill RegExp.escape for compatibility with ES2024 and TypeScript.
+// Ensures safe, standards-based regex escaping in all environments.
+declare global {
+  interface RegExpConstructor {
+    escape?: (s: string) => string;
+  }
+}
+
+if (!RegExp.escape) {
```
Comment (juliusv) [inline web/ui/module/codemirror-promql/src/complete/hybrid.ts]: Sorry, I didn't think that this would introduce so much trouble - if we got to define `escape` manually anyway in case it doesn't exist, then the previous solution was simpler.

But maybe the even better alternative is to just not escape anything, given that durations should never contain special characters?

Comment (ADITYATIWARI342005) [reply web/ui/module/codemirror-promql/src/complete/hybrid.ts]: @juliusv It is ready for review!

**Review by juliusv — APPROVED** [review]
Thanks! :+1:
