### PR TITLE
Fix: getting rid of EncOOOXOR from chunk encoding

### LINKED ISSUE #11835: Get rid of the `EncOOOXOR` from the chunk encodings
### Proposal

[EncOOOXOR](https://github.com/prometheus/prometheus/blob/f88a0a7d83bb9ef4387ff158d43f5a0c580fffdf/tsdb/chunkenc/chunk.go#L54) was added as part of OOO support to indicate that this chunk, while XOR encoded, belongs to the OOO part of the Head block. This is used only in the ChunkDiskMapper when m-mapping so that when Prometheus restarts we can identify which chunks belong to the OOO Head.

Since this is not a new encoding, we should simplify this and remove EncOOOXOR, and instead do the same bit in ChunkDiskMapper itself to identify OOO chunks. This will also simplify things when we have OOO support for native histograms.

This won't be a breaking change because the same bit will be set to `1` in the ChunkDiskMapper; it is just how we do it is changing.

---

This issue is broken down from https://github.com/prometheus/prometheus/issues/11329

### PR DESCRIPTION
**Pull request by mabhi**
## Explanation
Getting rid of EncOOOXOR from chunk encoding, as this is not an encoding but a flag to mark OOO encoded chunks

## Related Issue:
Fixes #11835

## Proposed Changes

- Refactor the code to get rid of `OOOXORChunk` struct
- Enhance the `ChunkDiskMapper` with the responsibility to verify for OOOChunks, apply OOO header and restore original encoding
- The ChunkDiskMapper uses the first bit to know if the chunk is from out-of-order or not, and uses the last 7 bits of the byte to get the chunk encoding, by assuming that the chunk encoding won't cross 7 bits anytime in near/far future.
- During chunk writes either directly or via job queue sending the `isOOO` flag to persist the extra 1st bit and that would be used during reads to check for OOO chunks and restore the original encoding for further processing.

### CODE REVIEW

File: tsdb/chunks/head_chunks.go [hunk 1]
```diff
@@ -273,6 +273,25 @@ func NewChunkDiskMapper(reg prometheus.Registerer, dir string, pool chunkenc.Poo
...
 }
 
+// Chunk encodings for out-of-order chunks.
+// These encodings must be only used by the Head block for its internal bookkeeping.
+const (
+	OutOfOrderMask        = 0b10000000
+	RestoreOutOfOrderMask = 0b01111111
+)
+
+func (cdm *ChunkDiskMapper) OutOfOrderEncoding(sourceEncoding chunkenc.Encoding) chunkenc.Encoding {
```
Comment (jesusvazquez) [inline tsdb/chunks/head_chunks.go:283]: I would rename this to `ApplyOutOfOrderEncoding` or something like that since its actually applying a mask over the giving encoding.

File: tsdb/chunks/head_chunks.go [hunk 2]
```diff
@@ -273,6 +273,25 @@ func NewChunkDiskMapper(reg prometheus.Registerer, dir string, pool chunkenc.Poo
...
+	return sourceEncoding | OutOfOrderMask
+}
+
+func (cdm *ChunkDiskMapper) IsOutOfOrderChunk(e chunkenc.Encoding) bool {
+	return (e & OutOfOrderMask) != 0
+}
+
+func (cdm *ChunkDiskMapper) OutOfOrderDecoding(sourceEncoding chunkenc.Encoding) chunkenc.Encoding {
```
Comment (jesusvazquez) [inline tsdb/chunks/head_chunks.go:291]: Same as above, we're applying a mask to decode

File: tsdb/head.go [hunk 3]
```diff
@@ -774,7 +774,11 @@ func (h *Head) loadMmappedChunks(refSeries map[chunks.HeadSeriesRef]*memSeries)
 	if err := h.chunkDiskMapper.IterateAllChunks(func(seriesRef chunks.HeadSeriesRef, chunkRef chunks.ChunkDiskMapperRef, mint, maxt int64, numSamples uint16, encoding chunkenc.Encoding) error {
 		secondLastRef = lastRef
 		lastRef = chunkRef
-		isOOO := chunkenc.IsOutOfOrderChunk(encoding)
+		isOOO := h.chunkDiskMapper.IsOutOfOrderChunk(encoding)
+		// flip the first bit to restore the original encoding
+		if isOOO {
+			encoding = h.chunkDiskMapper.OutOfOrderDecoding(encoding)
```
Comment (jesusvazquez) [inline tsdb/head.go:780]: Hm I wonder what could be done here, it seems here the head is aware of OOO chunk encodings and this is precisely what we wanted to hide in the chunk disk mapper.

Maybe we could change the function to return a boolean saying if its OOO instead of the encoding and then if its OOO we add it to `oooMmappedChunks`  and if its not we add it to `mmappedChunks`

What do you think @codesome

**Review by jesusvazquez — COMMENTED** [review]
So far the work looks good :muscle: 

I left one nitpick about the naming of a couple of functions.

The most important comment is the one in the head where the head is still aware of ooo chunk encodings. I think we can fix this refactoring the function by adding a boolean saying if the chunk is ooo but lets wait for @codesome 's comments.

Great work!

File: tsdb/chunks/head_chunks.go (hunk 1 above)
Comment (mabhi) [reply tsdb/chunks/head_chunks.go:283]: Ok, will rename it as suggested.

File: tsdb/chunks/head_chunks.go (hunk 2 above)
Comment (mabhi) [reply tsdb/chunks/head_chunks.go:291]: Ok, will rename it as suggested.

File: tsdb/head.go (hunk 3 above)
Comment (mabhi) [reply tsdb/head.go:780]: @jesusvazquez Can you point out as to which function you want to return `bool`.
The current function is part of the load chunks from initial read. I have tried to put all the logic in CDM. Do you want me to pass this `bool` as part of the callback function inside the `IterateAllChunks` ?

Comment (jesusvazquez) [reply tsdb/head.go:780]: Right! I believe I added the `encoding` to that function when we added the OOO chunks. If you notice the usages I think it should be fairly easy to change.

https://github.com/prometheus/prometheus/blob/3330d85ba8cd6c53e74af23ab96e9e2c134bec39/tsdb/chunks/head_chunks.go#L765

I would change that signature to something like
`func (cdm *ChunkDiskMapper) IterateAllChunks(f func(seriesRef HeadSeriesRef, chunkRef ChunkDiskMapperRef, mint, maxt int64, numSamples uint16, isOOO bool) error) (err error) {`

That will force you to refactor the call in https://github.com/prometheus/prometheus/blob/1f0cc09579b7d04bbcb2b9746b7040da55791d48/tsdb/head.go#L737 and remove the information about encodings in the head.

Comment (codesome) [reply tsdb/head.go:780]: +1 with what @jesusvazquez said. Let's change the function signature to return the isOOO boolean such that head doesn't need to infer it from the chunk encoding. The encoding coming out of ChunkDiskMapper here should have that ooo bit removed.

File: tsdb/chunks/head_chunks.go [hunk 4]
```diff
@@ -696,7 +720,11 @@ func (cdm *ChunkDiskMapper) Chunk(ref ChunkDiskMapperRef) (chunkenc.Chunk, error
 
 	// Encoding.
 	chkEnc := mmapFile.byteSlice.Range(chkStart, chkStart+ChunkEncodingSize)[0]
-
+	sourceChkEnc := chunkenc.Encoding(chkEnc)
+	if cdm.IsOutOfOrderChunk(sourceChkEnc) {
```
Comment (codesome) [inline tsdb/chunks/head_chunks.go:724]: You don't need this if check. You can simply just apply the bit mask everytime.

File: tsdb/chunks/head_chunks.go (hunk 2 above)
Comment (codesome) [reply tsdb/chunks/head_chunks.go:291]: After getting rid of `RestoreOutOfOrderMask` as suggested, this can be renamed as `UnapplyOutOfOrderMask`.

File: tsdb/chunks/head_chunks.go (hunk 1 above)
Comment (mabhi) [reply tsdb/chunks/head_chunks.go]: Ok, will do

File: tsdb/head.go (hunk 3 above)
Comment (mabhi) [reply tsdb/head.go]: Ok, will do

File: tsdb/chunks/head_chunks.go [hunk 5]
```diff
@@ -273,6 +273,25 @@ func NewChunkDiskMapper(reg prometheus.Registerer, dir string, pool chunkenc.Poo
 	return m, m.openMMapFiles()
 }
 
+// Chunk encodings for out-of-order chunks.
+// These encodings must be only used by the Head block for its internal bookkeeping.
+const (
+	OutOfOrderMask        = 0b10000000
+	RestoreOutOfOrderMask = 0b01111111
```
[the remark this answers is not in the document]
Comment (mabhi) [reply tsdb/chunks/head_chunks.go:280]: Ok, will do

File: tsdb/chunks/head_chunks.go (hunk 4 above)
Comment (mabhi) [reply tsdb/chunks/head_chunks.go:724]: understood

File: tsdb/chunks/head_chunks.go (hunk 2 above)
Comment (mabhi) [reply tsdb/chunks/head_chunks.go]: Ok, will do

**Review by jesusvazquez — APPROVED** [review]
LGTM :muscle: :muscle:

**Comment by mabhi** [comment]
@codesome / @jesusvazquez any other changes need in this PR. Do let me know.

File: tsdb/chunks/head_chunks.go [hunk 6]
```diff
@@ -273,6 +273,26 @@ func NewChunkDiskMapper(reg prometheus.Registerer, dir string, pool chunkenc.Poo
 	return m, m.openMMapFiles()
 }
 
+// Chunk encodings for out-of-order chunks.
+// These encodings must be only used by the Head block for its internal bookkeeping.
+const (
+	OutOfOrderMask = 0b10000000
```
Comment (codesome) [inline tsdb/chunks/head_chunks.go:279]: This should be uint8 to begin with and don't need typecasting elsewhere, else it can lead buggy code if not used correctly.
```suggestion
	OutOfOrderMask = uint8(0b10000000)
```

File: tsdb/chunks/head_chunks.go [hunk 7]
```diff
@@ -696,7 +721,9 @@ func (cdm *ChunkDiskMapper) Chunk(ref ChunkDiskMapperRef) (chunkenc.Chunk, error
 
 	// Encoding.
 	chkEnc := mmapFile.byteSlice.Range(chkStart, chkStart+ChunkEncodingSize)[0]
-
+	sourceChkEnc := chunkenc.Encoding(chkEnc)
+	// update the chunk encoding by restoring the original encoding, if needed
```
Comment (codesome) [inline tsdb/chunks/head_chunks.go:725]: Other than the reword, in Prometheus we start comments with capital letters where applicable and end with a full stop.
```suggestion
	// Extract the encoding from the byte. ChunkDiskMapper uses only the last 7 bits for the encoding.
```

File: tsdb/chunks/head_chunks.go [hunk 8]
```diff
@@ -860,8 +887,13 @@ func (cdm *ChunkDiskMapper) IterateAllChunks(f func(seriesRef HeadSeriesRef, chu
 			if maxt > mmapFile.maxt {
 				mmapFile.maxt = maxt
 			}
+			isOOO := cdm.IsOutOfOrderChunk(chkEnc)
+			// flip the first bit to restore the original encoding
+			if isOOO {
+				chkEnc = cdm.UnapplyOutOfOrderMask(chkEnc)
+			}
```
Comment (codesome) [inline tsdb/chunks/head_chunks.go:894]: Same reword as the other comment + don't need the `if` block.
```suggestion
			// Extract the encoding from the byte. ChunkDiskMapper uses only the last 7 bits for the encoding.
			chkEnc = cdm.UnapplyOutOfOrderMask(chkEnc)
```

File: tsdb/chunks/head_chunks.go [hunk 9]
```diff
@@ -273,6 +273,26 @@ func NewChunkDiskMapper(reg prometheus.Registerer, dir string, pool chunkenc.Poo
...
+
+func (cdm *ChunkDiskMapper) ApplyOutOfOrderMask(sourceEncoding chunkenc.Encoding) chunkenc.Encoding {
+	return sourceEncoding | OutOfOrderMask
+}
+
+func (cdm *ChunkDiskMapper) IsOutOfOrderChunk(e chunkenc.Encoding) bool {
+	return (e & OutOfOrderMask) != 0
+}
+
+func (cdm *ChunkDiskMapper) UnapplyOutOfOrderMask(sourceEncoding chunkenc.Encoding) chunkenc.Encoding {
```
Comment (codesome) [inline tsdb/chunks/head_chunks.go:290]: On another thought, I think this is better. Making it less specific to OOO such that it can be extended later if needed. 

```suggestion
func (cdm *ChunkDiskMapper) RemoveMasks(sourceEncoding chunkenc.Encoding) chunkenc.Encoding {
```

**Review by codesome — COMMENTED** [review]
Last nits

File: tsdb/chunks/head_chunks.go (hunk 6 above)
Comment (mabhi) [reply tsdb/chunks/head_chunks.go]: Done

File: tsdb/chunks/head_chunks.go (hunk 7 above)
Comment (mabhi) [reply tsdb/chunks/head_chunks.go]: Done

File: tsdb/chunks/head_chunks.go (hunk 8 above)
Comment (mabhi) [reply tsdb/chunks/head_chunks.go]: Done

File: tsdb/chunks/head_chunks.go (hunk 9 above)
Comment (mabhi) [reply tsdb/chunks/head_chunks.go]: Done

File: tsdb/chunks/head_chunks.go [hunk 10]
```diff
@@ -273,6 +273,27 @@ func NewChunkDiskMapper(reg prometheus.Registerer, dir string, pool chunkenc.Poo
...
+	enc := uint8(sourceEncoding) | OutOfOrderMask
+	return chunkenc.Encoding(enc)
+}
+
+func (cdm *ChunkDiskMapper) IsOutOfOrderChunk(e chunkenc.Encoding) bool {
+	return (uint8(e) & OutOfOrderMask) != 0
+}
+
+func (cdm *ChunkDiskMapper) RemoveMasks(sourceEncoding chunkenc.Encoding) chunkenc.Encoding {
+	oooMask := uint8(OutOfOrderMask)
```
Comment (codesome) [inline tsdb/chunks/head_chunks.go:292]: This variable is not required anymore

**Review by codesome — APPROVED** [review]
Last comment and we can merge. LGTM!

File: tsdb/chunks/head_chunks.go (hunk 10 above)
Comment (mabhi) [reply tsdb/chunks/head_chunks.go]: Updated
