### PR TITLE
tsdb: Early compaction of stale series

### LINKED ISSUE #13616: Eager compaction of stale series
### Proposal

Total number of series in memory has a direct correlation on the total memory being consumed. This is a problem when the series keep churning either because of pods either in crash loop backoff or when a user does a rollout that churned pods, did a roll back and then again rolled forward. this would 3x the total series in memory. 

I would like to propose an "eager compaction of stale series" based on a flag that says "compact when total stale series in memory crosses 1M". this would greatly improve our ability to observe high churn series.

### PR DESCRIPTION
**Pull request by codesome**
Closes #13616 

Based on https://github.com/prometheus/proposals/pull/55

Stale series tracking was added in #16925. This PR compacts the stale series into its own block before the normal compaction hits. Here is how the config works:

* `stale_series_compaction_threshold`: As soon as the ratio of stale series in the head block crosses `StaleSeriesImmediateCompactionThreshold`, TSDB performs a stale series compaction and puts all the stale series into a block and removed it from the head, but it does not remove it from the WAL. (technically this condition is checked every minute and not exactly immediate)

Additional details
* WAL replay: after a stale series compaction, tombstones are added with (MinInt64, MaxInt64) for all these stale series. During WAL replay we add a special condition where when we find such tombstone, it immediately removes the series from the memory instead of storing the tombstone. This is required so that we don't spike up memory during WAL replay and also don't keep the compacted stale series in the memory.
* Head block truncation ignores this block via the added metadata, similar to out-of-order blocks.

```release-notes
[ENHANCEMENT] tsdb: Experimental support for early compaction of stale series in the memory with configurable threshold.
```

### CODE REVIEW

**Comment by codesome** [comment]
Looks like stale series tracking is not working. Stale samples are not being put for the series I guess.

**Comment by codesome** [comment]
Here are the results from the PoC and the results are in-line with the expectations.

The good: memory and number of timeseries stayed down. For the prombench data pattern, the memory used was consistently 30-60% down.

The bad: The CPU usage is higher and instant queries took a hit. This is mostly because now it requires merging stale block and head block results for instant queries. 20-30% higher for this benchmark and peaks up to 50% sometimes.

I will fix some of the edge cases in the code and run it in our internal cluster to get some real world numbers.

Screenshot 2025-07-28 at 8 07 05 PM
Screenshot 2025-07-28 at 8 07 12 PM
Screenshot 2025-07-28 at 8 07 21 PM
Screenshot 2025-07-28 at 8 07 28 PM
Screenshot 2025-07-28 at 8 08 18 PM

**Comment by codesome** [comment]
Prombench decided to keep running even after stopping. So we have more numbers to look at.

Memory savings is great, but query/cpu is bonkers. I am guessing the queries in prombench are trying to touch a whole lot of series continuously.

Screenshot 2025-07-29 at 12 04 57 PM

Screenshot 2025-07-29 at 12 05 15 PM


Screenshot 2025-07-29 at 12 05 56 PM
Screenshot 2025-07-29 at 12 06 15 PM

**Comment by codesome** [comment]
Took a quick look at the profiles and confirmed that instant queries is taking the extra CPU. In the below pic, the red box is an additional CPU that stale series compaction introduces, since now it has to look at the block on disk for all instant queries. There is no way around it.

Screenshot 2025-07-29 at 12 15 15 PM


Here are the profiles that I downloaded from prombench:
[main branch profile.pb.gz](https://github.com/user-attachments/files/21496017/main.branch.profile.pb.gz)
[stale series profile.pb.gz](https://github.com/user-attachments/files/21496018/stale.series.profile.pb.gz)

**Comment by SuperQ** [comment]
The memory results look really good. For sure something we will want behind a feature flag for now. If we can improve on the CPU overhead, this may be something to enable by default in the future.

**Comment by bwplotka** [comment]
I'm surprised instant queries (or any queries) against TSDB blocks are so CPU intensive on Prometheus. OR... prombench results are not realistic -- like it spams queries way to often then realistically users would do. One important case is ofc alerting/recording rules - if they hit TSDB block, that block should be partially cached then (see below)

It would be useful to understand a single common query CPU overhead for in-mem and TSDB block... also we could cache index a bit at least for stale near-real time blocks to mitigate some CPU with a bit more memory (hopefully this will diminishes the memory results - this cache should only be short-living for similar queries or heavy instant query load 🤔). Maybe we learn about some need for optimizing the TSDB read path with this work (: 

I still think this would be an interesting mode e.g. for us (Google), where we keep local query capability for debugging in some cases but we use cloud as a first order.

Thanks for extensive research!

**Comment by bboreham** [comment]
> prombench results are not realistic -- like it spams queries way to often then realistically users would do

It queries frequently, which might be taken to simulate a large user population or a lot of recording rules, but perhaps more importantly it never queries more than 1 hour back.  That is what PRs like https://github.com/prometheus/test-infra/pull/782 are seeking to change.

So if you make every query hit every block, that will make quite a difference.

**Comment by bboreham** [comment]
Hello from the bug-scrub!  

@jesusvazquez I see you were assigned - do you think you will get a chance to look at it?

File: config/config.go [hunk 1]
```diff
@@ -1021,6 +1021,19 @@ type TSDBConfig struct {
...
+	// if the number of stale series crosses the given threshold.
+	StaleSeriesCompactionInterval model.Duration `yaml:"stale_series_compaction_interval,omitempty"`
+
+	// StaleSeriesCompactionThreshold is a number between 0.0-1.0 indicating the % of stale series in
+	// the in-memory Head block. If the % of stale series crosses this threshold, stale series
+	// compaction will be run in the next stale series compaction interval.
+	StaleSeriesCompactionThreshold float64 `yaml:"stale_series_compaction_threshold,omitempty"`
+
+	// StaleSeriesImmediateCompactionThreshold is a number between 0.0-1.0 indicating the % of stale series in
+	// the in-memory Head block. If the % of stale series crosses this threshold, stale series is run immediately.
```
Comment (yeya24) [inline config/config.go]: stale series compaction is run immediately

File: tsdb/head_read.go [hunk 2]
```diff
@@ -201,9 +202,112 @@ func (h *headIndexReader) Series(ref storage.SeriesRef, builder *labels.ScratchB
...
+	for p.Next() {
+		s := h.series.getByID(chunks.HeadSeriesRef(p.At()))
+		if s == nil {
+			notFoundSeriesCount++
+			continue
+		}
+
+		s.Lock()
+		if s.ooo != nil {
+			// Has out-of-order data; skip it.
```
Comment (yeya24) [inline tsdb/head_read.go]: Is there any reason why we skip OOO data

Comment (codesome) [reply tsdb/head_read.go]: It's hard to tell if the series is stale if it is getting out of order data. It may have stale sample in the in-order chunk but still getting out of order samples.

**Comment by jesusvazquez** [comment]
I'll have a look at this next week, starting my PTO today for a few days 🙏

**Comment by codesome** [comment]
@jesusvazquez I have synced this PR with main branch and fixed the lint and is ready for review

File: tsdb/db.go [hunk 3]
```diff
@@ -1145,6 +1156,16 @@ func (db *DB) run(ctx context.Context) {
 			}
 			db.cmtx.Unlock()
 
+			// TODO: check if normal compaction is soon, and don't run stale series compaction if it is soon.
```
Comment (jesusvazquez) [inline tsdb/db.go]: What would this take? Tracking time since last compaction in the leveled compactor + an estimated time of the next run based on the compaction interval when prometheus starts?

File: tsdb/db.go [hunk 4]
```diff
@@ -1583,6 +1606,54 @@ func (db *DB) compactHead(head *RangeHead) error {
...
+			return fmt.Errorf("persist stale head: %w", err)
+		}
+
+		db.logger.Info("Stale series block created", "ulids", fmt.Sprintf("%v", uids), "min_time", mint, "max_time", maxt)
+
+		if err := db.reloadBlocks(); err != nil {
+			multiErr := tsdb_errors.NewMulti(fmt.Errorf("reloadBlocks blocks: %w", err))
+			for _, uid := range uids {
+				if errRemoveAll := os.RemoveAll(filepath.Join(db.dir, uid.String())); errRemoveAll != nil {
+					multiErr.Add(fmt.Errorf("delete persisted stale head block after failed db reloadBlocks:%s: %w", uid, errRemoveAll))
```
Comment (jesusvazquez) [inline tsdb/db.go]: I find this bit very defensive but i see it seems its what we've been doing for a long time in the normal compact path too.

File: tsdb/head_read.go [hunk 5]
```diff
@@ -201,6 +202,112 @@ func (h *headIndexReader) Series(ref storage.SeriesRef, builder *labels.ScratchB
...
+// pre-calculated list of stale series refs that can be returned without re-reading the Head.
+type headStaleIndexReader struct {
+	*headIndexReader
+	staleSeriesRefs []storage.SeriesRef
+}
+
+func (h *headStaleIndexReader) Postings(ctx context.Context, name string, values ...string) (index.Postings, error) {
+	// If all postings are requested, return the precalculated list.
+	k, v := index.AllPostingsKey()
+	if len(h.staleSeriesRefs) > 0 && name == k && len(values) == 1 && values[0] == v {
```
Comment (jesusvazquez) [inline tsdb/head_read.go:224]: Is there a fast path here if h.staleSeriesRefs == 0 where you return nothing?

File: tsdb/db.go [hunk 6]
```diff
@@ -1583,6 +1606,54 @@ func (db *DB) compactHead(head *RangeHead) error {
...
+
+		uids, err := db.compactor.Write(db.dir, staleHead, staleHead.MinTime(), staleHead.BlockMaxTime(), meta)
+		if err != nil {
+			return fmt.Errorf("persist stale head: %w", err)
+		}
+
+		db.logger.Info("Stale series block created", "ulids", fmt.Sprintf("%v", uids), "min_time", mint, "max_time", maxt)
+
+		if err := db.reloadBlocks(); err != nil {
+			multiErr := tsdb_errors.NewMulti(fmt.Errorf("reloadBlocks blocks: %w", err))
```
Comment (SuperQ) [inline tsdb/db.go]: FYI, we've dropped the multi-error package in favor of stdlib `errors`.


```suggestion
			errs := []error{fmt.Errorf("reloadBlocks blocks: %w", err)}
```

File: tsdb/db.go (hunk 4 above)
Comment (SuperQ) [inline tsdb/db.go]:
```suggestion
					errs = append(errs, fmt.Errorf("delete persisted stale head block after failed db reloadBlocks:%s: %w", uid, errRemoveAll))
```

File: tsdb/db.go [hunk 7]
```diff
@@ -1583,6 +1606,54 @@ func (db *DB) compactHead(head *RangeHead) error {
...
+			for _, uid := range uids {
+				if errRemoveAll := os.RemoveAll(filepath.Join(db.dir, uid.String())); errRemoveAll != nil {
+					multiErr.Add(fmt.Errorf("delete persisted stale head block after failed db reloadBlocks:%s: %w", uid, errRemoveAll))
+				}
+			}
+			return multiErr.Err()
```
Comment (SuperQ) [inline tsdb/db.go]:
```suggestion
			return errors.Join(errs...)
```

File: tsdb/db.go (hunk 3 above)
Comment (codesome) [reply tsdb/db.go]: I guess that is how we will have to do it. I am thinking to keep a fixed 10m buffer.

File: tsdb/db.go (hunk 4 above)
Comment (codesome) [reply tsdb/db.go]: Since there could be many reasons the reload failed, being defensive seems the best option to avoid data loss.

File: tsdb/head_read.go (hunk 5 above)
Comment (codesome) [reply tsdb/head_read.go:224]: In current usage, it will always enter this `if` block. The rest of the code is for correctness of this function if not stale series refs are provided, and this `if` block is technically the fast path. So it should be okay.

File: tsdb/db.go (hunk 3 above)
Comment (codesome) [reply tsdb/db.go]: One rule is breaks is that TSDB does not assume the unit of time, because to estimate when will be the next compaction, we will need to look at the block range. Since it is just to decide when to not run stale series compaction, it should be okay.

**Comment by codesome** [comment]
> Should we document any recommendations or wait for more user feedback?

We should wait for some user feedback. IMO it's more to do with the pattern in which stale series ratio goes up and down and the memory headroom, and less about the actual value of the ratio. As part of my [upcoming talk](https://www.usenix.org/conference/srecon26americas/presentation/vernekar), I plan to do some more testing for config options.
