### PR TITLE
scraping: limit detail on dropped targets, to save memory

### LINKED ISSUE #12482: Proposal: limit the amount of information stored on dropped targets
### Proposal

As described at #12301, SD may use a lot of memory recording all the labels of any target dropped by rules.
Suppose you have 100,000 Kubernetes pods and have a rule to keep only 2 of them, then Prometheus will store 99,998 sets of information, including all the Kubernetes labels, annotations and other metadata available to relabeling rules.

As far as I can see, the only place this information is used is in rendering the `/service-discovery` page.
However, your browser will crash before it finishes rendering 100,000 targets, so this is of limited use.

My proposal is to change SD to record a limited number of dropped targets, say 20.
Change the UI to add "..." to show that more have been dropped but no details saved.

Maybe, add more advanced tooling to help admins troubleshoot their rules.

### PR DESCRIPTION
**Pull request by bboreham**
Fixes #12482

It's possible (quite common on Kubernetes) to have a service discovery return thousands of targets then drop most of them in relabel rules. The main place this data is used is to display in the web UI, where you don't want thousands of lines of display.

Set a default limit of 100 per job to store full detail, which I picked to be consistent with #4212. It seems that behaviour, of limiting the number drawn in the UI, has disappeared.

Update 2: needed to extend the API to let the UI show correct counts.
Please note I know nothing at all about React programming.

### CODE REVIEW

File: web/ui/react-app/src/pages/serviceDiscovery/Services.tsx [hunk 1]
```diff
@@ -10,10 +10,12 @@ import { API_PATH } from '../../constants/constants';
 import { KVSearch } from '@nexucis/kvsearch';
 import { Container } from 'reactstrap';
 import SearchBar from '../../components/SearchBar';
+import internal from 'stream';
```
Comment (juliusv) [inline web/ui/react-app/src/pages/serviceDiscovery/Services.tsx:13]: Did this line get added by accident? Seems like it shouldn't be there.

File: config/config.go [hunk 2]
```diff
@@ -155,6 +155,7 @@ var (
 		HonorLabels:             false,
 		HonorTimestamps:         true,
 		HTTPClientConfig:        config.DefaultHTTPClientConfig,
+		KeepDroppedTargets:      100,
```
Comment (juliusv) [inline config/config.go:158]: This reads like a boolean option, but I failed to quickly come up with a nice-sounding option that sounds more like a numeric limit, so I guess it's fine unless someone has a better idea :)

**Review by juliusv — COMMENTED** [review]
Nice, I like it. But are we allowed to change the default? We publicly document this API at https://prometheus.io/docs/prometheus/latest/querying/api/#targets and we promise stability for the HTTP API at https://prometheus.io/docs/prometheus/latest/stability/#api-stability-guarantees.

File: web/ui/react-app/src/pages/serviceDiscovery/Services.tsx (hunk 1 above)
Comment (bboreham) [reply web/ui/react-app/src/pages/serviceDiscovery/Services.tsx]: Removed.

**Comment by juliusv** [comment]
I mean honestly I'm all for breaking minor things like this, but I also wouldn't be surprised if someone out there was using this API in some large scenario to get all discovered targets. @roidelapluie what do you think?

> Adding `droppedTargetCounts` is a change to the API, albeit backwards-compatible. Would that be allowed, or does this have to be on a new path?

That's totally fine, just breaking changes like returning fewer targets than before (by default) would technically be disallowed by our promises. Whether we want to follow those promises to that degree is a matter of debate...

**Comment by bboreham** [comment]
I changed the default to 0, meaning no limit.
Also added as a global option, and added that to the Kubernetes example config.

Commits should be squashed before merging.

File: docs/configuration/configuration.md [hunk 3]
```diff
@@ -106,6 +106,10 @@ global:
   # change in the future.
   [ target_limit: <int> | default = 0 ]
 
+  # Per-job limit on the number of targets dropped by relabeling
+  # that will be kept in memory. 0 means no limit.
+	[ keep_dropped_targets: <int> | default = 0 ]
```
Comment (juliusv) [inline docs/configuration/configuration.md:111]: There seems to be a tab indent here which should be a two-space indent.

File: docs/configuration/configuration.md [hunk 4]
```diff
@@ -106,6 +106,10 @@ global:
   # change in the future.
   [ target_limit: <int> | default = 0 ]
 
+  # Per-job limit on the number of targets dropped by relabeling
```
Comment (juliusv) [inline docs/configuration/configuration.md:109]: This is not per job, but per scrape pool, which to the user is exposed as a scrape config (there can be multiple jobs per scrape config if targets have a `job` label set that overrides the scrape config's default job name). So I'd say "Per-scrape-config limit ..." or "Limit per scrape config ..." (less hyphenated) or something like that.

**Review by juliusv — COMMENTED** [review]
:+1: besides last comments

**Review by roidelapluie — APPROVED** [review]
LGTM!

**Comment by bboreham** [comment]
Note there was a bug, which required #12726.
