### PR TITLE
bug: Fix quality value in accept header

### LINKED ISSUE #13268: Quality values in Accept header in 2.48.0 are wrong
### What did you do?

After updating Prometheus to 2.48.0, Spring Boot Actuator metrics are no longer being collected.

### What did you expect to see?

It should also work correctly with 2.48.0.

### What did you see instead? Under which circumstances?

Before 2.47.2, the following Accept headers were sent
```
application/openmetrics-text;version=1.0.0,application/openmetrics-text;version=0.0.1;q=0.75,text/plain;version=0.0.4;q=0.5,*/*;q=0.1
```
In 2.48.0, the following Accept header is sent, but `*/*;q=2` is incorrect, resulting in an error in Spring Boot.
```
application/openmetrics-text;version=1.0.0;q=0.5,application/openmetrics-text;version=0.0.1;q=0.4,text/plain;version=0.0.4;q=0.3,*/*;q=2
```

Quality Values is incorrect because it ranges from 0 through 1.
https://www.rfc-editor.org/rfc/rfc9110.html#name-quality-values

### System information

Linux 5.15.133.1-microsoft-standard-WSL2 x86_64

### Prometheus version

```text
prometheus, version 2.48.0 (branch: main, revision: e4ec263bcc11493953c75d1b2e7bc78fd0463e05)
  build user:       root@aad5af94daee
  build date:       20231201-22:28:13
  go version:       go1.21.4
  platform:         linux/amd64
  tags:             netgo,builtinassets,stringlabels
```

### Prometheus configuration file

_No response_

### Alertmanager version

_No response_

### Alertmanager configuration file

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by kalpadiptyaroy**
Fixed #13268 - Now 'q' value will be strictly within the range of 0 to 1.

### CODE REVIEW

File: scrape/scrape.go [hunk 1]
```diff
@@ -675,7 +675,7 @@ func acceptHeader(sps []config.ScrapeProtocol) string {
 		weight--
 	}
 	// Default match anything.
-	vals = append(vals, fmt.Sprintf("*/*;q=%d", weight))
+	vals = append(vals, fmt.Sprintf("*/*;q=%d", weight-1))
```
Comment (rocketraman) [inline scrape/scrape.go:678]: The current quality value of `*/*` is 2.0 -- subtracting 1 will result in a quality value of 1.0 which is a higher precedence than `application/openmetrics-text` and `text/plain`. Wouldn't it be better to match the old behavior of Prometheus which assigned 0.1 to `*/*`?

Comment (yu-shiba) [reply scrape/scrape.go:678]: Hi, @kalpadiptyaroy @rocketraman, 
I am a former ticket reporter.

When I first discovered the problem we thought it would be appropriate to fix it as follows:
```golang
vals = append(vals, fmt.Sprintf("*/*;q=0.%d", weight))
```
By using this code, qvalue becomes `0.2` and the problem is avoided.

However, we also question whether this is the correct way to calculate weight.
I think you should ask the person involved in #12738 to check the specifications.

Comment (kalpadiptyaroy) [reply scrape/scrape.go:678]: @yu-shiba. I have gone through the issue #12738. This issue is more about bringing in flexibility to the Accept header definitions, such that it is not hardcoded. So let's not consider it as of now.

@rocketraman your suggestion too is good, but my perspective to this is as follows:
If we hardcode the `q` value for `text/plain` as `0.1` then later on their is a probability of confusion for the maintainers, that why `text/plain` is getting a special preference, when as per https://www.rfc-editor.org/rfc/rfc9110.html#name-accept specification, `q` value must be relative and calculated via normalisation
func. , hence I would like to go with @yu-shiba 's solution, since that will preserve the relative factor and avoid confusion.

```suggestion
	vals = append(vals, fmt.Sprintf("*/*;q=0.%d", weight))
```

Still I would like everyone to agree on a common point before merging this!

Comment (rocketraman) [reply scrape/scrape.go]: > per https://www.rfc-editor.org/rfc/rfc9110.html#name-accept specification, q value must be relative and calculated via normalisation

RFC says:

* It is relative to other q values
* It is normalized to a value between 0 and 1

It does *not* say it needs to be calculated. For example, if all values are tenths, `*/*` could be hard-coded to a hundredths value, like `0.01` and this would guarantee that both conditions from the RFC are met.

All that being said, the code of `0.%d` should in fact result in `0.1` for `*/*` anyway  if I'm reading this code right (not `0.2` as mentioned above by @yu-shiba ), so that approach is fine and makes sense to me.

Comment (rocketraman) [reply scrape/scrape.go]: Note also this code fails to produce a sensible result if there are 9 or more scrape protocols passed in! Probably not something we need to worry about now. :-)

Comment (kalpadiptyaroy) [reply scrape/scrape.go]: @rocketraman Noted and generalised for any number of scrape protocols.

Comment (yu-shiba) [reply scrape/scrape.go]: @kalpadiptyaroy Perhaps not the intended result?
```
application/openmetrics-text;version=1.0.0;q=0.500000,application/openmetrics-text;version=0.0.1;q=0.500000,text/plain;version=0.0.4;q=0.500000,*/*;q=0.500000
```
Also, if we are serious about the calculation, `%f` is dangerous in light of the RFC.
> ```
>   weight = OWS ";" OWS "q=" qvalue
>   qvalue = ( "0" [ "." 0*3DIGIT ] )
>          / ( "1" [ "." 0*3("0") ] )
> ```
It is better to specify the width.
```
"%.3g"
```

@rocketraman I thought it was 0.1 too, but the initial value of weight is the number of [ScrapeProtocolsHeaders](https://github.com/prometheus/prometheus/blob/main/config/config.go#L450).
This is why the qvalue results seem to differ from intuition.

**Comment by kalpadiptyaroy** [comment]
@yu-shiba Thanks for clarifying the `no. of digits <= 3 constraint`. I have reverted the changes. But, I think this constraint will not be violated if the number of Scrape Protocol Headers count remains below `1000`.

**Comment by roidelapluie** [comment]
Thanks!

**Comment by MVKozlov** [comment]
@kalpadiptyaroy,
`This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.`
and it not included in v2.49.0
