### PR TITLE
Check that rules don't contain metrics with the same labelset

### LINKED ISSUE #5529: Random value in recording rule with multiple identical series result
## Bug Report
**What did you do?**
Not sure if proposal of bug report but when recording rule expression results to multiple series with different values and has the `labels` section specified which will cause the two series having exact same labels. This results to recorded serie which will have randomly value of one of those values because of random ordering.

Simple example:
```yaml
 groups:
     - name: "test"
       interval: "1s"
       rules:
         - record: test_metric
           expr: "0"
           labels:
               label: "value"
         - record: "test_metric"
           expr: "1"
         - record: "result"
           expr: "max(test_metric) by (label)"
           labels:
               label: "value"
```

Will result to:
image

I understand that it is users responsibility to make sure the resulting metrics won't be identical, but on the other hand I'd expect this to result as a failed rule evaluation or at least log something or increment metric about it?
This way user has no notice that the data he has recorded are invalid.

### PR DESCRIPTION
**Pull request by roidelapluie**
Closes #5529

Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

### CODE REVIEW

**Comment by juliusv** [comment]
Have you looked into how doable it would be to fix this on the TSDB side instead? There are error codes defined there that aren't returned correctly at the moment in this scenario (duplicate series in the same batch), and I wonder if alerting rules (`ALERTS` time series) and ingestion could be affected as well.

**Comment by brian-brazil** [comment]
This is the correct fix from the Prometheus standpoint, the TSDB at most would silently drop some of the data - which is what we're trying to fix here. I'll give a proper review in the morning.

**Comment by roidelapluie** [comment]
It is tricker with alerts - what to do with same alertset ? Fail and let them expire? Fail and don't make them fire?

**Comment by juliusv** [comment]
> This is the correct fix from the Prometheus standpoint, the TSDB at most would silently drop some of the data - which is what we're trying to fix here. I'll give a proper review in the morning.

What's the reason not to fix this in the TSDB though? Is it infeasible? The TSDB already tries to detect this situation (via `ErrAmendSample`), but currently doesn't do so correctly if the conflicting sample is in the same batch. So without understanding more I would have assumed that that's the right place to fix it. But maybe you also want to really ensure here that the entire vector fails if it contains duplicates?

**Comment by juliusv** [comment]
> It is tricker with alerts - what to do with same alertset ? Fail and let them expire? Fail and don't make them fire? As they will end up being the same in TSDB I would let them as is

At least it should detect the situation and log an error so that someone has a chance of catching it. Not sure if other behavioral changes make sense there, yeah.

**Comment by brian-brazil** [comment]
> What's the reason not to fix this in the TSDB though?

Better error reporting in the TSDB wouldn't hurt but doesn't solve the problem here.

> At least it should detect the situation and log an error so that someone has a chance of catching it.

PromQL will report an error if you try to do this sort of thing, however as alert templating is messing about with labels outside of PromQL we need to duplicate that logic here.

This should look the same as any other PromQL error during rule execution.

File: rules/recording.go [hunk 1]
```diff
@@ -93,6 +93,16 @@ func (rule *RecordingRule) Eval(ctx context.Context, ts time.Time, query QueryFu
 
 		sample.Metric = lb.Labels()
 	}
+
+	// Check that the rule does not produce identical metrics after applying
+	// labels #5529
```
Comment (brian-brazil) [inline rules/recording.go]: I'd put the reference to the issue in the unittest. This isn't some weird corner case, it's a design thing so feels weird to document by bug.

File: rules/recording.go [hunk 2]
```diff
@@ -93,6 +93,16 @@ func (rule *RecordingRule) Eval(ctx context.Context, ts time.Time, query QueryFu
 
 		sample.Metric = lb.Labels()
 	}
+
+	// Check that the rule does not produce identical metrics after applying
```
Comment (brian-brazil) [inline rules/recording.go]: full stop

File: rules/recording.go [hunk 3]
```diff
@@ -93,6 +93,16 @@ func (rule *RecordingRule) Eval(ctx context.Context, ts time.Time, query QueryFu
...
+	// labels #5529
+	if vector.ContainsSameLabelset() {
+		err = fmt.Errorf("resulting vector cannot contain metrics with the same labelset")
```
Comment (brian-brazil) [inline rules/recording.go]: I'd make this more in line with the error inside PromQL, but also indicating that this is related to templating and not PromQL per-se.

**Comment by juliusv** [comment]
@brian-brazil Ok yeah, makes sense. Still think it'd be good to fix the TSDB as well, but can be separate.

**Comment by roidelapluie** [comment]
ready for a second pass

File: rules/alerting.go [hunk 4]
```diff
@@ -404,6 +407,16 @@ func (r *AlertingRule) Eval(ctx context.Context, ts time.Time, query QueryFunc,
 		}
 	}
 
+	// Check that the alert does not produce identical metrics after applying
+	// labels.
+	if res.ContainsSameLabelset() {
+		level.Warn(r.logger).Log("msg", "Ooops")
```
Comment (brian-brazil) [inline rules/alerting.go]: Debugging?

File: rules/alerting.go [hunk 5]
```diff
@@ -404,6 +407,16 @@ func (r *AlertingRule) Eval(ctx context.Context, ts time.Time, query QueryFunc,
...
+		err = fmt.Errorf("vector cannot contain metrics with the same labelset after applying extra labels")
```
Comment (brian-brazil) [inline rules/alerting.go]: vector contains metrics with the same labelset after applying rule/alert labels

File: rules/alerting.go [hunk 6]
```diff
@@ -311,7 +311,9 @@ func (r *AlertingRule) Eval(ctx context.Context, ts time.Time, query QueryFunc,
 	resultFPs := map[uint64]struct{}{}
 
 	var vec promql.Vector
-	for _, smpl := range res {
+	for i := range res {
```
Comment (brian-brazil) [inline rules/alerting.go]: Why this change?

Comment (roidelapluie) [reply rules/alerting.go]: To get the pointer and be able to change the sample in place

Comment (brian-brazil) [reply rules/alerting.go]: What's that got to do with this PR?

Comment (roidelapluie) [reply rules/alerting.go]: I need to alter the 'res' vector to look for common labels

Comment (brian-brazil) [reply rules/alerting.go]: I'm not seeing it, ContainsSameLabelset doesn't alter the vector.

Comment (roidelapluie) [reply rules/alerting.go]: It does not but we must have a vector to run it against.

Comment (brian-brazil) [reply rules/alerting.go]: Ah, I see what you're up to now.

File: rules/alerting_test.go [hunk 7]
```diff
@@ -289,3 +292,38 @@ func TestAlertingRuleEmptyLabelFromTemplate(t *testing.T) {
...
+		expr,
+		time.Minute,
+		labels.FromStrings("test", "test"),
+		nil,
+		nil,
+		true, log.NewNopLogger(),
+	)
+	_, err := rule.Eval(ctx, now, EngineQueryFunc(engine, storage), nil)
+	testutil.NotOk(t, err)
+	fmt.Println(err.Error())
```
Comment (brian-brazil) [inline rules/alerting_test.go]: This line should go.

Comment (roidelapluie) [reply rules/alerting_test.go]: updated

File: rules/alerting.go [hunk 8]
```diff
@@ -404,6 +407,15 @@ func (r *AlertingRule) Eval(ctx context.Context, ts time.Time, query QueryFunc,
 		}
 	}
 
+	// Check that the alert does not produce identical metrics after applying
```
Comment (brian-brazil) [inline rules/alerting.go]: What happens to h.active etc. above? We should probably do this check before all that, so this has the same effect as a query failure.

Comment (roidelapluie) [reply rules/alerting.go]: @brian-brazil in that case I completely changed the way we check for duplicate alerts

File: rules/alerting.go [hunk 9]
```diff
@@ -361,15 +362,16 @@ func (r *AlertingRule) Eval(ctx context.Context, ts time.Time, query QueryFunc,
...
 		resultFPs[h] = struct{}{}
 
-		// Check whether we already have alerting state for the identifying label set.
-		// Update the last value and annotations if so, create a new alert entry otherwise.
-		if alert, ok := r.active[h]; ok && alert.State != StateInactive {
-			alert.Value = smpl.V
-			alert.Annotations = annotations
-			continue
+		if _, ok := alerts[h]; ok {
+			err = fmt.Errorf("vector contains metrics with the same labelset after applying rule/alert labels")
```
Comment (brian-brazil) [inline rules/alerting.go]: we're in the alert file, we know it's an alert

Comment (roidelapluie) [reply rules/alerting.go]: fixed

**Comment by brian-brazil** [comment]
Thanks!
