### PR TITLE
Reuse the same appender for report and scrape

### LINKED ISSUE #6950: Ingestion: Use the same appender for regular samples and reporting (`up` and friends)
This is a follow-up issue to #1893.

The regular samples are appended to TSDB with an appender that is committed or rolled-back, depending on success or failure. After that, a new appender is created to append the reporting samples (`up`, `scrape_...`, etc.). The problem with this approach is that the reporting samples will become visible to the query engine a bit after the regular samples are visible.

To fix this, only one appender has to be used for both samples in the case of success. If appending the regular samples already fails for some reason, that appender has to be rolled back and a new appender has to be used for the reporting samples (which still need to be appended because `up` is now 0). If all looks successful but then the final commit for the one appender errors out, things are most likely so broken that we don't need to retry appending with just the reporting samples.

### PR DESCRIPTION
**Pull request by roidelapluie**
Fix  #6950

Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

### CODE REVIEW

File: scrape/scrape.go [hunk 1]
```diff
@@ -1005,6 +951,83 @@ mainLoop:
 	}
 }
 
+// scrapeAndReport is responsible for running a scape, and inserting with its
```
Comment (beorn7) [inline scrape/scrape.go:954]: scape → scrape

File: scrape/scrape.go [hunk 2]
```diff
@@ -1005,6 +951,83 @@ mainLoop:
...
+// report in the storage, with a single appender.
```
Comment (beorn7) [inline scrape/scrape.go:955]: Suggested rewording: "scrapeAndReport performs a scrape and then appends the result to the storage together with reporting metrics, all using the same appender."

**Comment by roidelapluie** [comment]
Thanks for the review, I have addressed the comments.

**Comment by roidelapluie** [comment]
@beorn7 I added another commit, which makes the end of run staleness consistent.

Also now it takes into consideration that Commit() will do a Rollback() if things go mad.

File: scrape/scrape_test.go [hunk 3]
```diff
@@ -1928,3 +1970,66 @@ func TestCheckAddError(t *testing.T) {
 	sl.checkAddError(nil, nil, nil, storage.ErrOutOfOrderSample, nil, &appErrs)
 	testutil.Equals(t, 1, appErrs.numOutOfOrder)
 }
+
+func TestScrapeReportIsolation(t *testing.T) {
```
Comment (brian-brazil) [inline scrape/scrape_test.go:1974]: I'm not seeing how this is testing isolation, as there's nothing to ensure the query runs between the scrape ingestion and the report ingestion.

File: scrape/scrape.go [hunk 4]
```diff
@@ -932,77 +932,99 @@ mainLoop:
...
-				sl.lastScrapeSize = len(b)
-			}
-		} else {
-			level.Debug(sl.l).Log("msg", "Scrape failed", "err", scrapeErr.Error())
-			if errc != nil {
-				errc <- scrapeErr
-			}
-		}
+// scrapeAndReport performs a scrape and then appends the result to the storage
+// together with reporting metrics, all using the same appender.
```
Comment (brian-brazil) [inline scrape/scrape.go:955]: "the same" is a little misleading as a 2nd appender will be created if there's a scrape error.

File: scrape/scrape.go [hunk 5]
```diff
@@ -932,77 +932,99 @@ mainLoop:
...
 		}
-		last = start
+	}
 
-		select {
-		case <-sl.parentCtx.Done():
-			close(sl.stopped)
+	app := sl.appender()
+	var err error
+	defer func() {
```
Comment (brian-brazil) [inline scrape/scrape.go:992]: There's no early returns, so I don't see a need to use a defer here compared to putting this code at the end of the function - which would be clearer.

Comment (roidelapluie) [reply scrape/scrape.go:992]: We guard ourselves against potential panic()

File: scrape/scrape_test.go (hunk 3 above)
Comment (roidelapluie) [reply scrape/scrape_test.go:1974]: Queries run continuously. We should always have a multiple of 9 metrics.

That test is failing almost instantly without the code.

Comment (beorn7) [reply scrape/scrape_test.go:1974]: Yes, I was assuming it would happen as @roidelapluie has confirmed now.

File: scrape/scrape.go (hunk 4 above)
Comment (beorn7) [reply scrape/scrape.go:955]: But in case of a scrape error, the 1st appender is rolled back, so it will not append anything to the storage, so only one and the same appender will ever append any samples to the storage.

But if you have a better suggestion for the wording, I'm sure @roidelapluie will appreciate it.

Comment (roidelapluie) [reply scrape/scrape.go:955]: // scrapeAndReport performs a scrape and then appends the result to the storage
// together with reporting metrics, by using as few appenders as possible.
// In the happy scenario, a single appender is used.

**Comment by beorn7** [comment]
Is this good to go @brian-brazil ? Would be great to have this in the release.

**Comment by beorn7** [comment]
Or in case @brian-brazil is busy, I guess @codesome or @krasi-georgiev are qualified here, too, as it is close to TSDB.

File: scrape/scrape_test.go (hunk 3 above)
Comment (brian-brazil) [reply scrape/scrape_test.go:1974]: The test name is misleading, as this doesn't test anything about isolation per-se. What it's testing is that it's all done in one append.

Comment (beorn7) [reply scrape/scrape_test.go:1974]: @roidelapluie that name should be easy to fix.
@brian-brazil is that the only remaining concern in this PR?

Comment (brian-brazil) [reply scrape/scrape_test.go:1974]: Yes, the rest I can live with.

Comment (roidelapluie) [reply scrape/scrape_test.go]: Renamed. I originally named it like this because if the underlying appender does not support isolation, the test failed as well.

**Comment by brian-brazil** [comment]
:+1:

**Comment by beorn7** [comment]
:smile: Thanks everyone.
