### PR TITLE
Kubernetes SD: Add labels for all node addresses and discover node port

### LINKED ISSUE #1680: [v0.19.1]K8S SD failing if the cluster is in OpenStack
OpenStack utilizes 2 IP Addresses. A Private (Management IP) and a Public (Floating) IP.
with 0.19.1; Prometheus is only detecting the Private IP; thus it fails it's probe when hitting the Node Port and cAdvisor port.

screen shot 2016-05-27 at 11 47 20 am

If I hit that same path using the Public (FloatingIP) that's tied to that endpoint; the /metrics page pulls up just fine.

So; is this a Prometheus issue? or a Kubernetes issue?
I'm going through both repos to see where the problem might be coming from.
This worked fine using the 0.19.0 container; started failing with 0.19.1.

### PR DESCRIPTION
**Pull request by jimmidyson**
Fixes #1680 by allowing relabelling to any discovered node IP.

Also switches to discovered node port if available via API, overriding default configured node port.

### CODE REVIEW

File: retrieval/discovery/kubernetes/discovery.go [hunk 1]
```diff
@@ -292,18 +297,31 @@ func (kd *Discovery) updateNodesTargetGroup() *config.TargetGroup {
...
+
+		address := fmt.Sprintf("%s:%d", defaultNodeAddress.String(), kubeletPort)
 
 		t := model.LabelSet{
 			model.AddressLabel:  model.LabelValue(address),
 			model.InstanceLabel: model.LabelValue(nodeName),
 		}
+
+		for addrType, ip := range nodeAddressMap {
+			labelName := strutil.SanitizeLabelName(nodeAddressPrefix + toSnake(string(addrType)))
```
Comment (brian-brazil) [inline retrieval/discovery/kubernetes/discovery.go]: We usually only sanitize

File: retrieval/discovery/kubernetes/discovery.go [hunk 2]
```diff
@@ -292,18 +297,31 @@ func (kd *Discovery) updateNodesTargetGroup() *config.TargetGroup {
...
 	for nodeName, node := range kd.nodes {
-		nodeAddress, err := nodeHostIP(node)
+		defaultNodeAddress, nodeAddressMap, err := nodeAddresses(node)
 		if err != nil {
 			log.Debugf("Skipping node %s: %s", node.Name, err)
 			continue
 		}
 
-		address := fmt.Sprintf("%s:%d", nodeAddress.String(), kd.Conf.KubeletPort)
+		kubeletPort := int(node.Status.DaemonEndpoints.KubeletEndpoint.Port)
```
Comment (brian-brazil) [inline retrieval/discovery/kubernetes/discovery.go]: Can we expect this to usually be present? If so we can remove the config option.

File: retrieval/discovery/kubernetes/discovery.go (hunk 1 above)
Comment (jimmidyson) [inline retrieval/discovery/kubernetes/discovery.go]: So leave labels as `__meta_kubernetes_node_address_InternalIP`, etc? Don't mind either way personally but seems tidier to snake case it.

File: retrieval/discovery/kubernetes/discovery.go (hunk 2 above)
Comment (jimmidyson) [inline retrieval/discovery/kubernetes/discovery.go]: From Kubernetes 1.1 yes I would assume it to be present. I'm not sure what versions we should be supporting but from what I've seen the majority of Kubernetes users seem to upgrade reasonably quickly to take advantage of new features so wouldn't expect too many installations on < 1.1 (no hard numbers on that though).

File: retrieval/discovery/kubernetes/discovery.go (hunk 1 above)
Comment (brian-brazil) [inline retrieval/discovery/kubernetes/discovery.go]: When the label name is coming from the 3rd party system, that's what we usually do.

File: retrieval/discovery/kubernetes/discovery.go (hunk 2 above)
Comment (brian-brazil) [inline retrieval/discovery/kubernetes/discovery.go]: 1.1 was Sep 2015, so I'd say it's safe to remove it. Worst case it'll use 0.

Comment (jimmidyson) [inline retrieval/discovery/kubernetes/discovery.go]: Removed config option.

File: retrieval/discovery/kubernetes/discovery.go (hunk 1 above)
Comment (jimmidyson) [inline retrieval/discovery/kubernetes/discovery.go]: Done.

File: retrieval/discovery/kubernetes/discovery.go [hunk 3]
```diff
@@ -778,28 +792,33 @@ func until(f func(), period time.Duration, stopCh <-chan struct{}) {
...
 // 3. NodeLegacyHostIP
 //
 // Copied from k8s.io/kubernetes/pkg/util/node/node.go
-func nodeHostIP(node *Node) (net.IP, error) {
+func nodeAddresses(node *Node) (net.IP, map[NodeAddressType][]net.IP, error) {
 	addresses := node.Status.Addresses
-	addressMap := make(map[NodeAddressType][]NodeAddress)
-	for i := range addresses {
-		addressMap[addresses[i].Type] = append(addressMap[addresses[i].Type], addresses[i])
+	addressMap := make(map[NodeAddressType][]net.IP)
```
Comment (brian-brazil) [inline retrieval/discovery/kubernetes/discovery.go]: `map[NodeAddressType][]net.IP{}` is idiomatic.

Comment (jimmidyson) [inline retrieval/discovery/kubernetes/discovery.go]: Updated.

**Comment by brian-brazil** [comment]
Thanks!

**Comment by jimmidyson** [comment]
You're very welcome :)
