### PR TITLE
promtool: Fix credentials file check

### LINKED ISSUE #9874: [Promtool] `promtool check config` doesn't properly check `bearer_token_file` file existence
**What did you do?**

While working on #5222, I was trying to reproduce the error with `bearer_token_file`. I ran `promtool check config $my_config` against a config file that has `bearer_token_file` set to a path to a file that doesn't exist.

**What did you expect to see?**

Promtool should fail, as it explicitly checks if a file exists for the `bearer_token_file` path.

**What did you see instead? Under which circumstances?**

Promtool check succeeded. During unmarshalling of configs, they'll call `c.HTTPClientConfig.Validate()`. This [validate function moves](https://github.com/prometheus/common/blob/ce7006ede1b27960d267508d7ae0af2f51422610/config/http_config.go#L243-L252) the `bearer_token_file` info to `Authorization.CredentialsFile` and sets `bearer_token_file` to `""`. So when promtool goes to check the config struct, it [only checks the `bearer_token_file`](https://github.com/prometheus/prometheus/blob/b48a1e9e9bc3575e2f6ef3e7ea8573434288e0bb/cmd/promtool/main.go#L356-L358) which is set to empty string.

If we want to keep the same functionality, we need to update this check to look at `config.HTTPClientConfig.Authorization.CredentialsFile` instead.

**Environment**

* System information:

Darwin 21.0.1 arm64

* Prometheus version:

prometheus, version 2.32.0-beta.0 (branch: main, revision: 4cae788689121b624557c63d955fbffeef1a91e9)
  build user:       Me
  build date:       20211123-18:19:06
  go version:       go1.17.3
  platform:         darwin/arm64

### PR DESCRIPTION
**Pull request by fpetkovski**
The promtool check config command still uses the bearer_token_file
field which is deprecated in favour of authorization.credentials_file.

This commit modifies the command to use the new field insted.

Fixes #9874

Signed-off-by: fpetkovski <filip.petkovsky@gmail.com>

### CODE REVIEW

File: cmd/promtool/main.go [hunk 1]
```diff
@@ -353,8 +353,9 @@ func checkConfig(agentMode bool, filename string) ([]string, error) {
 	}
 
 	for _, scfg := range cfg.ScrapeConfigs {
-		if err := checkFileExists(scfg.HTTPClientConfig.BearerTokenFile); err != nil {
-			return nil, errors.Wrapf(err, "error checking bearer token file %q", scfg.HTTPClientConfig.BearerTokenFile)
+		authzSet := scfg.HTTPClientConfig.Authorization != nil
+		if err := checkFileExists(scfg.HTTPClientConfig.Authorization.CredentialsFile); authzSet && err != nil {
```
Comment (fpetkovski) [inline cmd/promtool/main.go:357]: The compiler seems to be smart enough to not run `err := ...` if `authzSet` is already false. This is quite neat since it avoids using a nested `if` statement.

**Review by DrAuYueng — COMMENTED** [review]
No need authzSet judgement in statement `authzSet && err != nil`.

**Comment by fpetkovski** [comment]
Thanks @DrAuYueng, should be removed now.

File: cmd/promtool/main.go [hunk 2]
```diff
@@ -353,8 +353,11 @@ func checkConfig(agentMode bool, filename string) ([]string, error) {
...
 
 	for _, scfg := range cfg.ScrapeConfigs {
-		if err := checkFileExists(scfg.HTTPClientConfig.BearerTokenFile); err != nil {
-			return nil, errors.Wrapf(err, "error checking bearer token file %q", scfg.HTTPClientConfig.BearerTokenFile)
+		authzSet := scfg.HTTPClientConfig.Authorization != nil
+		if authzSet {
+			if err := checkFileExists(scfg.HTTPClientConfig.Authorization.CredentialsFile); err != nil {
+				return nil, errors.Wrapf(err, "error checking authorization credentials file %q", scfg.HTTPClientConfig.Authorization.CredentialsFile)
+			}
 		}
```
Comment (JessicaGreben) [inline cmd/promtool/main.go:361]: curious if we should have an `else` block that still supports bearer token? Not sure if anyone would still be using that?

Comment (LeviHarrison) [reply cmd/promtool/main.go:361]: common is moving `BearerTokenFile` into `CredentialsFile`, so it's not possible that `BearerTokenFile` is being used.

https://github.com/prometheus/common/blob/ce7006ede1b27960d267508d7ae0af2f51422610/config/http_config.go#L243-L252

File: cmd/promtool/main.go [hunk 3]
```diff
@@ -353,8 +353,11 @@ func checkConfig(agentMode bool, filename string) ([]string, error) {
 	}
 
 	for _, scfg := range cfg.ScrapeConfigs {
-		if err := checkFileExists(scfg.HTTPClientConfig.BearerTokenFile); err != nil {
-			return nil, errors.Wrapf(err, "error checking bearer token file %q", scfg.HTTPClientConfig.BearerTokenFile)
+		authzSet := scfg.HTTPClientConfig.Authorization != nil
+		if authzSet {
```
Comment (LeviHarrison) [inline cmd/promtool/main.go:357]: nit: this variable isn't really needed.

```suggestion
		if scfg.HTTPClientConfig.Authorization != nil {
```

File: cmd/promtool/main_test.go [hunk 4]
```diff
@@ -203,3 +204,40 @@ func TestCheckTargetConfig(t *testing.T) {
...
+			_, err := checkConfig(false, "testdata/"+test.file)
+
+			if runtime.GOOS != "windows" && test.err != "" {
+				require.Equal(t, test.err, err.Error(), "Expected error %q, got %q", test.err, err.Error())
+				return
+			}
+			if runtime.GOOS == "windows" && test.errWin != "" {
+				require.Equal(t, test.errWin, err.Error(), "Expected error %q, got %q", test.err, err.Error())
+				return
+			}
```
Comment (LeviHarrison) [inline cmd/promtool/main_test.go:239]: While accounting for operating systems' different error messages is nice, I think it would be simpler to just check if the error contains the part of the message we generate (`error checking authorization credentials file`).

```suggestion
			if test.err != "" {
				require.Contains(t, err.Error(), t.err, "Expected error %q to contain %q", err.Error(), test.err)
				return
			}
```

**Review by LeviHarrison — COMMENTED** [review]
Thanks!

File: cmd/promtool/main.go [hunk 5]
```diff
@@ -353,8 +353,10 @@ func checkConfig(agentMode bool, filename string) ([]string, error) {
 	}
 
 	for _, scfg := range cfg.ScrapeConfigs {
-		if err := checkFileExists(scfg.HTTPClientConfig.BearerTokenFile); err != nil {
-			return nil, errors.Wrapf(err, "error checking bearer token file %q", scfg.HTTPClientConfig.BearerTokenFile)
+		if scfg.HTTPClientConfig.Authorization != nil {
+			if err := checkFileExists(scfg.HTTPClientConfig.Authorization.CredentialsFile); err != nil {
+				return nil, errors.Wrapf(err, "error checking authorization credentials file %q", scfg.HTTPClientConfig.Authorization.CredentialsFile)
```
Comment (LeviHarrison) [inline cmd/promtool/main.go:358]: This could also be the bearer token file, so we should specify that in the error message to avoid confusion.

```suggestion
				return nil, errors.Wrapf(err, "error checking authorization credentials or bearer token file %q", scfg.HTTPClientConfig.Authorization.CredentialsFile)
```

Comment (fpetkovski) [reply cmd/promtool/main.go]: Ah yes, bearer token files are still accepted. Updated the message.

**Review by LeviHarrison — APPROVED** [review]

**Review by dgl — APPROVED** [review]

**Comment by dgl** [comment]
Thanks!
