### PR TITLE
discovery - handle Discoverers that send only target Group updates.

### LINKED ISSUE #3653: invalid memory address or nil pointer dereference
**What did you do?**

I ran the latest build from master, and it paniced.

**What did you expect to see?**

Happy Prometheus.

**What did you see instead? Under which circumstances?**

```
level=info ts=2018-01-04T12:34:30.797481431Z caller=main.go:221 msg="Starting Prometheus" version="(version=2.0.0, branch=master, revision=ec94df49d45baa8e680d81e732294eb04fff00de)"
level=info ts=2018-01-04T12:34:30.797587605Z caller=main.go:222 build_context="(go=go1.9.2, user=root@1885792ecf46, date=20171229-20:03:34)"
level=info ts=2018-01-04T12:34:30.797618333Z caller=main.go:223 host_details="(Linux 4.4.64+ #1 SMP Wed Aug 30 20:27:36 PDT 2017 x86_64 weave-cortex-agent-1352299515-q9b40 (none))"
level=info ts=2018-01-04T12:34:30.797643323Z caller=main.go:224 fd_limits="(soft=1048576, hard=1048576)"
level=info ts=2018-01-04T12:34:30.802483848Z caller=manager.go:58 component="scrape manager" msg="Starting scrape manager..."
level=info ts=2018-01-04T12:34:30.802561868Z caller=main.go:434 msg="Starting TSDB ..."
level=info ts=2018-01-04T12:34:30.806440473Z caller=web.go:383 component=web msg="Start listening for connections" address=:8080
level=info ts=2018-01-04T12:34:30.812878794Z caller=main.go:444 msg="TSDB started"
level=info ts=2018-01-04T12:34:30.812978586Z caller=main.go:511 msg="Loading configuration file" filename=/etc/prometheus/prometheus.yml
level=info ts=2018-01-04T12:34:30.814840891Z caller=kubernetes.go:191 component="discovery manager" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2018-01-04T12:34:30.816859216Z caller=kubernetes.go:191 component="discovery manager" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2018-01-04T12:34:30.817553956Z caller=kubernetes.go:191 component="discovery manager" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2018-01-04T12:34:30.818090353Z caller=kubernetes.go:191 component="discovery manager" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2018-01-04T12:34:30.81978125Z caller=kubernetes.go:191 component="discovery manager" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2018-01-04T12:34:30.821172572Z caller=main.go:421 msg="Server is ready to receive requests."
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x155d32a]

goroutine 123 [running]:
github.com/prometheus/prometheus/discovery.(*Manager).allGroups.func1(0x29062c0, 0xc420402c00)
	/go/src/github.com/prometheus/prometheus/discovery/manager.go:188 +0x28a
github.com/prometheus/prometheus/discovery.(*Manager).Run(0xc4203a9700, 0x29062c0, 0xc420402c00, 0x0, 0x0)
	/go/src/github.com/prometheus/prometheus/discovery/manager.go:96 +0x54
main.main.func5(0x0, 0x0)
	/go/src/github.com/prometheus/prometheus/cmd/prometheus/main.go:338 +0x52
github.com/prometheus/prometheus/vendor/github.com/oklog/oklog/pkg/group.(*Group).Run.func1(0xc420052240, 0xc42047fb60, 0xc4204424c0)
	/go/src/github.com/prometheus/prometheus/vendor/github.com/oklog/oklog/pkg/group/group.go:38 +0x27
created by github.com/prometheus/prometheus/vendor/github.com/oklog/oklog/pkg/group.(*Group).Run
	/go/src/github.com/prometheus/prometheus/vendor/github.com/oklog/oklog/pkg/group/group.go:37 +0xa8
```

**Environment**

Kubernetes 1.7 on GKE.

* Prometheus version:

```
> docker run prom/prometheus@sha256:6050e90c156d4e6be31a23e87b53673b2a2d2ab5b71677225555675b43a1b445 --version                 
prometheus, version 2.0.0 (branch: master, revision: ec94df49d45baa8e680d81e732294eb04fff00de)
  build user:       root@1885792ecf46
  build date:       20171229-20:03:34
  go version:       go1.9.2
```

* Prometheus configuration file:
```
        global:
          scrape_interval: 5s
        remote_write:
          - url: 'https://cloud.weave.works./api/prom/push'
            basic_auth:
              password: <snip>
        remote_read:
          - url: 'https://cloud.weave.works./api/prom/read'
            basic_auth:
              password: <snip>
        scrape_configs:
          - job_name: kubernetes-apiservers
            kubernetes_sd_configs:
              - role: endpoints
            scheme: https
            tls_config:
              ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
            relabel_configs:
              - source_labels:
                  - __meta_kubernetes_namespace
                  - __meta_kubernetes_service_name
                  - __meta_kubernetes_endpoint_port_name
                action: keep
                regex: default;kubernetes;https
              - source_labels:
                  - __meta_kubernetes_namespace
                target_label: _weave_namespace
              - source_labels:
                  - __meta_kubernetes_endpoints_name
                target_label: _weave_service
          - job_name: kubernetes-pods
            kubernetes_sd_configs:
              - role: pod
            relabel_configs:
              - source_labels:
                  - __meta_kubernetes_pod_annotation_prometheus_io_scrape
                action: drop
                regex: 'false'
              - source_labels:
                  - __meta_kubernetes_pod_annotation_prometheus_io_scheme
                action: replace
                target_label: __scheme__
                regex: ^(https?)$
                replacement: $1
              - source_labels:
                  - __meta_kubernetes_pod_annotation_prometheus_io_path
                action: replace
                target_label: __metrics_path__
                regex: ^(.+)$
                replacement: $1
              - source_labels:
                  - __address__
                  - __meta_kubernetes_pod_annotation_prometheus_io_port
                action: replace
                target_label: __address__
                regex: '([^:]+)(?::\d+)?;(\d+)'
                replacement: '$1:$2'
              - source_labels:
                  - __meta_kubernetes_namespace
                target_label: _weave_namespace
              - source_labels:
                  - __meta_kubernetes_pod_name
                  - __meta_kubernetes_pod_node_name
                target_label: node
                regex: ^weave-cortex-node-exporter-.+;(.+)$
                replacement: $1
              - source_labels:
                  - _weave_service
                  - __meta_kubernetes_pod_name
                target_label: _weave_service
                regex: '^;(kube-.*)-(?:ip|gke)-.*$'
                replacement: $1
              - source_labels:
                  - _weave_service
                  - __meta_kubernetes_pod_name
                target_label: _weave_service
                regex: '^;(.*?)(?:(?:-[0-9bcdf]+)?-[0-9a-z]{5})?$'
                replacement: $1
              - source_labels:
                  - _weave_service
                  - __meta_kubernetes_pod_name
                regex: ^;(.+)$
                target_label: _weave_service
                replacement: $1
          - job_name: kubernetes-nodes
            kubernetes_sd_configs:
              - role: node
            tls_config:
              insecure_skip_verify: true
            bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
            relabel_configs:
              - target_label: __scheme__
                replacement: https
              - target_label: __address__
                replacement: 'kubernetes.default.svc:443'
              - source_labels:
                  - __meta_kubernetes_node_name
                regex: (.+)
                target_label: __metrics_path__
                replacement: '/api/v1/nodes/${1}/proxy/metrics'
              - target_label: _weave_namespace
                replacement: default
              - target_label: _weave_service
                replacement: kubelet
          - job_name: weave-net
            kubernetes_sd_configs:
              - role: pod
            relabel_configs:
              - source_labels:
                  - __meta_kubernetes_namespace
                  - __meta_kubernetes_pod_label_name
                action: keep
                regex: ^kube-system;weave-net$
              - source_labels:
                  - __meta_kubernetes_pod_container_name
                  - __address__
                action: replace
                target_label: __address__
                regex: '^weave;(.+?)(?::\d+)?$'
                replacement: '$1:6782'
              - source_labels:
                  - __meta_kubernetes_pod_container_name
                  - __address__
                action: replace
                target_label: __address__
                regex: '^weave-npc;(.+?)(?::\d+)?$'
                replacement: '$1:6781'
              - source_labels:
                  - __meta_kubernetes_namespace
                target_label: _weave_namespace
              - target_label: _weave_service
                replacement: weave-net
          - job_name: cadvisor
            kubernetes_sd_configs:
              - role: node
            tls_config:
              insecure_skip_verify: true
            bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
            scheme: https
            relabel_configs:
              - target_label: __address__
                replacement: 'kubernetes.default.svc:443'
              - source_labels:
                  - __meta_kubernetes_node_name
                regex: (.+)
                target_label: __metrics_path__
                replacement: '/api/v1/nodes/${1}/proxy/metrics/cadvisor'
              - target_label: _weave_namespace
                replacement: default
              - target_label: _weave_service
                replacement: cadvisor
            metric_relabel_configs:
              - source_labels:
                  - _weave_pod_name
                  - pod_name
                target_label: _weave_pod_name
                regex: '^;(kube-.*)-(?:ip|gke)-.*$'
                replacement: $1
              - source_labels:
                  - _weave_pod_name
                  - pod_name
                target_label: _weave_pod_name
                regex: '^;(.*?)(?:(?:-[0-9bcdf]+)?-[0-9a-z]{5})?$'
                replacement: $1
              - source_labels:
                  - _weave_pod_name
                  - pod_name
                regex: ^;(.+)$
                target_label: _weave_pod_name
                replacement: $1
```

### PR DESCRIPTION
**Pull request by krasi-georgiev**
The new Service Discovery implementation  assumed that SD providers will send all target groups on every update which is not the case for all SD providers. 
k8s for example sends only the updates and removed targets are send as an update to a target group  with zero targets in the struct.

So now we are using a string map for the targetGroups and just match the targetgroup updates by the `target Source` identifier.

fixes #3653 , #3651

Signed-off-by: Krasi Georgiev <krasi.root@gmail.com>

### CODE REVIEW

File: discovery/manager.go [hunk 1]
```diff
@@ -153,41 +146,38 @@ func (m *Manager) cancelDiscoverers() {
...
-func (m *Manager) addGroup(poolKey poolKey, tg []*targetgroup.Group) {
+func (m *Manager) updateGroup(poolKey poolKey, tgs []*targetgroup.Group) {
 	done := make(chan struct{})
 
 	m.actionCh <- func(ctx context.Context) {
-		if tg != nil {
-			m.targets[poolKey] = tg
+		if tgs != nil {
+			for _, tg := range tgs {
+				if tg != nil { // Some Discoverers send nil targetgroup so need to check for it to avoid panics.
```
Comment (simonpasquier) [inline discovery/manager.go]: nit but i found this more readable:

```
if tg == nil {
    continue
}
...
```

File: discovery/manager.go [hunk 2]
```diff
@@ -153,41 +146,38 @@ func (m *Manager) cancelDiscoverers() {
...
 }
 
-func (m *Manager) addGroup(poolKey poolKey, tg []*targetgroup.Group) {
+func (m *Manager) updateGroup(poolKey poolKey, tgs []*targetgroup.Group) {
 	done := make(chan struct{})
 
 	m.actionCh <- func(ctx context.Context) {
-		if tg != nil {
-			m.targets[poolKey] = tg
+		if tgs != nil {
```
Comment (simonpasquier) [inline discovery/manager.go]: Instead of checking `tgs` for nil here, you can do it at the very beginning of the method and return early (or even on the caller side).

File: discovery/manager.go (hunk 1 above)
Comment (simonpasquier) [reply discovery/manager.go]: And FWIW I've spotted the places in the K8S SD where it sends nil target groups (see https://github.com/prometheus/prometheus/pull/3660) but it doesn't mean that all SD providers are safe either.

File: discovery/manager.go (hunk 2 above)
Comment (krasi-georgiev) [reply discovery/manager.go]: yeah we can check it here

```
		case tgs, ok := <-updates:
			// Handle the case that a target provider exits and closes the channel
			// before the context is done.
			if !ok || tgs ==nil {
				return
			}
```

but I am thinking if `updateGroup` is used by another caller which forgets to make the `nil` check?

File: discovery/manager.go (hunk 1 above)
Comment (krasi-georgiev) [reply discovery/manager.go]: thanks

File: discovery/manager.go [hunk 3]
```diff
@@ -83,7 +74,9 @@ type Manager struct {
 	logger         log.Logger
 	actionCh       chan func(context.Context)
 	discoverCancel []context.CancelFunc
-	targets        map[poolKey][]*targetgroup.Group
+	// Some Discoverers(eg. k8s) send only the updates for a given target group
+	// so we use map[tg.Source]*targetgroup.Group to  know which group to update.
```
Comment (Gouthamve) [inline discovery/manager.go]: Extra space b/w `to` and `know`

File: discovery/manager.go [hunk 4]
```diff
@@ -153,41 +146,41 @@ func (m *Manager) cancelDiscoverers() {
...
 }
 
-func (m *Manager) addGroup(poolKey poolKey, tg []*targetgroup.Group) {
+func (m *Manager) updateGroup(poolKey poolKey, tgs []*targetgroup.Group) {
 	done := make(chan struct{})
 
 	m.actionCh <- func(ctx context.Context) {
-		if tg != nil {
-			m.targets[poolKey] = tg
+		if tgs == nil {
```
Comment (Gouthamve) [inline discovery/manager.go]: We don't need this check right?

File: discovery/manager.go [hunk 5]
```diff
@@ -153,41 +146,41 @@ func (m *Manager) cancelDiscoverers() {
...
+			close(done)
+			return
+		}
+
+		for _, tg := range tgs {
+			if tg != nil { // Some Discoverers send nil targetgroup so need to check for it to avoid panics.
+				if _, ok := m.targets[poolKey]; !ok {
+					m.targets[poolKey] = make(map[string]*targetgroup.Group)
+				}
+				m.targets[poolKey][tg.Source] = tg
```
Comment (Gouthamve) [inline discovery/manager.go]: Check if `len(tg.Targets) == 0`. This means those targets went away and we can remove the group from the map. So if a SD has a target per source, and is highly dynamic, the map simply grows and we might have a memory leak.

Comment (Gouthamve) [reply discovery/manager.go]: In hindsight, this would break the discovery further down where we call `allGroups()` and we might not send anything against a `setName` and the old targets still hang around. 

Should we worry about the memory leak though?

File: discovery/manager.go (hunk 3 above)
Comment (krasi-georgiev) [reply discovery/manager.go]: ok

File: discovery/manager.go (hunk 4 above)
Comment (krasi-georgiev) [reply discovery/manager.go]: I think we do. 
it fixes this bug https://github.com/prometheus/prometheus/issues/3653
k8s was sending `nil` and it panicked.

this is fixed in https://github.com/prometheus/prometheus/pull/3660  , but I prefer to keep one more check just in case any other Discoverer decided to do the same.

File: discovery/manager.go (hunk 5 above)
Comment (krasi-georgiev) [reply discovery/manager.go]: I was worried that the map will grow indefinitely   as well, but this is how it was implemented before so I guess it wasn't a problem. Anyway I added some  code to delete empty maps

**Comment by cstyan** [comment]
lgtm

Just to clarify, sending only updates/removed targets is the correct behaviour, so I think we should open issues if any sd implementations are sending all target groups when only one has updated. From this comment https://github.com/prometheus/prometheus/issues/3658#issuecomment-355523651 it sounds like Consul SD is one offender?

```Prometheus will call the Run() method on a provider to initialise the discovery mechanism. The mechanism will then send all the TargetGroups into the channel. Now the mechanism will watch for changes and then send only changed and new TargetGroups down the channel.```

File: discovery/manager.go [hunk 6]
```diff
@@ -153,41 +147,43 @@ func (m *Manager) cancelDiscoverers() {
...
 		tSetsAll := map[string][]*targetgroup.Group{}
-		for _, pk := range pKeys {
-			for _, tg := range m.targets[pk] {
-				if tg.Source != "" { // Don't add empty targets.
-					tSetsAll[pk.setName] = append(tSetsAll[pk.setName], tg)
-				}
+		for pkey, tsets := range m.targets {
+			for _, tg := range tsets {
+				// Even if the target group 'tg' is empty we still need to send it to the 'Scrape manager'
+				// to singal that is needs to stop all scrape loops for this target set.
```
Comment (simonpasquier) [inline discovery/manager.go]: s/singal that is/signal that it/

Comment (krasi-georgiev) [reply discovery/manager.go]: thanks,

I also run some tests locally with consul , k8x and static configs and can't see any problems.

File: discovery/manager.go (hunk 4 above)
Comment (krasi-georgiev) [reply discovery/manager.go]: @Gouthamve , oops , that was for the line below: `if tg != nil {` 
I have removed this check.
I wasn't sure what happens when you range over nil maps, but just now did a quick check and it doesn't cause any panics so safe to remove

**Comment by Gouthamve** [comment]
Thanks!
