### PR TITLE
fixed disappeared target groups in http_sd #9019

### LINKED ISSUE #9019: HTTP SD does not remove disappeared target groups
**What did you do?**
I removed some target groups from my [HTTP SD](https://prometheus.io/docs/prometheus/latest/http_sd/) endpoint.

For example, the endpoint returns three target groups (`mylabel` :`v1`, `v2`, `v3`) at the first scraping.

```json
[
  {"labels": {"mylabel": "v1"}, "targets": ["127.0.0.1:9090"]},
  {"labels": {"mylabel": "v2"}, "targets": ["127.0.0.1:9090"]},
  {"labels": {"mylabel": "v3"}, "targets": ["127.0.0.1:9090"]}
]
```

Then the endpoint returns only one target group (`v1`) at the second scraping.

```json
[
  {"labels": {"mylabel": "v1"}, "targets": ["127.0.0.1:9090"]}
]
```

**What did you expect to see?**

HTTP SD removes disappeared target groups from scrape targets. In the case of the example, `v2`, `v3` should be deleted.

**What did you see instead? Under which circumstances?**

I still see disappeared target groups (`v2`, `v3` in the example) in scrape targets.

HTTP SD may need to send empty updates for deletion as [File SD does](https://github.com/prometheus/prometheus/blob/v2.28.0/discovery/file/file.go#L350-L365).

**Environment**

* Prometheus version: `prom/prometheus:v2.28.0`
* Prometheus configuration file:
```yaml
scrape_configs:
  - job_name: http_sd_job
    http_sd_configs:
    - url: http://localhost:8080/targets.json
      refresh_interval: 5s
```

### PR DESCRIPTION
**Pull request by servak**
This PR insert an empty source when a source is lost in HTTP_SD, and to update the target group appropriately.
Fixes #9019

### CODE REVIEW

File: discovery/http/http.go [hunk 1]
```diff
@@ -183,6 +184,15 @@ func (d *Discovery) refresh(ctx context.Context) ([]*targetgroup.Group, error) {
 		tg.Labels[httpSDURLLabel] = model.LabelValue(d.url)
 	}
 
+	// Generate empty updates for sources that disappeared.
+	if l := len(targetGroups); d.tgMaxLength > l {
+		for i := l; i < d.tgMaxLength; i++ {
+			targetGroups = append(targetGroups, &targetgroup.Group{Source: urlSource(d.url, i)})
+		}
```
Comment (roidelapluie) [inline discovery/http/http.go:191]: We should reset d.tgMaxLength.

**Review by roidelapluie — COMMENTED** [review]
Thank you. This is indeed a bug. Could you please add tests for this?

File: discovery/http/http.go [hunk 2]
```diff
@@ -183,6 +184,15 @@ func (d *Discovery) refresh(ctx context.Context) ([]*targetgroup.Group, error) {
...
+	} else {
+		d.tgMaxLength = l
```
Comment (roidelapluie) [inline discovery/http/http.go:193]: Ths should be un-conditional

**Comment by servak** [comment]
Thanks for review. I added testcase.

File: discovery/http/http_test.go [hunk 3]
```diff
@@ -162,3 +162,142 @@ func TestContentTypeRegex(t *testing.T) {
 		})
 	}
 }
+
+func TestSourceDisappeared(t *testing.T) {
+	const path = "/http_disappeared.json"
```
Comment (roidelapluie) [inline discovery/http/http_test.go:167]: I would just do without a path in this case.

File: discovery/http/http.go [hunk 4]
```diff
@@ -183,6 +185,15 @@ func (d *Discovery) refresh(ctx context.Context) ([]*targetgroup.Group, error) {
 		tg.Labels[httpSDURLLabel] = model.LabelValue(d.url)
 	}
 
+	// Generate empty updates for sources that disappeared.
+	if l := len(targetGroups); d.tgMaxLength > l {
```
Comment (roidelapluie) [inline discovery/http/http.go:189]:
```suggestion
	l := len(targetGroups)
	if d.tgMaxLength > l {
```

File: discovery/http/http.go [hunk 5]
```diff
@@ -183,6 +185,15 @@ func (d *Discovery) refresh(ctx context.Context) ([]*targetgroup.Group, error) {
...
+		for i := l; i < d.tgMaxLength; i++ {
+			targetGroups = append(targetGroups, &targetgroup.Group{Source: urlSource(d.url, i)})
+		}
+	} else {
```
Comment (roidelapluie) [inline discovery/http/http.go:193]: Can you remove the else?

File: discovery/http/http_test.go [hunk 6]
```diff
@@ -162,3 +162,142 @@ func TestContentTypeRegex(t *testing.T) {
...
+					Targets: nil,
+					Labels:  nil,
+					Source:  urlSource(ts.URL+path, 2),
+				},
+			},
+		},
+	}
+
+	for _, test := range cases {
+		cfg := SDConfig{
```
Comment (roidelapluie) [inline discovery/http/http_test.go:285]: This should  be called outside of the loop.

File: discovery/http/http_test.go [hunk 7]
```diff
@@ -162,3 +162,142 @@ func TestContentTypeRegex(t *testing.T) {
...
+			HTTPClientConfig: config.DefaultHTTPClientConfig,
+			URL:              ts.URL + path,
+			RefreshInterval:  model.Duration(1 * time.Second),
+		}
+		d, err := NewDiscovery(&cfg, log.NewNopLogger())
```
Comment (roidelapluie) [inline discovery/http/http_test.go:290]: This should  be called outside of the loop.

**Review by roidelapluie — COMMENTED** [review]
Thank you, I have a few more comments.

File: discovery/http/http.go (hunk 4 above)
Comment (servak) [reply discovery/http/http.go:189]: ok!

**Comment by servak** [comment]
Thanks you. I fixed it. if this change pass, i want to rebase.

File: discovery/http/http.go [hunk 8]
```diff
@@ -122,6 +123,7 @@ func NewDiscovery(conf *SDConfig, logger log.Logger) (*Discovery, error) {
 		url:             conf.URL,
 		client:          client,
 		refreshInterval: time.Duration(conf.RefreshInterval), // Stored to be sent as headers.
+		tgLastLength:     0,
```
Comment (roidelapluie) [inline discovery/http/http.go:126]: that is not needed as it is the default value.

File: discovery/http/http_test.go [hunk 9]
```diff
@@ -162,3 +162,241 @@ func TestContentTypeRegex(t *testing.T) {
 		})
 	}
 }
+
+func TestSourceDisappeared(t *testing.T) {
+	var stubResponse string
+	ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
+		w.Header().Set("Content-Type", "application/json")
+		fmt.Fprintln(w, stubResponse)
```
Comment (roidelapluie) [inline discovery/http/http_test.go:170]: I just wonder if that will work or if we need pointers.

**Review by roidelapluie — COMMENTED** [review]
If you rebase, can you rebase on top of the branch release-2.28? Thanks.

**Comment by roidelapluie** [comment]
I have already updated the PR to the release-2.28 branch.

**Comment by roidelapluie** [comment]
(this is to release a 2.28.1 with this fix)

**Comment by roidelapluie** [comment]
sorry for everyone receiving a notification because I changed the base branch :)

File: discovery/http/http.go (hunk 8 above)
Comment (servak) [reply discovery/http/http.go]: I deleted it.

File: discovery/http/http_test.go (hunk 9 above)
Comment (servak) [reply discovery/http/http_test.go:170]: should I change the testcase?

**Review by roidelapluie — APPROVED** [review]
Thanks!

**Review by roidelapluie — APPROVED** [review]
