### PR TITLE
Fix multiple issues around chunks to persist.

### LINKED ISSUE #1323: prometheus_local_storage_chunks_to_persist includes
chunksToPersist in function loadSeriesMapAndHeads is incremented for every chunk read from the snapshot. even if it is a still open head chunk. That overestimates the number of chunks to persist

### PR DESCRIPTION
**Pull request by beorn7**
See commit description.

@fabxc 

Fixes #1323 and #1320.

### CODE REVIEW

File: storage/local/storage.go [hunk 1]
```diff
@@ -1144,37 +1161,80 @@ func (s *memorySeriesStorage) incNumChunksToPersist(by int) {
...
+			s.checkpointInterval,
+		)
+		return true
+	}
+	// ...then WRT memChunks.
+	s.rushed = memChunks > float64(s.maxMemoryChunks)*factorMemChunksForEnteringRushedMode &&
+		chunksToPersist > float64(s.maxChunksToPersist)*factorMinChunksToPersistToAllowRushedMode
+	if s.rushed {
+		log.Warnf(
+			"%.0f chunks in memory (%.1f%% of the allowed maximum %d). Storage is now in rushed mode. Series files are not synced anymore if following the adaptive strategy. Checkpoints are not performed more often than every %v. Series maintenance happens as frequently as possible.",
```
Comment (fabxc) [inline storage/local/storage.go]: The level of detailed of those logs are borderline documentation in my opinion. What adaptive mode actually means can be simply documented elsewhere and doesn't need to be repeated with each message.

File: storage/local/storage.go [hunk 2]
```diff
@@ -1144,37 +1161,80 @@ func (s *memorySeriesStorage) incNumChunksToPersist(by int) {
...
-	nowDegraded := s.getNumChunksToPersist() > s.maxChunksToPersist*percentChunksToPersistForDegradation/100
-	if s.degraded && !nowDegraded {
-		log.Warn("Storage has left graceful degradation mode. Things are back to normal.")
-	} else if !s.degraded && nowDegraded {
+// inRushedMode returns whether the storage is in "rushed mode", which is the
+// case if there are too many chunks waiting for persistence or there are too
+// many chunks in memory. The method is not goroutine safe (but only ever called
+// from the goroutine dealing with series maintenance).  Changes of degradation
+// mode are logged.
+func (s *memorySeriesStorage) inRushedMode() bool {
```
Comment (fabxc) [inline storage/local/storage.go]: That method name is misleading. It implies being a getter, which it's not.

File: storage/local/storage.go [hunk 3]
```diff
@@ -1144,37 +1161,80 @@ func (s *memorySeriesStorage) incNumChunksToPersist(by int) {
...
 // about how close we are to degradation. This score is 1.0 if no chunks are
-// waiting for persistence and 0.0 if we are at or above the degradation
-// threshold.
+// waiting for persistence or we are not over the threshold for memory chunks,
+// and 0.0 if we are at or above the thresholds. However, the score is always 0
+// if the storage is currently in rushed mode. (Getting out of it has a
+// hysteresis, so we might be below thresholds again but still in rushed mode.)
 func (s *memorySeriesStorage) persistenceBacklogScore() float64 {
-	score := 1 - float64(s.getNumChunksToPersist())/float64(s.maxChunksToPersist*percentChunksToPersistForDegradation/100)
+	if s.inRushedMode() {
```
Comment (fabxc) [inline storage/local/storage.go]: This call makes the issue with method name is transitively true here for `persistenceBacklogScore()`.

File: storage/local/storage.go (hunk 2 above)
Comment (beorn7) [inline storage/local/storage.go]: Traditional getters start with "get" or "is", no? And Go really doesn't have a notion of getters.
What's your suggestion for a better name?

File: storage/local/storage.go (hunk 1 above)
Comment (beorn7) [inline storage/local/storage.go]: Can you suggest something concretely? While I found your points valid, I also want to provide something normal users can easily get.

File: storage/local/storage.go (hunk 3 above)
Comment (beorn7) [inline storage/local/storage.go]: Suggestions?

File: storage/local/storage.go (hunk 2 above)
Comment (fabxc) [inline storage/local/storage.go]: Go still has getters but generally "get" and "set" as prefixes are hardly used. Sure, Go lacks static constraints to enforce read-only – methods names are still suggestive to the behavior.

To me functions that return are bool and could easily be suffixed with a `?` always seem like getters.
I don't mind too much since it's an internal method.

`checkRushedMode` would be clearer to me – but that's highly subjective.

Comment (beorn7) [inline storage/local/storage.go]: I thought about it as lazy evaluation, but arguably, the hysteresis is only entered upon calling the method, so it's in a way state-changing...

I have an idea how to make everything clearer. Stay tuned...

File: storage/local/storage.go (hunk 3 above)
Comment (beorn7) [inline storage/local/storage.go]: I have an idea... see next commit.

File: storage/local/storage.go (hunk 1 above)
Comment (fabxc) [inline storage/local/storage.go]: What I just said in person, for completeness:

In this particular case I wonder what a good decision procedure is for whether data exposed via metrics should be repeated in logs.
With less frequent state switches here (implemented by this change  set), the normal way seems to see that it changed and then look up the metrics to properly see what's going on. The individual values are not too helpful when checking the logs and only useful for in-depth debugging anyway for which the respective time series data is far superior.

`Storage switched to rushed mode (81% chunk memory limit reached).`

Even the last part is optional since the thresholds are fixed and it will be within a narrow margin around that.

**Comment by beorn7** [comment]
PHAL!

File: storage/local/storage.go [hunk 4]
```diff
@@ -1144,36 +1171,83 @@ func (s *memorySeriesStorage) incNumChunksToPersist(by int) {
...
+		// persintenceUrgencyScoreForLeavingRushedMode, return 1 and
+		// leave things as they are.
+		if score > persintenceUrgencyScoreForLeavingRushedMode {
+			return 1
+		}
+		// We are out of rushed mode!
+		s.rushed = false
+		s.rushedMode.Set(0)
+		log.
+			With("urgency score", score).
```
Comment (fabxc) [inline storage/local/storage.go]: Since these are keys, probably camelCase is better.

File: storage/local/storage.go [hunk 5]
```diff
@@ -1144,36 +1171,83 @@ func (s *memorySeriesStorage) incNumChunksToPersist(by int) {
...
+// persintenceUrgencyScoreForLeavingRushedMode.
+//
+// This method is not goroutine-safe, but it is only ever called by the single
+// goroutine that is in charge of series maintenance. According to the returned
+// score, series maintenence should be sped up. If a score of 1 is returned,
+// checkpointing based on dirty-series count should be disabled, and series
+// files should not by synced anymore provided the user has specified the
+// adaptive sync strategy.
+func (s *memorySeriesStorage) calculatePersistenceUrgencyScore() float64 {
+	chunksToPersist := float64(s.getNumChunksToPersist())
```
Comment (fabxc) [inline storage/local/storage.go]: Totally a fan of 

```
var (
...
)
```

blocks here – just my taste though ;)

**Comment by fabxc** [comment]
Yay! :100: after the logging keys.

File: storage/local/storage.go (hunk 5 above)
Comment (beorn7) [inline storage/local/storage.go]: Sure (and if it is only to make gofmt align things nicely).

**Comment by beorn7** [comment]
I'll add "rushed mode" to the docs in that other PR, though.

File: storage/local/storage.go (hunk 5 above)
Comment (fabxc) [inline storage/local/storage.go]: That's actually exactly why I like it :)
