### PR TITLE
promql: fix info() handling of negated __name__ matchers

### LINKED ISSUE #17931: promql: info() function incorrectly handles negated __name__ matchers
### Bug description

The `info()` function incorrectly handles negated `__name__` matchers in the second argument. When using `__name__!~` or `__name__!=`, base metric series are incorrectly added to the `ignoreSeries` set and returned unchanged instead of being filtered out.

### Steps to reproduce

```promql
info(db_queries_total, {env="prod", __name__!~".+_info"})
```

### Expected behavior

Since no info metrics match `__name__!~".+_info"` (all info metrics end in `_info`), and the `env="prod"` matcher doesn't match the empty string, the query should return no series.

### Actual behavior

The query returns `db_queries_total` series unchanged (without any info labels added):

```
db_queries_total{instance="prod-db-1:5432", job="database", operation="UPDATE"}    1000
db_queries_total{instance="prod-db-1:5432", job="database", operation="SELECT"}    1000
db_queries_total{instance="prod-db-1:5432", job="database", operation="INSERT"}    1000
```

### Root cause

In `promql/info.go` (lines 50-60), series are added to `ignoreSeries` if their name matches any `infoNameMatchers`:

```go
for _, s := range mat {
    name := s.Metric.Get(labels.MetricName)
    for _, m := range infoNameMatchers {
        if m.Matches(name) {
            ignoreSeries[s.Metric.Hash()] = struct{}{}
            continue loop
        }
    }
}
```

The intent is "don't enrich info metrics with themselves". However, with negated matchers like `__name__!~".+_info"`:

1. `"db_queries_total"` does NOT match the pattern `.+_info`
2. The negated matcher `!~".+_info"` therefore returns `true`
3. `db_queries_total` is incorrectly added to `ignoreSeries`
4. Series in `ignoreSeries` are returned unchanged (lines 372-378)

### Suggested fix

The `ignoreSeries` logic should only consider positive matchers (`=` and `=~`), or the matching logic needs to be inverted for the purpose of determining which series to skip.

### PR DESCRIPTION
**Pull request by aknuds1**
#### Which issue(s) does the PR fix:

Fixes #17931

#### Does this PR introduce a user-facing change?

Fix how the `info()` function handles `__name__` matchers in the second argument:

1. **Negated matchers no longer break `ignoreSeries`**: Previously, negated matchers (`!=`, `!~`) could cause base metrics to be incorrectly added to `ignoreSeries`, or cause series to vanish when they matched positive matchers but were excluded by negative ones. Now `ignoreSeries` uses the same resolved matcher set as the info series fetch, via `effectiveInfoNameMatchers`.

2. **Negated-only `__name__` matchers select info metrics correctly**: When only negated `__name__` matchers are provided, a broad `.+_info` pattern is used to select info metrics, then the negative matchers filter them. Previously, negated matchers alone would incorrectly select non-info metrics as info sources.

3. **Multiple positive `__name__` matchers are supported**: All positive `__name__` matchers are applied with AND semantics. Previously, only the last one was kept.

```release-notes
[BUGFIX] PromQL: Fix `info()` function incorrectly handling negated `__name__` matchers
```

### CODE REVIEW

File: promql/info.go [hunk 1]
```diff
@@ -55,12 +55,15 @@ func (ev *evaluator) evalInfo(ctx context.Context, args parser.Expressions) (par
...
+	// Only consider positive matchers (= and =~) to identify info series,
+	// since negated matchers (!=, !~) specify what NOT to match and shouldn't
+	// be used to determine which series are info metrics.
 	ignoreSeries := map[uint64]struct{}{}
 loop:
 	for _, s := range mat {
 		name := s.Metric.Get(labels.MetricName)
 		for _, m := range infoNameMatchers {
-			if m.Matches(name) {
+			if (m.Type == labels.MatchEqual || m.Type == labels.MatchRegexp) && m.Matches(name) {
```
Comment (zenador) [inline promql/info.go]: Sorry I'm a bit confused here, but I find the new logic very complicated. Was the previous behaviour to ignore the series if it matched any of the multiple info name matchers? If so, wouldn't it be better to ignore only if it matched all of the provided matchers, since that's how it works for looking up info series? If we make that change instead, then perhaps we wouldn't need the extra logic below to override what the user specifies, which could be very surprising and confusing.

File: promql/info.go [hunk 2]
```diff
@@ -183,12 +186,23 @@ func (ev *evaluator) fetchInfoSeries(ctx context.Context, mat Matrix, ignoreSeri
 	for name, re := range idLblRegexps {
 		infoLabelMatchers = append(infoLabelMatchers, labels.MustNewMatcher(labels.MatchRegexp, name, re))
 	}
-	var nameMatcher *labels.Matcher
+	// Collect __name__ matchers separately: positive matchers (=, =~) are used
+	// to select info metrics, while negative matchers (!=, !~) are used to filter.
+	// Only positive matchers can positively identify info metrics; negative matchers
+	// alone would incorrectly select non-info metrics as info sources.
+	var positiveNameMatcher *labels.Matcher
```
Comment (zenador) [inline promql/info.go]: What if there are multiple positive matchers, e.g. one exact and one regex? There is no good reason for users to need to provide both, but in case they do because of some messy templating or whatever, the regex matcher might overwrite the exact matcher and we would ignore the exact matcher in our info series lookup right?

File: promql/info.go [hunk 3]
```diff
@@ -198,9 +212,18 @@ func (ev *evaluator) fetchInfoSeries(ctx context.Context, mat Matrix, ignoreSeri
 			delete(dataLabelMatchers, name)
 		}
 	}
-	if nameMatcher == nil {
-		// Default to using the target_info metric.
-		infoLabelMatchers = append([]*labels.Matcher{labels.MustNewMatcher(labels.MatchEqual, labels.MetricName, targetInfo)}, infoLabelMatchers...)
+	switch {
+	case positiveNameMatcher != nil:
+		// Use the positive __name__ matcher to select info metrics.
+		infoLabelMatchers = append(infoLabelMatchers, positiveNameMatcher)
```
Comment (zenador) [inline promql/info.go]: Does this mean that if a positive name matcher is provided, all negative matchers are ignored? What if the user wants to combine a positive regex matcher with negative matchers?

File: promql/info.go (hunk 1 above)
Comment (aknuds1) [reply promql/info.go]: Please see latest revision.

File: promql/info.go (hunk 2 above)
Comment (aknuds1) [reply promql/info.go]: Please see latest revision.

File: promql/info.go (hunk 3 above)
Comment (aknuds1) [reply promql/info.go]: Please see latest revision.

**Comment by aknuds1** [comment]
@zenador Thank you for raising those concerns. Can you PTAL at the latest revision?
