### PR TITLE
SD: Add target creation failure counter and change failure handling

### LINKED ISSUE #8438: SD: Need error counter in case the creation of targets fails, and reconsider target drop strategy
**What did you do?**

Consul service discovery Job for wmi and node exporters

**What did you expect to see?**

Expected to have all targets discovered and scraped

**What did you see instead? Under which circumstances?**

Node exporters were fine but nothing in discovery page and nothing scraped for wmi
Got error in log prometheus (see log)
Only one server had a wrong IP address but the whole discovery job failed. (249 IP were OK and 1 was wrong ==> no scrape at all)

Didnt find any metrics that reflect this error, impossible to monitor
sd shouldnt discard all targets if only one is wrong

**Environment**

* System information:

	Linux 3.10.0-1127.18.2.el7.x86_64 x86_64

* Prometheus version:

	version 2.23.0

* Prometheus configuration file:
```
- job_name: 'generic-exporter-consul'
  scrape_timeout: 30s
  consul_sd_configs:
    - server: 'ipconsul:8500'
      token : 'token'
      datacenter: 'dc1'
      tag_separator: ';'
      services:
        - node-exporter
        - wmi-exporter
 
  relabel_configs:

    - source_labels: ['__meta_consul_service']
      target_label:  'job'

    - source_labels: ['__meta_consul_node']
      target_label:  'info_fqdn'
      replacement:   '$1'
```

* Logs:
```
level=error ts=2021-02-03T15:13:20.828Z caller=scrape.go:421 component="scrape manager" scrape_pool=generic-exporter-consul msg="creating targets failed" err="instance 564 in group wmi-exporter: \"172.x.x.x/172.x.x.x:9182\" is not a valid hostname",
```

### PR DESCRIPTION
**Pull request by LeviHarrison**
This PR adds an error counter for target creation failures and changes the way failures are handled so that a single invalid target does not pause scraping for the entire group.

Fixes #8438

On a side note, maybe it would be better to change this counter to a gauge and have it represent the current number of failures, not just the accumulated failures over time. That might provide more useful information for remediation.

### CODE REVIEW

**Comment by roidelapluie** [comment]
> On a side note, maybe it would be better to change this counter to a gauge and have it represent the current number of failures, not just the accumulated failures over time. That might provide more useful information for remediation.

A counter is easier to implement and I expect this to simply be 0 in any setups.

File: scrape/scrape.go [hunk 1]
```diff
@@ -445,11 +454,11 @@ func (sp *scrapePool) Sync(tgs []*targetgroup.Group) {
 	var all []*Target
 	sp.droppedTargets = []*Target{}
 	for _, tg := range tgs {
-		targets, err := targetsFromGroup(tg, sp.config)
-		if err != nil {
+		targets, failures := targetsFromGroup(tg, sp.config)
+		for _, err := range failures {
 			level.Error(sp.logger).Log("msg", "creating targets failed", "err", err)
```
Comment (roidelapluie) [inline scrape/scrape.go:459]:
```suggestion
			level.Error(sp.logger).Log("msg", "Creating target failed", "err", err)
```

This is now for just one target.

Comment (LeviHarrison) [reply scrape/scrape.go:459]: Whoops. Nice catch!

**Comment by roidelapluie** [comment]
If you are into mixins, would you do the mixin update in the same PR?

**Comment by LeviHarrison** [comment]
Never done any mixin work before, but I'll guess give it a try. Do you mean to add an alert `alerts.libsonnet`?

**Comment by roidelapluie** [comment]
That one is scrape, not discovery.

Just an alert would do.

File: scrape/scrape.go [hunk 2]
```diff
@@ -346,6 +354,7 @@ func (sp *scrapePool) stop() {
 		targetScrapePoolTargetLimit.DeleteLabelValues(sp.config.JobName)
 		targetScrapePoolTargetsAdded.DeleteLabelValues(sp.config.JobName)
 		targetSyncIntervalLength.DeleteLabelValues(sp.config.JobName)
+		targetSyncFailed.DeleteLabelValues(sp.config.JobName)
```
Comment (roidelapluie) [inline scrape/scrape.go:357]: Do we initiate it for each scrape job?

Comment (LeviHarrison) [reply scrape/scrape.go:357]: I believe so

https://github.com/prometheus/prometheus/blob/212e6b91b63e163b47391cc2785e4e8355365aae/scrape/scrape.go#L461

File: documentation/prometheus-mixin/alerts.libsonnet [hunk 3]
```diff
@@ -275,6 +275,20 @@
               description: 'Prometheus %(prometheusName)s has dropped {{ printf "%%.0f" $value }} targets because some samples exceeded the configured label_limit, label_name_length_limit or label_value_length_limit.' % $._config,
             },
           },
+          {
+            alert: 'PrometheusTargetSyncFailure',
+            expr: |||
+              increase(prometheus_target_sync_failed_total{%(prometheusSelector)s}[5m]) > 0
+            ||| % $._config,
+            'for': '5m',
```
Comment (roidelapluie) [inline documentation/prometheus-mixin/alerts.libsonnet:283]: I am wondering if that is fine.

Service discovery might not trigger every 5 minutes. It might be wrong "one time", then not re-trigger. Should we alert when > 0?


cc @beorn7 what do you think?

Comment (LeviHarrison) [reply documentation/prometheus-mixin/alerts.libsonnet:283]: Wouldn't we just perpetually alert then? `prometheus_target_sync_failed_total` never will decrease, even if the problem has been resolved.

Comment (roidelapluie) [reply documentation/prometheus-mixin/alerts.libsonnet:283]: Yes, maybe we need a gauge after all? Let's collect more feedback.

Comment (LeviHarrison) [reply documentation/prometheus-mixin/alerts.libsonnet:283]: Yeah, it definitely could help because the operator would know when they have successfully fixed the issue, not only if it ever existed.

Comment (beorn7) [reply documentation/prometheus-mixin/alerts.libsonnet:283]: Not sure, either. My thinking is that for events that clearly happen less often than a scrape, a gauge should be fine. And I guess a sync naturally happens much less often than a scrape (but I might be wrong here). So if we used a gauge, it would contain the number of failures in the last sync of that group.

Comment (roidelapluie) [reply documentation/prometheus-mixin/alerts.libsonnet:283]: The minimum for syncs is 5 seconds, and in dynamic environments we can reach that cadence (e.g. kubernetes).

Comment (beorn7) [reply documentation/prometheus-mixin/alerts.libsonnet:283]: Hmm, yeah, so I guess the best trade-off has to be done by someone more familiar with the scraping code.

Fundamentally, if an error can happen as often as once every 5s, I'd go for a counter, even if that makes precise alerting a bit harder.

We could extend the time range to an hour or two to make it more likely that the alert keep firing, or at least the alert will fire for at least an hour or two, which is, of course, also a problem because it will continue to fire for an hour or two even if the problem is solved. The latter can be addressed in the description ("In the last two hours, there were x errors."), so that at least the receiver understands why the alert is still firing.

On the other hand, not all alerts have the nice property of only resolving if the problem is solved for good. So we could also just accept that here. (I'd still go at least a bit higher than 5m with the time range.)

Comment (LeviHarrison) [reply documentation/prometheus-mixin/alerts.libsonnet:283]: I think that in this scenario it's especially important to know when the problem has been resolved, so having a potential hour(s) long delay isn't optimal. I definitely think that extending to 15m (or even 30) is warranted though.

**Comment by LeviHarrison** [comment]
I changed the range to 30 minutes, which should give enough time for the alert to be noticed.

@juliusv You can ignore this I accidentally committed a package-lock.json 🤦🏻

File: documentation/prometheus-mixin/alerts.libsonnet [hunk 4]
```diff
@@ -275,6 +275,20 @@
...
+            expr: |||
+              increase(prometheus_target_sync_failed_total{%(prometheusSelector)s}[30m]) > 0
+            ||| % $._config,
+            'for': '5m',
+            labels: {
+              severity: 'critical',
+            },
+            annotations: {
+              summary: 'Prometheus has failed to sync targets.',
+              description: '{{ printf "%%.of" $value }} targets in Prometheus %(prometheusName)s have failed to sync because invalid configuration was supplied.' % $._config,
```
Comment (beorn7) [inline documentation/prometheus-mixin/alerts.libsonnet:289]: `%%.of` → `%%.0f`, I guess.

**Review by beorn7 — COMMENTED** [review]
Modulo the typo, I think we can try it that way. @roidelapluie or any others, I leave the final verdict to you.

**Review by roidelapluie — APPROVED** [review]
LGTM, after typo fix.

**Comment by LeviHarrison** [comment]
Ok that should be it.

**Comment by roidelapluie** [comment]
Thanks!
