### PR TITLE
Fix the duplicated results issue from /api/v1/series

### LINKED ISSUE #7801: Duplicated results from /api/v1/series
When multiple matchers are passed to `/api/v1/series`, this API doesn't guarantee deduplicated results.

To my understanding this is caused by fetch series using `.Select(false, ...)`:
https://github.com/prometheus/prometheus/blob/b521612042ec87103088b45b7b5dfee3bb8dc732/web/api/v1/api.go#L604-L608

But then we use `NewMergeSeriesSet()` which expects sorted series sets in order to correctly deduplicate series:
https://github.com/prometheus/prometheus/blob/b521612042ec87103088b45b7b5dfee3bb8dc732/web/api/v1/api.go#L610

Two questions:
1. Am I missing anything?
2. What's the expected behaviour of `/api/v1/series`? We would like to do the "right thing" in Cortex, but I'm not sure what's that 😄

### PR DESCRIPTION
**Pull request by showuon**
Fix #7801 . Sort the Select returned series sets for later merge to de-duplicate results. And add test to try to overlap the select returned series sets and make sure it'll return expected results. I tested if I reverted my change (not sort the select results), the test result will fail sometimes due to the duplicated results returned. (About 20%~30% possibility to reproduce it since the result set is still not large enough. But it somehow can protect the behavior since it'll fail sometimes if behavior changed.)

Signed-off-by: Luke Chen <showuon@gmail.com>

### CODE REVIEW

**Comment by brian-brazil** [comment]
:+1: 

@roidelapluie What do you want done with this?

**Comment by roidelapluie** [comment]
Yes it makes sense to have this in 2.21.

@showuon can you please rebase this on the 2.21 branch? Thanks

**Comment by showuon** [comment]
rebased to `release-2.21`. Thanks.

**Comment by showuon** [comment]
@roidelapluie , I rebased to release-2.21. Thanks.

File: web/api/v1/api.go [hunk 1]
```diff
@@ -603,7 +603,8 @@ func (api *API) series(r *http.Request) (result apiFuncResult) {
 
 	var sets []storage.SeriesSet
 	for _, mset := range matcherSets {
-		s := q.Select(false, nil, mset...)
+		// We need to sort this select results to merge(deduplicate) the series sets later.
```
Comment (roidelapluie) [inline web/api/v1/api.go:606]:
```suggestion
		// We need to sort this select results to merge (deduplicate) the series sets later.
```

**Comment by showuon** [comment]
I saw I didn't pass DCO check. I'll fix it later when I'm back home. Thanks.

**Comment by showuon** [comment]
@roidelapluie , I've updated the commit. Thanks for the comment.

**Review by roidelapluie — APPROVED** [review]
