### PR TITLE
Fix panic in ARM builds of Prometheus

### LINKED ISSUE #6105: Prometheus for ARM on Docker (from Docker Hub) is crashing
## Bug Report
**What did you do?**
I updated my prometheus docker image from Docker Hub on my Raspberry Pi 2.

**What did you expect to see?**
Prometheus runing

**What did you see instead? Under which circumstances?**
This backtrace:
```
prometheus_1  | level=info ts=2019-10-05T09:51:23.035Z caller=main.go:296 msg="no time or size retention was set so using the default time retention" duration=15d
prometheus_1  | level=info ts=2019-10-05T09:51:23.036Z caller=main.go:332 msg="Starting Prometheus" version="(version=2.13.0, branch=HEAD, revision=6ea4252299f542669aca11860abc2192bdc7bede)"
prometheus_1  | level=info ts=2019-10-05T09:51:23.037Z caller=main.go:333 build_context="(go=go1.13.1, user=root@f30bdad2c3fd, date=20191004-12:23:30)"
prometheus_1  | level=info ts=2019-10-05T09:51:23.038Z caller=main.go:334 host_details="(Linux 4.14.78-4-osmc #1 SMP PREEMPT Wed Dec 12 17:58:11 UTC 2018 armv7l e8bfc40ea4d5 osmc.tv)"
prometheus_1  | level=info ts=2019-10-05T09:51:23.039Z caller=main.go:335 fd_limits="(soft=1048576, hard=1048576)"
prometheus_1  | level=info ts=2019-10-05T09:51:23.040Z caller=main.go:336 vm_limits="(soft=unlimited, hard=unlimited)"
prometheus_1  | level=info ts=2019-10-05T09:51:23.058Z caller=main.go:657 msg="Starting TSDB ..."
prometheus_1  | level=info ts=2019-10-05T09:51:23.059Z caller=web.go:450 component=web msg="Start listening for connections" address=0.0.0.0:9090
prometheus_1  | level=info ts=2019-10-05T09:51:23.114Z caller=head.go:512 component=tsdb msg="replaying WAL, this may take awhile"
prometheus_1  | panic: runtime error: invalid memory address or nil pointer dereference
prometheus_1  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0x12464]
prometheus_1  | 
prometheus_1  | goroutine 210 [running]:
prometheus_1  | github.com/prometheus/prometheus/tsdb.(*Head).MinTime(...)
prometheus_1  |     /app/tsdb/head.go:1172
prometheus_1  | github.com/prometheus/prometheus/tsdb.(*Head).updateMinMaxTime(0x445a580, 0xffffffff, 0x7fffffff, 0x0, 0x80000000)
prometheus_1  |     /app/tsdb/head.go:306 +0x2c
prometheus_1  | github.com/prometheus/prometheus/tsdb.(*Head).processWALSamples(0x445a580, 0x0, 0x80000000, 0x4486900, 0x4486840, 0x0, 0x0)
prometheus_1  |     /app/tsdb/head.go:299 +0x484
prometheus_1  | github.com/prometheus/prometheus/tsdb.(*Head).loadWAL.func2(0x445a580, 0x4230238, 0x4230240, 0x4486900, 0x4486840)
prometheus_1  |     /app/tsdb/head.go:359 +0x3c
prometheus_1  | created by github.com/prometheus/prometheus/tsdb.(*Head).loadWAL
prometheus_1  |     /app/tsdb/head.go:358 +0x160
```

On x86_64 is working fine.

Versión 2.12 is working fine in ARM: image: prom/prometheus:v2.12.0

**Environment**

* System information:
Linux 4.14.78-4-osmc armv7l
But using docker!

```
services:
    prometheus:
        image: prom/prometheus
        restart: always
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
            - prometheus-storage:/prometheus
```
I tried with a new "prometheus-storage" (like a clean install) but it crash too.

### PR DESCRIPTION
**Pull request by csmarchbanks**
An extra sync.Pool was added during a refactor which caused some 64 bit,
atomically accessed variables to no longer be 64 bit aligned. By moving
all atomically accessed variables to the beginning of the struct they
are guaranteed to be 64 bit aligned.

Note that this PR is against the release-2.13 branch and will need to be
merged back into master.

cc: @krasi-georgiev since you are the release shepherd.

Closes #6105

### CODE REVIEW

File: tsdb/head.go [hunk 1]
```diff
@@ -61,18 +61,21 @@ var (
 
 // Head handles reads and writes of time series data within a time window.
 type Head struct {
-	chunkRange int64
+	// Keep all 64bit atomically accessed variables at the top of this struct.
+	// Otherwise ARM builds of Prometheus can fail due to alignment issues.
```
Comment (codesome) [inline tsdb/head.go]: 🤯

Comment (brian-brazil) [inline tsdb/head.go]: This line can be removed. ARM isn't related.

Comment (csmarchbanks) [reply tsdb/head.go]: :+1:

**Comment by csmarchbanks** [comment]
I also found a couple places where this could happen in the remote code and applied the same fix/comment just in case.

**Comment by brian-brazil** [comment]
:+1:

**Comment by krasi-georgiev** [comment]
> An extra sync.Pool was added during a refactor...

Which commit is this? I can't seem to find it.

**Comment by unixlab** [comment]
@krasi-georgiev pull request #5999 (commit `3344bb5`) in tsdb/head.go around line 67
https://github.com/prometheus/prometheus/pull/5999/files#diff-6fb13507bfadf9819fea5bda61f599e6L66

**Comment by krasi-georgiev** [comment]
Thanks
Will wait few days and if there are no new bug reports will make a new 2.13.1 release.
