### PR TITLE
Fix deadlock when stopping a shard

### LINKED ISSUE #10264: Remote write stop sending samples
**What did you see ? Under which circumstances?**

Prometheus stop sending samples to remote write.
I see in log that desired shards exploded

ts=2022-02-07T21:25:56.883Z caller=dedupe.go:112 component=remote level=info remote_name=29a4b7 url=http://x.x.x.x:yyy/insert/0/prometheus/api/v1/write msg="Remote storage resharding" from=1 to=2

ts=2022-02-07T21:26:06.883Z caller=dedupe.go:112 component=remote level=info remote_name=29a4b7 url=http://x.x.x.x:yyy/insert/0/prometheus/api/v1/write msg="Remote storage resharding" from=2 to=3

ts=2022-02-07T21:26:16.884Z caller=dedupe.go:112 component=remote level=info remote_name=29a4b7 url=http://x.x.x.x:yyy/insert/0/prometheus/api/v1/write msg="Remote storage resharding" from=3 to=5

...

ts=2022-02-07T21:27:26.883Z caller=dedupe.go:112 component=remote level=debug remote_name=29a4b7 url=http://x.x.x.x:yyy/insert/0/prometheus/api/v1/write msg=QueueManager.updateShardsLoop lowerBound=30.79999
9999999997 desiredShards=53.58719996305498 upperBound=57.2

ts=2022-02-07T21:39:16.884Z caller=dedupe.go:112 component=remote level=warn remote_name=29a4b7 url=http://x.x.x.x:yyy/insert/0/prometheus/api/v1/write msg="Skipping resharding, last successful send was beyond threshold" lastSendTimestamp=1644269277 minSendTimestamp=1644269946

prometheus stats

**Environment**

Prometheus docker version.
prometheus, version 2.33.1 (branch: HEAD, revision: 4e08110891fd5177f9174c4179bc38d789985a13)
  build user:       root@37fc1ebac798
  build date:       20220202-15:23:18
  go version:       go1.17.6
  platform:         linux/amd64

* Prometheus configuration file:
```
global:
  scrape_interval: 1m
  scrape_timeout: 55s
  evaluation_interval: 30s
  external_labels:
    datacenter: xxxxx

remote_write:
  - url: http://x.x.x.x:yyyy/insert/0/prometheus/api/v1/write
    queue_config:
      batch_send_deadline: 5s
      min_backoff: 1s
      max_backoff: 30s
```

### PR DESCRIPTION
**Pull request by csmarchbanks**
If a queue is stopped and one of its shards happens to hit the
batch_send_deadline at the same time a deadlock can occur where stop
holds the mutex and will not release it until the send is finished, but
the send needs the mutex to retrieve the most recent batch. This is
fixed by using a second mutex just for writing.

In addition, the test I wrote exposed a case where during shutdown a
batch could be sent twice due to concurrent calls to queue.Batch() and
queue.FlushAndShutdown(). Protect these with a mutex as well.

Fixes #10264 

This change is a bit slower due to the extra mutexes, but still much faster
than before #9830. Some work could be done in the future to remove some
mutexes/speed this up but this is the safest change to fix the issue I came
up with.
```
name           old time/op    new time/op    delta
SampleSend-16    1.64ms ± 2%    1.75ms ± 1%  +6.79%  (p=0.000 n=10+9)

name           old alloc/op   new alloc/op   delta
SampleSend-16    50.9kB ± 8%    51.9kB ± 5%    ~     (p=0.247 n=10+10)

name           old allocs/op  new allocs/op  delta
SampleSend-16       148 ± 1%       150 ± 1%  +1.35%  (p=0.001 n=9+9)
```

cc: @beorn7 this is pointing to the release-2.33 branch.

### CODE REVIEW

File: storage/remote/queue_manager.go [hunk 1]
```diff
@@ -1026,6 +1031,9 @@ func (s *shards) enqueue(ref chunks.HeadSeriesRef, data sampleOrExemplar) bool {
 type queue struct {
 	batch      []sampleOrExemplar
 	batchQueue chan []sampleOrExemplar
+	// batchMtx covers sending to the batchQueue and batch operations other
+	// than appending a sample.
+	batchMtx sync.Mutex
```
Comment (cstyan) [inline storage/remote/queue_manager.go:1036]: nit, can we keep mtx fields above the things they lock in the struct field listings

File: storage/remote/queue_manager.go [hunk 2]
```diff
@@ -1186,18 +1202,18 @@ func (s *shards) runShard(ctx context.Context, shardID int, queue *queue) {
 			timer.Reset(time.Duration(s.qm.cfg.BatchSendDeadline))
 
 		case <-timer.C:
-			// We need to take the lock when getting a batch to avoid
+			// We need to take the write lock when getting a batch to avoid
```
Comment (cstyan) [inline storage/remote/queue_manager.go:1205]: A comment as to why this needs to be the shard write mutex instead of the queue batch mutex would be useful.

**Review by cstyan — APPROVED** [review]

File: storage/remote/queue_manager.go (hunk 1 above)
Comment (csmarchbanks) [reply storage/remote/queue_manager.go]: :+1: I also change the other mutex for queue to be consistent.

File: storage/remote/queue_manager.go (hunk 2 above)
Comment (csmarchbanks) [reply storage/remote/queue_manager.go:1204]: I expanded some on this comment for the reasoning here. Let me know if it addresses your concerns!

**Review by bwplotka — COMMENTED** [review]
+1
