### PR TITLE
Fix data corruption in remote write if max_sample_age is applied

### LINKED ISSUE #13979: Corrupting data written to remote storage in case sample_age_limit is hit
### What did you do?

We've started experiencing data corruption since we have started using `remote_write.queue_config.sample_age_limit`. We want to drop old samples after our Disaster recovery tests, in order to make sure we see fresh data as soon as possible (and we do not care much about samples scraped during the test itself). After these tests (which is basically the only time when `sample_age_limit` applies as we try to make sure we do not hit it during normal operation) we have seen unexpected counter resets as well as new, unexpected timeseries.

### What did you expect to see?

Hitting `sample_age_limit` should only drop old data.

### What did you see instead? Under which circumstances?

Our production setup is Prometheus with remote write directed towards Mimir cluster. In case when remote write endpoint is not accessible for more than `sample_age_limit`, we have seen corruptions in data ingested to remote storage. In both cases, just 2-3 samples just after remote write endpoint resumes its operation, and Prometheus drops old data and starts ingesting again.

So far we have notices two cases:
1. unexpected samples gets appended to an existing timeseries. Timestamp does not align with our scrape_interval, and value also does not align the timeseries. It probably happens to any metric type, but we have noticed this only with counters as the "fake" values are interpreted as a counter reset, causing huge spikes in our graphs.
2. new timeseries is created, with just a few samples just after the remote_write resume to ingest data to remote storage just like in the previous case. We have noticed it for cases which are clearly nonsense. It seems that existing series get mixed, like in this case when we tested it with Prometheus holding only its own exposed metrics and node_exporter - `go_gc_duration_seconds_count{cluster="local-test", instance="localhost:9100", job="node-exporter", name="systemd-networkd.service", state="activating", type="notify-reload"}`

The above we have been able to reproduce in setup with localy running Prometheus binary with configured remote_write towards our staging Mimir cluster. The outage have been simulated by `iptables -I OUTPUT -d __IP__ -j DROP`.

We have also tried to reproduce it in setup with two Prometheis with one serving as a remote_write receiver (see the attached docker-compose). In this scenario, we haven't seen any corrupted data in the receiving Prometheus, but we are getting log complaining about corrupted data:

### System information

Linux 6.5.0-27-generic x86_64

### Prometheus version

```text
prometheus, version 2.50.1 (branch: HEAD, revision: 8c9b0285360a0b6288d76214a75ce3025bce4050)
  build user:       root@6213bb3ee580
  build date:       20240226-11:36:26
  go version:       go1.21.7
  platform:         linux/amd64
  tags:             netgo,builtinassets,stringlabels
```

### Prometheus configuration file

```yaml
global:
        scrape_interval: 30s
        scrape_timeout: 10s
        scrape_protocols:
        - OpenMetricsText1.0.0
        - OpenMetricsText0.0.1
        - PrometheusText0.0.4
        evaluation_interval: 30s
        external_labels:
          __replica__: prometheus-local-test-0
          cluster: local-test
      scrape_configs:
      - job_name: prometheus-scif-monitoring
        honor_timestamps: false
        track_timestamps_staleness: false
        scrape_interval: 30s
        scrape_timeout: 10s
        scrape_protocols:
        - OpenMetricsText1.0.0
        - OpenMetricsText0.0.1
        - PrometheusText0.0.4
        metrics_path: /metrics
        scheme: http
        enable_compression: false
        follow_redirects: false
        enable_http2: false
        static_configs:
        - targets:
          - localhost:9090
      - job_name: node-exporter
        honor_timestamps: false
        track_timestamps_staleness: false
        scrape_interval: 5s
        scrape_timeout: 1s
        scrape_protocols:
        - OpenMetricsText1.0.0
        - OpenMetricsText0.0.1
        - PrometheusText0.0.4
        scheme: http
        enable_compression: false
        follow_redirects: false
        enable_http2: false
        metrics_path: /metrics
        static_configs:
        - targets:
          - node-exporter:9100
      remote_write:
      - url: http://receive-prometheus:9090/api/v1/write
        remote_timeout: 12s
        follow_redirects: true
        enable_http2: true
        queue_config:
          capacity: 100
          max_shards: 3
          min_shards: 12
          batch_send_deadline: 5s
          min_backoff: 30ms
          max_backoff: 5s
          sample_age_limit: 1m
        metadata_config:
          send: true
          send_interval: 1m
          max_samples_per_send: 100
```

### Alertmanager version

_No response_

### Alertmanager configuration file

_No response_

### Logs

```text
prometheus          | ts=2024-04-23T10:06:18.038Z caller=dedupe.go:112 component=remote level=warn remote_name=dabaca url=http://receive-prometheus:9090/api/v1/write msg="Failed to send batch, retrying" err="Post \"http://receive-prometheus:9090/api/v1/write\": context deadline exceeded"
prometheus          | ts=2024-04-23T10:07:26.043Z caller=dedupe.go:112 component=remote level=warn remote_name=dabaca url=http://receive-prometheus:9090/api/v1/write msg="Failed to send batch, retrying" err="Post \"http://receive-prometheus:9090/api/v1/write\": context deadline exceeded"
prometheus          | ts=2024-04-23T10:08:34.050Z caller=dedupe.go:112 component=remote level=warn remote_name=dabaca url=http://receive-prometheus:9090/api/v1/write msg="Failed to send batch, retrying" err="Post \"http://receive-prometheus:9090/api/v1/write\": context deadline exceeded"
prometheus          | ts=2024-04-23T10:09:11.336Z caller=dedupe.go:112 component=remote level=info remote_name=dabaca url=http://receive-prometheus:9090/api/v1/write msg="Remote storage resharding" from=12 to=3
receive-prometheus  | ts=2024-04-23T10:09:11.998Z caller=write_handler.go:77 level=error component=web msg="Error appending remote write" err="label name \"job\" is not unique: invalid sample"
receive-prometheus  | ts=2024-04-23T10:09:11.998Z caller=write_handler.go:77 level=error component=web msg="Error appending remote write" err="label name \"job\" is not unique: invalid sample"
prometheus          | ts=2024-04-23T10:09:12.029Z caller=dedupe.go:112 component=remote level=warn remote_name=dabaca url=http://receive-prometheus:9090/api/v1/write msg="Failed to send batch, retrying" err="server returned HTTP status 500 Internal Server Error: label name \"job\" is not unique: invalid sample"
receive-prometheus  | ts=2024-04-23T10:09:12.035Z caller=write_handler.go:134 level=error component=web msg="Out of order sample from remote write" err="duplicate sample for timestamp" series="{__name__=\"go_gc_duration_seconds\", __replica__=\"prometheus-local-test-0\", cluster=\"local-test\", instance=\"node-exporter:9100\", job=\"node-exporter\"}" timestamp=1713866946725
receive-prometheus  | ts=2024-04-23T10:09:12.035Z caller=write_handler.go:77 level=error component=web msg="Error appending remote write" err="label name \"job\" is not unique: invalid sample"
prometheus          | ts=2024-04-23T10:09:12.035Z caller=dedupe.go:112 component=remote level=error remote_name=dabaca url=http://receive-prometheus:9090/api/v1/write msg="non-recoverable error" count=2000 exemplarCount=0 err="server returned HTTP status 400 Bad Request: duplicate sample for timestamp"
```

### PR DESCRIPTION
**Pull request by FUSAKLA**
/fixes #13979 

The PR https://github.com/prometheus/prometheus/pull/13002  added the option to drop old samples in remote write.

Unfortunatelly we bumped into a bug causing data to be corrupted (metrics withlabels getting merged with other metrics labels was the most obvious) reported here https://github.com/prometheus/prometheus/issues/13979

after trying to repproduce the issue it showed up it is strictly connected to situations, when retries does happen and the `filter` in `buildTimeSeries` is applied.

We did investigate and it appears that the issue is in the newly added  `buildTimeSeries` function which does modify the `timeSeries` argument  causing the corruption. 

The suggested change, which avoids modification of the original timeSeries seems to fix the issue, but is naive and not sure how optimal.

### CODE REVIEW

**Comment by FUSAKLA** [comment]
Unfortunately, I had no luck with writing a test that would cover the case yet

Yet, it is possible to reproduce the bug with 100% "success" 

Run locally Prometheus with following config
```yaml
global:
  scrape_interval: 5s
  external_labels:
    __replica__: prometheus-local-test-0
    cluster: local-test
    mimir_cluster_id: monitoring.scif.cz/local-test

remote_write:
  - url: http://foo.bar // URL of some remote write endpoint with known IP si it can be blocked
    queue_config:
      max_shards: 1
      min_shards: 1
      batch_send_deadline: 5s
      capacity: 100
      sample_age_limit: 30s
    metadata_config:
      send: true
      send_interval: 1m
      max_samples_per_send: 100

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090

  - job_name: node-exporter // running with default configuration
    static_configs:
      - targets:
          - localhost:9100
```

When it is running, block the communication to the remote write endpoint IP using `sudo iptables -I OUTPUT -d <ip> -j DROP`

Wait until you see a context deadline exceeded, log in the Prometheus and enable the traffic again `sudo iptables -F OUTPUT` 

At this point the issue happens. If you run with debugger inspecting the `pendingData` variable in the `runShard` function, you can find for example `up` metrics with duplicated labels like `job`, `mimir_cluster_id` etc

**Comment by FUSAKLA** [comment]
Mentioning @marctc and @tpaschalis as you were authors of the original code and have most context, hope you don't mind.

**Comment by cstyan** [comment]
Sorry, but for a bug that sounds as bad as what you're describing we need a test case to ensure we've fixed the problem/this doesn't happen again. I think because of the number of functions at play here and the fact that some of them are closures within other functions that is obscuring the underlying problem and also making it hard to test things here.

My suggestion would be to add a test that uses a version of the test client that can fail and enforce a retry since you're saying this only happens when we need to retry sending an existing write request.

Beyond that, we likely need to refactor some of the code path here so that it's easier to test and less likely to break again.

**Comment by FUSAKLA** [comment]
Hi @cstyan, thanks for answer.

Yes, I agree. We used this bug fix successfully in our production, since we needed it asap,
but I'm planning to look into writing the test, so I can verify it's really not happening anymore (it's hard to find the corrupted data).

I'll ping you once I manage to reproduce it, if you don't mind.

**Comment by cstyan** [comment]
I've pinged Paschalis and Marc internally as well, they're aware of the problem and are looking into it.


> We used this bug fix successfully in our production, since we needed it asap

That's good to know, if it becomes pressing we can just move forward with your PR as is. Having a test is still ideal, some part of me feels like while the fix here works it might not be the correct fix because it seems like what's happening is we're modifying the underlying slice of buffered data but not returning a reference to the proper range for the modified slice.


> I'll ping you once I manage to reproduce it, if you don't mind.

:+1:

**Review by tpaschalis — COMMENTED** [review]
Just to understand, the difference proposed here is to not mutate the input `timeSeries` slice, right? Otherwise the logic looks the same.

Do you think that's why it's impacted on retries? I'd also like to have a test to make sure we don't accidentally regress on this.

**Comment by FUSAKLA** [comment]
@tpaschalis yes, this seemed to fix the issue using the above described way to reproduce. 

I'm trying to reproduce it in a test case, but with no luck yet.
Here is a text case I'm working on right now https://github.com/prometheus/prometheus/pull/14157

**Comment by david-vavra** [comment]
I rebased this over https://github.com/prometheus/prometheus/pull/14157 which adds a test case which reproduces the bug reported in https://github.com/prometheus/prometheus/issues/13979.

**Comment by FUSAKLA** [comment]
@cstyan @tpaschalis would you take a look? 

As @david-vavra noted above (we are from the same company) we managed to reproduce the issue in https://github.com/prometheus/prometheus/pull/14157 and the fix from this PR resolves it (not saying it should be accepted this way even though we run it in production without any significant memory impact observed)

We still do not exactly know where the actual corruption happens, just that avoiding reusing the `[]prompb.TimeSeries` slice does solve the issue.

**Comment by david-vavra** [comment]
I believe I got into the bottom of this. 
In case when just a part of a single batch gets dropped (because samples hit `maxSampleAge` during retrying), `timeSeries []prompb.TimeSeries` is rewritten so that timeseries which are to be kept are copied to the beginning of the slice so that it can be cut to a number of kept timeseries - [see queue_manager.go:buildTimeSeries](https://github.com/prometheus/prometheus/blob/1c3f322f7832d6ebbba9dc3a13b398e03e014bcf/storage/remote/queue_manager.go#L1787). 
The problem shows itself when a new batch is getting filled into `[]prompb.TimeSeries` (which is reused across batches) and those positions which refer to the same `prompb.TimeSeries` share the same data for underlying slices (`[]Labels`, `[]Samples`,...). This leads to mixing/corruption of labels and samples.

I propose fix which would swap data within `[]prompb.TimeSeries` instead of copying them. Other options may be more readable, but I wanted to keep the number of changes to a minimum and to avoid changes to "happy-path" (samples do not age-out during retrying).

**Comment by cstyan** [comment]
@FUSAKLA @david-vavra sorry for the delayed response, I had a noisy on-call shift followed by an in person team offsite.

The main thing I still want to see is a test that reproduces the issue we see. From @david-vavra's comment it sounds like we know the specific case in which the labels 'corruption ' can occur, so a test should be our next step.

That being said, I'm still not sure how the corruption can happen as you're describing it. In [populateTimeSeries](https://github.com/prometheus/prometheus/blob/1c3f322f7832d6ebbba9dc3a13b398e03e014bcf/storage/remote/queue_manager.go#L1496) we're explicitly writing the new data into the reused `[]prompb.TimeSeries` slice starting from index 0, and then returning the count for how many things we wrote into the slice. Am I missing something here?

I do agree that the issue is likely in the modifying of the elements in the slice and the reference indexes.

In the meantime I've opened this PR: https://github.com/prometheus/prometheus/pull/14318

**Comment by cstyan** [comment]
@FUSAKLA @david-vavra My mistake, I pressed the `update branch` since it looked locally I saw the test still failing and thought that there was some code changes in `main` that you guys were missing, which would show in a CI failure here. I must have missed something last night when trying the test locally. 

It passes! Fails without the change to `queue_manager.go` but passes with the change, which is good news. Feel free to pull main locally, rebase, and force push over my merge commit. My final ask would be to cherry pick the benchmark from here: https://github.com/prometheus/prometheus/commit/5609bd7b1c08968f2bd58ec79c8d990e651775e8

And then lets merge :+1:

**Comment by david-vavra** [comment]
I rebased and cherry-picked the benchmark mentioned in by https://github.com/prometheus/prometheus/pull/14078#issuecomment-2181746353.

Benchmark result:

Without fix (benchmark cherry-picked to [current main](https://github.com/prometheus/prometheus/tree/d78253319daa62c8f28ed47e40bafcad2dd8b586):
```
goos: linux
goarch: amd64
pkg: github.com/prometheus/prometheus/storage/remote
cpu: AMD Ryzen 7 7840HS with Radeon 780M Graphics   
BenchmarkBuildTimeSeries-16    	     738	   1531949 ns/op	 2650813 B/op	   39748 allocs/op
BenchmarkBuildTimeSeries-16    	     757	   1543058 ns/op	 2650798 B/op	   39748 allocs/op
BenchmarkBuildTimeSeries-16    	     741	   1557946 ns/op	 2650801 B/op	   39748 allocs/op
BenchmarkBuildTimeSeries-16    	     751	   1544889 ns/op	 2650809 B/op	   39748 allocs/op
BenchmarkBuildTimeSeries-16    	     732	   1546391 ns/op	 2650812 B/op	   39748 allocs/op
BenchmarkBuildTimeSeries-16    	     730	   1530907 ns/op	 2650807 B/op	   39748 allocs/op
BenchmarkBuildTimeSeries-16    	     733	   1532309 ns/op	 2650811 B/op	   39748 allocs/op
BenchmarkBuildTimeSeries-16    	     739	   1539659 ns/op	 2650808 B/op	   39748 allocs/op
BenchmarkBuildTimeSeries-16    	     741	   1546674 ns/op	 2650816 B/op	   39748 allocs/op
BenchmarkBuildTimeSeries-16    	     739	   1538725 ns/op	 2650810 B/op	   39748 allocs/op
PASS
ok  	github.com/prometheus/prometheus/storage/remote	13.073s
```

[With fix](https://github.com/prometheus/prometheus/tree/ed78a97197ba446861c820c64b5e16617f0e1ea4):
```
goos: linux
goarch: amd64
pkg: github.com/prometheus/prometheus/storage/remote
cpu: AMD Ryzen 7 7840HS with Radeon 780M Graphics   
BenchmarkBuildTimeSeries-16    	     721	   1572745 ns/op	 2650812 B/op	   39748 allocs/op
BenchmarkBuildTimeSeries-16    	     733	   1583777 ns/op	 2650815 B/op	   39748 allocs/op
BenchmarkBuildTimeSeries-16    	     746	   1563748 ns/op	 2650818 B/op	   39748 allocs/op
BenchmarkBuildTimeSeries-16    	     726	   1563117 ns/op	 2650818 B/op	   39748 allocs/op
BenchmarkBuildTimeSeries-16    	     728	   1572327 ns/op	 2650805 B/op	   39748 allocs/op
BenchmarkBuildTimeSeries-16    	     724	   1556734 ns/op	 2650817 B/op	   39748 allocs/op
BenchmarkBuildTimeSeries-16    	     740	   1574076 ns/op	 2650809 B/op	   39748 allocs/op
BenchmarkBuildTimeSeries-16    	     722	   1571599 ns/op	 2650806 B/op	   39748 allocs/op
BenchmarkBuildTimeSeries-16    	     706	   1565431 ns/op	 2650812 B/op	   39748 allocs/op
BenchmarkBuildTimeSeries-16    	     709	   1590074 ns/op	 2650795 B/op	   39748 allocs/op
PASS
ok  	github.com/prometheus/prometheus/storage/remote	13.101s
```

**Review by cstyan — APPROVED** [review]
Nice :+1: 

Benchmark shows that we're slightly slower now, which could be concerning given that if people turn this on it's on the hot path for sending data, but now that we have a test for correctness we can iterate on improving performance as well.

File: storage/remote/queue_manager_test.go [hunk 1]
```diff
@@ -1668,3 +1813,14 @@ func TestBuildTimeSeries(t *testing.T) {
 		})
 	}
 }
+
+func BenchmarkBuildTimeSeries(b *testing.B) {
+	// Send one sample per series, which is the typical remote_write case
+	const numSamples = 10000
+	filter := func(ts prompb.TimeSeries) bool { return filterTsLimit(99, ts) }
+	for i := 0; i < b.N; i++ {
+		samples := createProtoTimeseriesWithOld(numSamples, 100, extraLabels...)
```
Comment (bboreham) [inline storage/remote/queue_manager_test.go:1822]: Should this be included in the benchmark timing?
