### PR TITLE
promql(histograms): Fix counter reset hint handling when aggregating

### LINKED ISSUE #17308: PromQL (histograms): counter reset hint (AKA gauge vs. counter) is inconsistent when aggregating native histograms
### What did you do?

Aggregate a number of native histograms with `avg`/`sum` or their `_over_time` versions where those histograms are not all gauge histograms.

This is a relatively rare use case (as you should commonly only aggregate gauge histograms), and the counter reset hint is not heavily used from the user perspective. Thus, I would not let this issue block declaring NH a stable feature, but just consider it a known bug. However, let's aim for fixing it in time. Therefore, marking it as P2 for now.

### What did you expect to see?

A consistent and reproducible handling of those:
1. If all counter reset hints are the same, the result has that same counter reset hint.
2. Otherwise, if there is at least one `GaugeType`, the outcome is `GaugeType`.
3. Otherwise, the outcome is `UnknownCounterReset`.
4. If in any case (except (1)), there is a direct contradiction in the mix (`CounterReset` vs. `CounterReset`), add a warn-level annotation.

### What did you see instead? Under which circumstances?

The aggregation happen in pseudo-random order, and this leads to different outcomes. Furthermore, the avg calculation is using incremental mean calculation, which uses the `Sub` method of the `FloatHistogram`, which always sets the counter reset hint to `GaugeType`.

This results in the following behavior in the cases above:

1. Works for `sum`/`sum_over_time`, but `avg/`avg_over_time` always results in `GaugeType` even if the counter reset hint shared by all involved histograms is a different one.
2. This works already.
3. Works for `sum`/`sum_over_time`, but `avg/`avg_over_time` always results in `GaugeType`.
4. The warn-level annotation is omitted in some cases, because a "lucky" order of aggregation might turn the contradicting counter reset hints into `UnknownCounterReset` or `GaugeType` before they hit their counterpart.

### System information

_No response_

### Prometheus version

```text

```

### Prometheus configuration file

```yaml

```

### Alertmanager version

```text

```

### Alertmanager configuration file

```yaml

```

### Logs

```text

```

### PR DESCRIPTION
**Pull request by beorn7**
Fixes #17308.

As explained adding the warn-annotation about conflicting counter reset hints doesn't happen consistently. Furthermore, because of incremental mean calculation being used so far (which includes subtraction), avg calculation always created gauge histograms.

The fix is to make Sub behave like Add WRT counter reset handling, and then set the result of a subtraction to gauge explicitly in actual PromQL subtraction (rather than using Sub for something else, like incremental mean calculation). Also, track the presence of a CounterReset hint and a NotCounterReset hint separately for the entirety of aggregated histograms and create the warn-annotation based on that.

As a minor fix, this commit also consistently creates the warn annotation in aggregation to be about "aggregation" rather than "subtraction" or "addition", because the latter are just internal operations within the aggregation, which is not of interest for the user.

#### Does this PR introduce a user-facing change?

```release-notes
[BUGFIX] Consistent handling of gauge vs. counter histograms in aggregations.
```

### CODE REVIEW

File: model/histogram/float_histogram.go [hunk 1]
```diff
@@ -283,7 +283,8 @@ func (h *FloatHistogram) ZeroBucket() Bucket[float64] {
 // bucket counts including the zero bucket and the count and the sum of
 // observations. The bucket layout stays the same. This method changes the
 // receiving histogram directly (rather than acting on a copy). It returns a
-// pointer to the receiving histogram for convenience.
+// pointer to the receiving histogram for convenience. If factor is negative,
+// the counter reset hint is set to GaugeType.
```
Comment (krajorama) [inline model/histogram/float_histogram.go:287]: please also add to Div for consistency

File: model/histogram/float_histogram.go [hunk 2]
```diff
@@ -1387,3 +1351,49 @@ func (h *FloatHistogram) ReduceResolution(targetSchema int32) *FloatHistogram {
...
+		h.CounterResetHint = GaugeType
+	case h.CounterResetHint == UnknownCounterReset:
+		// With the receiver's CounterResetHint being "unknown", this could still be legitimate
+		// if the caller knows what they are doing. Outcome is then again "unknown".
+		// No need to do anything since the receiver's CounterResetHint is already "unknown".
+	case other.CounterResetHint == UnknownCounterReset:
+		// Similar to before, but now we have to set the receiver's CounterResetHint to "unknown".
+		h.CounterResetHint = UnknownCounterReset
+	default:
+		// All other cases shouldn't actually happen.
```
Comment (krajorama) [inline model/histogram/float_histogram.go:1393]: Kind of weird to call out just this case. I would expect most queries to do rate first (resulting in gauge) and then do sum/add/sub , so maybe this line should be further up?

File: model/histogram/float_histogram.go [hunk 3]
```diff
@@ -417,19 +391,16 @@ func (h *FloatHistogram) Add(other *FloatHistogram) (res *FloatHistogram, counte
 	return h, counterResetCollision, nil
 }
 
-// Sub works like Add but subtracts the other histogram.
+// Sub works like Add but subtracts the other histogram. It uses the same logic
+// to adjust the counter reset hint. This is useful where this method is used
+// for incremental mean calculation. However, if it is used for the actual "-"
+// operator in PromQL, the counter reset needs to be set to GaugeType after
```
Comment (krajorama) [inline model/histogram/float_histogram.go:398]: Sounds like it would be better to implement `Sub()` as a call to `SubKeepHint()` + setting the hint. To encode the expected behavior in code, rather then doc string.

File: promql/engine.go [hunk 4]
```diff
@@ -3125,6 +3125,8 @@ func vectorElemBinop(op parser.ItemType, lhs, rhs float64, hlhs, hrhs *histogram
 				if err != nil {
 					return 0, nil, false, err
 				}
+				// The result must be marked as gauge.
+				res.CounterResetHint = histogram.GaugeType
```
Comment (krajorama) [inline promql/engine.go:3129]: Following my comment on `Sub` this should not be needed.

File: model/histogram/float_histogram.go (hunk 3 above)
Comment (beorn7) [reply model/histogram/float_histogram.go:398]: We only need this special case once. So in hindsight, it was wrong to implement the special case in `Sub`. I only added it to the doc string here to avoid a misunderstanding because people might already got used to the old behavior.

File: promql/engine.go (hunk 4 above)
Comment (beorn7) [reply promql/engine.go:3129]: As this is the only time we have to do it, creating a separate method just for it seems counterproductive.

File: promql/engine.go [hunk 5]
```diff
@@ -3194,6 +3198,12 @@ func (ev *evaluator) aggregation(e *parser.AggregateExpr, q float64, inputMatrix
 				} else {
 					group.histogramValue = h.Copy()
 					group.hasHistogram = true
+					switch h.CounterResetHint {
```
Comment (krajorama) [inline promql/engine.go:3201]: Seems like a candidate for a little helper function, I think it could be inlined easily.

File: promql/engine.go [hunk 6]
```diff
@@ -3419,6 +3432,9 @@ func (ev *evaluator) aggregation(e *parser.AggregateExpr, q float64, inputMatrix
 			default:
 				aggr.floatValue = aggr.floatValue/aggr.groupCount + aggr.floatKahanC/aggr.groupCount
 			}
+			if aggr.counterResetSeen && aggr.notCounterResetSeen {
```
Comment (krajorama) [inline promql/engine.go]: optional: since we only keep track of these for SUM and AVG, we could move outside the switch and just do this once? These won't be both true in any other case. Just a thought.

File: promql/functions.go [hunk 7]
```diff
@@ -820,25 +820,38 @@ func funcAvgOverTime(_ []Vector, matrixVal Matrix, args parser.Expressions, enh
 		// The passed values only contain histograms.
 		var annos annotations.Annotations
 		vec, err := aggrHistOverTime(matrixVal, enh, func(s Series) (*histogram.FloatHistogram, error) {
+			var counterResetSeen, notCounterResetSeen bool
+
+			trackCounterReset := func(h *histogram.FloatHistogram) {
```
Comment (krajorama) [inline promql/functions.go:825]: In this case this seems like overkill, it's just used once, makes the code not consistent with `funcSumOverTime`

File: promql/promqltest/testdata/native_histograms.test [hunk 8]
```diff
@@ -1552,35 +1552,156 @@ eval instant at 54m30s histogram_count(increase(metric[54m45s]))
...
+# Subtraction results in gauges, even if the result is not negative.
+eval instant at 5m metric - 0.5 * metric
+  expect no_warn
+  expect no_info
+  {id="1"} {{count:2 sum:2 counter_reset_hint:gauge buckets:[0.5 1 0.5]}}
+  {id="2"} {{count:2 sum:2 counter_reset_hint:gauge buckets:[0.5 1 0.5]}}
 
-# Unary minus turns counters into gauges.
-eval instant at 5m -metric
+eval instant at 5m metric - 2 * metric
```
Comment (krajorama) [inline promql/promqltest/testdata/native_histograms.test:1575]: Doesn't have docstring

File: promql/promqltest/testdata/native_histograms.test [hunk 9]
```diff
@@ -1552,35 +1552,156 @@ eval instant at 54m30s histogram_count(increase(metric[54m45s]))
...
+  {} {{count:8 sum:8 counter_reset_hint:not_reset buckets:[2 4 2]}}
+
+eval instant at 5m avg(metric)
+  expect no_warn
+  expect no_info
+  {} {{count:4 sum:4 counter_reset_hint:not_reset buckets:[1 2 1]}}
+
 clear
 
+load 1m
```
Comment (krajorama) [inline promql/promqltest/testdata/native_histograms.test:1597]: We need a comment above that currently the counter resets show up as unknown reset hint when the samples are directly read (refer to the infamous issue) , but if you read through the histogram_count and thereby the histogram stats iterator, then we do a counter reset detection and we do get actual counter reset hint.

File: promql/promqltest/testdata/native_histograms.test [hunk 10]
```diff
@@ -1552,35 +1552,156 @@ eval instant at 54m30s histogram_count(increase(metric[54m45s]))
...
+  expect no_warn
+  expect no_info
+  {} {{count:105 sum:90 counter_reset_hint:unknown buckets:[35 40 30]}}
+
+eval instant at 15m avg_over_time(mixed[10m])
+  expect no_warn
+  expect no_info
+  {} {{count:10.5 sum:9 counter_reset_hint:unknown buckets:[3.5 4 3]}}
+
+# Simulate direct counter reset collisions by going through the HistogramStatsIterator.
```
Comment (krajorama) [inline promql/promqltest/testdata/native_histograms.test]: Took me a while to understand this, please provide a short explanation like above.

File: model/histogram/float_histogram.go (hunk 1 above)
Comment (beorn7) [reply model/histogram/float_histogram.go:287]: Good point. DOne.

File: model/histogram/float_histogram.go (hunk 2 above)
Comment (beorn7) [reply model/histogram/float_histogram.go:1393]: I mean, we do all of this (and don't just reject additions of counters altogether) because users might know what they are doing and add up counter histograms that they know are "in sync" (getting reset at the same time). That's why we allow this. But then it should never happen that we see directly contradicting counter reset hints. That's why this case is special.

Another point is the logical flow. `default:` has to be at the end. It would be more verbose to explicitly ask for the two-way direct counter reset collision. And then we would probably still want to add a `default:` section (that maybe panics because we have dealt with all combinations explicitly?).

When this was written (long ago - this just looks now here because it got pulled out into its own helper function), we thought it is the clearest way… (this actually happened during a group coding session in Whistler…).

File: promql/promqltest/testdata/native_histograms.test (hunk 8 above)
Comment (beorn7) [reply promql/promqltest/testdata/native_histograms.test:1575]: Added.

File: promql/promqltest/testdata/native_histograms.test (hunk 10 above)
Comment (beorn7) [reply promql/promqltest/testdata/native_histograms.test]: Done.

File: promql/engine.go (hunk 5 above)
Comment (beorn7) [reply promql/engine.go:3201]: I thought so, too, but the little helper function needs to receive both the bools via pointers. It would replace five pretty clear and obvious lines by one long and fairly mysterious line. I created a local function where I do this multiple times in the same scope, because the local function doesn't need the bools passed in, but decided to not go down the helper function route here. But the price is to repeat these five lines quite often. I could be convinced otherwise if you like it more.

For reference, call would look like:

```Go
    trackCounterReset(h, &group.counterResetSeen, &group.notCounterResetSeen)
```

File: promql/engine.go (hunk 6 above)
Comment (beorn7) [reply promql/engine.go]: True. Done.

File: promql/functions.go (hunk 7 above)
Comment (beorn7) [reply promql/functions.go:825]: It is used twice, see also comment above.

File: model/histogram/float_histogram.go (hunk 2 above)
Comment (krajorama) [reply model/histogram/float_histogram.go:1393]: Lol  , "users might know what they are doing" is such a deep cut w.r.t. PromQL. Anyway, all good.

File: promql/functions.go [hunk 11]
```diff
@@ -1077,15 +1090,26 @@ func funcSumOverTime(_ []Vector, matrixVal Matrix, args parser.Expressions, enh
...
+
 			sum := s.Histograms[0].H.Copy()
 			for _, h := range s.Histograms[1:] {
-				_, counterResetCollision, err := sum.Add(h.H)
+				switch h.H.CounterResetHint {
+				case histogram.CounterReset:
+					counterResetSeen = true
+				case histogram.NotCounterReset:
+					notCounterResetSeen = true
+				}
```
Comment (charleskorn) [inline promql/functions.go:1108]: Does this need to be done for `s.Histograms[0].H` as well? Otherwise if the first histogram is `CounterReset` and the rest are `NotCounterReset` (or vice versa), then the annotation won't be emitted.

Comment (beorn7) [reply promql/functions.go:1108]: You are right. I actually did this right for `avg_over_time` (and I vaguely remember that I even wrote a test for it, but now I'm confused because I run the same tests for avg_over_time and sum_over_time). I will investigate and create a fix with a test.

Comment (beorn7) [reply promql/functions.go:1108]: https://github.com/prometheus/prometheus/pull/17331

File: model/histogram/float_histogram.go [hunk 12]
```diff
@@ -417,19 +392,16 @@ func (h *FloatHistogram) Add(other *FloatHistogram) (res *FloatHistogram, counte
...
-	}
-	if h.UsesCustomBuckets() && !CustomBucketBoundsMatch(h.CustomValues, other.CustomValues) {
-		return nil, false, ErrHistogramsIncompatibleBounds
+	if err := h.checkSchemaAndBounds(other); err != nil {
+		return nil, false, err
 	}
-
-	counterResetCollision = hasCounterResetCollision(h, other)
-
-	h.CounterResetHint = GaugeType
```
Comment (krajorama) [inline model/histogram/float_histogram.go:431]: ignore, bookmark
