### PR TITLE
Fix Hetzner Robot SD decoding with non HTTP 2xx

### LINKED ISSUE #7870: Hetzner service discovery does not check the status code of the robot api
**What did you do?**

Try  HZ robot against a local endpoint, which returns a 404

**What did you expect to see?**

Service discovery tries to unmarshal the response.

**What did you see instead? Under which circumstances?**

Only unmarshal if the answer is 200. it means that it will also do that for 403 (unauthorized).

cc @LKaemmerling

### PR DESCRIPTION
**Pull request by LKaemmerling**
Fix Hetzner Robot SD trying to decode response when a non 2xx HTTP code was returned.
Closes #7870
Signed-off-by: Lukas Kämmerling <lukas.kaemmerling@hetzner-cloud.de>

### CODE REVIEW

File: discovery/hetzner/robot.go [hunk 1]
```diff
@@ -70,10 +71,16 @@ func (d *robotDiscovery) refresh(ctx context.Context) ([]*targetgroup.Group, err
 	if err != nil {
 		return nil, err
 	}
+
 	defer func() {
 		io.Copy(ioutil.Discard, resp.Body)
 		resp.Body.Close()
 	}()
+
+	if (resp.StatusCode < 200) || (resp.StatusCode >= 300) {
```
Comment (roidelapluie) [inline discovery/hetzner/robot.go:80]:
```suggestion
	if resp.StatusCode/100 != 2 {
```

File: discovery/hetzner/robot.go [hunk 2]
```diff
@@ -70,10 +71,16 @@ func (d *robotDiscovery) refresh(ctx context.Context) ([]*targetgroup.Group, err
...
+		return nil, errors.Errorf("non 2xx status '%v' response during hetzner service discovery with role robot", resp.StatusCode)
```
Comment (roidelapluie) [inline discovery/hetzner/robot.go:81]:
```suggestion
		return nil, errors.Errorf("non 2xx status '%d' response during hetzner service discovery with role robot", resp.StatusCode)
```

File: discovery/hetzner/robot_test.go [hunk 3]
```diff
@@ -84,3 +82,26 @@ func TestRobotSDRefresh(t *testing.T) {
 		})
 	}
 }
+
+func TestRobotSDRefreshHandleError(t *testing.T) {
+	suite := &robotSDTestSuite{}
+	suite.SetupTest(t)
+	suite.Mock.HandleRobotServersWithError()
+	cfg := DefaultSDConfig
+	cfg.HTTPClientConfig.BasicAuth = &config.BasicAuth{Username: robotTestUsername, Password: robotTestPassword}
```
Comment (roidelapluie) [inline discovery/hetzner/robot_test.go:91]:
```suggestion
```

**Review by roidelapluie — COMMENTED** [review]
Can you rewrite your test to just call the existing mock without username? that is what users will most likely do and the mock can alrady return an unauthorized error.

And other nits.


Thanks!

File: discovery/hetzner/robot_test.go [hunk 4]
```diff
@@ -84,3 +83,24 @@ func TestRobotSDRefresh(t *testing.T) {
...
+	suite := &robotSDTestSuite{}
+	suite.SetupTest(t)
+	cfg := DefaultSDConfig
+	cfg.robotEndpoint = suite.Mock.Endpoint()
+
+	d, err := newRobotDiscovery(&cfg, log.NewNopLogger())
+	testutil.Ok(t, err)
+
+	targetGroups, err := d.refresh(context.Background())
+	if err == nil {
```
Comment (roidelapluie) [inline discovery/hetzner/robot_test.go:97]: testutil.NotOk(t,err)

File: discovery/hetzner/robot_test.go [hunk 5]
```diff
@@ -84,3 +83,24 @@ func TestRobotSDRefresh(t *testing.T) {
...
+		t.Fatalf("Expected err got, nil")
+	}
+	if err.Error() != "non 2xx status '401' response during hetzner service discovery with role robot" {
```
Comment (roidelapluie) [inline discovery/hetzner/robot_test.go:100]: testutil.Equal(t, "non 2xx status '401' response during hetzner service discovery with role robot", err.Error())

File: discovery/hetzner/robot_test.go [hunk 6]
```diff
@@ -84,3 +83,24 @@ func TestRobotSDRefresh(t *testing.T) {
...
+		t.Fatalf("Expected another error message, got %s", err)
+	}
+	if len(targetGroups) != 0 {
```
Comment (roidelapluie) [inline discovery/hetzner/robot_test.go:103]: testutil.Equal(t, 0, len(targetGroups))

File: discovery/hetzner/robot_test.go [hunk 7]
```diff
@@ -84,3 +83,20 @@ func TestRobotSDRefresh(t *testing.T) {
...
+	suite := &robotSDTestSuite{}
+	suite.SetupTest(t)
+	cfg := DefaultSDConfig
+	cfg.robotEndpoint = suite.Mock.Endpoint()
+
+	d, err := newRobotDiscovery(&cfg, log.NewNopLogger())
+	testutil.Ok(t, err)
+
+	targetGroups, err := d.refresh(context.Background())
+
```
Comment (roidelapluie) [inline discovery/hetzner/robot_test.go:97]: That line can go away

**Comment by roidelapluie** [comment]
Thanks! I will merge on green tests.

**Review by roidelapluie — APPROVED** [review]
