### PR TITLE
Scrape: do not put staleness marker when cache is reused

### LINKED ISSUE #6997: Fatal error after reload when configuration got changed (increasing sample_limit)
**What did you do?**
A configuration has been changed:
`sample_limit` from `100000` to `130000`
then the new configuration has been deployed to kubernetes.

**What did you expect to see?**
A configuration reload as usual.

**What did you see instead? Under which circumstances?**
Prometheus got restarted with a bunch of errors within logs.

**Environment**

* System information:
```
 Kernel Version:                  5.3.0-24-generic
 OS Image:                        Ubuntu 18.04.1 LTS
 Operating System:                linux
 Architecture:                    amd64
 Kubelet Version:                 v1.14.8
```

* Prometheus version:
2.16.0

* Logs:
```
fatal error: concurrent map read and map write

goroutine 7926 [running]:
runtime.throw(0x25d4f3b, 0x21)
	/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.12.16/share/go/src/runtime/panic.go:617 +0x72 fp=0xc0248e16c0 sp=0xc0248e1690 pc=0x42f552
runtime.mapaccess2_fast64(0x217f780, 0xc21aaea3c0, 0x329a094c9e427070, 0x45dea01, 0xc256bc5d00)
	/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.12.16/share/go/src/runtime/map_fast64.go:61 +0x1c2 fp=0xc0248e16e8 sp=0xc0248e16c0 pc=0x412ed2
github.com/prometheus/prometheus/scrape.(*scrapeCache).forEachStale(0xc21aaf0100, 0xc0248e1a10)
	/build/go/src/github.com/prometheus/prometheus/scrape/scrape.go:766 +0xdf fp=0xc0248e1798 sp=0xc0248e16e8 pc=0x1d7fbff
github.com/prometheus/prometheus/scrape.(*scrapeLoop).append(0xc0f1760240, 0x45dd750, 0x0, 0x0, 0x0, 0x0, 0xbf94458d1f2e81b8, 0x6181c1af2c1ca, 0x45bf9e0, 0x0, ...)
	/build/go/src/github.com/prometheus/prometheus/scrape/scrape.go:1219 +0xce5 fp=0xc0248e1a48 sp=0xc0248e1798 pc=0x1d83825
github.com/prometheus/prometheus/scrape.(*scrapeLoop).endOfRunStaleness(0xc0f1760240, 0xbf9445895f2e5033, 0x618189ce0ba36, 0x45bf9e0, 0xc16d72bf90, 0x37e11d600)
	/build/go/src/github.com/prometheus/prometheus/scrape/scrape.go:1046 +0x36b fp=0xc0248e1c58 sp=0xc0248e1a48 pc=0x1d8260b
github.com/prometheus/prometheus/scrape.(*scrapeLoop).run(0xc0f1760240, 0x37e11d600, 0x2540be400, 0x0)
	/build/go/src/github.com/prometheus/prometheus/scrape/scrape.go:1003 +0x929 fp=0xc0248e1fc0 sp=0xc0248e1c58 pc=0x1d816d9
runtime.goexit()
	/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.12.16/share/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc0248e1fc8 sp=0xc0248e1fc0 pc=0x45e8f1
created by github.com/prometheus/prometheus/scrape.(*scrapePool).sync
	/build/go/src/github.com/prometheus/prometheus/scrape/scrape.go:425 +0x52c

goroutine 1 [chan receive, 28589 minutes]:
github.com/prometheus/prometheus/vendor/github.com/oklog/run.(*Group).Run(0xc0009b7c38, 0xc000212410, 0x8)
	/build/go/src/github.com/prometheus/prometheus/vendor/github.com/oklog/run/group.go:43 +0xf0
main.main()
	/build/go/src/github.com/prometheus/prometheus/cmd/prometheus/main.go:739 +0x6edd

goroutine 109 [IO wait, 28589 minutes]:
internal/poll.runtime_pollWait(0x7f46bd265de8, 0x72, 0xffffffffffffffff)
	/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.12.16/share/go/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc0005ae198, 0x72, 0x8000, 0x8000, 0xffffffffffffffff)
	/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.12.16/share/go/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
	/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.12.16/share/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0005ae180, 0xc0009be000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.12.16/share/go/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc0005ae180, 0xc0009be000, 0x8000, 0x8000, 0x45b3a0, 0xc000554300, 0x4)
	/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.12.16/share/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc000010028, 0xc0009be000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.12.16/share/go/src/net/net.go:177 +0x69
bufio.(*Reader).Read(0xc00015ea80, 0xc0004921f8, 0x9, 0x9, 0x4591a0, 0xc00073c6c0, 0xc0000705f8)
	/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.12.16/share/go/src/bufio/bufio.go:223 +0x23e
io.ReadAtLeast(0x2bed900, 0xc00015ea80, 0xc0004921f8, 0x9, 0x9, 0x9, 0x1000000022d6ce0, 0xc0004a00e0, 0xc0007400d0)
	/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.12.16/share/go/src/io/io.go:310 +0x88
io.ReadFull(...)
	/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.12.16/share/go/src/io/io.go:329
github.com/prometheus/prometheus/vendor/golang.org/x/net/http2.readFrameHeader(0xc0004921f8, 0x9, 0x9, 0x2bed900, 0xc00015ea80, 0x0, 0xc000000000, 0xc0007031c0, 0xc00066c910)
	/build/go/src/github.com/prometheus/prometheus/vendor/golang.org/x/net/http2/frame.go:237 +0x88
github.com/prometheus/prometheus/vendor/golang.org/x/net/http2.(*Framer).ReadFrame(0xc0004921c0, 0xc000542150, 0x1, 0x0, 0x0)
	/build/go/src/github.com/prometheus/prometheus/vendor/golang.org/x/net/http2/frame.go:492 +0xa1
github.com/prometheus/prometheus/vendor/google.golang.org/grpc/internal/transport.(*http2Client).reader(0xc000432540)
	/build/go/src/github.com/prometheus/prometheus/vendor/google.golang.org/grpc/internal/transport/http2_client.go:1242 +0x168
created by github.com/prometheus/prometheus/vendor/google.golang.org/grpc/internal/transport.newHTTP2Client
	/build/go/src/github.com/prometheus/prometheus/vendor/google.golang.org/grpc/internal/transport/http2_client.go:289 +0xd42

goroutine 6 [syscall, 28589 minutes]:
os/signal.signal_recv(0x0)
	/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.12.16/share/go/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
	/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.12.16/share/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.12.16/share/go/src/os/signal/signal_unix.go:29 +0x41
...
```

For more see the attached file, please.

### PR DESCRIPTION
**Pull request by roidelapluie**
Fixes #6997 

When we reuse a cache, it makes no sense to track staleness after the loop is closed.

Because at the time we track staleness, the cache is poisoned and it would attempt to create wrong staleness markers.

It also means that we might have concurrency on the maps used by the cache.

I need to think how to produce an effective test for this.

NOTE: This approach is better than adding mutexes all around the place IMO and also more semantically correct.

cc @beorn7 @brian-brazil 

Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

### CODE REVIEW

**Comment by roidelapluie** [comment]
(For those who subscribe by mails, I have updated the description of this PR.)

**Comment by roidelapluie** [comment]
Note than this bug was introduced #6670 in 2.16.0.

**Comment by roidelapluie** [comment]
The real difficulty here is that we can not use testScraper{} as its cache logic is not guaranteed (and is not the same) as the actual scraper.

We would the need to server metrics over http, serve them, etc.

So, really, all the ideas are welcome.

**Comment by roidelapluie** [comment]
I do have a test now:

```
$ go test -race -run TestReuseCacheRace
==================                                                   
WARNING: DATA RACE                                                                                                                         
Read at 0x00c000110828 by goroutine 73:                      
  github.com/prometheus/prometheus/scrape.(*scrapeCache).forEachStale()                                  
      /home/roidelapluie/go/src/github.com/prometheus/prometheus/release-2.17/scrape/scrape.go:761 +0x56
  github.com/prometheus/prometheus/scrape.(*scrapeLoop).append()
      /home/roidelapluie/go/src/github.com/prometheus/prometheus/release-2.17/scrape/scrape.go:1233 +0x12ad                                
  github.com/prometheus/prometheus/scrape.(*scrapeLoop).run()                                                                              
      /home/roidelapluie/go/src/github.com/prometheus/prometheus/release-2.17/scrape/scrape.go:966 +0xad6                            
                                                                                                                                           
Previous write at 0x00c000110828 by goroutine 38:               
  github.com/prometheus/prometheus/scrape.(*scrapeCache).iterDone()                                                                        
      /home/roidelapluie/go/src/github.com/prometheus/prometheus/release-2.17/scrape/scrape.go:719 +0x22e
  github.com/prometheus/prometheus/scrape.(*scrapeLoop).append.func1()                                    
      /home/roidelapluie/go/src/github.com/prometheus/prometheus/release-2.17/scrape/scrape.go:1082 +0xf6
  github.com/prometheus/prometheus/scrape.(*scrapeLoop).append()                                                                           
      /home/roidelapluie/go/src/github.com/prometheus/prometheus/release-2.17/scrape/scrape.go:1245 +0x11ee                                
  github.com/prometheus/prometheus/scrape.(*scrapeLoop).endOfRunStaleness()
      /home/roidelapluie/go/src/github.com/prometheus/prometheus/release-2.17/scrape/scrape.go:1042 +0x4e5
  github.com/prometheus/prometheus/scrape.(*scrapeLoop).run()                                                                              
      /home/roidelapluie/go/src/github.com/prometheus/prometheus/release-2.17/scrape/scrape.go:999 +0xef7                                  
                                                                     
Goroutine 73 (running) created at:                                                                                                         
  github.com/prometheus/prometheus/scrape.(*scrapePool).reload.func1()                                  
      /home/roidelapluie/go/src/github.com/prometheus/prometheus/release-2.17/scrape/scrape.go:340 +0x9d                                   
                                                                     
Goroutine 38 (finished) created at:
  github.com/prometheus/prometheus/scrape.(*scrapePool).reload.func1()
      /home/roidelapluie/go/src/github.com/prometheus/prometheus/release-2.17/scrape/scrape.go:340 +0x9d
==================
```

**Comment by roidelapluie** [comment]
If this looks good I propose we run a final RC tomorrow with this and #6998 and by Monday we cut the final release. @beorn7 @brian-brazil

File: scrape/scrape.go [hunk 1]
```diff
@@ -593,6 +594,7 @@ type loop interface {
 	run(interval, timeout time.Duration, errc chan<- error)
 	stop()
 	getCache() *scrapeCache
+	disableStalenessMarkers()
```
Comment (brian-brazil) [inline scrape/scrape.go]: This name is a misleading, as it's only the staleness markers after the scrape stops that it is affecting

Comment (roidelapluie) [reply scrape/scrape.go]: update ; it is longer but explicit

**Comment by brian-brazil** [comment]
:+1:

**Comment by beorn7** [comment]
:+1: to cutting a next (and hopefully final) RC with this. WRT the code changes here, I have full confidence in @brian-brazil 's :+1: .

**Comment by roidelapluie** [comment]
Yes, random crashes of prometheus after consecutive reloads are not good and we should not put a new release with this so this will be a RC with prombench over the weekend.

**Comment by chhetripradeep** [comment]
Curious if we can backport this to 2.16.0 and release 2.16.1 :)

**Comment by beorn7** [comment]
With 2.17.0 almost done, I'd say that's unlikely. Unless any reason turns up that makes it hard to upgrade to 2.17.0. Ultimately @cstyan's call as the 2.16 release shepherd.

**Comment by chhetripradeep** [comment]
The reason I asked is because with 2.17.0 increase, it's expected to have memory increase (with tsdb isolation work which will require us to do some testing before rolling out to production), Hence it will be good to have this bug fix in 2.16.0.

**Comment by beorn7** [comment]
There are also improvements in memory usage. The total effect might very well be a decrease in memory usage.

**Comment by cstyan** [comment]
With the work I have planned this week it's unlikely I'd do another 2.16 release unless there was a critical bug that needed to be fixed and 2.17 gets delayed for some reason.
