### PR TITLE
bugfix: Decouple native histogram ingestions and protobuf parsing

### LINKED ISSUE #13920: Feature Flag "Created Timestamps Zero Injection" requires enabled "Native Histograms"
### What did you do?

If you activate the feature flag `--enable-feature=created-timestamp-zero-ingestion` in Prometheus, you must also activate the feature flag `--enable-feature=native-histograms`, otherwise the following error message will appear when you scrape your own Prometheus metrics (`:9090/metrics`):

Bildschirmfoto 2024-04-11 um 10 57 39

I don't know if this is intentional, but otherwise it should be documented as a dependency in the documentation?

### What did you expect to see?

_No response_

### What did you see instead? Under which circumstances?

Error: `native histograms are disabled`

### System information

_No response_

### Prometheus version

```text
prometheus, version 2.51.2 (branch: HEAD, revision: b4c0ab52c3e9b940ab803581ddae9b3d9a452337)
  build user:       root@b63f02a423d9
  build date:       20240410-14:05:54
  go version:       go1.22.2
  platform:         linux/amd64
  tags:             netgo,builtinassets,stringlabels
```

### Prometheus configuration file

_No response_

### Alertmanager version

_No response_

### Alertmanager configuration file

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by ArthurSens**
Up until this point, if a scrape was done with the protobuf format Prometheus would always try to ingest native histograms even with the feature flag disabled. This causes problems with other feature-flags that depend on the protobuf format, like 'created-timestamp-zero-ingestion'. This commit decouples native histogram parsing from ingestion, making sure ingestion only happens when the 'native-histogram' feature-flag is enabled.

Fix #13920

### CODE REVIEW

**Comment by krajorama** [comment]
I've tested the fix locally, the error does disappear, now for the review.

File: scrape/manager.go [hunk 1]
```diff
@@ -81,6 +81,8 @@ type Options struct {
 	// Option to enable the ingestion of the created timestamp as a synthetic zero sample.
 	// See: https://github.com/prometheus/proposals/blob/main/proposals/2023-06-13_created-timestamp.md
 	EnableCreatedTimestampZeroIngestion bool
+	// Option to enable the ingestion of the native histograms.
```
Comment (krajorama) [inline scrape/manager.go:84]: nit:
```suggestion
	// Option to enable the ingestion of native histograms.
```

File: scrape/scrape.go [hunk 2]
```diff
@@ -826,8 +827,11 @@ type scrapeLoop struct {
 	labelLimits              *labelLimits
 	interval                 time.Duration
 	timeout                  time.Duration
-	scrapeClassicHistograms  bool
-	enableCTZeroIngestion    bool
+
+	// Feature flagged options.
+	scrapeClassicHistograms        bool
```
Comment (krajorama) [inline scrape/scrape.go:832]: Actually `scrapeClassicHistograms` comes from scrape config, so should be kept in place.

**Review by krajorama — COMMENTED** [review]
Looks good, two nit comments

**Comment by ArthurSens** [comment]
Thanks, fixed the two comments :)

I wonder if the base branch should be `release-2.52` instead of `main` 🤔

**Comment by krajorama** [comment]
> Thanks, fixed the two comments :)
> 
> I wonder if the base branch should be `release-2.52` instead of `main` 🤔

The bug concerns experimental features and has a workaround, so I'm personally ok with either. On the other hand 2.53 is pretty far away so it makes sense to do it on 2.52

**Review by krajorama — APPROVED** [review]
LGTM

**Comment by ArthurSens** [comment]
> > Thanks, fixed the two comments :)
> > I wonder if the base branch should be `release-2.52` instead of `main` 🤔
> 
> The bug concerns experimental features and has a workaround, so I'm personally ok with either. On the other hand 2.53 is pretty far away so it makes sense to do it on 2.52

I'll leave it for 2.53 because the release process started a few days ago already 😬
