### PR TITLE
Fixes service-discovery view when accessed from unhealthy targets

### LINKED ISSUE #5677: When you pick "unhealthy" in targets the service discovery page is empty
## Proposal
**Use case. Why is this important?**

we want to see SD even when on the other page we pick unhealty

## Bug Report
**What did you do?**

Pick unhealthy in targets
Go to service discovery page

**What did you expect to see?**

The service discovery details

**What did you see instead? Under which circumstances?**

Empty page

**Environment**

* Prometheus version:

2.9.2

### PR DESCRIPTION
**Pull request by Harkishen-Singh**
This PR fixes #5677 

**Explanation**
To retain the previous screen (reported by #4599 ), PR [link](https://github.com/prometheus/prometheus/pull/5201) was merged. However, this did not add any check for the current `url` and hence assigned `display: none` to the `table-container` which should only be done in the `targets` screen and not in the `service-discovery` screen. 

This PR fixes the issue by adding the URL check to find out in which screen the current view-port is and based on that access the `localStorage`.

**Before fixing the bug [gif]**
before

**After fixing the bug [gif]**
after

Signed-off-by: Harkishen Singh harkishensingh@hotmail.com

### CODE REVIEW

**Comment by Harkishen-Singh** [comment]
please review @juliusv @simonpasquier @brian-brazil

File: web/ui/static/js/targets.js [hunk 1]
```diff
@@ -21,12 +21,16 @@ function showUnhealthy(_, container) {
 }
 
 function init() {
-  if (!localStorage.selectedTab || localStorage.selectedTab == "all-targets"){
-    $("#all-targets").parent().addClass("active");
+  if (document.URL.includes('targets')) {
```
Comment (simonpasquier) [inline web/ui/static/js/targets.js]: Rather that checking the URL, it should be possible to check `$("#unhealthy-targets").length`: if > 0 then apply `localStorage.selectedTab` preferences otherwise show everything. What do you think?

Comment (Harkishen-Singh) [reply web/ui/static/js/targets.js]: sure. that would work in a better way too. Thanks for the suggestion. Implementing..

**Comment by Harkishen-Singh** [comment]
@simonpasquier done! please have a look

**Comment by Harkishen-Singh** [comment]
@simonpasquier  Done!

**Comment by simonpasquier** [comment]
Thanks! It could be merged on green CI.
