### PR TITLE
Fixes #4090. Marathon service discovery for 5XX http response

### LINKED ISSUE #4090: Marathon service discovery successful for 500 response with valid JSON in response body
## Problem statement
We run multiple Prometheus clusters at large scale with Marathon service discovery. At times, marathon responds with 500 error but a valid JSON response is returned. Marathon service discovery does not check for HTTP status code and continues to process. This results in a job without targets and services are not monitored until the next API call.

**Use case. Why is this important?**
We miss metrics intermittently.

## Solution
Treat non-2xx HTTP response as error. It will preserve the existing targets.

## Bug Report

**What did you do?**
It's happening on our production systems intermittently. Was able to reproduce the same with simulated marathon responses in staging.

**What did you expect to see?**
No target loss. No missing metrics.

**What did you see instead? Under which circumstances?**
Sudden metric drop for all containers at once triggering alerts.

* Prometheus version:
Prometheus 2.2.1

* Alertmanager version:
version 0.11.0

* Prometheus configuration file:
A standard config with `marathon_sd_config`

* Logs:
All ok in logs.

### PR DESCRIPTION
**Pull request by rohit01**
Test execution without fix:

```bash
$ go test -v
=== RUN   TestMarathonSDHandleError
--- PASS: TestMarathonSDHandleError (0.00s)
=== RUN   TestMarathonSDEmptyList
--- PASS: TestMarathonSDEmptyList (0.00s)
=== RUN   TestMarathonSDSendGroup
--- PASS: TestMarathonSDSendGroup (0.00s)
=== RUN   TestMarathonSDRemoveApp
--- PASS: TestMarathonSDRemoveApp (0.00s)
=== RUN   TestMarathonSDRunAndStop
--- PASS: TestMarathonSDRunAndStop (0.01s)
=== RUN   TestMarathonSDSendGroupWithMutiplePort
--- PASS: TestMarathonSDSendGroupWithMutiplePort (0.00s)
=== RUN   TestMarathonZeroTaskPorts
--- PASS: TestMarathonZeroTaskPorts (0.00s)
=== RUN   Test500ErrorHttpResponseWithValidJSONBody
--- FAIL: Test500ErrorHttpResponseWithValidJSONBody (0.00s)
    marathon_test.go:356: Expected error for 5xx HTTP response from marathon server
=== RUN   TestMarathonSDSendGroupWithoutPortMappings
--- PASS: TestMarathonSDSendGroupWithoutPortMappings (0.00s)
=== RUN   TestMarathonSDSendGroupWithoutPortDefinitions
--- PASS: TestMarathonSDSendGroupWithoutPortDefinitions (0.00s)
=== RUN   TestMarathonSDSendGroupWithContainerPortMappings
--- PASS: TestMarathonSDSendGroupWithContainerPortMappings (0.00s)
FAIL
exit status 1
FAIL    github.com/prometheus/prometheus/discovery/marathon    0.026s
```

Test execution with fix:

```bash
$ go test -v
=== RUN   TestMarathonSDHandleError
--- PASS: TestMarathonSDHandleError (0.00s)
=== RUN   TestMarathonSDEmptyList
--- PASS: TestMarathonSDEmptyList (0.00s)
=== RUN   TestMarathonSDSendGroup
--- PASS: TestMarathonSDSendGroup (0.00s)
=== RUN   TestMarathonSDRemoveApp
--- PASS: TestMarathonSDRemoveApp (0.00s)
=== RUN   TestMarathonSDRunAndStop
--- PASS: TestMarathonSDRunAndStop (0.01s)
=== RUN   TestMarathonSDSendGroupWithMutiplePort
--- PASS: TestMarathonSDSendGroupWithMutiplePort (0.00s)
=== RUN   TestMarathonZeroTaskPorts
--- PASS: TestMarathonZeroTaskPorts (0.00s)
=== RUN   Test500ErrorHttpResponseWithValidJSONBody
--- PASS: Test500ErrorHttpResponseWithValidJSONBody (0.00s)
=== RUN   TestMarathonSDSendGroupWithoutPortMappings
--- PASS: TestMarathonSDSendGroupWithoutPortMappings (0.00s)
=== RUN   TestMarathonSDSendGroupWithoutPortDefinitions
--- PASS: TestMarathonSDSendGroupWithoutPortDefinitions (0.00s)
=== RUN   TestMarathonSDSendGroupWithContainerPortMappings
--- PASS: TestMarathonSDSendGroupWithContainerPortMappings (0.00s)
PASS
ok      github.com/prometheus/prometheus/discovery/marathon    0.024s
```

### CODE REVIEW

File: discovery/marathon/marathon_test.go [hunk 1]
```diff
@@ -326,6 +328,32 @@ func TestMarathonZeroTaskPorts(t *testing.T) {
...
+		ch     = make(chan []*targetgroup.Group, 1)
+		client = fetchApps
+	)
+	// Simulate 500 error with valid JSON response
+	respHandler := func(w http.ResponseWriter, r *http.Request) {
+		w.WriteHeader(http.StatusInternalServerError)
+		w.Header().Set("Content-Type", "application/json")
+		io.WriteString(w, `{}`)
+	}
+	// create test server with handler
```
Comment (brian-brazil) [inline discovery/marathon/marathon_test.go]: Comments should be full sentences, starting with a capital letter and ending with a full stop.

Comment (rohit01) [reply discovery/marathon/marathon_test.go]: Done. Please check.

**Comment by brian-brazil** [comment]
Thanks!
