### PR TITLE
retrieval/discovery/kubernetes: fix cache state unknown behavior

### LINKED ISSUE #2178: Prometheus panic: &runtime.TypeAssertionError
**What did you do?**
Running Prometheus inside Kubernetes. When I scale down number of replicas for a deployment, Prometheus panic.

**What did you expect to see?**
Not panic

**What did you see instead? Under which circumstances?**
When I scale 350 replicas to 0, Prometheus crashed.

**Environment**

* System information:

        CentOS Linux release 7.2.1511 (Core)
	Linux 3.10.0-327.4.4.el7.x86_64 x86_64

* Prometheus version: 

       Docker image: prom/prometheus:v1.3.1

* Docker version:

       Server:
        Version:      1.11.2
        API version:  1.23
        Go version:   go1.5.4
        Git commit:   b9f10c9
        Built:        Wed Jun  1 21:23:11 2016
        OS/Arch:      linux/amd64

* Kubelet version:

       Kubernetes v1.4.1

* Prometheus configuration file:
```
global:
  scrape_interval: 600s

scrape_configs:
  - job_name: 'cadvisor-exporter'
    scrape_interval: 60s
    scheme: 'http'
    kubernetes_sd_configs:
    - role: node
      api_server: https://API_SERVER
      tls_config:
        ca_file: CA_CRT_PATH
    relabel_configs:
      - source_labels: [__meta_kubernetes_node_address_InternalIP]
        regex: (.*)
        replacement: ${1}:4194
        action: replace
        target_label: __address__
      - source_labels: [instance]
        regex: (.*)\.(.*)\.(.*)
        replacement: ${1}
        action: replace
        target_label: hostname
  - job_name: 'node-exporter'
    scrape_interval: 60s
    scheme: 'http'
    kubernetes_sd_configs:
    - role: node
      api_server: https://API_SERVER
      tls_config:
        ca_file: CA_CRT_PATH
    relabel_configs:
      - source_labels: [__meta_kubernetes_node_address_InternalIP]
        regex: (.*)
        replacement: ${1}:9100
        action: replace
        target_label: __address__
      - source_labels: [instance]
        regex: (.*)\.(.*)\.(.*)
        replacement: ${1}
        action: replace
        target_label: hostname
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
  - job_name: 'prod-pod-exporter'
    scrape_interval: 60s
    scheme: 'http'
    kubernetes_sd_configs:
    - role: pod
      api_server: https://API_SERVER
      tls_config:
        ca_file: CA_CRT_PATH
    tls_config:
      ca_file: CA_CRT_PATH
      server_name: '*.k8s.local'
    relabel_configs:
    - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
      action: replace
      target_label: __metrics_path__
      regex: (.+)
    - source_labels: [__meta_kubernetes_pod_label_prometheus_io_scrape]
      action: keep
      regex: true
    - source_labels: [__meta_kubernetes_pod_container_port_name]
      action: keep
      regex: prometheus-port
    - source_labels: [__address__, __meta_kubernetes_pod_container_port_map_prometheus_port]
      action: replace
      regex: (.+):(?:\d+);(\d+)
      replacement: ${1}:${2}
      target_label: __address__
    - action: labelmap
      regex: __meta_kubernetes_pod_label_(.+)
    - source_labels: [__meta_kubernetes_pod_namespace]
      action: replace
      target_label: kubernetes_namespace
    - source_labels: [__meta_kubernetes_pod_name]
      action: replace
      target_label: kubernetes_pod_name
```

* Logs:
```
E1109 20:02:54.793285       1 runtime.go:64] Observed a panic: &runtime.TypeAssertionError{interfaceString:"interface {}", concreteString:"cache.DeletedFinalStateUnknown", assertedString:"*v1.Pod", missingMethod:""} (interface conversion: interface {} is cache.DeletedFinalStateUnknown, not *v1.Pod)
/go/src/github.com/prometheus/prometheus/vendor/k8s.io/client-go/1.5/pkg/util/runtime/runtime.go:70
/go/src/github.com/prometheus/prometheus/vendor/k8s.io/client-go/1.5/pkg/util/runtime/runtime.go:63
/go/src/github.com/prometheus/prometheus/vendor/k8s.io/client-go/1.5/pkg/util/runtime/runtime.go:49
/usr/local/go/src/runtime/asm_amd64.s:479
/usr/local/go/src/runtime/panic.go:458
/usr/local/go/src/runtime/iface.go:201
/go/src/github.com/prometheus/prometheus/retrieval/discovery/kubernetes/pod.go:77
/go/src/github.com/prometheus/prometheus/vendor/k8s.io/client-go/1.5/tools/cache/controller.go:182
<autogenerated>:52
/go/src/github.com/prometheus/prometheus/vendor/k8s.io/client-go/1.5/tools/cache/shared_informer.go:408
/usr/local/go/src/runtime/asm_amd64.s:2086
panic: interface conversion: interface {} is cache.DeletedFinalStateUnknown, not *v1.Pod [recovered]
panic: interface conversion: interface {} is cache.DeletedFinalStateUnknown, not *v1.Pod

goroutine 419 [running]:
  panic(0x17a4060, 0xc514b803c0)
/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/prometheus/prometheus/vendor/k8s.io/client-go/1.5/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
/go/src/github.com/prometheus/prometheus/vendor/k8s.io/client-go/1.5/pkg/util/runtime/runtime.go:56 +0x126
panic(0x17a4060, 0xc514b803c0)
/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/prometheus/prometheus/retrieval/discovery/kubernetes.(*Pod).Run.func3(0x1816540, 0xc502773820)
/go/src/github.com/prometheus/prometheus/retrieval/discovery/kubernetes/pod.go:77 +0x166
github.com/prometheus/prometheus/vendor/k8s.io/client-go/1.5/tools/cache.ResourceEventHandlerFuncs.OnDelete(0xc4d5821240, 0xc4d5821280, 0xc5266dcf40, 0x1816540, 0xc502773820)
/go/src/github.com/prometheus/prometheus/vendor/k8s.io/client-go/1.5/tools/cache/controller.go:182 +0x49
github.com/prometheus/prometheus/vendor/k8s.io/client-go/1.5/tools/cache.(*ResourceEventHandlerFuncs).OnDelete(0xc4d58212a0, 0x1816540, 0xc502773820)
<autogenerated>:52 +0x78
github.com/prometheus/prometheus/vendor/k8s.io/client-go/1.5/tools/cache.(*processorListener).run(0xc4cbe56e80, 0xc49c814ba0)
/go/src/github.com/prometheus/prometheus/vendor/k8s.io/client-go/1.5/tools/cache/shared_informer.go:408 +0x356
created by github.com/prometheus/prometheus/vendor/k8s.io/client-go/1.5/tools/cache.(*sharedIndexInformer).AddEventHandler
/go/src/github.com/prometheus/prometheus/vendor/k8s.io/client-go/1.5/tools/cache/shared_informer.go:257 +0x24b
```

### PR DESCRIPTION
**Pull request by brancz**
The `OnDelete` handler can under certain circumstances [return a `DeletedFinalStateUnknown`](https://github.com/kubernetes/client-go/blob/843f7c4f28b1f647f664f883697107d5c02c5acc/1.5/tools/cache/controller.go#L146-L149) object. In that case we have a stale cache, but will only return to a correct cache once the refresh period has passed, so we keep our cache and use it on a best effort basis until then, without `panic`ing here.

@fabxc @brian-brazil 

Fixes #2178

### CODE REVIEW

File: retrieval/discovery/kubernetes/pod.go [hunk 1]
```diff
@@ -74,7 +74,10 @@ func (p *Pod) Run(ctx context.Context, ch chan<- []*config.TargetGroup) {
 			send(p.buildPod(o.(*apiv1.Pod)))
 		},
 		DeleteFunc: func(o interface{}) {
-			send(&config.TargetGroup{Source: podSource(o.(*apiv1.Pod))})
+			pod, ok := o.(*apiv1.Pod)
```
Comment (jimmidyson) [inline retrieval/discovery/kubernetes/pod.go]: We only need the namespace & name which is available in the (albeit stale) `DeletedFinalStateUnknown.Obj` field?

Comment (brancz) [inline retrieval/discovery/kubernetes/pod.go]: Yep, [sounds like](https://github.com/kubernetes/client-go/blob/843f7c4f28b1f647f664f883697107d5c02c5acc/1.5/tools/cache/delta_fifo.go#L631-L634) the type cast should be safe on the inner Obj. Will update.

File: retrieval/discovery/kubernetes/endpoints.go [hunk 2]
```diff
@@ -89,6 +89,11 @@ func (e *Endpoints) Run(ctx context.Context, ch chan<- []*config.TargetGroup) {
 			send(e.buildEndpoints(o.(*apiv1.Endpoints)))
 		},
 		DeleteFunc: func(o interface{}) {
+			s, ok := o.(*cache.DeletedFinalStateUnknown)
+			if ok {
+				o = s.Obj
+			}
+
 			send(&config.TargetGroup{Source: endpointsSource(o.(*apiv1.Endpoints).ObjectMeta)})
```
Comment (jimmidyson) [inline retrieval/discovery/kubernetes/endpoints.go]: Is it worth adding a type assertion test to make sure there's no chance of a panic here?

Comment (fabxc) [inline retrieval/discovery/kubernetes/endpoints.go]: Yea, I think we should stick with proper validation everywhere to avoid future panics. The underlying code is not easy enough to reason about to rely on contract here as the issue has shown.

https://github.com/kubernetes/kubernetes/pull/34694/files

Comment (fabxc) [inline retrieval/discovery/kubernetes/endpoints.go]: I generally agree that panicking on contract violation is fine. But this is a third party dependency that's too large and too quickly changing that we can realistically validate changes and correctness on every vendoring update.

And we cannot really risk crashing our users servers just because a dependency of the SD integration is not working as we expect.

Comment (brancz) [inline retrieval/discovery/kubernetes/endpoints.go]: Updated.

**Comment by fabxc** [comment]
Can we embed the check in the `send()` functions?
Shouldn't work without modifications for the non-delete case as well and make those a bit safer too.

**Comment by brancz** [comment]
sgtm, also makes it a bit more readable

**Comment by brancz** [comment]
Actually we can't, as the send function expects a `TargetGroup`, and as the `DeleteFunc` needs to build an empty `TargetGroup`, we can't build the `TargetGroup` in the send functions. What I'll do is have a cast/convert function that does this before building the actual `TargetGroup`.

**Comment by brancz** [comment]
Extracted the conversion/casting and added some test to cover the reported bug in terms of possible regressions. Re-review would be appreciated @fabxc @jimmidyson

**Comment by fabxc** [comment]
👍

File: retrieval/discovery/kubernetes/endpoints.go [hunk 3]
```diff
@@ -83,23 +83,50 @@ func (e *Endpoints) Run(ctx context.Context, ch chan<- []*config.TargetGroup) {
...
+			return
+		}
+
 		ep := &apiv1.Endpoints{}
 		ep.Namespace = svc.Namespace
 		ep.Name = svc.Name
 		obj, exists, err := e.endpointsStore.Get(ep)
 		if exists && err != nil {
-			send(e.buildEndpoints(obj.(*apiv1.Endpoints)))
+			eps, err := convertToEndpoints(obj)
```
Comment (brancz) [inline retrieval/discovery/kubernetes/endpoints.go]: Removed this as discussed offline with @fabxc , because we are relying in many places that at least the store stores consistently typed objects.
