### PR TITLE
annotations: add warning for ineffective sort in range queries

### LINKED ISSUE #14115: Emit a warning when `sort` is used for range queries
### Proposal

Using `sort` with range queries will not work: the series in a range query result will always be sorted by the series labels.

This may be confusing for users. It would be nice to emit a warning annotation when `sort` is used for a range query to explain what is happening.

(acknowledgement: this is @bboreham's idea from https://github.com/prometheus/prometheus/pull/14083#issuecomment-2112022774)

### PR DESCRIPTION
**Pull request by ldufr**
We add to revert https://github.com/prometheus/prometheus/pull/16628, because it failed the CI after merging (the CI on the PR were quite old at the time of the merge), so we @krajorama and I wanted to fix that up to get the feature back in the main branch.

In addition, the tests were moved to the ".test" files that didn't exist when the PR was initially created.

#### Which issue(s) does the PR fix:
Fixes https://github.com/prometheus/prometheus/issues/14115

#### Release notes for end users (**ALL** commits must be considered).
```release-notes
[FEATURE] Emit a warning when `sort`, `sort_by_label` or `sort_by_label_desc` is used within range (matrix) queries, as these functions do not have effect in that context.
```

### CODE REVIEW

File: promql/engine.go [hunk 1]
```diff
@@ -2010,6 +2010,11 @@ func (ev *evaluator) eval(ctx context.Context, expr parser.Expr) (parser.Value,
 			return ev.evalInfo(ctx, e.Args)
 		}
 
+		// Emit a warning when sort is used for range queries
```
Comment (krajorama) [inline promql/engine.go]:
```suggestion
		// Emit a warning when sort is used for range queries.
```

**Review by krajorama — APPROVED** [review]
lgtm
