### PR TITLE
Fix `kuma_sd` targetgroup reporting

### LINKED ISSUE #9155: `kuma_sd` does not report all targets
**What did you do?**

Use the new `kuma_sd` to discover scrape targets.

**What did you expect to see?**

5 targets.

**What did you see instead? Under which circumstances?**

Only 1 target, which changes when the discovery reports new targets.

It looks like they are just being overwritten, likely because of the "Source" of all the groups is `"kuma"`, which is used as a key for targets in the manager. 

We could solve this by namespacing group sources, i.e.: instead of `"kuma"`, `"kuma/{mesh}/{dataplane}" which is unique.

* Prometheus version: 2.29-rc.0

* Prometheus configuration file:
```
global:
  evaluation_interval: 1m
  scrape_interval: 10s
  scrape_timeout: 10s
scrape_configs:
  - honor_labels: true
    job_name: 'kuma-dataplanes'
    kuma_sd_configs:
      - server: "http://localhost:5676"
```

cc @roidelapluie 

I'll have a fix PR in shortly.

### PR DESCRIPTION
**Pull request by austince**
There are currently a few related issues this PR addresses:
* xDS targetgroups are currently all given the same source name, so each job can only have max 1 group
* xDS targetgroups are not tracked between polling, so it is impossible to remove a target
* The Kuma MADS API's `MonitoringAssignment` is mapped directly into a `targetgroup.Group`, but does not contain a unique identifier.

This PR bundles all discovered targets into a single `targetgroup.Group` by changing the `resourceParser` func to return a set of targets instead of groups.

I've built an image with these patches from `2.29-rc.0` and pushed it to `austince/prometheus:2.29-rc.0-fix2`. I've also tested both adding multiple targets in a single job and removing targets. Testing repo here: https://github.com/austince/kuma-sd-playground

Fixes #9155

### CODE REVIEW

**Comment by austince** [comment]
@roidelapluie, could you have a look at this? 🙏🏼 endless thank-yous 🙏🏼

**Comment by roidelapluie** [comment]
Can you rebase this against release-2.29?

**Comment by austince** [comment]
Wait, which should be the target branch?

**Comment by roidelapluie** [comment]
release-2.29, but I have changed back to main for my initial review :) please rebase and change the branch at the same time :)

**Comment by austince** [comment]
> release-2.29, but I have changed back to main for my initial review :) please rebase and change the branch at the same time :)

ah, okie :) rebase and change back to `main` incoming...

**Comment by roidelapluie** [comment]
Could we just group all the targets in one targetgroup?

**Comment by roidelapluie** [comment]
I have discussed with Austin ; it would be better to stop utils Labels in TargetGroup, putting all the labels in Targets, therefore having a single TargetGroup with a "kuma" Source. That would simplify the code a lot.

**Comment by austince** [comment]
> I have discussed with Austin ; it would be better to stop using Labels in TargetGroup, putting all the labels in Targets, therefore having a single TargetGroup with a "kuma" Source. That would simplify the code a lot.

Implemented and tested @roidelapluie  !

File: discovery/xds/kuma_test.go [hunk 1]
```diff
@@ -138,65 +138,49 @@ func TestKumaMadsV1ResourceParserValidResources(t *testing.T) {
...
-		},
-		Labels: model.LabelSet{
-			"__meta_kuma_mesh":               "metrics",
-			"__meta_kuma_service":            "prometheus",
-			"__meta_kuma_label_team":         "infra",
-			"__meta_kuma_label_kuma_io_zone": "us-east-1",
-		},
+	require.Len(t, targets, 3)
+
+	expectedTarget1 := model.LabelSet{
```
Comment (roidelapluie) [inline discovery/xds/kuma_test.go:145]: Can we make this a slice?

File: discovery/xds/xds.go [hunk 2]
```diff
@@ -154,23 +156,19 @@ func (d *fetchDiscovery) poll(ctx context.Context, ch chan<- []*targetgroup.Grou
...
 	}
 
-	for _, group := range parsedGroups {
-		group.Source = d.source
-	}
-
-	level.Debug(d.logger).Log("msg", "updated to version", "version", response.VersionInfo, "groups", len(parsedGroups))
+	level.Debug(d.logger).Log("msg", "updated to version", "version", response.VersionInfo, "targets", len(parsedTargets))
 
 	// Check the context before sending an update on the channel.
```
Comment (roidelapluie) [inline discovery/xds/xds.go:168]: This comment is technically incorrect, can you remove it? Go does not follow the order in which it is written.

File: discovery/xds/xds.go [hunk 3]
```diff
@@ -154,23 +156,19 @@ func (d *fetchDiscovery) poll(ctx context.Context, ch chan<- []*targetgroup.Grou
...
 		d.fetchFailuresCount.Inc()
 		return
 	}
 
-	for _, group := range parsedGroups {
-		group.Source = d.source
-	}
-
-	level.Debug(d.logger).Log("msg", "updated to version", "version", response.VersionInfo, "groups", len(parsedGroups))
+	level.Debug(d.logger).Log("msg", "updated to version", "version", response.VersionInfo, "targets", len(parsedTargets))
```
Comment (roidelapluie) [inline discovery/xds/xds.go:166]:
```suggestion
	level.Debug(d.logger).Log("msg", "Updated to version", "version", response.VersionInfo, "targets", len(parsedTargets))
```
