### PR TITLE
fix recording inconsistency due to duplicate labels

### LINKED ISSUE #5529: Random value in recording rule with multiple identical series result
## Bug Report
**What did you do?**
Not sure if proposal of bug report but when recording rule expression results to multiple series with different values and has the `labels` section specified which will cause the two series having exact same labels. This results to recorded serie which will have randomly value of one of those values because of random ordering.

Simple example:
```yaml
 groups:
     - name: "test"
       interval: "1s"
       rules:
         - record: test_metric
           expr: "0"
           labels:
               label: "value"
         - record: "test_metric"
           expr: "1"
         - record: "result"
           expr: "max(test_metric) by (label)"
           labels:
               label: "value"
```

Will result to:
image

I understand that it is users responsibility to make sure the resulting metrics won't be identical, but on the other hand I'd expect this to result as a failed rule evaluation or at least log something or increment metric about it?
This way user has no notice that the data he has recorded are invalid.

### PR DESCRIPTION
**Pull request by Harkishen-Singh**
Signed-off-by: Harkishen-Singh <harkishensingh@hotmail.com>

Refers #5529. It **warns** the user from inconsistent data which might occur if more than one labels in the same group are found.

### CODE REVIEW

**Comment by Harkishen-Singh** [comment]
@brian-brazil  please have a look

File: cmd/promtool/main.go [hunk 1]
```diff
@@ -303,9 +304,30 @@ func checkRules(filename string) (int, []error) {
 		numRules += len(rg.Rules)
 	}
 
+	duplicateLabels := checkDuplicateLabels(rgs.Groups)
+	if duplicateLabels != 0 {
+		fmt.Printf("%d duplicate label(s) found. Might cause inconsistency while recording expressions.\n", duplicateLabels)
```
Comment (brian-brazil) [inline cmd/promtool/main.go]: It'd be more useful to print the relevant labels. You should also check the metric name.

Comment (Harkishen-Singh) [reply cmd/promtool/main.go]: Sure. I will implement it in the following commit.

**Comment by Harkishen-Singh** [comment]
@brian-brazil  implemented the suggestions! please have a look.

File: cmd/promtool/main.go [hunk 2]
```diff
@@ -303,9 +304,74 @@ func checkRules(filename string) (int, []error) {
...
 }
 
+func checkDuplicates(r []rulefmt.RuleGroup) (int, int, []string, []string) {
+	duplicateLabels, duplicateMetrics := 0, 0
+	labelNames, metricName := []string{}, []string{}
+	for _, rule := range r {
+		var stackLabels []map[string]string
+		var stackMetrics []string
+		for _, props := range rule.Rules {
+			for _, labels := range stackLabels {
```
Comment (brian-brazil) [inline cmd/promtool/main.go]: A map would be more efficient, and easier to understant

File: cmd/promtool/main.go [hunk 3]
```diff
@@ -303,9 +304,74 @@ func checkRules(filename string) (int, []error) {
...
+						}
+					}
+					if !found {
+						labelNames = append(labelNames, labels["label"])
+					}
+				}
+			}
+			stackLabels = append(stackLabels, props.Labels)
+
+			for _, mname := range stackMetrics {
```
Comment (brian-brazil) [inline cmd/promtool/main.go]: You need to check the metric names and labels at the same time, not independently.

File: cmd/promtool/main.go (hunk 2 above)
Comment (Harkishen-Singh) [reply cmd/promtool/main.go]: sure

File: cmd/promtool/main.go (hunk 3 above)
Comment (Harkishen-Singh) [reply cmd/promtool/main.go]: sure

**Comment by Harkishen-Singh** [comment]
@brian-brazil  done! please have a look.

File: cmd/promtool/main.go [hunk 4]
```diff
@@ -303,9 +304,42 @@ func checkRules(filename string) (int, []error) {
...
+	var stack, stackDuplicates []duplicateRules
+
+	for _, rule := range r {
+		for _, props := range rule.Rules {
+			for _, inst := range stack {
+				if reflect.DeepEqual(inst, duplicateRules{metric: props.Record, label: props.Labels}) {
+					stackDuplicates = append(stackDuplicates, duplicateRules{metric: props.Record, label: props.Labels})
+				}
+			}
+			stack = append(stack, duplicateRules{metric: props.Record, label: props.Labels})
```
Comment (brian-brazil) [inline cmd/promtool/main.go]: Building this up is odd, I'd suggest using an index variable in the for.

Comment (Harkishen-Singh) [reply cmd/promtool/main.go]: sure

**Comment by Harkishen-Singh** [comment]
@brian-brazil, implemented index values in the necessary *for loops*. Please have a look.

File: cmd/promtool/main.go (hunk 4 above)
Comment (brian-brazil) [reply cmd/promtool/main.go]: More exactly, get rid of the stack - you don't need it. Nested iteration over the rules will do it.

Comment (Harkishen-Singh) [reply cmd/promtool/main.go]: @brian-brazil, stack array is used only to check whether the duplicate rule has been already scanned in the earlier iteration since we aim to print the duplicate rule only once in the warning. 

Please note that stack does not implement the stack concept. It is surely misleading and i will change in the following commit.

Suppose if I remove the `stack array` (which is used for maintaining a check) and do simple nesting, then we might print a duplicated rule twice in the output like in the case when the label value is repeated more than twice.

Please correct me if I am getting it wrong.

Comment (Harkishen-Singh) [reply cmd/promtool/main.go]: @brian-brazil , done! pleae have a look.

**Comment by Harkishen-Singh** [comment]
@brian-brazil , as suggested, I have removed the `stack array` and implemented the mechanism via nesting of rules! please review.

**Comment by brian-brazil** [comment]
Thanks!
