### PR TITLE
Increase block writer size for backfilling

### LINKED ISSUE #8476: promtool fail to creat block with out of bounds - maybe becaue the data is old
**What did you do?**
I run
```
$ promtool tsdb create-blocks-from openmetrics metrics.1.txt
block creation: process blocks: add sample: out of bounds
```
[metrics.1.txt](https://github.com/prometheus/prometheus/files/5967214/metrics.1.txt)

**What did you expect to see?**
promtool should have created the blocks from the metrics
**What did you see instead? Under which circumstances?**
```
block creation: process blocks: add sample: out of bounds
```
**Environment**
Prometheus over docker with centos as a host
* System information:

Linux 3.10.0-1062.12.1.el7.x86_64 x86_64

* Prometheus version:

prometheus, version 2.24.1 (branch: HEAD, revision: e4487274853c587717006eeda8804e597d120340)
  build user:       root@0b5231a0de0f
  build date:       20210120-00:09:36
  go version:       go1.15.6
  platform:         linux/amd64

* Prometheus configuration file:
```
global:
  scrape_interval: 20s # By default, scrape targets every 20 second.
  scrape_timeout: 15s # Timeout before trying to scape a target again

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'scylla-monitor'
rule_files:
  - /etc/prometheus/prometheus.rules.yml
    #
# Alerting specifies settings related to the Alertmanager.
alerting:
        #  alert_relabel_configs:
        #    [ - <relabel_config> ... ]
  alertmanagers:
  - static_configs:
    - targets:
        - 172.17.0.2:9093

scrape_configs:
- job_name: scylla
  honor_labels: false
  file_sd_configs:
    - files:
      - /etc/scylla.d/prometheus/scylla_servers.yml
  relabel_configs:
    - source_labels: [__address__]
      regex:  '([^:]+)'
      target_label: __address__
      replacement: '${1}:9180'

    - source_labels: [__address__]
      regex:  '(.*):.+'
      target_label: instance
      replacement: '${1}'
  metric_relabel_configs:
    - source_labels: [version]
      regex:  '(.+)'
      target_label: CPU
      replacement: 'cpu'
    - source_labels: [version]
      regex:  '(.+)'
      target_label: CQL
      replacement: 'cql'
    - source_labels: [version]
      regex:  '(.+)'
      target_label: OS
      replacement: 'os'
    - source_labels: [version]
      regex:  '(.+)'
      target_label: IO
      replacement: 'io'
    - source_labels: [version]
      regex:  '(.+)'
      target_label: Errors
      replacement: 'errors'
    - regex: 'help|exported_instance|type'
      action: labeldrop
    - source_labels: [version]
      regex: '([0-9]+\.[0-9]+)(\.?[0-9]*).*'
      replacement: '$1$2'
      target_label: svr

- job_name: node_exporter
  honor_labels: false
  scrape_interval: 1m # By default, scrape targets every 20 second.
  scrape_timeout: 20s # Timeout before trying to scape a target again
  file_sd_configs:
    - files:
      - /etc/scylla.d/prometheus/node_exporter_servers.yml
  relabel_configs:
    - source_labels: [__address__]
      regex:  '(.*):\d+'
      target_label: instance
      replacement: '${1}'
    - source_labels: [__address__]
      regex:  '([^:]+)'
      target_label: instance
      replacement: '${1}'
    - source_labels: [instance]
      regex:  '(.*)'
      target_label: __address__
      replacement: '${1}:9100'
- job_name: manager_agent
  honor_labels: false
  file_sd_configs:
    - files:
      - /etc/scylla.d/prometheus/scylla_servers.yml
  relabel_configs:
    - source_labels: [__address__]
      regex:  '(.*):\d+'
      target_label: instance
      replacement: '${1}'
    - source_labels: [__address__]
      regex:  '([^:]+)'
      target_label: instance
      replacement: '${1}'
    - source_labels: [instance]
      regex:  '(.*)'
      target_label: __address__
      replacement: '${1}:56090'

- job_name: manager_agent1
  honor_labels: false
  file_sd_configs:
    - files:
      - /etc/scylla.d/prometheus/scylla_servers.yml
  relabel_configs:
    - source_labels: [__address__]
      regex:  '(.*):\d+'
      target_label: instance
      replacement: '${1}'
    - source_labels: [__address__]
      regex:  '([^:]+)'
      target_label: instance
      replacement: '${1}'
    - source_labels: [instance]
      regex:  '(.*)'
      target_label: __address__
      replacement: '${1}:5090'

- job_name: scylla_manager
  honor_labels: false
  file_sd_configs:
    - files:
      - /etc/scylla.d/prometheus/scylla_manager_servers.yml
  metric_relabel_configs:
    - source_labels: [host]
      target_label: instance

- job_name: 'prometheus'
  # Override the global default and scrape targets from this job every 5 seconds.
  scrape_interval: 5s
  static_configs:
    - targets:
      - localhost:9090
```

### PR DESCRIPTION
**Pull request by codesome**
Fixes #8476

### CODE REVIEW

**Comment by roidelapluie** [comment]
Can you please rebase this to release-2.25? Thanks!

**Comment by codesome** [comment]
@roidelapluie done

File: cmd/promtool/backfill.go [hunk 1]
```diff
@@ -93,7 +93,10 @@ func createBlocks(input []byte, mint, maxt int64, maxSamplesInAppender int, outp
 		nextSampleTs = math.MaxInt64
 
 		err := func() error {
-			w, err := tsdb.NewBlockWriter(log.NewNopLogger(), outputDir, blockDuration)
+			// 2*blockDuration block size keep the appendable window to blockDuration
+			// irrespective of which timestamp is added within the blockDuration range.
+			// The final block will be at max blockDuration since it depends on the samples.
```
Comment (beorn7) [inline cmd/promtool/backfill.go:98]: That doesn't quite parse. Perhaps insert a "to" between "size" and "keep"?

Since this is a bit hard to understand in general, it might also be better to explain more. Suggestion:

"To prevent races with compaction, a block writer only allows appending samples that are at most half a block size older than the most recent sample appended so far. However, in the way we use the block writer here, compaction doesn't happen, while we also need to append samples throughout the whole block range. To allow that, we  pretend that the block is twice as large here, but only really add sample in the original interval later."

**Review by beorn7 — APPROVED** [review]
Good catch. I'm surprised this hasn't hit us earlier.

I suggested a more verbose explanation so that less TSDB-savy people can still understand what's going on.

**Review by roidelapluie — APPROVED** [review]
