### PR TITLE
Consolidate offset modifier parsing

### LINKED ISSUE #1338: Range vector incorrectly accepts embedded offset modifier
Hi,

rate(mysql_global_status_questions{alias="$host"} offset 1d[$interval])

is allowed and it returns data without any offset. 

rate(mysql_global_status_questions{alias="$host"}[$interval] offset 1d)

is correct syntax which returns proper data

Is there any reason 1st variant does not return and error ?

### PR DESCRIPTION
**Pull request by grobie**
Remove duplicated offset modifier parsing and ensure offset can only
appear at the end of a selector statement.

Fixes #1338.

@fabxc @PeterZaitsev

### CODE REVIEW

File: promql/parse.go [hunk 1]
```diff
@@ -927,10 +930,28 @@ func (p *parser) metric() model.Metric {
...
+	return offset
+}
+
+// vectorSelector parses a new vector selector.
+//
+//		<metric_identifier> [<label_matchers>]
+//		[<metric_identifier>] <label_matchers>
 //
 func (p *parser) vectorSelector(name string) *VectorSelector {
 	const ctx = "metric selector"
```
Comment (grobie) [inline promql/parse.go]: @fabxc should this be `vector selector` as well?

File: promql/parse.go [hunk 2]
```diff
@@ -609,7 +624,7 @@ func (p *parser) rangeSelector(vs *VectorSelector) *MatrixSelector {
 	const ctx = "matrix selector"
```
Comment (grobie) [inline promql/parse.go]: @fabxc @juliusv In the documentation we call that actually a `range selector`. Or am I missing something?

File: promql/parse.go (hunk 1 above)
Comment (fabxc) [inline promql/parse.go]: Yes, let's go with what the docs say then.

**Comment by fabxc** [comment]
:+1: Thanks
