### PR TITLE
Close resources after failing to startup TSDB

### LINKED ISSUE #8028: Close opened resources on TSDB startup error
When there is an error on startup of TSDB, we don't close the open resources (files, especially m-mapped files). When TSDB is used externally, the resources stay open and can cause mmap explosion (see [cortex#3282](https://github.com/cortexproject/cortex/issues/3282)).

We should be gracefully closing the Head and open blocks on startup errors.

For anyone looking to tackle this: the fix would go in [this method](https://github.com/prometheus/prometheus/blob/da3ea43242a0a6796c08e7fc55adbdac1a83522d/tsdb/db.go#L556).

### PR DESCRIPTION
**Pull request by ArthurSens**
Fixes #8028

### CODE REVIEW

**Comment by roidelapluie** [comment]
Maybe have a look at multierr ?

**Comment by ArthurSens** [comment]
Yeah, I was thinking about multierr, but I was not going to return it anywhere, so I decided so just log the errors. WDYT?

File: tsdb/db.go [hunk 1]
```diff
@@ -638,6 +638,21 @@ func open(dir string, l log.Logger, r prometheus.Registerer, opts *Options, rngs
 		return nil, err
 	}
 
+	defer func() {
+		// Close files if startup fails somewhere
+		if err != nil {
+			if err = db.head.Close(); err != nil {
```
Comment (roidelapluie) [inline tsdb/db.go:644]: You should NOT override err

Comment (ArthurSens) [reply tsdb/db.go:644]: Oh thanks for pointing that out! :open_mouth:

Comment (roidelapluie) [reply tsdb/db.go:644]: It is because this function is using named returns

File: tsdb/db.go [hunk 2]
```diff
@@ -638,6 +638,21 @@ func open(dir string, l log.Logger, r prometheus.Registerer, opts *Options, rngs
 		return nil, err
 	}
 
+	defer func() {
+		// Close files if startup fails somewhere
+		if err != nil {
+			if er := db.head.Close(); er != nil {
```
Comment (roidelapluie) [inline tsdb/db.go:644]: you should check for nil head.

Comment (ArthurSens) [reply tsdb/db.go:644]: We have this right above the deferred function
```
db.head, err = NewHead(r, l, wlog, rngs[0], dir, db.chunkPool, opts.StripeSize, opts.SeriesLifecycleCallback)
if err != nil {
	return nil, err
}
```

Can `NewHead` return a nil head? I assumed that this behavior would only occur with err != nil, in that case, we don't need to check for a nil head

But again, I'm a beginner here, please correct me if I'm wrong

Comment (roidelapluie) [reply tsdb/db.go:644]: you are right.

I think we need to change NewHead too, to close the head in a defer if it is returning an error.

Comment (ArthurSens) [reply tsdb/db.go:644]: I've just taken a look at the NewHead function and I think there is no need.

The only resources opened are [chunk disks](https://github.com/prometheus/prometheus/blob/a7429890475045b1304cd690464b859af1ae1ce0/tsdb/head.go#L333-L336), which are closed by [db.head.Close()](https://github.com/prometheus/prometheus/blob/a7429890475045b1304cd690464b859af1ae1ce0/tsdb/head.go#L1441).

Comment (roidelapluie) [reply tsdb/db.go:644]: If NewHead errors you do not call that

Comment (roidelapluie) [reply tsdb/db.go:644]: don't we need to close the wal?

Comment (ArthurSens) [reply tsdb/db.go]: you're right with both comments! I've misplaced the deferred function

should be right now

File: tsdb/db.go [hunk 3]
```diff
@@ -621,6 +621,30 @@ func open(dir string, l log.Logger, r prometheus.Registerer, opts *Options, rngs
 
 	var wlog *wal.WAL
 	segmentSize := wal.DefaultSegmentSize
+
+	defer func() {
+		// Close files if startup fails somewhere
+		if err != nil {
```
Comment (roidelapluie) [inline tsdb/db.go:627]:
```suggestion
		if err == nil {
		  return
		}
```

File: tsdb/db.go [hunk 4]
```diff
@@ -621,6 +621,30 @@ func open(dir string, l log.Logger, r prometheus.Registerer, opts *Options, rngs
...
+			if wlog != nil {
+				if er := wlog.Close(); er != nil {
```
Comment (roidelapluie) [inline tsdb/db.go:629]:
```suggestion
				if wlog != nil && er := wlog.Close(); er != nil {
```

Comment (ArthurSens) [reply tsdb/db.go:629]: This does not compile, it would compile if I did this:
```
if er := wlog.Close(); wlog != nil && er != nil {
```
But then I could try to close a nil wal

Comment (roidelapluie) [reply tsdb/db.go:629]: oh sorry :) then 2 lines are fine I guess

File: tsdb/db.go (hunk 3 above)
Comment (ArthurSens) [reply tsdb/db.go:627]: I committed this change but didn't understand what are the benefits. Do you mind explaining :slightly_smiling_face:?

Comment (roidelapluie) [reply tsdb/db.go]: losing an indentation level tends to make the code easier to read/understand

**Comment by roidelapluie** [comment]
I am wondering wheter it would work to just call db.Close (and maybe add nil checks here ) @codesome

**Comment by ArthurSens** [comment]
> I am wondering wheter it would work to just call db.Close (and maybe add nil checks here ) @codesome

I'm having some trouble with some tests at #8007. I think that some blocks are left open even after db.close() on a previous test.
I'm wondering if closing everything on db.close() might help me with that PR as well

File: tsdb/db.go [hunk 5]
```diff
@@ -621,6 +621,33 @@ func open(dir string, l log.Logger, r prometheus.Registerer, opts *Options, rngs
...
+		// Close files if startup fails somewhere
+		if err == nil {
+			return
+		}
+
+		if wlog != nil {
+			if er := wlog.Close(); er != nil {
+				level.Error(l).Log("msg", "failed to close wal after failed TSDB startup", "err", er)
+			}
+		}
```
Comment (codesome) [inline tsdb/db.go:635]: WAL is closed inside Head, so this is not needed here.

**Review by codesome — COMMENTED** [review]
> I am wondering wheter it would work to just call db.Close (and maybe add nil checks here ) @codesome

Yes, this should be better with nil checks inside db.Close.

File: tsdb/db.go [hunk 6]
```diff
@@ -621,6 +621,18 @@ func open(dir string, l log.Logger, r prometheus.Registerer, opts *Options, rngs
 
 	var wlog *wal.WAL
 	segmentSize := wal.DefaultSegmentSize
+
+	defer func() {
+		// Close files if startup fails somewhere
```
Comment (bwplotka) [inline tsdb/db.go:626]:
```suggestion
		// Close files if startup fails somewhere.
```

File: tsdb/db.go [hunk 7]
```diff
@@ -621,6 +621,18 @@ func open(dir string, l log.Logger, r prometheus.Registerer, opts *Options, rngs
 
 	var wlog *wal.WAL
 	segmentSize := wal.DefaultSegmentSize
+
+	defer func() {
```
Comment (bwplotka) [inline tsdb/db.go:625]: Shouldn't we do this immediately after `&DB`?

File: tsdb/db.go [hunk 8]
```diff
@@ -621,6 +621,18 @@ func open(dir string, l log.Logger, r prometheus.Registerer, opts *Options, rngs
...
+		// Close files if startup fails somewhere
+		if err == nil {
+			return
+		}
+
+		if er := db.Close(); er != nil {
```
Comment (bwplotka) [inline tsdb/db.go:631]:
```suggestion
		if err := db.Close(); err != nil {
```
if you don't want to shadow `err` you can od `dbErr`  - but not `er`

**Review by bwplotka — COMMENTED** [review]
Awesome, some tiny only, but generally ok

File: tsdb/db.go (hunk 8 above)
Comment (ArthurSens) [reply tsdb/db.go:631]: I named `er` based on what I saw in a [piece of code](https://github.com/prometheus/prometheus/blob/416e3e0c3f620d4f6129305e50fe935c03f44b9e/tsdb/db.go#L1511) while working on another PR, but I agree with you.
I'll fix it on both PRs.

File: tsdb/db.go (hunk 7 above)
Comment (ArthurSens) [reply tsdb/db.go:625]: I think that starting the wal is the first thing that opens a file, so it works where it is, but it does no harm doing right after `&DB`. It might be easier to read also...

File: tsdb/db.go [hunk 9]
```diff
@@ -595,6 +595,17 @@ func open(dir string, l log.Logger, r prometheus.Registerer, opts *Options, rngs
...
 	}
+	defer func() {
+		// Close files if startup fails somewhere.
+		if err == nil {
+			return
+		}
+
+		if dbErr := db.Close(); dbErr != nil {
+			level.Error(l).Log("msg", "failed to close files after failed TSDB startup", "err", dbErr)
+		}
```
Comment (codesome) [inline tsdb/db.go:606]: `err` can mean anything, so we should change return variable to be clear, to maybe `returnErr`, and return close error instead of logging it. 
```suggestion
		// Close files if startup fails somewhere.
		if returnErr == nil {
			return
		}

		var merr tsdb_errors.MultiError
		merr.Add(returnErr)
		merr.Add(errors.Wrap(db.Close(), "close DB after failed startup"))
		returnErr = merr.Err()
```

File: tsdb/db.go [hunk 10]
```diff
@@ -621,6 +632,7 @@ func open(dir string, l log.Logger, r prometheus.Registerer, opts *Options, rngs
 
 	var wlog *wal.WAL
 	segmentSize := wal.DefaultSegmentSize
+
```
Comment (codesome) [inline tsdb/db.go:635]: Unintended change I believe

**Review by codesome — COMMENTED** [review]
Nit, and we should be good to merge!

File: tsdb/db.go (hunk 9 above)
Comment (ArthurSens) [reply tsdb/db.go:606]: This function has a named return, so I think I should keep `err` as the variable name, right?

Changing from logging to return the closing error make a lot of sense :slightly_smiling_face:

Comment (codesome) [reply tsdb/db.go]: > This function has a named return, so I think I should keep err as the variable name, right?

We also use `err` for other errors, so the variable name could be confused

**Review by codesome — APPROVED** [review]
Thanks! Will merge on green tests
