### PR TITLE
Fixed incorrect query results caused by buffer reuse in merge adapter

### LINKED ISSUE #7359: Merger adapter causes invalid query results due to slice reuse
**What did you do?**

I'm investigating an issue in Cortex blocks storage (running Prometheus `master`) and I ended up realising that the issue is caused by `seriesMergerAdapter`'s buffer.

The problem is that `seriesMergerAdapter` reuse the same slice to cast the `Series` and then this slice is passed to `ChainedSeriesMerge` which retains the slice, so subsequent calls to `seriesMergerAdapter.Merge()` will overwrite the (unintentionally) shared slice:
https://github.com/prometheus/prometheus/blob/e5ffa8c9a08a5ee4185271c8c26051ddc1388b7a/storage/generic.go#L114-L120

_I'm still checking the impact on Prometheus, but I preferred to open the issue earlier to raise a flag._

### PR DESCRIPTION
**Pull request by pracucci**
Fixes #7359.

### CODE REVIEW

File: storage/fanout_test.go [hunk 1]
```diff
@@ -195,10 +195,18 @@ func TestMergeQuerierWithChainMerger(t *testing.T) {
...
 
-			merged, _, _ := NewMergeQuerier(qs[0], qs, ChainedSeriesMerge).Select(false, nil)
-			for merged.Next() {
+			mergedQuerier, _, _ := NewMergeQuerier(qs[0], qs, ChainedSeriesMerge).Select(false, nil)
+
+			// Get all merged series upfront to make sure there are no incorrectly retained shared
+			// buffers causing bugs.
+			var mergedSeries []Series
+			for mergedQuerier.Next() {
+				mergedSeries = append(mergedSeries, mergedQuerier.At())
```
Comment (bwplotka) [inline storage/fanout_test.go:204]: Eh, again we are hit but "broken" usage of PromQL. Hopefully, we can fix it here: https://github.com/prometheus/prometheus/issues/7326 

This is good hot fix for now :muscle:

**Comment by bwplotka** [comment]
Once merged I am happy to cherry-pick for v.2.

**Comment by bwplotka** [comment]
https://github.com/prometheus/prometheus/pull/7364
