### PR TITLE
web/api: Add a limit parameter to /query and /query_range

### LINKED ISSUE #15443: Add a limit parameter to /query and /query_range
### Proposal

Add a limit parameter to /api/v1/query and /api/v1/query_range.

As mentioned in https://github.com/prometheus/prometheus/issues/12795, it was agreed to implement the same `limit` parameter for /query and /query_range API.

```
This was agreed at the [dev summit 2023-06-22](https://docs.google.com/document/d/11LC3wJcVk00l8w5P3oLQ-m3Y37iom6INAMEu2ZAGIIE/edit#bookmark=kix.sof7zj2b5694).

In the meeting we agreed that /query and /query_range could use the same feature.

CONSENSUS: We will have a LIMIT feature in the API. Ordering will not be guaranteed, and we will document this.
CONSENSUS: If a LIMIT is set, and the limit is exceeded, the API will make this obvious in the response.
```

### Use Cases

- Enforce a upper limit of number of series in the query response. This is useful because it doesn't make sense to return too many series to the UI (like Grafana) as browser might just crash
- Services like Cortex/Thanos/Mimir where there are Query Frontend and Queriers, `limit` doesn't need to be exposed at Query Frontend. But it can be enforced internally in Querier to protect the service.

### PR DESCRIPTION
**Pull request by Vandit1604**
Fixes #15443

### CODE REVIEW

File: web/api/v1/api.go [hunk 1]
```diff
@@ -2099,3 +2114,22 @@ func toHintLimit(limit int) int {
...
+	case promql.Matrix:
+		if len(v) > limit {
+			result.Value = v[:limit]
+		}
+	case promql.Vector:
+		if len(v) > limit {
+			result.Value = v[:limit]
+		}
+	default:
+		// No truncation for other types (Scalars or Strings)
```
Comment (beorn7) [inline web/api/v1/api.go:2129]: End sentence with a period.

Comment (beorn7) [reply web/api/v1/api.go:2129]: In different news, we don't really need this default section. We return the result below anyway.  I suggest to remove the `default` branch and have a comment below that the returned result is unchanged for other types.

**Review by beorn7 — CHANGES_REQUESTED** [review]
Thank you very much.

Three general things:
1. I guess we should also add a warning if the result is truncated.
2. The documentation needs an update. 
3. Adding a test would be good.
 
#13396 could serve as a template how to address all three points.

@machine424 @bboreham could you check if this makes sense overall? I'm not very familiar with this whole decision of limiting API endpoints, and you were involved with the previous related PRs.

File: web/api/v1/api.go (hunk 1 above)
Comment (Vandit1604) [reply web/api/v1/api.go:2129]: Should we write tests specifically for `truncateResults`, or would it be better to focus on `query` and `queryRange` where `truncateResults` is indirectly tested?

Comment (beorn7) [reply web/api/v1/api.go:2129]: I would think a test on the query level (like in #13396) should suffice.

Comment (Vandit1604) [reply web/api/v1/api.go]: I have implemented the following things according to the changes requested:
- updated the documentation
- added a warning if the result gets truncated

and I'm working on the test case now.

Comment (Vandit1604) [reply web/api/v1/api.go]: In the testEndpoints function, there are no test cases for matrix/vector responses returning multiple values that I can use to test the limit parameter. I added the limit expecting it to constrain FPoint values, but it didn't work as intended. Any ideas for predicting or verifying the response?

https://github.com/prometheus/prometheus/blob/main/web/api/v1/api_test.go#L1210-L1231

Is there a reason why we are not covering testing matrix/vector for Query API and queryRange API? Is it because that's not possible in the test suite?

File: docs/querying/api.md [hunk 2]
```diff
@@ -86,6 +86,7 @@ URL query parameters:
 - `time=<rfc3339 | unix_timestamp>`: Evaluation timestamp. Optional.
 - `timeout=<duration>`: Evaluation timeout. Optional. Defaults to and
    is capped by the value of the `-query.timeout` flag.
+- `limit=<number>`: Maximum number of returned series. doesn’t affect scalars or strings but truncates series for matrices and vectors. Optional.
```
Comment (beorn7) [inline docs/querying/api.md:89]:
```suggestion
- `limit=<number>`: Maximum number of returned series. Doesn’t affect scalars or strings but truncates the number of series for matrices and vectors. Optional. 0 means disabled.
```

File: docs/querying/api.md [hunk 3]
```diff
@@ -154,6 +155,7 @@ URL query parameters:
 - `step=<duration | float>`: Query resolution step width in `duration` format or float number of seconds.
 - `timeout=<duration>`: Evaluation timeout. Optional. Defaults to and
    is capped by the value of the `-query.timeout` flag.
+- `limit=<number>`: Maximum number of returned series. Optional.
```
Comment (beorn7) [inline docs/querying/api.md:158]:
```suggestion
- `limit=<number>`: Maximum number of returned series. Optional. 0 means disabled.
```

File: web/api/v1/api.go [hunk 4]
```diff
@@ -476,6 +480,11 @@ func (api *API) query(r *http.Request) (result apiFuncResult) {
 		return apiFuncResult{nil, returnAPIError(res.Err), res.Warnings, qry.Close}
 	}
 
+	var warnings annotations.Annotations
```
Comment (beorn7) [inline web/api/v1/api.go:483]:
```suggestion
	warnings := res.Warnings
```

We should not disregard the warnings coming from the query.

File: web/api/v1/api.go [hunk 5]
```diff
@@ -476,6 +480,11 @@ func (api *API) query(r *http.Request) (result apiFuncResult) {
...
+	if limit > 0 {
+		res = truncateResults(res, limit)
+		warnings = warnings.Add(errors.New("results truncated due to limit"))
```
Comment (beorn7) [inline web/api/v1/api.go:486]: You should only add the warning if the results were actually truncated.

`truncateResults` could return an additional `bool` telling the caller if a truncation has happened.

File: web/api/v1/api.go [hunk 6]
```diff
@@ -587,6 +600,12 @@ func (api *API) queryRange(r *http.Request) (result apiFuncResult) {
...
+	}
```
Comment (beorn7) [inline web/api/v1/api.go:607]: Same comments apply here as above.

**Review by beorn7 — CHANGES_REQUESTED** [review]

**Comment by beorn7** [comment]
> Is there a reason why we are not covering testing matrix/vector for Query API and queryRange API? Is it because that's not possible in the test suite?

I think the reason is that we do not fill the TSDB with any data for these simple tests. Therefore, all the queries are just using PromQL that still returns something with an empty TSDB.

There are ways to create a fully fledged vector with multiple elements. Not sure what's the best, but here is my spontaneous attempt:

`label_replace(vector(42), "foo", "bar", "", "") or label_replace(vector(3.1415), "dings", "bums", "", "")`

This returns a vector with two elements, so you could try out `limit=1` to see if only one is returned. (And same for a range query.)

**Comment by beorn7** [comment]
In different news: I'll be off for my Xmas vacations. Back 2025-01-07. In the meantime, it would be cool if @machine424 and @bboreham could say if this is doing the right thing. (I think it does, modulo the warnings handling, see above. So we only need the tests beyond that.)

File: web/api/v1/api.go (hunk 5 above)
Comment (Vandit1604) [reply web/api/v1/api.go]: done.

**Comment by Vandit1604** [comment]
> There are ways to create a fully fledged vector with multiple elements. Not sure what's the best, but here is my spontaneous attempt:
> 
> `label_replace(vector(42), "foo", "bar", "", "") or label_replace(vector(3.1415), "dings", "bums", "", "")`
> 
> This returns a vector with two elements, so you could try out `limit=1` to see if only one is returned. (And same for a range query.)

I couldn't find where I could fill the TSDB with testing data. Added some tests for `query` and `query_range` checking `warningCount`.

**Comment by beorn7** [comment]
My point was that with a test query like `label_replace(vector(42), "foo", "bar", "", "") or label_replace(vector(3.1415), "dings", "bums", "", "")` you can create a vector with multiple elements without the need to fill the test TSDB with data.

**Comment by Vandit1604** [comment]
The test case for the query:

```promql
label_replace(vector(42), "foo", "bar", "", "") or label_replace(vector(3.1415), "dings", "bums", "", "")
```
Failed due to a mismatch in the timestamps. The test expected a hardcoded timestamp of 0, but during testing we assign the current timestamp (in Unix epoch format) to generated values by default during execution. Prometheus does not allow you to control or ignore timestamps directly in queries.

The test comparison failed because the timestamps in the actual response did not match the expected value.

```diff
+               {
+                       endpoint: api.query,
+                       query: url.Values{
+                               "query": []string{
+                                       `label_replace(vector(42), "foo", "bar", "", "") or label_replace(vector(3.1415), "dings", "bums", "", "")`,
+                               },
+                       },
+                       responseAsJSON: `{
+               "resultType": "vector",
+               "result": [
+                       {
+                               "metric": {
+                                       "foo": "bar"
+                               },
+                               "value": [0, "42"]
+                       },
+                       {
+                               "metric": {
+                                       "dings": "bums"
+                               },
+                               "value": [0, "3.1415"]
+                       }
+               ]
+       }`,
+               },
```

Can we ignore the timestamps in this test case?

**Comment by Vandit1604** [comment]
I've pushed the changes with tests (in https://github.com/prometheus/prometheus/pull/15552/commits/587c690dd377db433968ee4489945488ca80dab5) that simulate a vector using `label_replace`. The values match as expected, but the timestamps are different causing the tests to fail. 
Should we ignore the timestamp differences, or is there a way to make them match in code?

File: web/api/v1/api_test.go [hunk 7]
```diff
@@ -1207,6 +1250,55 @@ func testEndpoints(t *testing.T, api *API, tr *testTargetRetriever, es storage.E
 				},
 			},
 		},
+		{
+			endpoint: api.query,
+			query: url.Values{
+				"query": []string{
+					`label_replace(vector(42), "foo", "bar", "", "") or label_replace(vector(3.1415), "dings", "bums", "", "")`,
```
[the remark this answers is not in the document]
Comment (Vandit1604) [reply web/api/v1/api_test.go:1257]: Thank you!

File: web/api/v1/api_test.go [hunk 8]
```diff
@@ -1207,6 +1250,56 @@ func testEndpoints(t *testing.T, api *API, tr *testTargetRetriever, es storage.E
...
+				},
+				"time": []string{"123.4"},
```
Comment (beorn7) [inline web/api/v1/api_test.go:1259]: I would add a `"limit": []string{"2"},` here and then repeat the test with `"limit": []string{"1"},` and `"limit": []string{"0"},`.

File: web/api/v1/api_test.go [hunk 9]
```diff
@@ -1207,6 +1250,56 @@ func testEndpoints(t *testing.T, api *API, tr *testTargetRetriever, es storage.E
...
+			response: &QueryData{
+				ResultType: parser.ValueTypeMatrix,
+				Result: promql.Matrix{
+					promql.Series{
+						Floats: []promql.FPoint{
+							{F: 0, T: timestamp.FromTime(start)},
+							{F: 1, T: timestamp.FromTime(start.Add(1 * time.Second))},
+							{F: 2, T: timestamp.FromTime(start.Add(2 * time.Second))},
+						},
+						// No Metric returned - use zero value for comparison.
```
Comment (beorn7) [inline web/api/v1/api_test.go:1297]: This comment looks out of place. There is a metric returned.

File: web/api/v1/api_test.go [hunk 10]
```diff
@@ -1207,6 +1250,56 @@ func testEndpoints(t *testing.T, api *API, tr *testTargetRetriever, es storage.E
...
+	}`,
+		},
+		{
+			endpoint: api.queryRange,
+			query: url.Values{
+				"query": []string{"time()"},
+				"start": []string{"0"},
+				"end":   []string{"2"},
+				"step":  []string{"1"},
+				"limit": []string{"1"},
```
Comment (beorn7) [inline web/api/v1/api_test.go:1286]: Let's repeat this test with `"limit": []string{"2"},` and  `"limit": []string{"0"},`.

File: web/api/v1/api_test.go [hunk 11]
```diff
@@ -1237,6 +1330,66 @@ func testEndpoints(t *testing.T, api *API, tr *testTargetRetriever, es storage.E
 			},
 			responseAsJSON: `{"resultType":"vector","result":[]}`,
 		},
+		// limit disabled
```
Comment (beorn7) [inline web/api/v1/api_test.go:1333]: The remaining tests below (through line 1392) don't make sense as they only have one metric. If you repeat the tests above with the different permutations as recommended, you can remove all the tests below.

**Review by beorn7 — CHANGES_REQUESTED** [review]

File: web/api/v1/api_test.go (hunk 9 above)
Comment (Vandit1604) [reply web/api/v1/api_test.go:1297]: I thought the comment referred to the Metric field in promql.Series being empty, not the Floats values. Are Floats considered part of the Metric in this context?

Comment (beorn7) [reply web/api/v1/api_test.go:1297]: OK, I get it now. (What is called "Metric" in this context is essentially the label set.) Still, I wouldn't comment on that. If the returned result doesn't have labels, it's just normal to represent that by the zero value. If a comment explains the obvious, it is confusing because the reader will assume that the comment wants to point to something non-obvious.

File: web/api/v1/api_test.go (hunk 10 above)
Comment (Vandit1604) [reply web/api/v1/api_test.go:1286]: Since there's no metric returned in this test case, the response for "limit": []string{"2"} and "limit": []string{"0"} will be the same. Is this behavior acceptable? 
Asking, since the `Result` is identical in all three cases.

File: web/api/v1/api_test.go (hunk 9 above)
Comment (Vandit1604) [reply web/api/v1/api_test.go:1297]: Makes sense, removed the comment.

File: web/api/v1/api_test.go (hunk 10 above)
Comment (beorn7) [reply web/api/v1/api_test.go:1338]: Sorry, I forgot that the `"query"` also has to be changed to the same as above, i.e. it should return two series.

Then limit=0 will return both result because it means "no limits". limit=2 will return both results because it coincides with the limit. and limit=1 will return one result because it got limited.

Comment (Vandit1604) [reply web/api/v1/api_test.go]: Implemented the changes here https://github.com/prometheus/prometheus/pull/15552/commits/861688da8290315a284e9c8f9165e0e2301bb2c7

PTAL in your own time.
Thanks.

**Review by beorn7 — DISMISSED** [review]
Looks great now. Thank you very much.

**Comment by beorn7** [comment]
Sorry, tests are still failing. Seems like a simple fix.

**Comment by Vandit1604** [comment]
> Sorry, tests are still failing. Seems like a simple fix.

Fixed.

**Review by beorn7 — APPROVED** [review]

**Comment by beorn7** [comment]
:tada: thank you very much.
