### PR TITLE
fix: Replaced os.MkdirTemp with t.TempDir

### LINKED ISSUE #9594: Use testing.T.TempDir() instead of ioutil.TempDir() in unit tests
## Proposal
**Use case. Why is this important?**

Instead of writing the code below in many many unit tests:
```go
      dir, err := ioutil.TempDir("", "wal_fuzz_live")
      require.NoError(t, err)
      defer func() {
        require.NoError(t, os.RemoveAll(dir))
      }()
```

Write this instead:
```go
    dir := t.TempDir()
```

Advantages:
- Error handling is implicit.
- Cleanup is implicit.
- Naming of directory derives from name of test, again, implicit.

Current occurences:
```console
0 ✓ (40.6ms) 11:11:22 invidian@dellxps15mateusz ~/repos/prometheus (⎇  main)$ git show --no-patch
commit a6e6011d55ed913cb8e53968cead9a6a6fd84911 (HEAD -> main, upstream/main, upstream/HEAD)
Author: Furkan Türkal <furkan.turkal@trendyol.com>
Date:   Mon Oct 25 00:45:31 2021 +0300

    Add scrape_body_size_bytes metric (#9569)

    Fixes #9520

    Signed-off-by: Furkan <furkan.turkal@trendyol.com>
0 ✓ (37.3ms) 11:11:29 invidian@dellxps15mateusz ~/repos/prometheus (⎇  main)$ git grep ioutil.TempDir *_test.go | wc -l
129
```

### PR DESCRIPTION
**Pull request by suryaaprakassh**
## Fixes #9594 

- Replace os.MkdirTemp with t.TempDir.
- Removed the cleanup logic for os.MkdirTemp.

### CODE REVIEW

**Comment by bwplotka** [comment]
I see more places than just this one.

Do you mind fixing them all while you are on it? (: 

image

**Comment by suryaaprakassh** [comment]
> I see more places than just this one.
> 
> Do you mind fixing them all while you are on it? (:
> 
> image

Sure I will fix it 👍

File: promql/promqltest/test.go [hunk 1]
```diff
@@ -1328,8 +1330,9 @@ type LazyLoaderOpts struct {
 }
 
 // NewLazyLoader returns an initialized empty LazyLoader.
-func NewLazyLoader(input string, opts LazyLoaderOpts) (*LazyLoader, error) {
+func NewLazyLoader(t testutil.T, input string, opts LazyLoaderOpts) (*LazyLoader, error) {
```
Comment (dgl) [inline promql/promqltest/test.go:1333]: This shouldn't take a testutil.T, as it's also used in promtool for user facing unit tests, which don't run under the test framework.

File: util/teststorage/storage.go [hunk 2]
```diff
@@ -31,18 +31,16 @@ import (
...
 }
 
 // NewWithError returns a new TestStorage for user facing tests, which reports
 // errors directly.
-func NewWithError(outOfOrderTimeWindow ...int64) (*TestStorage, error) {
-	dir, err := os.MkdirTemp("", "test_storage")
-	if err != nil {
-		return nil, fmt.Errorf("opening test directory: %w", err)
-	}
+func NewWithError(t testutil.T, outOfOrderTimeWindow ...int64) (*TestStorage, error) {
```
Comment (dgl) [inline util/teststorage/storage.go:41]: This shouldn't be changed, `os.MkdirTemp` is fine here as it's used in a user facing (`promtool test rules`) rather than testing path.

File: promql/promqltest/test.go (hunk 1 above)
Comment (suryaaprakassh) [reply promql/promqltest/test.go]: Indeed, I have just noticed those issues and will promptly revert my changes. I will submit a pull request once the necessary fixes have been implemented.

**Comment by suryaaprakassh** [comment]
The current changes involve modifying every `os.MkdirTemp()` call to `t.TempDir();`. However, some of these `os.MkdirTemp()` calls are not located within test environments. Additionally, `os.MkdirTemp()` in `api_test.go` cannot be modified, as previously mentioned by @dgl.

**Review by bwplotka — APPROVED** [review]
Thanks!
