### PR TITLE
Fix IPv6 scraping

### LINKED ISSUE #1944: ipv6 addresses not automatically wrapped
**What did you do?**
We installed Kubernetes and Prometheus on top of Rackspace and seeing sometimes ipv4, sometimes ipv6 addresses for nodes, service and pod ips.

**What did you expect to see?**
All endpoints either declared explicitly or via autodiscovery should be in state `UP`

**What did you see instead? Under which circumstances?**
Endpoints with a ipv6 addresses have a state `DOWN` and the error says `Get http://xxxx:xxxx:xxxx:xxx:xxxx:xxxx:xxxx:xxx:9100/metrics: dial tcp: too many colons in address xxxx:xxxx:xxxx:xxx:xxxx:xxxx:xxxx:xxx:9100`

**Environment**

* System information:
Linux 4.7.0-coreos x86_64

* Prometheus version: 
prometheus, version 1.1.0 (branch: master, revision: a60378c77765080a781e313ece0d0ab47c2e54e2)
  build user:       root@583368332c21
  build date:       20160903-19:35:49
  go version:       go1.6.3

* Alertmanager version:

none

* Prometheus configuration file:

https://raw.githubusercontent.com/prometheus/prometheus/v1.1.0/documentation/examples/prometheus-kubernetes.yml

* Alertmanager configuration file:
none

* Logs:
none

* Screens:
bildschirmfoto 2016-09-05 um 12 18 47

### PR DESCRIPTION
**Pull request by fabxc**
Fixes #1944 and #914

@w0mbat @jimmidyson @juliusv

### CODE REVIEW

File: retrieval/targetmanager.go [hunk 1]
```diff
@@ -417,79 +417,96 @@ func providersFromConfig(cfg *config.ScrapeConfig) map[string]TargetProvider {
...
-func targetsFromGroup(tg *config.TargetGroup, cfg *config.ScrapeConfig) ([]*Target, error) {
-	targets := make([]*Target, 0, len(tg.Targets))
-
-	for i, labels := range tg.Targets {
-		for k, v := range cfg.Params {
-			if len(v) > 0 {
-				labels[model.LabelName(model.ParamLabelPrefix+k)] = model.LabelValue(v[0])
-			}
+// populateLabels builds a target from the given label set and scrape configuration.
+// Returns a nil target if the target is dropped due during relabeling.
```
Comment (jimmidyson) [inline retrieval/targetmanager.go]: Remove `due`?

File: retrieval/targetmanager.go [hunk 2]
```diff
@@ -417,79 +417,96 @@ func providersFromConfig(cfg *config.ScrapeConfig) map[string]TargetProvider {
...
+
+	// Check if the target was dropped.
+	if lset == nil {
+		return nil, nil, nil
+	}
+
+	// hasPort checks whether s is an IPv6 or IPv4 address that contains a port.
+	// We don't have to catch whether they are valid addresses, just whether they
+	// have a port if they are valid.
+	hasPort := func(s string) bool {
```
Comment (jimmidyson) [inline retrieval/targetmanager.go]: Can `s` only be an IP address? What if it's a hostname (not sure if it can be at the point it's called)?

Comment (fabxc) [inline retrieval/targetmanager.go]: Right, of course.

Comment (jimmidyson) [inline retrieval/targetmanager.go]: Right what? It is always an IP?

Comment (fabxc) [inline retrieval/targetmanager.go]: Of course it can be hostname – fixing stuff because we forgot the one, then forgetting the other :) not so smart

File: retrieval/targetmanager.go [hunk 3]
```diff
@@ -417,79 +417,97 @@ func providersFromConfig(cfg *config.ScrapeConfig) map[string]TargetProvider {
...
+	// Check if the target was dropped.
+	if lset == nil {
+		return nil, nil, nil
+	}
+
+	// hasPort checks whether the address is suffixed by a port.
+	// We don't have to catch whether they are valid addresses, just whether they
+	// have a port if they are valid.
+	hasPort := func(s string) bool {
+		s = strings.TrimRight(s, "0123456789")
```
Comment (jimmidyson) [inline retrieval/targetmanager.go]: Won't this also match for IPv6 addresses if they're not wrapped in `[...]`? e.g. 2001:cdba:0000:0000:0000:0000:3257:9652

Comment (jimmidyson) [inline retrieval/targetmanager.go]: Why not just use `net.SplitHostPort`?

File: retrieval/targetmanager.go [hunk 4]
```diff
@@ -417,79 +417,97 @@ func providersFromConfig(cfg *config.ScrapeConfig) map[string]TargetProvider {
...
-func targetsFromGroup(tg *config.TargetGroup, cfg *config.ScrapeConfig) ([]*Target, error) {
-	targets := make([]*Target, 0, len(tg.Targets))
-
-	for i, labels := range tg.Targets {
-		for k, v := range cfg.Params {
-			if len(v) > 0 {
-				labels[model.LabelName(model.ParamLabelPrefix+k)] = model.LabelValue(v[0])
-			}
+// populateLabels builds a label set from the given label set and scrape configuration.
+// It returns a label set before relabeling was applied as the second argument.
```
Comment (juliusv) [inline retrieval/targetmanager.go]: "argument" -> "return value"

File: retrieval/targetmanager.go [hunk 5]
```diff
@@ -417,79 +417,97 @@ func providersFromConfig(cfg *config.ScrapeConfig) map[string]TargetProvider {
...
+// Returns a nil label sets if the target is dropped during relabeling.
```
Comment (juliusv) [inline retrieval/targetmanager.go]: "sets" -> "set"

File: retrieval/targetmanager.go (hunk 3 above)
Comment (fabxc) [inline retrieval/targetmanager.go]: Hm, I was assuming now that they should be wrapped when they get there. `net.SplitHostPort` assumes the same. But still right that we should just use that function.

File: retrieval/targetmanager.go [hunk 6]
```diff
@@ -417,79 +417,97 @@ func providersFromConfig(cfg *config.ScrapeConfig) map[string]TargetProvider {
...
+	// have a port if they are valid.
+	hasPort := func(s string) bool {
+		s = strings.TrimRight(s, "0123456789")
+		return len(s) > 0 && s[len(s)-1] == ':'
+	}
+	// If it's an address with no trailing port, infer it based on the used scheme.
+	if addr := string(lset[model.AddressLabel]); !hasPort(addr) {
+		switch lset[model.SchemeLabel] {
+		case "http", "":
+			addr = fmt.Sprintf("%s:80", addr)
```
Comment (juliusv) [inline retrieval/targetmanager.go]: Do those not need to use `net.JoinHostPort()` as well? But I'm not done reading everything yet...

File: retrieval/targetmanager.go (hunk 3 above)
Comment (fabxc) [inline retrieval/targetmanager.go]: Then again, this returns an error for an invalid address, which is nice. But also if the port is missing. However, the error is not a checkable constant and we've to inspect the error string for "missing port", which is also fragile.

File: retrieval/targetmanager_test.go [hunk 7]
```diff
@@ -72,3 +74,135 @@ dns_sd_configs:
...
+
+func mustNewRegexp(s string) config.Regexp {
+	re, err := config.NewRegexp(s)
+	if err != nil {
+		panic(err)
+	}
+	return re
+}
+
+func TestPopulateLabels(t *testing.T) {
```
Comment (juliusv) [inline retrieval/targetmanager_test.go]: Add an IPv6 test here, since it's kind of relevant?

File: retrieval/targetmanager.go (hunk 3 above)
Comment (fabxc) [inline retrieval/targetmanager.go]: Okay, this is kind of a hack now, but seems safe.

File: retrieval/targetmanager.go [hunk 8]
```diff
@@ -417,79 +418,102 @@ func providersFromConfig(cfg *config.ScrapeConfig) map[string]TargetProvider {
...
-			switch labels[model.SchemeLabel] {
-			case "http", "":
-				addr = fmt.Sprintf("%s:80", addr)
-			case "https":
-				addr = fmt.Sprintf("%s:443", addr)
-			default:
-				return nil, fmt.Errorf("invalid scheme: %q", cfg.Scheme)
-			}
-			labels[model.AddressLabel] = model.LabelValue(addr)
+		// If adding a port makes it valid, the previous error
```
Comment (jimmidyson) [inline retrieval/targetmanager.go]: Funky!

File: retrieval/targetmanager_test.go (hunk 7 above)
Comment (fabxc) [inline retrieval/targetmanager_test.go]: Added to another test that was redundant for IPv4.

File: retrieval/targetmanager.go [hunk 9]
```diff
@@ -417,79 +418,102 @@ func providersFromConfig(cfg *config.ScrapeConfig) map[string]TargetProvider {
...
+		// was not due to an invalid address and we can append a port.
+		_, _, err := net.SplitHostPort(s + ":1234")
+		return err == nil
+	}
+	// If it's an address with no trailing port, infer it based on the used scheme.
+	if addr := string(lset[model.AddressLabel]); addPort(addr) {
+		switch lset[model.SchemeLabel] {
+		case "http", "":
+			addr = fmt.Sprintf("%s:80", addr)
```
Comment (juliusv) [inline retrieval/targetmanager.go]: Ah I think I get it. Incoming addrs are already correctly formatted (with `[]` for IPv6), and `net.JoinHostPort()` actually adds another layer of `[]` around the address part if the brackets are already present. Would be good to make clear (in a comment?) that any addrs that are inputs here are assumed to not be a raw IPv6 address (`::1`), anymore but already wrapped. From something thinking that ends up being clear anyways because the typical addr in Go can always contain a port, and then the bracket notation is necessary in any case for disambiguation. Hmm...

Comment (fabxc) [inline retrieval/targetmanager.go]: Clarified in a comment.

**Comment by fabxc** [comment]
Okay, I hope this is good now. Can I have a final look? @jimmidyson @brancz, Julius is on vacation.

**Comment by brancz** [comment]
LGTM
