### PR TITLE
Check for timeout in each iteration of matrixSelector

### LINKED ISSUE #4288: Promql won't time-out queries in matrixSelector
## Bug Report
**What did you do?**
Someone sent a large query such as `{__name__=~".+"}[5d]` to our prometheus host.

**What did you expect to see?**
I expect the query to timeout before completing, while consuming some memory and CPU along the way.

**What did you see instead? Under which circumstances?**
The query runs until it exhausts all available memory on the host and OOM killer get is. I have set it up in a repro env locally and the query has been running for ~60m (its still going) even though I have the timeout set to the default 2m.

**Environment**

* Prometheus version:

2.2

### PR DESCRIPTION
**Pull request by jacksontj**
Fixes #4288

### CODE REVIEW

File: promql/engine.go [hunk 1]
```diff
@@ -1044,6 +1044,10 @@ func (ev *evaluator) matrixSelector(node *MatrixSelector) Matrix {
 
 	var it *storage.BufferedSeriesIterator
 	for i, s := range node.series {
+		// check for timeout/cancellation here.
```
Comment (brian-brazil) [inline promql/engine.go]: No need for the comment

**Comment by jacksontj** [comment]
Comment removed, CI looks good (except for the one travis test that has been failing for at least the last week).

**Comment by brian-brazil** [comment]
Thanks!

We're aware of that, it's a resource issue that we're in the process of getting resolved.
