### PR TITLE
rules: Make deleted rule series as stale after a reload

### LINKED ISSUE #5195: Deleted rules don't go stale after a reload
## Bug Report
**What did you do?**

I noticed this while digging into https://github.com/prometheus/prometheus/issues/5193.

If you delete a recording rule from the end of your rules and reload, the rule doesn't go stale.

**What did you expect to see?**

After deleting a rule and reloading, I expect it to go stale in the next eval cycle.

**What did you see instead? Under which circumstances?**

The recording rule time series sticks around for 5m.

**Environment**

docker container

* System information:

```
/prometheus $ uname -srm
Linux 4.20.6-arch1-1-ARCH x86_64
```

* Prometheus version:

```
/prometheus $ prometheus --version
prometheus, version 2.7.1 (branch: HEAD, revision: 62e591f928ddf6b3468308b7ac1de1c63aa7fcf3)
  build user:       root@f9f82868fc43
  build date:       20190131-11:16:59
  go version:       go1.11.5
```

* Prometheus configuration file:
```
/etc/prometheus $ cat prometheus.yml
# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.                             
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.                                     
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.                                  
rule_files:                
- "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:                                                              
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.                                
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']
```

```
/etc/prometheus $ cat first_rules.yml 
groups:
- name: testgroup
  rules:
  - record: test
    expr: 11111
    labels:
      name: my-first
  - record: test
    expr: 22222
    labels:
      name: my-second
```

### PR DESCRIPTION
**Pull request by roidelapluie**
Fix #5195

Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

### CODE REVIEW

File: rules/manager.go [hunk 1]
```diff
@@ -901,6 +905,12 @@ func (m *Manager) Update(interval time.Duration, files []string, externalLabels
 	// Stop remaining old groups.
 	for n, oldg := range m.groups {
 		oldg.stop()
+		for _, rule := range oldg.seriesInPreviousEval {
+			for _, s := range rule {
+				oldg.staleSeries = append(oldg.staleSeries, s)
+			}
+		}
+		oldg.cleanupStaleSeries(time.Now())
```
Comment (brian-brazil) [inline rules/manager.go]: You're doing this too early. What if a new rules is created with the same name before when the next eval interval will be?

Comment (roidelapluie) [reply rules/manager.go]: Done. It will make reloads longer but now is right.

Comment (roidelapluie) [reply rules/manager.go]: Note that to be completely safe we probably should wait 2*time.interval because the rule groups are delayed by a seed.

File: rules/manager.go [hunk 2]
```diff
@@ -922,16 +931,16 @@ func (m *Manager) Update(interval time.Duration, files []string, externalLabels
 	// Stop remaining old groups.
 	wg.Add(len(m.groups))
 	for n, oldg := range m.groups {
-		go func() {
-			oldg.stop()
+		go func(n string, g *Group) {
+			g.stopAndMakeStale()
+			if m := g.metrics; m != nil {
+				m.groupInterval.DeleteLabelValues(n)
```
Comment (roidelapluie) [inline rules/manager.go]: @brian-brazil is this thread safe to your knowledge?

**Comment by roidelapluie** [comment]
I still need to add a test to see that we don't insert stale maker on stopping

**Comment by roidelapluie** [comment]
I think I will move the stale markers to a goroutine. That way it will not impact the reload and it should be safe.

**Comment by roidelapluie** [comment]
I think I underestimated the task but hey now here we go ... ready for review ... i might still create helpers function to shorten the storage creation etc in tests, WDYT?

File: rules/manager.go (hunk 2 above)
Comment (brian-brazil) [reply rules/manager.go]: Looking at the code in client_golang, there's a mutex in use.

File: rules/manager.go [hunk 3]
```diff
@@ -314,14 +325,36 @@ func (g *Group) run(ctx context.Context) {
 	tick := time.NewTicker(g.interval)
 	defer tick.Stop()
 
+	makeStale := func(s bool) {
+		if !s || g.opts.LookbackDelta < g.interval {
```
Comment (brian-brazil) [inline rules/manager.go]: Why is LookbackDelta being considered here? Whether we write stale markers should have nothing to do with how a subsequent query happens to be configured.

**Comment by brian-brazil** [comment]
> I think I underestimated the task but hey now here we go

They way I've looked at is that if you're deleting a rule group it's you no longer care about recording rules and their output, so there's not much point in getting the staleness just right in that case.

File: rules/manager.go (hunk 3 above)
Comment (roidelapluie) [reply rules/manager.go]: it is a safety if someone deletes a rule with interval: 30m so that we don't have go routine out there for 1 hour.

Comment (brian-brazil) [reply rules/manager.go]: That's already how it works for scraping, let's keep things simple.

File: rules/manager.go (hunk 2 above)
Comment (roidelapluie) [reply rules/manager.go]: https://github.com/prometheus/client_golang/blob/76dd6c581988366a52807465d426f83e776128ad/prometheus/vec.go#L253

great!

File: rules/manager.go (hunk 3 above)
Comment (roidelapluie) [reply rules/manager.go]: I have removed that bit and simplified the tests.

File: rules/manager.go [hunk 4]
```diff
@@ -314,14 +325,36 @@ func (g *Group) run(ctx context.Context) {
...
+		}
+		go func(now time.Time) {
+			// Wait for 2 intervals to give the opportunity to renamed rules
+			// to insert new series in the tsdb. At this point if there is a
+			// renamed rule, it should already be started.
+			select {
+			case <-g.managerDone:
+			case <-time.After(2 * g.interval):
+				for _, rule := range g.seriesInPreviousEval {
+					for _, s := range rule {
```
Comment (brian-brazil) [inline rules/manager.go]: You're shadowing `s` here. Why not move the top if out of this function?

Comment (roidelapluie) [reply rules/manager.go]: Done, I have also set g.seriesInPreviousEval to nil so it can be garbage collected before 2 * g.interval

File: rules/manager.go [hunk 5]
```diff
@@ -330,17 +330,19 @@ func (g *Group) run(ctx context.Context) {
 			return
 		}
 		go func(now time.Time) {
+			for _, rule := range g.seriesInPreviousEval {
+				for _, r := range rule {
```
Comment (brian-brazil) [inline rules/manager.go]: You can do `g.staleSeries = append(g.staleSeries, rule...)`

Comment (roidelapluie) [reply rules/manager.go]: cannot use rules (type map[string]labels.Labels) as type labels.Labels in append

Comment (roidelapluie) [reply rules/manager.go]: I will improve it

Comment (roidelapluie) [reply rules/manager.go]: Well not sure how to improve that

**Comment by brian-brazil** [comment]
:+1:
