### PR TITLE
SD Managers taking over responsibility for registration of debug metrics

### LINKED ISSUE #13312: SD: failed to register metric: duplicate metrics collector registration attempted consul.go:349
### Proposal

From @roman-vynar https://github.com/prometheus/prometheus/issues/13245#issuecomment-1863001187:

> looks like I have discovered another bug while testing this, not in v2.48.0 but it is in the main.
> Looks like the following commit https://github.com/prometheus/prometheus/commit/6de80d7fb03f7cd5ed44b85559886e73d89e720d
> It throws errors like this

> ts=2023-12-19T15:35:28.274Z caller=consul.go:349 level=error component="discovery manager scrape"
 discovery=consul config=xxx msg="Unable to register metrics" 
err="failed to register metric: duplicate metrics collector registration attempted"
> if you have 1+ jobs with the same type of SD, e.g. 2 jobs with consul_sd_config or azure_sd_config etc.

cc @ptodev do you mind double checking this?

### PR DESCRIPTION
**Pull request by ptodev**
Follow up to the discussion in #13316.

Fixes #13312.

If Prometheus SD mechanisms are imported by other Go projects as a library, it would be good to see the debug metrics of each SD instance in a separate series. However, as discussed in #13316, the debug metrics of Prometheus itself should stay as they are. There are [two ways](https://github.com/prometheus/prometheus/pull/13316#issuecomment-1871244345) of doing this:
1. Using the `AlreadyRegisteredError` pattern. I would prefer not to do this, because it makes the code harder to read. It also makes it harder to find a way to unregister the metrics.
2. Creating a new struct in the `DiscovererOptions` which contains pre-registered (by the Manager) metrics. This feels cleaner and more intuitive from a coding point of view. The main downside is that the SD mechanism is no longer encapsulated as well as it used to be. It would have been nice if the SD mechanism could be responsible for registering and unregistering its own metrics.

This is a draft PR which attempts the 2nd approach for the File SD. Please let me know if this solution would be acceptable? If it is, then I could implement this for all other SD mechanisms.

### CODE REVIEW

**Comment by beorn7** [comment]
I don't feel strongly about the two different approaches. You prefer the 2nd, so I'd say go with it.

Thanks for all the work, and sorry that this needs to be so complicated.

File: discovery/nomad/nomad_test.go [hunk 1]
```diff
@@ -128,8 +130,15 @@ func TestConfiguredService(t *testing.T) {
 	conf := &SDConfig{
 		Server: "http://localhost:4646",
 	}
-	_, err := NewDiscovery(conf, nil, prometheus.NewRegistry())
+
+	refreshDebugMetrics := discovery.NewRefreshDebugMetrics(prometheus.DefaultRegisterer)
+	metrics := conf.NewDiscovererDebugMetrics(prometheus.NewRegistry(), refreshDebugMetrics)
+	require.NoError(t, metrics.Register())
```
Comment (ptodev) [inline discovery/nomad/nomad_test.go:136]: These lines are very repetitive across tests. I could try to reduce the repetition.

File: discovery/puppetdb/puppetdb.go [hunk 2]
```diff
@@ -158,11 +170,11 @@ func NewDiscovery(conf *SDConfig, logger log.Logger, reg prometheus.Registerer)
 
 	d.Discovery = refresh.NewDiscovery(
 		refresh.Options{
-			Logger:   logger,
-			Mech:     "http",
-			Interval: time.Duration(conf.RefreshInterval),
-			RefreshF: d.refresh,
-			Registry: reg,
+			Logger:              logger,
+			Mech:                "http",
```
Comment (ptodev) [inline discovery/puppetdb/puppetdb.go:174]: I think `Mech` should be set to `puppetdb` instead of `http`.
`Mech` was set to `http` in #8883, the pull request which originally added the Puppet SD.
@roidelapluie, could you please confirm if `Mech` should be set to "puppetdb"? It'd be better to do it in a separate PR though.

**Comment by ptodev** [comment]
> I don't feel strongly about the two different approaches. You prefer the 2nd, so I'd say go with it.
> 
> Thanks for all the work, and sorry that this needs to be so complicated.

@beorn7 No worries, and thank you too for the help! I updated the PR, and it is mostly finished now. The only remaining bits are to polish the tests a bit more (there is a lot of repetition in them) and to do more local testing. Do you mind taking a look please, to let me know if anything else needs changing before I do this final polish?

File: promql/parser/generated_parser.y.go
Comment (beorn7) [inline promql/parser/generated_parser.y.go:1]: Why is this file changing? Did you maybe apply some formatter to this file? (It should stay as the auto-generator creates it, even if it is not correctly formatted.)

**Review by beorn7 — COMMENTED** [review]
It looks like this is the way to go (although it is sad that it has to be so complicated).

I'm not a domain expert when it comes to SD, but why the term "debug metrics"? It seems to bloat many many names. Why not just "metrics", e.g. `discovery.DiscovererMetrics`?

**Comment by roidelapluie** [comment]
Indeed, I think we should drop "debug" from the terminology. Those are just normal metrics.

File: promql/parser/generated_parser.y.go
Comment (ptodev) [reply promql/parser/generated_parser.y.go:1]: Apologies, you're right - this change is from an automatic formatter and is unintentional. I'll revert it.

File: cmd/prometheus/main.go [hunk 3]
```diff
@@ -630,9 +630,16 @@ func main() {
 		level.Error(logger).Log("msg", "failed to register Kubernetes client metrics", "err", err)
 		os.Exit(1)
 	}
+
+	sdDiscMetrics, err := discovery.CreateAndRegisterSDMetrics(prometheus.DefaultRegisterer)
```
[the remark this answers is not in the document]
Comment (ptodev) [reply cmd/prometheus/main.go:634]: True! I'll rename this.

File: discovery/xds/kuma_mads.pb.go
Comment (beorn7) [inline discovery/xds/kuma_mads.pb.go:1]: Another autogenerated file potentially touched by your auto-formatter. If this change was created because you regenerated the file, that's fine. Otherwise, I would leave it untouched.

**Review by beorn7 — CHANGES_REQUESTED** [review]
I'm fine merging this "almost" as-is. Just see my two comments.

We should, however, give @roidelapluie a few days to raise objections, if needed.

**Comment by roidelapluie** [comment]
I agree with Beorn. This is almost ready and it is probably the best approach.

File: discovery/xds/kuma_mads.pb.go
Comment (ptodev) [reply discovery/xds/kuma_mads.pb.go:1]: Apologies, I reverted this and a few others like it.

File: cmd/prometheus/main.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (ptodev) [reply cmd/prometheus/main.go]: I'm sorry, I fixed it in a [different file](https://github.com/prometheus/prometheus/pull/13375/commits/cc697f3af59617bce3960b583ea43b7937ecf1dd#diff-4b5061b484fa7335e0aa5fc2be927041bc0269e739b84464e63813649006648aR75) but didn't fix it in this one. I think I must have been searching for "sdDisc" just in the "discovery" directory.

**Comment by ptodev** [comment]
@beorn7 @roidelapluie Thank you for your reviews. I reviewed the whole PR myself today to make sure that all changes comply with your suggestions. I believe this is the case now, and I hope I didn't miss anything by accident.

File: discovery/puppetdb/puppetdb.go (hunk 2 above)
Comment (beorn7) [reply discovery/puppetdb/puppetdb.go:174]: Reminder for @roidelapluie that this is still on open question.

File: discovery/registry.go [hunk 4]
```diff
@@ -258,3 +260,24 @@ func replaceYAMLTypeError(err error, oldTyp, newTyp reflect.Type) error {
 	}
 	return err
 }
+
+// RegisterSDMetrics registers the metrics used by service discovery mechanisms.
+// RegisterSDMetrics should be called only once during the lifetime of the PRometheus process.
```
Comment (beorn7) [inline discovery/registry.go:265]:
```suggestion
// RegisterSDMetrics should be called only once during the lifetime of the Prometheus process.
```

**Review by beorn7 — APPROVED** [review]
Thank you very much for the epic work.

I'll fix the one typo myself in the GH UI.

**Comment by beorn7** [comment]
Will merge on green.

File: discovery/puppetdb/puppetdb.go (hunk 2 above)
Comment (ptodev) [reply discovery/puppetdb/puppetdb.go:174]: I raised another PR for this:
https://github.com/prometheus/prometheus/pull/13447
