### PR TITLE
[FIX] PromQL: support variable scalar parameter in aggregations in range queries

### LINKED ISSUE #15971: Aggregations that take a numeric parameter only use value from first time step in range query
### What did you do?

I ran `topk(scalar(param), some_series)` as a range query over many time steps.

`param` selects a single series with different values at each time step: first 1, then 2, then 3 etc.

`some_series` selects many series.

### What did you expect to see?

I expected to receive one value at the first time step, then two at the second step, three at the third step etc.

### What did you see instead? Under which circumstances?

I received only one value at all time steps.

If I run the query as an instant query at each of the time steps in the range, I get the expected behaviour above.

Looking at [the code for this](https://github.com/prometheus/prometheus/blob/96f31e370b2ac59c323faf8f6d7149a92bf139a0/promql/engine.go#L1603), I believe a similar issue applies to all aggregations that take a scalar parameter: `topk`, `bottomk`, `quantile`, `limitk` and `limit_ratio`.

### System information

_No response_

### Prometheus version

```text
Prometheus at commit 0a19f1268e2dbb9bae9568f007a9809e8fba0402
```

### Prometheus configuration file

```yaml
n/a
```

### Alertmanager version

```text
n/a
```

### Alertmanager configuration file

```yaml
n/a
```

### Logs

```text
n/a
```

### PR DESCRIPTION
**Pull request by NeerajGartia21**
Fixes #15971

### CODE REVIEW

**Comment by NeerajGartia21** [comment]
CC: @beorn7 @charleskorn 
Also tagging @bboreham since he worked on this earlier.

**Comment by beorn7** [comment]
Thanks for tackling this.

While this isn't directly un-doing https://github.com/prometheus/prometheus/pull/13744, it neither does what we sketched out in the dev-summit (find out if the parameter is constant at parse-time and take different code paths then).

But maybe the approach here is still fast enough? Have you tried running the micro benchmarks? You could compare the effect of this PR with the findings in https://github.com/prometheus/prometheus/pull/13744 .

Maybe we could also do something more in the `allParamMatchCondition` style, e.g. first finding out if the parameter doesn't change.

I would also welcome @bboreham and @machine424 to take a look here. You are way better domain experts here than me.

File: promql/engine.go [hunk 1]
```diff
@@ -1585,8 +1596,13 @@ func (ev *evaluator) eval(ctx context.Context, expr parser.Expr) (parser.Value,
 		// Grouping labels must be sorted (expected both by generateGroupingKey() and aggregation()).
 		sortedGrouping := e.Grouping
 		slices.Sort(sortedGrouping)
+		isDynamicParam := true
```
Comment (beorn7) [inline promql/engine.go:1599]: Maybe let's invert this and go with the more common term "const"? E.g. `constParam`. (The "is" in there sounds a bit Java-esque to me.)

**Comment by beorn7** [comment]
Remember to run the `RangeQuery` benchmarks with steps=100 and steps=1000 as it was done in https://github.com/prometheus/prometheus/pull/13744 back then to show the improvements.

**Comment by NeerajGartia21** [comment]
These are the benchmarks run against this PR. First 1000 steps and then 100 steps.

```
goos: darwin
goarch: arm64
pkg: github.com/prometheus/prometheus/promql
cpu: Apple M1
                                                                                                         │ /Users/neerajgartia/Desktop/dev/cp/before_1000.txt │ /Users/neerajgartia/Desktop/dev/cp/after_1000.txt │
                                                                                                         │                       sec/op                       │           sec/op            vs base               │
RangeQuery/expr=a_one,steps=1000-8                                                                                                               35.22µ ±  8%                 35.23µ ±  1%        ~ (p=0.937 n=6)
RangeQuery/expr=a_ten,steps=1000-8                                                                                                               302.0µ ±  1%                 300.9µ ±  0%        ~ (p=0.065 n=6)
RangeQuery/expr=a_hundred,steps=1000-8                                                                                                           2.981m ± 64%                 2.996m ±  1%        ~ (p=0.310 n=6)
RangeQuery/expr=rate(a_one[1m]),steps=1000-8                                                                                                     82.58µ ±  0%                 82.62µ ±  1%        ~ (p=0.394 n=6)
RangeQuery/expr=rate(a_ten[1m]),steps=1000-8                                                                                                     776.1µ ± 12%                 775.1µ ±  0%        ~ (p=0.589 n=6)
RangeQuery/expr=rate(a_hundred[1m]),steps=1000-8                                                                                                 7.734m ±  1%                 7.774m ±  0%        ~ (p=0.180 n=6)
RangeQuery/expr=rate(a_one[1m]),steps=10000-8                                                                                                    797.6µ ±  0%                 801.7µ ±  1%   +0.52% (p=0.009 n=6)
RangeQuery/expr=rate(a_ten[1m]),steps=10000-8                                                                                                    8.159m ±  5%                 8.140m ±  0%        ~ (p=0.589 n=6)
RangeQuery/expr=rate(a_hundred[1m]),steps=10000-8                                                                                                81.56m ±  0%                 81.80m ±  1%        ~ (p=0.065 n=6)
RangeQuery/expr=rate(sparse[1m]),steps=10000-8                                                                                                   5.318m ±  5%                 5.367m ±  1%        ~ (p=0.065 n=6)
RangeQuery/expr=double_exponential_smoothing(a_one[1d],_0.3,_0.3),steps=1000-8                                                                   58.36m ±  0%                 58.36m ±  0%        ~ (p=0.699 n=6)
RangeQuery/expr=double_exponential_smoothing(a_ten[1d],_0.3,_0.3),steps=1000-8                                                                   582.2m ±  0%                 583.1m ±  1%        ~ (p=0.180 n=6)
RangeQuery/expr=double_exponential_smoothing(a_hundred[1d],_0.3,_0.3),steps=1000-8                                                                5.808 ±  1%                  5.820 ±  1%        ~ (p=0.180 n=6)
RangeQuery/expr=changes(a_one[1d]),steps=1000-8                                                                                                  19.33m ±  0%                 19.27m ±  1%        ~ (p=0.180 n=6)
RangeQuery/expr=changes(a_ten[1d]),steps=1000-8                                                                                                  192.6m ±  0%                 192.4m ±  0%        ~ (p=0.240 n=6)
RangeQuery/expr=changes(a_hundred[1d]),steps=1000-8                                                                                               1.921 ±  0%                  1.927 ±  3%        ~ (p=0.093 n=6)
RangeQuery/expr=rate(a_one[1d]),steps=1000-8                                                                                                     5.853m ±  1%                 5.864m ±  1%        ~ (p=0.485 n=6)
RangeQuery/expr=rate(a_ten[1d]),steps=1000-8                                                                                                     58.73m ±  2%                 59.01m ± 14%        ~ (p=0.310 n=6)
RangeQuery/expr=rate(a_hundred[1d]),steps=1000-8                                                                                                 584.3m ±  1%                 589.7m ±  3%   +0.93% (p=0.009 n=6)
RangeQuery/expr=absent_over_time(a_one[1d]),steps=1000-8                                                                                         2.661m ±  1%                 2.706m ±  2%   +1.70% (p=0.041 n=6)
RangeQuery/expr=absent_over_time(a_ten[1d]),steps=1000-8                                                                                         26.74m ±  3%                 26.75m ±  3%        ~ (p=1.000 n=6)
RangeQuery/expr=absent_over_time(a_hundred[1d]),steps=1000-8                                                                                     269.6m ±  4%                 269.2m ±  4%        ~ (p=0.485 n=6)
RangeQuery/expr=-a_one,steps=1000-8                                                                                                              37.32µ ±  1%                 36.99µ ±  1%   -0.90% (p=0.041 n=6)
RangeQuery/expr=-a_ten,steps=1000-8                                                                                                              312.6µ ±  2%                 308.7µ ±  0%   -1.22% (p=0.002 n=6)
RangeQuery/expr=-a_hundred,steps=1000-8                                                                                                          3.096m ±  0%                 3.058m ±  0%   -1.22% (p=0.002 n=6)
RangeQuery/expr=a_one_-_b_one,steps=1000-8                                                                                                       355.3µ ± 17%                 351.0µ ±  1%        ~ (p=0.065 n=6)
RangeQuery/expr=a_ten_-_b_ten,steps=1000-8                                                                                                       3.390m ±  0%                 3.395m ±  0%        ~ (p=0.485 n=6)
RangeQuery/expr=a_hundred_-_b_hundred,steps=1000-8                                                                                               37.95m ±  0%                 38.05m ±  0%        ~ (p=0.132 n=6)
RangeQuery/expr=a_one_-_b_one,steps=10000-8                                                                                                      3.509m ±  2%                 3.467m ±  0%        ~ (p=0.065 n=6)
RangeQuery/expr=a_ten_-_b_ten,steps=10000-8                                                                                                      34.58m ±  1%                 34.50m ±  1%        ~ (p=0.180 n=6)
RangeQuery/expr=a_hundred_-_b_hundred,steps=10000-8                                                                                              385.0m ±  0%                 386.8m ±  2%        ~ (p=0.132 n=6)
RangeQuery/expr=a_one_and_b_one{l=~'.*[0-4]$'},steps=1000-8                                                                                      124.5µ ±  1%                 125.0µ ±  4%        ~ (p=0.394 n=6)
RangeQuery/expr=a_ten_and_b_ten{l=~'.*[0-4]$'},steps=1000-8                                                                                      1.201m ±  0%                 1.201m ±  0%        ~ (p=0.937 n=6)
RangeQuery/expr=a_hundred_and_b_hundred{l=~'.*[0-4]$'},steps=1000-8                                                                              14.90m ±  5%                 14.91m ±  1%        ~ (p=0.818 n=6)
RangeQuery/expr=a_one_or_b_one{l=~'.*[0-4]$'},steps=1000-8                                                                                       186.2µ ±  0%                 185.3µ ±  0%   -0.46% (p=0.026 n=6)
RangeQuery/expr=a_ten_or_b_ten{l=~'.*[0-4]$'},steps=1000-8                                                                                       1.756m ±  1%                 1.746m ±  0%        ~ (p=0.065 n=6)
RangeQuery/expr=a_hundred_or_b_hundred{l=~'.*[0-4]$'},steps=1000-8                                                                               19.88m ±  0%                 19.96m ±  0%        ~ (p=0.065 n=6)
RangeQuery/expr=a_one_unless_b_one{l=~'.*[0-4]$'},steps=1000-8                                                                                   184.0µ ±  1%                 184.3µ ±  4%        ~ (p=0.818 n=6)
RangeQuery/expr=a_ten_unless_b_ten{l=~'.*[0-4]$'},steps=1000-8                                                                                   1.205m ±  4%                 1.204m ±  5%        ~ (p=0.818 n=6)
RangeQuery/expr=a_hundred_unless_b_hundred{l=~'.*[0-4]$'},steps=1000-8                                                                           14.88m ±  1%                 14.89m ±  2%        ~ (p=0.589 n=6)
RangeQuery/expr=a_one_and_b_one{l='notfound'},steps=1000-8                                                                                       117.2µ ±  1%                 116.3µ ±  1%        ~ (p=0.485 n=6)
RangeQuery/expr=a_ten_and_b_ten{l='notfound'},steps=1000-8                                                                                       448.7µ ±  0%                 451.7µ ±  1%   +0.65% (p=0.026 n=6)
RangeQuery/expr=a_hundred_and_b_hundred{l='notfound'},steps=1000-8                                                                               3.817m ±  1%                 3.893m ±  1%   +1.98% (p=0.002 n=6)
RangeQuery/expr=abs(a_one),steps=1000-8                                                                                                          141.0µ ±  1%                 141.4µ ±  2%        ~ (p=0.394 n=6)
RangeQuery/expr=abs(a_ten),steps=1000-8                                                                                                          1.041m ±  2%                 1.042m ±  2%        ~ (p=0.818 n=6)
RangeQuery/expr=abs(a_hundred),steps=1000-8                                                                                                      10.97m ±  1%                 10.92m ±  0%        ~ (p=0.180 n=6)
RangeQuery/expr=label_replace(a_one,_'l2',_'$1',_'l',_'(.*)'),steps=1000-8                                                                       44.43µ ±  5%                 43.86µ ±  1%   -1.29% (p=0.002 n=6)
RangeQuery/expr=label_replace(a_ten,_'l2',_'$1',_'l',_'(.*)'),steps=1000-8                                                                       316.0µ ±  2%                 314.8µ ±  0%        ~ (p=0.180 n=6)
RangeQuery/expr=label_replace(a_hundred,_'l2',_'$1',_'l',_'(.*)'),steps=1000-8                                                                   3.059m ±  1%                 3.045m ±  3%        ~ (p=0.394 n=6)
RangeQuery/expr=label_join(a_one,_'l2',_'-',_'l',_'l'),steps=1000-8                                                                              41.46µ ±  1%                 41.53µ ±  0%        ~ (p=0.818 n=6)
RangeQuery/expr=label_join(a_ten,_'l2',_'-',_'l',_'l'),steps=1000-8                                                                              312.2µ ±  1%                 311.5µ ±  1%        ~ (p=0.699 n=6)
RangeQuery/expr=label_join(a_hundred,_'l2',_'-',_'l',_'l'),steps=1000-8                                                                          3.036m ±  1%                 3.041m ±  2%        ~ (p=0.394 n=6)
RangeQuery/expr=sum(a_one),steps=1000-8                                                                                                          66.03µ ±  2%                 65.67µ ±  1%        ~ (p=0.190 n=6)
RangeQuery/expr=sum(a_ten),steps=1000-8                                                                                                          369.9µ ±  2%                 363.3µ ±  2%        ~ (p=0.065 n=6)
RangeQuery/expr=sum(a_hundred),steps=1000-8                                                                                                      3.453m ±  1%                 3.428m ±  1%   -0.73% (p=0.004 n=6)
RangeQuery/expr=avg(a_one),steps=1000-8                                                                                                          66.24µ ±  1%                 66.14µ ±  1%        ~ (p=0.818 n=6)
RangeQuery/expr=avg(a_ten),steps=1000-8                                                                                                          372.8µ ±  1%                 367.5µ ±  1%   -1.43% (p=0.009 n=6)
RangeQuery/expr=avg(a_hundred),steps=1000-8                                                                                                      3.502m ±  1%                 3.472m ±  4%        ~ (p=0.589 n=6)
RangeQuery/expr=sum_without_(l)(h_one),steps=1000-8                                                                                              480.3µ ±  1%                 476.0µ ±  0%   -0.90% (p=0.002 n=6)
RangeQuery/expr=sum_without_(l)(h_ten),steps=1000-8                                                                                              3.861m ±  2%                 3.808m ±  2%   -1.38% (p=0.041 n=6)
RangeQuery/expr=sum_without_(l)(h_hundred),steps=1000-8                                                                                          42.52m ±  2%                 42.10m ±  1%   -1.00% (p=0.015 n=6)
RangeQuery/expr=sum_without_(le)(h_one),steps=1000-8                                                                                             403.6µ ± 32%                 401.0µ ±  2%        ~ (p=0.240 n=6)
RangeQuery/expr=sum_without_(le)(h_ten),steps=1000-8                                                                                             3.884m ±  1%                 3.810m ±  1%   -1.90% (p=0.002 n=6)
RangeQuery/expr=sum_without_(le)(h_hundred),steps=1000-8                                                                                         43.63m ±  1%                 43.38m ±  1%        ~ (p=0.093 n=6)
RangeQuery/expr=sum_by_(l)(h_one),steps=1000-8                                                                                                   403.4µ ±  2%                 399.0µ ±  1%   -1.09% (p=0.015 n=6)
RangeQuery/expr=sum_by_(l)(h_ten),steps=1000-8                                                                                                   3.894m ±  2%                 3.817m ±  1%   -1.97% (p=0.002 n=6)
RangeQuery/expr=sum_by_(l)(h_hundred),steps=1000-8                                                                                               43.76m ±  2%                 43.11m ±  1%   -1.48% (p=0.009 n=6)
RangeQuery/expr=sum_by_(le)(h_one),steps=1000-8                                                                                                  479.6µ ±  1%                 476.0µ ±  1%   -0.75% (p=0.041 n=6)
RangeQuery/expr=sum_by_(le)(h_ten),steps=1000-8                                                                                                  3.904m ±  1%                 3.834m ±  1%   -1.81% (p=0.002 n=6)
RangeQuery/expr=sum_by_(le)(h_hundred),steps=1000-8                                                                                              42.98m ±  4%                 42.20m ±  1%   -1.82% (p=0.004 n=6)
RangeQuery/expr=count_values('value',_h_one),steps=100-8                                                                                         928.3µ ±  1%                 925.4µ ±  1%        ~ (p=0.485 n=6)
RangeQuery/expr=count_values('value',_h_ten),steps=100-8                                                                                         10.79m ±  0%                 10.87m ±  1%        ~ (p=0.065 n=6)
RangeQuery/expr=count_values('value',_h_hundred),steps=100-8                                                                                     133.3m ±  3%                 132.3m ±  5%        ~ (p=0.699 n=6)
RangeQuery/expr=topk(1,_a_one),steps=1000-8                                                                                                      277.4µ ±  1%                 284.2µ ±  0%   +2.45% (p=0.002 n=6)
RangeQuery/expr=topk(1,_a_ten),steps=1000-8                                                                                                      671.1µ ±  2%                 672.8µ ±  2%        ~ (p=0.589 n=6)
RangeQuery/expr=topk(1,_a_hundred),steps=1000-8                                                                                                  4.222m ±  2%                 4.267m ±  3%   +1.07% (p=0.026 n=6)
RangeQuery/expr=topk(5,_a_one),steps=1000-8                                                                                                      278.0µ ±  1%                 283.7µ ±  1%   +2.06% (p=0.002 n=6)
RangeQuery/expr=topk(5,_a_ten),steps=1000-8                                                                                                      1.264m ±  1%                 1.268m ±  1%        ~ (p=0.132 n=6)
RangeQuery/expr=topk(5,_a_hundred),steps=1000-8                                                                                                  7.271m ±  1%                 7.321m ±  1%        ~ (p=0.180 n=6)
RangeQuery/expr=limitk(1,_a_one),steps=1000-8                                                                                                    268.4µ ±  1%                 273.8µ ±  1%   +1.98% (p=0.002 n=6)
RangeQuery/expr=limitk(1,_a_ten),steps=1000-8                                                                                                    572.4µ ±  4%                 581.4µ ±  0%        ~ (p=0.065 n=6)
RangeQuery/expr=limitk(1,_a_hundred),steps=1000-8                                                                                                3.345m ±  2%                 3.488m ±  1%   +4.28% (p=0.002 n=6)
RangeQuery/expr=limitk(5,_a_one),steps=1000-8                                                                                                    268.5µ ±  3%                 274.4µ ±  1%   +2.21% (p=0.041 n=6)
RangeQuery/expr=limitk(5,_a_ten),steps=1000-8                                                                                                    967.6µ ±  3%                 985.9µ ±  1%        ~ (p=0.065 n=6)
RangeQuery/expr=limitk(5,_a_hundred),steps=1000-8                                                                                                3.764m ±  2%                 3.877m ±  1%   +3.01% (p=0.002 n=6)
RangeQuery/expr=limit_ratio(0.1,_a_one),steps=1000-8                                                                                             226.2µ ±  1%                 225.0µ ±  2%        ~ (p=0.065 n=6)
RangeQuery/expr=limit_ratio(0.1,_a_ten),steps=1000-8                                                                                             1.233m ±  1%                 1.242m ±  1%        ~ (p=0.093 n=6)
RangeQuery/expr=limit_ratio(0.1,_a_hundred),steps=1000-8                                                                                         9.599m ±  1%                 9.691m ±  1%        ~ (p=0.065 n=6)
RangeQuery/expr=limit_ratio(0.5,_a_one),steps=1000-8                                                                                             227.8µ ±  2%                 224.5µ ±  1%   -1.49% (p=0.015 n=6)
RangeQuery/expr=limit_ratio(0.5,_a_ten),steps=1000-8                                                                                             1.607m ±  8%                 1.649m ±  1%        ~ (p=0.065 n=6)
RangeQuery/expr=limit_ratio(0.5,_a_hundred),steps=1000-8                                                                                         14.19m ±  1%                 14.32m ±  0%   +0.95% (p=0.002 n=6)
RangeQuery/expr=limit_ratio(-0.5,_a_one),steps=1000-8                                                                                            309.1µ ±  0%                 313.2µ ±  0%   +1.33% (p=0.002 n=6)
RangeQuery/expr=limit_ratio(-0.5,_a_ten),steps=1000-8                                                                                            1.597m ±  2%                 1.612m ±  0%        ~ (p=0.310 n=6)
RangeQuery/expr=limit_ratio(-0.5,_a_hundred),steps=1000-8                                                                                        14.35m ±  1%                 14.44m ±  1%        ~ (p=0.132 n=6)
RangeQuery/expr=rate(a_one[1m])_+_rate(b_one[1m]),steps=1000-8                                                                                   445.5µ ±  1%                 437.0µ ±  2%   -1.91% (p=0.004 n=6)
RangeQuery/expr=rate(a_ten[1m])_+_rate(b_ten[1m]),steps=1000-8                                                                                   4.228m ±  2%                 4.123m ±  0%   -2.48% (p=0.002 n=6)
RangeQuery/expr=rate(a_hundred[1m])_+_rate(b_hundred[1m]),steps=1000-8                                                                           45.79m ±  2%                 45.23m ±  1%   -1.23% (p=0.002 n=6)
RangeQuery/expr=sum_without_(l)(rate(a_one[1m])),steps=1000-8                                                                                    117.0µ ± 20%                 115.0µ ±  1%   -1.71% (p=0.002 n=6)
RangeQuery/expr=sum_without_(l)(rate(a_ten[1m])),steps=1000-8                                                                                    880.8µ ±  4%                 848.4µ ±  1%   -3.69% (p=0.009 n=6)
RangeQuery/expr=sum_without_(l)(rate(a_hundred[1m])),steps=1000-8                                                                                8.377m ±  1%                 8.230m ±  1%   -1.76% (p=0.004 n=6)
RangeQuery/expr=sum_without_(l)(rate(a_one[1m]))_/_sum_without_(l)(rate(b_one[1m])),steps=1000-8                                                 517.8µ ± 13%                 501.8µ ±  1%   -3.09% (p=0.015 n=6)
RangeQuery/expr=sum_without_(l)(rate(a_ten[1m]))_/_sum_without_(l)(rate(b_ten[1m])),steps=1000-8                                                 2.009m ±  1%                 1.970m ±  1%   -1.97% (p=0.002 n=6)
RangeQuery/expr=sum_without_(l)(rate(a_hundred[1m]))_/_sum_without_(l)(rate(b_hundred[1m])),steps=1000-8                                         17.15m ±  1%                 16.92m ±  1%        ~ (p=0.065 n=6)
RangeQuery/expr=histogram_quantile(0.9,_rate(h_one[5m])),steps=1000-8                                                                            1.753m ±  1%                 1.727m ±  1%        ~ (p=0.065 n=6)
RangeQuery/expr=histogram_quantile(0.9,_rate(h_ten[5m])),steps=1000-8                                                                            18.89m ±  0%                 18.79m ±  1%   -0.54% (p=0.009 n=6)
RangeQuery/expr=histogram_quantile(0.9,_rate(h_hundred[5m])),steps=1000-8                                                                        201.7m ±  2%                 199.2m ±  1%   -1.25% (p=0.002 n=6)
RangeQuery/expr=a_one_+_on(l)_group_right_a_one,steps=1000-8                                                                                     452.9µ ±  2%                 444.8µ ±  5%        ~ (p=0.180 n=6)
RangeQuery/expr=a_ten_+_on(l)_group_right_a_one,steps=1000-8                                                                                     859.7µ ±  1%                 852.7µ ±  1%   -0.82% (p=0.041 n=6)
RangeQuery/expr=a_hundred_+_on(l)_group_right_a_one,steps=1000-8                                                                                 9.228m ±  1%                 9.181m ±  0%        ~ (p=0.180 n=6)
RangeQuery/expr=count({__name__!=""}),steps=1-8                                                                                                  2.802m ±  1%                 2.910m ±  6%   +3.87% (p=0.002 n=6)
RangeQuery/expr=count({__name__!="",l=""}),steps=1-8                                                                                             108.2µ ±  1%                 108.2µ ±  1%        ~ (p=0.699 n=6)
RangeQuery/expr=timestamp(a_one),steps=1000-8                                                                                                    192.7µ ±  2%                 208.6µ ±  0%   +8.21% (p=0.002 n=6)
RangeQuery/expr=timestamp(a_ten),steps=1000-8                                                                                                    1.096m ±  1%                 1.189m ±  0%   +8.45% (p=0.002 n=6)
RangeQuery/expr=timestamp(a_hundred),steps=1000-8                                                                                                11.10m ±  0%                 12.63m ±  1%  +13.73% (p=0.002 n=6)
geomean                                                                                                                                          2.610m                       2.613m         +0.11%

                                                                                                         │ /Users/neerajgartia/Desktop/dev/cp/before_1000.txt │ /Users/neerajgartia/Desktop/dev/cp/after_1000.txt │
                                                                                                         │                        B/op                        │            B/op              vs base              │
RangeQuery/expr=a_one,steps=1000-8                                                                                                              9.601Ki ±  0%                 9.599Ki ±  0%  -0.02% (p=0.009 n=6)
RangeQuery/expr=a_ten,steps=1000-8                                                                                                              38.66Ki ±  0%                 38.66Ki ±  0%       ~ (p=0.723 n=6)
RangeQuery/expr=a_hundred,steps=1000-8                                                                                                          319.9Ki ±  0%                 319.8Ki ±  0%       ~ (p=0.818 n=6)
RangeQuery/expr=rate(a_one[1m]),steps=1000-8                                                                                                    11.91Ki ±  0%                 11.92Ki ±  0%       ~ (p=0.959 n=6)
RangeQuery/expr=rate(a_ten[1m]),steps=1000-8                                                                                                    40.42Ki ±  0%                 40.42Ki ±  0%       ~ (p=0.851 n=6)
RangeQuery/expr=rate(a_hundred[1m]),steps=1000-8                                                                                                316.9Ki ±  0%                 316.9Ki ±  0%       ~ (p=0.937 n=6)
RangeQuery/expr=rate(a_one[1m]),steps=10000-8                                                                                                   53.59Ki ±  1%                 53.43Ki ±  2%       ~ (p=0.513 n=6)
RangeQuery/expr=rate(a_ten[1m]),steps=10000-8                                                                                                   297.3Ki ±  1%                 297.3Ki ±  0%       ~ (p=0.056 n=6)
RangeQuery/expr=rate(a_hundred[1m]),steps=10000-8                                                                                               2.602Mi ±  1%                 2.603Mi ±  1%       ~ (p=0.699 n=6)
RangeQuery/expr=rate(sparse[1m]),steps=10000-8                                                                                                  44.54Ki ±  2%                 44.54Ki ±  2%       ~ (p=0.937 n=6)
RangeQuery/expr=double_exponential_smoothing(a_one[1d],_0.3,_0.3),steps=1000-8                                                                  1.044Mi ±  0%                 1.044Mi ±  2%  +0.02% (p=0.015 n=6)
RangeQuery/expr=double_exponential_smoothing(a_ten[1d],_0.3,_0.3),steps=1000-8                                                                  1.239Mi ±  1%                 1.239Mi ±  1%       ~ (p=0.515 n=6)
RangeQuery/expr=double_exponential_smoothing(a_hundred[1d],_0.3,_0.3),steps=1000-8                                                              3.365Mi ± 42%                 3.368Mi ± 42%       ~ (p=0.485 n=6)
RangeQuery/expr=changes(a_one[1d]),steps=1000-8                                                                                                 562.8Ki ±  1%                 566.5Ki ±  2%       ~ (p=0.790 n=6)
RangeQuery/expr=changes(a_ten[1d]),steps=1000-8                                                                                                 857.1Ki ±  9%                 856.6Ki ±  9%       ~ (p=0.331 n=6)
RangeQuery/expr=changes(a_hundred[1d]),steps=1000-8                                                                                             3.331Mi ± 42%                 3.333Mi ± 42%       ~ (p=0.818 n=6)
RangeQuery/expr=rate(a_one[1d]),steps=1000-8                                                                                                    558.0Ki ±  1%                 564.6Ki ±  1%       ~ (p=0.065 n=6)
RangeQuery/expr=rate(a_ten[1d]),steps=1000-8                                                                                                    804.5Ki ±  0%                 804.5Ki ±  3%       ~ (p=1.000 n=6)
RangeQuery/expr=rate(a_hundred[1d]),steps=1000-8                                                                                                3.125Mi ±  7%                 3.123Mi ±  0%       ~ (p=0.589 n=6)
RangeQuery/expr=absent_over_time(a_one[1d]),steps=1000-8                                                                                        572.8Ki ±  1%                 579.1Ki ±  1%  +1.10% (p=0.004 n=6)
RangeQuery/expr=absent_over_time(a_ten[1d]),steps=1000-8                                                                                        950.0Ki ±  1%                 955.7Ki ±  1%       ~ (p=0.102 n=6)
RangeQuery/expr=absent_over_time(a_hundred[1d]),steps=1000-8                                                                                    4.556Mi ±  3%                 4.556Mi ±  0%       ~ (p=0.797 n=6)
RangeQuery/expr=-a_one,steps=1000-8                                                                                                             10.23Ki ±  0%                 10.23Ki ±  0%       ~ (p=0.777 n=6)
RangeQuery/expr=-a_ten,steps=1000-8                                                                                                             39.46Ki ±  0%                 39.45Ki ±  0%  -0.04% (p=0.030 n=6)
RangeQuery/expr=-a_hundred,steps=1000-8                                                                                                         322.0Ki ±  0%                 321.9Ki ±  0%       ~ (p=0.937 n=6)
RangeQuery/expr=a_one_-_b_one,steps=1000-8                                                                                                      67.30Ki ±  0%                 67.31Ki ±  0%       ~ (p=0.558 n=6)
RangeQuery/expr=a_ten_-_b_ten,steps=1000-8                                                                                                      152.4Ki ±  0%                 152.6Ki ±  0%       ~ (p=1.000 n=6)
RangeQuery/expr=a_hundred_-_b_hundred,steps=1000-8                                                                                              1.932Mi ±  0%                 1.933Mi ±  0%       ~ (p=0.699 n=6)
RangeQuery/expr=a_one_-_b_one,steps=10000-8                                                                                                     572.9Ki ±  0%                 572.0Ki ±  0%       ~ (p=0.240 n=6)
RangeQuery/expr=a_ten_-_b_ten,steps=10000-8                                                                                                     1.221Mi ±  1%                 1.220Mi ±  1%       ~ (p=0.699 n=6)
RangeQuery/expr=a_hundred_-_b_hundred,steps=10000-8                                                                                             17.28Mi ±  0%                 17.31Mi ±  1%       ~ (p=0.310 n=6)
RangeQuery/expr=a_one_and_b_one{l=~'.*[0-4]$'},steps=1000-8                                                                                     72.06Ki ±  0%                 72.06Ki ±  0%       ~ (p=0.264 n=6)
RangeQuery/expr=a_ten_and_b_ten{l=~'.*[0-4]$'},steps=1000-8                                                                                     124.0Ki ±  0%                 124.0Ki ±  0%       ~ (p=0.788 n=6)
RangeQuery/expr=a_hundred_and_b_hundred{l=~'.*[0-4]$'},steps=1000-8                                                                             3.011Mi ±  0%                 3.011Mi ±  0%       ~ (p=0.065 n=6)
RangeQuery/expr=a_one_or_b_one{l=~'.*[0-4]$'},steps=1000-8                                                                                      72.14Ki ±  0%                 72.14Ki ±  0%       ~ (p=0.905 n=6)
RangeQuery/expr=a_ten_or_b_ten{l=~'.*[0-4]$'},steps=1000-8                                                                                      409.3Ki ±  0%                 409.3Ki ±  0%       ~ (p=0.368 n=6)
RangeQuery/expr=a_hundred_or_b_hundred{l=~'.*[0-4]$'},steps=1000-8                                                                              5.764Mi ±  0%                 5.764Mi ±  0%       ~ (p=0.589 n=6)
RangeQuery/expr=a_one_unless_b_one{l=~'.*[0-4]$'},steps=1000-8                                                                                  72.15Ki ±  0%                 72.16Ki ±  0%       ~ (p=0.102 n=6)
RangeQuery/expr=a_ten_unless_b_ten{l=~'.*[0-4]$'},steps=1000-8                                                                                  124.0Ki ±  0%                 124.0Ki ±  0%       ~ (p=0.623 n=6)
RangeQuery/expr=a_hundred_unless_b_hundred{l=~'.*[0-4]$'},steps=1000-8                                                                          3.011Mi ±  0%                 3.010Mi ±  0%       ~ (p=0.180 n=6)
RangeQuery/expr=a_one_and_b_one{l='notfound'},steps=1000-8                                                                                      60.75Ki ±  0%                 60.75Ki ±  0%       ~ (p=0.288 n=6)
RangeQuery/expr=a_ten_and_b_ten{l='notfound'},steps=1000-8                                                                                      93.68Ki ±  0%                 93.68Ki ±  0%       ~ (p=0.143 n=6)
RangeQuery/expr=a_hundred_and_b_hundred{l='notfound'},steps=1000-8                                                                              407.9Ki ±  0%                 408.0Ki ±  0%       ~ (p=0.240 n=6)
RangeQuery/expr=abs(a_one),steps=1000-8                                                                                                         34.35Ki ±  0%                 34.35Ki ±  0%       ~ (p=0.281 n=6)
RangeQuery/expr=abs(a_ten),steps=1000-8                                                                                                         67.79Ki ±  0%                 67.77Ki ±  0%       ~ (p=0.104 n=6)
RangeQuery/expr=abs(a_hundred),steps=1000-8                                                                                                     387.6Ki ±  0%                 387.5Ki ±  0%       ~ (p=0.937 n=6)
RangeQuery/expr=label_replace(a_one,_'l2',_'$1',_'l',_'(.*)'),steps=1000-8                                                                      16.28Ki ±  0%                 16.29Ki ±  0%       ~ (p=0.260 n=6)
RangeQuery/expr=label_replace(a_ten,_'l2',_'$1',_'l',_'(.*)'),steps=1000-8                                                                      46.77Ki ±  0%                 46.77Ki ±  0%       ~ (p=0.768 n=6)
RangeQuery/expr=label_replace(a_hundred,_'l2',_'$1',_'l',_'(.*)'),steps=1000-8                                                                  342.0Ki ±  0%                 342.0Ki ±  0%       ~ (p=0.818 n=6)
RangeQuery/expr=label_join(a_one,_'l2',_'-',_'l',_'l'),steps=1000-8                                                                             13.51Ki ±  0%                 13.51Ki ±  0%       ~ (p=0.810 n=6)
RangeQuery/expr=label_join(a_ten,_'l2',_'-',_'l',_'l'),steps=1000-8                                                                             43.69Ki ±  0%                 43.68Ki ±  0%       ~ (p=0.511 n=6)
RangeQuery/expr=label_join(a_hundred,_'l2',_'-',_'l',_'l'),steps=1000-8                                                                         335.3Ki ±  0%                 335.3Ki ±  0%       ~ (p=0.084 n=6)
RangeQuery/expr=sum(a_one),steps=1000-8                                                                                                         10.90Ki ±  0%                 10.90Ki ±  0%       ~ (p=0.301 n=6)
RangeQuery/expr=sum(a_ten),steps=1000-8                                                                                                         40.83Ki ±  0%                 40.83Ki ±  0%       ~ (p=0.848 n=6)
RangeQuery/expr=sum(a_hundred),steps=1000-8                                                                                                     329.8Ki ±  0%                 329.8Ki ±  0%       ~ (p=0.485 n=6)
RangeQuery/expr=avg(a_one),steps=1000-8                                                                                                         10.90Ki ±  0%                 10.90Ki ±  0%       ~ (p=0.351 n=6)
RangeQuery/expr=avg(a_ten),steps=1000-8                                                                                                         40.83Ki ±  0%                 40.83Ki ±  0%       ~ (p=0.474 n=6)
RangeQuery/expr=avg(a_hundred),steps=1000-8                                                                                                     329.7Ki ±  0%                 329.7Ki ±  0%       ~ (p=0.732 n=6)
RangeQuery/expr=sum_without_(l)(h_one),steps=1000-8                                                                                             48.06Ki ±  0%                 48.06Ki ±  0%       ~ (p=0.788 n=6)
RangeQuery/expr=sum_without_(l)(h_ten),steps=1000-8                                                                                             378.2Ki ±  0%                 378.1Ki ±  0%       ~ (p=0.065 n=6)
RangeQuery/expr=sum_without_(l)(h_hundred),steps=1000-8                                                                                         3.524Mi ±  0%                 3.526Mi ±  0%       ~ (p=0.818 n=6)
RangeQuery/expr=sum_without_(le)(h_one),steps=1000-8                                                                                            44.13Ki ±  0%                 44.12Ki ±  0%       ~ (p=0.223 n=6)
RangeQuery/expr=sum_without_(le)(h_ten),steps=1000-8                                                                                            377.9Ki ±  0%                 377.9Ki ±  0%       ~ (p=0.699 n=6)
RangeQuery/expr=sum_without_(le)(h_hundred),steps=1000-8                                                                                        3.566Mi ±  0%                 3.561Mi ±  0%  -0.15% (p=0.041 n=6)
RangeQuery/expr=sum_by_(l)(h_one),steps=1000-8                                                                                                  44.07Ki ±  0%                 44.07Ki ±  0%       ~ (p=0.682 n=6)
RangeQuery/expr=sum_by_(l)(h_ten),steps=1000-8                                                                                                  377.9Ki ±  0%                 377.9Ki ±  0%       ~ (p=0.738 n=6)
RangeQuery/expr=sum_by_(l)(h_hundred),steps=1000-8                                                                                              3.564Mi ±  0%                 3.560Mi ±  0%       ~ (p=0.394 n=6)
RangeQuery/expr=sum_by_(le)(h_one),steps=1000-8                                                                                                 48.03Ki ±  0%                 48.03Ki ±  0%       ~ (p=0.177 n=6)
RangeQuery/expr=sum_by_(le)(h_ten),steps=1000-8                                                                                                 378.0Ki ±  0%                 378.0Ki ±  0%       ~ (p=1.000 n=6)
RangeQuery/expr=sum_by_(le)(h_hundred),steps=1000-8                                                                                             3.522Mi ±  0%                 3.523Mi ±  0%       ~ (p=0.818 n=6)
RangeQuery/expr=count_values('value',_h_one),steps=100-8                                                                                        831.2Ki ±  0%                 831.1Ki ±  0%       ~ (p=0.937 n=6)
RangeQuery/expr=count_values('value',_h_ten),steps=100-8                                                                                        8.308Mi ±  1%                 8.301Mi ±  0%       ~ (p=0.310 n=6)
RangeQuery/expr=count_values('value',_h_hundred),steps=100-8                                                                                    103.1Mi ±  0%                 103.1Mi ±  0%       ~ (p=0.937 n=6)
RangeQuery/expr=topk(1,_a_one),steps=1000-8                                                                                                     231.0Ki ±  0%                 231.0Ki ±  0%       ~ (p=0.714 n=6)
RangeQuery/expr=topk(1,_a_ten),steps=1000-8                                                                                                     262.5Ki ±  0%                 262.5Ki ±  0%       ~ (p=0.699 n=6)
RangeQuery/expr=topk(1,_a_hundred),steps=1000-8                                                                                                 562.0Ki ±  0%                 562.0Ki ±  0%       ~ (p=0.589 n=6)
RangeQuery/expr=topk(5,_a_one),steps=1000-8                                                                                                     231.1Ki ±  0%                 231.0Ki ±  0%       ~ (p=0.584 n=6)
RangeQuery/expr=topk(5,_a_ten),steps=1000-8                                                                                                     521.0Ki ±  0%                 521.0Ki ±  0%       ~ (p=0.485 n=6)
RangeQuery/expr=topk(5,_a_hundred),steps=1000-8                                                                                                 820.7Ki ±  0%                 820.7Ki ±  0%       ~ (p=1.000 n=6)
RangeQuery/expr=limitk(1,_a_one),steps=1000-8                                                                                                   231.1Ki ±  0%                 231.1Ki ±  0%       ~ (p=0.900 n=6)
RangeQuery/expr=limitk(1,_a_ten),steps=1000-8                                                                                                   262.5Ki ±  0%                 262.4Ki ±  0%  -0.01% (p=0.004 n=6)
RangeQuery/expr=limitk(1,_a_hundred),steps=1000-8                                                                                               562.1Ki ±  0%                 562.1Ki ±  0%       ~ (p=0.589 n=6)
RangeQuery/expr=limitk(5,_a_one),steps=1000-8                                                                                                   231.1Ki ±  0%                 231.1Ki ±  0%       ~ (p=0.859 n=6)
RangeQuery/expr=limitk(5,_a_ten),steps=1000-8                                                                                                   481.9Ki ±  0%                 481.9Ki ±  0%       ~ (p=0.071 n=6)
RangeQuery/expr=limitk(5,_a_hundred),steps=1000-8                                                                                               781.6Ki ±  0%                 781.4Ki ±  0%  -0.02% (p=0.041 n=6)
RangeQuery/expr=limit_ratio(0.1,_a_one),steps=1000-8                                                                                            168.5Ki ±  0%                 168.5Ki ±  0%       ~ (p=1.000 n=6)
RangeQuery/expr=limit_ratio(0.1,_a_ten),steps=1000-8                                                                                            372.2Ki ±  0%                 372.2Ki ±  0%       ~ (p=0.667 n=6)
RangeQuery/expr=limit_ratio(0.1,_a_hundred),steps=1000-8                                                                                        2.277Mi ±  0%                 2.277Mi ±  0%  -0.01% (p=0.026 n=6)
RangeQuery/expr=limit_ratio(0.5,_a_one),steps=1000-8                                                                                            168.5Ki ±  0%                 168.5Ki ±  0%       ~ (p=0.818 n=6)
RangeQuery/expr=limit_ratio(0.5,_a_ten),steps=1000-8                                                                                            1.006Mi ±  0%                 1.006Mi ±  0%       ~ (p=0.853 n=6)
RangeQuery/expr=limit_ratio(0.5,_a_hundred),steps=1000-8                                                                                        8.154Mi ±  0%                 8.153Mi ±  0%       ~ (p=0.310 n=6)
RangeQuery/expr=limit_ratio(-0.5,_a_one),steps=1000-8                                                                                           231.1Ki ±  0%                 231.1Ki ±  0%       ~ (p=0.236 n=6)
RangeQuery/expr=limit_ratio(-0.5,_a_ten),steps=1000-8                                                                                           1.006Mi ±  0%                 1.006Mi ±  0%  -0.01% (p=0.009 n=6)
RangeQuery/expr=limit_ratio(-0.5,_a_hundred),steps=1000-8                                                                                       8.154Mi ±  0%                 8.154Mi ±  0%       ~ (p=0.310 n=6)
RangeQuery/expr=rate(a_one[1m])_+_rate(b_one[1m]),steps=1000-8                                                                                  72.03Ki ±  0%                 72.03Ki ±  0%       ~ (p=0.775 n=6)
RangeQuery/expr=rate(a_ten[1m])_+_rate(b_ten[1m]),steps=1000-8                                                                                  155.7Ki ±  0%                 155.8Ki ±  0%       ~ (p=0.699 n=6)
RangeQuery/expr=rate(a_hundred[1m])_+_rate(b_hundred[1m]),steps=1000-8                                                                          1.922Mi ±  0%                 1.922Mi ±  0%       ~ (p=0.937 n=6)
RangeQuery/expr=sum_without_(l)(rate(a_one[1m])),steps=1000-8                                                                                   13.68Ki ±  0%                 13.69Ki ±  0%       ~ (p=0.851 n=6)
RangeQuery/expr=sum_without_(l)(rate(a_ten[1m])),steps=1000-8                                                                                   43.08Ki ±  0%                 43.07Ki ±  0%       ~ (p=0.123 n=6)
RangeQuery/expr=sum_without_(l)(rate(a_hundred[1m])),steps=1000-8                                                                               327.4Ki ±  0%                 327.3Ki ±  0%       ~ (p=0.240 n=6)
RangeQuery/expr=sum_without_(l)(rate(a_one[1m]))_/_sum_without_(l)(rate(b_one[1m])),steps=1000-8                                                76.60Ki ±  0%                 76.60Ki ±  0%       ~ (p=0.173 n=6)
RangeQuery/expr=sum_without_(l)(rate(a_ten[1m]))_/_sum_without_(l)(rate(b_ten[1m])),steps=1000-8                                                135.4Ki ±  0%                 135.4Ki ±  0%       ~ (p=0.457 n=6)
RangeQuery/expr=sum_without_(l)(rate(a_hundred[1m]))_/_sum_without_(l)(rate(b_hundred[1m])),steps=1000-8                                        704.1Ki ±  0%                 703.8Ki ±  0%       ~ (p=0.223 n=6)
RangeQuery/expr=histogram_quantile(0.9,_rate(h_one[5m])),steps=1000-8                                                                           102.3Ki ±  0%                 102.3Ki ±  0%       ~ (p=0.310 n=6)
RangeQuery/expr=histogram_quantile(0.9,_rate(h_ten[5m])),steps=1000-8                                                                           499.9Ki ±  0%                 499.9Ki ±  0%       ~ (p=1.000 n=6)
RangeQuery/expr=histogram_quantile(0.9,_rate(h_hundred[5m])),steps=1000-8                                                                       4.241Mi ±  1%                 4.257Mi ±  1%       ~ (p=0.394 n=6)
RangeQuery/expr=a_one_+_on(l)_group_right_a_one,steps=1000-8                                                                                    192.8Ki ±  0%                 192.8Ki ±  0%  +0.02% (p=0.013 n=6)
RangeQuery/expr=a_ten_+_on(l)_group_right_a_one,steps=1000-8                                                                                    114.5Ki ±  0%                 114.5Ki ±  0%       ~ (p=0.331 n=6)
RangeQuery/expr=a_hundred_+_on(l)_group_right_a_one,steps=1000-8                                                                                1.518Mi ±  0%                 1.520Mi ±  0%       ~ (p=0.310 n=6)
RangeQuery/expr=count({__name__!=""}),steps=1-8                                                                                                 858.6Ki ±  0%                 859.2Ki ±  0%       ~ (p=0.132 n=6)
RangeQuery/expr=count({__name__!="",l=""}),steps=1-8                                                                                            24.28Ki ±  0%                 24.28Ki ±  0%       ~ (p=0.372 n=6)
RangeQuery/expr=timestamp(a_one),steps=1000-8                                                                                                   112.0Ki ±  0%                 112.0Ki ±  0%       ~ (p=0.180 n=6)
RangeQuery/expr=timestamp(a_ten),steps=1000-8                                                                                                   649.2Ki ±  0%                 649.2Ki ±  0%       ~ (p=0.461 n=6)
RangeQuery/expr=timestamp(a_hundred),steps=1000-8                                                                                               6.305Mi ±  0%                 6.304Mi ±  0%       ~ (p=0.310 n=6)
geomean                                                                                                                                         316.6Ki                       316.7Ki        +0.03%

                                                                                                         │ /Users/neerajgartia/Desktop/dev/cp/before_1000.txt │ /Users/neerajgartia/Desktop/dev/cp/after_1000.txt │
                                                                                                         │                     allocs/op                      │         allocs/op          vs base                │
RangeQuery/expr=a_one,steps=1000-8                                                                                                                 144.0 ± 0%                  144.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=a_ten,steps=1000-8                                                                                                                 463.0 ± 0%                  463.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=a_hundred,steps=1000-8                                                                                                            3.544k ± 0%                 3.544k ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=rate(a_one[1m]),steps=1000-8                                                                                                       194.0 ± 0%                  194.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=rate(a_ten[1m]),steps=1000-8                                                                                                       523.0 ± 0%                  523.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=rate(a_hundred[1m]),steps=1000-8                                                                                                  3.709k ± 0%                 3.709k ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=rate(a_one[1m]),steps=10000-8                                                                                                      486.0 ± 0%                  486.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=rate(a_ten[1m]),steps=10000-8                                                                                                     3.012k ± 0%                 3.012k ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=rate(a_hundred[1m]),steps=10000-8                                                                                                 27.65k ± 0%                 27.65k ± 0%       ~ (p=0.970 n=6)
RangeQuery/expr=rate(sparse[1m]),steps=10000-8                                                                                                     673.0 ± 0%                  673.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=double_exponential_smoothing(a_one[1d],_0.3,_0.3),steps=1000-8                                                                     512.0 ± 0%                  512.0 ± 0%       ~ (p=0.545 n=6)
RangeQuery/expr=double_exponential_smoothing(a_ten[1d],_0.3,_0.3),steps=1000-8                                                                    2.782k ± 0%                 2.782k ± 0%       ~ (p=0.515 n=6)
RangeQuery/expr=double_exponential_smoothing(a_hundred[1d],_0.3,_0.3),steps=1000-8                                                                24.75k ± 1%                 24.75k ± 1%       ~ (p=0.981 n=6)
RangeQuery/expr=changes(a_one[1d]),steps=1000-8                                                                                                    420.0 ± 0%                  420.0 ± 0%       ~ (p=1.000 n=6)
RangeQuery/expr=changes(a_ten[1d]),steps=1000-8                                                                                                   2.691k ± 0%                 2.689k ± 0%       ~ (p=0.210 n=6)
RangeQuery/expr=changes(a_hundred[1d]),steps=1000-8                                                                                               24.68k ± 1%                 24.68k ± 1%       ~ (p=0.818 n=6)
RangeQuery/expr=rate(a_one[1d]),steps=1000-8                                                                                                       426.0 ± 0%                  426.0 ± 0%       ~ (p=0.455 n=6)
RangeQuery/expr=rate(a_ten[1d]),steps=1000-8                                                                                                      2.728k ± 0%                 2.728k ± 0%       ~ (p=0.316 n=6)
RangeQuery/expr=rate(a_hundred[1d]),steps=1000-8                                                                                                  25.07k ± 0%                 25.07k ± 0%       ~ (p=0.318 n=6)
RangeQuery/expr=absent_over_time(a_one[1d]),steps=1000-8                                                                                           421.0 ± 0%                  421.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=absent_over_time(a_ten[1d]),steps=1000-8                                                                                          2.694k ± 0%                 2.694k ± 0%       ~ (p=1.000 n=6)
RangeQuery/expr=absent_over_time(a_hundred[1d]),steps=1000-8                                                                                      24.74k ± 0%                 24.74k ± 0%       ~ (p=0.331 n=6)
RangeQuery/expr=-a_one,steps=1000-8                                                                                                                163.0 ± 0%                  163.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=-a_ten,steps=1000-8                                                                                                                483.0 ± 0%                  483.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=-a_hundred,steps=1000-8                                                                                                           3.571k ± 0%                 3.571k ± 0%       ~ (p=1.000 n=6)
RangeQuery/expr=a_one_-_b_one,steps=1000-8                                                                                                        2.276k ± 0%                 2.276k ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=a_ten_-_b_ten,steps=1000-8                                                                                                        2.998k ± 0%                 2.998k ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=a_hundred_-_b_hundred,steps=1000-8                                                                                                11.58k ± 0%                 11.58k ± 0%       ~ (p=0.926 n=6)
RangeQuery/expr=a_one_-_b_one,steps=10000-8                                                                                                       20.84k ± 0%                 20.84k ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=a_ten_-_b_ten,steps=10000-8                                                                                                       26.29k ± 0%                 26.29k ± 0%       ~ (p=0.939 n=6)
RangeQuery/expr=a_hundred_-_b_hundred,steps=10000-8                                                                                               95.53k ± 0%                 95.56k ± 0%       ~ (p=0.089 n=6)
RangeQuery/expr=a_one_and_b_one{l=~'.*[0-4]$'},steps=1000-8                                                                                       2.304k ± 0%                 2.304k ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=a_ten_and_b_ten{l=~'.*[0-4]$'},steps=1000-8                                                                                       2.833k ± 0%                 2.833k ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=a_hundred_and_b_hundred{l=~'.*[0-4]$'},steps=1000-8                                                                               12.96k ± 0%                 12.96k ± 0%       ~ (p=0.504 n=6)
RangeQuery/expr=a_one_or_b_one{l=~'.*[0-4]$'},steps=1000-8                                                                                        2.305k ± 0%                 2.305k ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=a_ten_or_b_ten{l=~'.*[0-4]$'},steps=1000-8                                                                                        3.856k ± 0%                 3.856k ± 0%       ~ (p=1.000 n=6)
RangeQuery/expr=a_hundred_or_b_hundred{l=~'.*[0-4]$'},steps=1000-8                                                                                16.10k ± 0%                 16.10k ± 0%       ~ (p=0.420 n=6)
RangeQuery/expr=a_one_unless_b_one{l=~'.*[0-4]$'},steps=1000-8                                                                                    2.305k ± 0%                 2.305k ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=a_ten_unless_b_ten{l=~'.*[0-4]$'},steps=1000-8                                                                                    2.833k ± 0%                 2.833k ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=a_hundred_unless_b_hundred{l=~'.*[0-4]$'},steps=1000-8                                                                            12.96k ± 0%                 12.96k ± 0%       ~ (p=0.366 n=6)
RangeQuery/expr=a_one_and_b_one{l='notfound'},steps=1000-8                                                                                        2.224k ± 0%                 2.224k ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=a_ten_and_b_ten{l='notfound'},steps=1000-8                                                                                        2.554k ± 0%                 2.554k ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=a_hundred_and_b_hundred{l='notfound'},steps=1000-8                                                                                5.726k ± 0%                 5.727k ± 0%       ~ (p=1.000 n=6)
RangeQuery/expr=abs(a_one),steps=1000-8                                                                                                           1.180k ± 0%                 1.180k ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=abs(a_ten),steps=1000-8                                                                                                           1.500k ± 0%                 1.500k ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=abs(a_hundred),steps=1000-8                                                                                                       4.585k ± 0%                 4.584k ± 0%       ~ (p=0.242 n=6)
RangeQuery/expr=label_replace(a_one,_'l2',_'$1',_'l',_'(.*)'),steps=1000-8                                                                         296.0 ± 0%                  296.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=label_replace(a_ten,_'l2',_'$1',_'l',_'(.*)'),steps=1000-8                                                                         644.0 ± 0%                  644.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=label_replace(a_hundred,_'l2',_'$1',_'l',_'(.*)'),steps=1000-8                                                                    4.092k ± 0%                 4.092k ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=label_join(a_one,_'l2',_'-',_'l',_'l'),steps=1000-8                                                                                255.0 ± 0%                  255.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=label_join(a_ten,_'l2',_'-',_'l',_'l'),steps=1000-8                                                                                593.0 ± 0%                  593.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=label_join(a_hundred,_'l2',_'-',_'l',_'l'),steps=1000-8                                                                           3.861k ± 0%                 3.861k ± 0%       ~ (p=1.000 n=6)
RangeQuery/expr=sum(a_one),steps=1000-8                                                                                                            173.0 ± 0%                  173.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=sum(a_ten),steps=1000-8                                                                                                            492.0 ± 0%                  492.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=sum(a_hundred),steps=1000-8                                                                                                       3.573k ± 0%                 3.573k ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=avg(a_one),steps=1000-8                                                                                                            173.0 ± 0%                  173.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=avg(a_ten),steps=1000-8                                                                                                            492.0 ± 0%                  492.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=avg(a_hundred),steps=1000-8                                                                                                       3.573k ± 0%                 3.573k ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=sum_without_(l)(h_one),steps=1000-8                                                                                                550.0 ± 0%                  550.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=sum_without_(l)(h_ten),steps=1000-8                                                                                               4.019k ± 0%                 4.019k ± 0%       ~ (p=1.000 n=6)
RangeQuery/expr=sum_without_(l)(h_hundred),steps=1000-8                                                                                           37.82k ± 0%                 37.82k ± 0%       ~ (p=0.688 n=6)
RangeQuery/expr=sum_without_(le)(h_one),steps=1000-8                                                                                               537.0 ± 0%                  537.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=sum_without_(le)(h_ten),steps=1000-8                                                                                              4.019k ± 0%                 4.019k ± 0%       ~ (p=0.545 n=6)
RangeQuery/expr=sum_without_(le)(h_hundred),steps=1000-8                                                                                          37.93k ± 0%                 37.93k ± 0%       ~ (p=0.052 n=6)
RangeQuery/expr=sum_by_(l)(h_one),steps=1000-8                                                                                                     535.0 ± 0%                  535.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=sum_by_(l)(h_ten),steps=1000-8                                                                                                    4.018k ± 0%                 4.018k ± 0%       ~ (p=1.000 n=6)
RangeQuery/expr=sum_by_(l)(h_hundred),steps=1000-8                                                                                                37.92k ± 0%                 37.92k ± 0%       ~ (p=0.390 n=6)
RangeQuery/expr=sum_by_(le)(h_one),steps=1000-8                                                                                                    552.0 ± 0%                  552.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=sum_by_(le)(h_ten),steps=1000-8                                                                                                   4.021k ± 0%                 4.021k ± 0%       ~ (p=1.000 n=6)
RangeQuery/expr=sum_by_(le)(h_hundred),steps=1000-8                                                                                               37.82k ± 0%                 37.82k ± 0%       ~ (p=0.619 n=6)
RangeQuery/expr=count_values('value',_h_one),steps=100-8                                                                                          6.366k ± 0%                 6.367k ± 0%       ~ (p=0.545 n=6)
RangeQuery/expr=count_values('value',_h_ten),steps=100-8                                                                                          58.54k ± 0%                 58.54k ± 0%       ~ (p=0.628 n=6)
RangeQuery/expr=count_values('value',_h_hundred),steps=100-8                                                                                      575.1k ± 0%                 575.1k ± 0%       ~ (p=0.721 n=6)
RangeQuery/expr=topk(1,_a_one),steps=1000-8                                                                                                       3.193k ± 0%                 3.193k ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=topk(1,_a_ten),steps=1000-8                                                                                                       3.513k ± 0%                 3.513k ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=topk(1,_a_hundred),steps=1000-8                                                                                                   6.596k ± 0%                 6.596k ± 0%       ~ (p=1.000 n=6)
RangeQuery/expr=topk(5,_a_one),steps=1000-8                                                                                                       3.193k ± 0%                 3.193k ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=topk(5,_a_ten),steps=1000-8                                                                                                       5.515k ± 0%                 5.515k ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=topk(5,_a_hundred),steps=1000-8                                                                                                   8.598k ± 0%                 8.598k ± 0%       ~ (p=1.000 n=6)
RangeQuery/expr=limitk(1,_a_one),steps=1000-8                                                                                                     3.193k ± 0%                 3.193k ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=limitk(1,_a_ten),steps=1000-8                                                                                                     3.513k ± 0%                 3.513k ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=limitk(1,_a_hundred),steps=1000-8                                                                                                 6.596k ± 0%                 6.596k ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=limitk(5,_a_one),steps=1000-8                                                                                                     3.193k ± 0%                 3.193k ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=limitk(5,_a_ten),steps=1000-8                                                                                                     3.513k ± 0%                 3.513k ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=limitk(5,_a_hundred),steps=1000-8                                                                                                 6.596k ± 0%                 6.596k ± 0%       ~ (p=0.455 n=6)
RangeQuery/expr=limit_ratio(0.1,_a_one),steps=1000-8                                                                                              2.195k ± 0%                 2.195k ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=limit_ratio(0.1,_a_ten),steps=1000-8                                                                                              4.518k ± 0%                 4.518k ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=limit_ratio(0.1,_a_hundred),steps=1000-8                                                                                          10.61k ± 0%                 10.61k ± 0%       ~ (p=0.152 n=6)
RangeQuery/expr=limit_ratio(0.5,_a_one),steps=1000-8                                                                                              2.195k ± 0%                 2.195k ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=limit_ratio(0.5,_a_ten),steps=1000-8                                                                                              6.521k ± 0%                 6.521k ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=limit_ratio(0.5,_a_hundred),steps=1000-8                                                                                          12.62k ± 0%                 12.62k ± 0%       ~ (p=0.294 n=6)
RangeQuery/expr=limit_ratio(-0.5,_a_one),steps=1000-8                                                                                             3.197k ± 0%                 3.197k ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=limit_ratio(-0.5,_a_ten),steps=1000-8                                                                                             6.521k ± 0%                 6.521k ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=limit_ratio(-0.5,_a_hundred),steps=1000-8                                                                                         12.62k ± 0%                 12.62k ± 0%       ~ (p=0.061 n=6)
RangeQuery/expr=rate(a_one[1m])_+_rate(b_one[1m]),steps=1000-8                                                                                    2.370k ± 0%                 2.370k ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=rate(a_ten[1m])_+_rate(b_ten[1m]),steps=1000-8                                                                                    3.112k ± 0%                 3.112k ± 0%       ~ (p=0.455 n=6)
RangeQuery/expr=rate(a_hundred[1m])_+_rate(b_hundred[1m]),steps=1000-8                                                                            11.90k ± 0%                 11.90k ± 0%       ~ (p=0.227 n=6)
RangeQuery/expr=sum_without_(l)(rate(a_one[1m])),steps=1000-8                                                                                      229.0 ± 0%                  229.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=sum_without_(l)(rate(a_ten[1m])),steps=1000-8                                                                                      558.0 ± 0%                  558.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=sum_without_(l)(rate(a_hundred[1m])),steps=1000-8                                                                                 3.744k ± 0%                 3.744k ± 0%       ~ (p=0.545 n=6)
RangeQuery/expr=sum_without_(l)(rate(a_one[1m]))_/_sum_without_(l)(rate(b_one[1m])),steps=1000-8                                                  2.448k ± 0%                 2.448k ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=sum_without_(l)(rate(a_ten[1m]))_/_sum_without_(l)(rate(b_ten[1m])),steps=1000-8                                                  3.106k ± 0%                 3.106k ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=sum_without_(l)(rate(a_hundred[1m]))_/_sum_without_(l)(rate(b_hundred[1m])),steps=1000-8                                          9.479k ± 0%                 9.479k ± 0%       ~ (p=1.000 n=6)
RangeQuery/expr=histogram_quantile(0.9,_rate(h_one[5m])),steps=1000-8                                                                             2.680k ± 0%                 2.680k ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=histogram_quantile(0.9,_rate(h_ten[5m])),steps=1000-8                                                                             6.640k ± 0%                 6.640k ± 0%       ~ (p=1.000 n=6)
RangeQuery/expr=histogram_quantile(0.9,_rate(h_hundred[5m])),steps=1000-8                                                                         45.31k ± 0%                 45.32k ± 0%       ~ (p=0.249 n=6)
RangeQuery/expr=a_one_+_on(l)_group_right_a_one,steps=1000-8                                                                                      4.293k ± 0%                 4.293k ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=a_ten_+_on(l)_group_right_a_one,steps=1000-8                                                                                      2.633k ± 0%                 2.633k ± 0%       ~ (p=1.000 n=6)
RangeQuery/expr=a_hundred_+_on(l)_group_right_a_one,steps=1000-8                                                                                  7.579k ± 0%                 7.582k ± 0%       ~ (p=0.260 n=6)
RangeQuery/expr=count({__name__!=""}),steps=1-8                                                                                                   10.27k ± 0%                 10.27k ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=count({__name__!="",l=""}),steps=1-8                                                                                               256.0 ± 0%                  256.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=timestamp(a_one),steps=1000-8                                                                                                     3.171k ± 0%                 3.171k ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=timestamp(a_ten),steps=1000-8                                                                                                     3.531k ± 0%                 3.532k ± 0%       ~ (p=0.242 n=6)
RangeQuery/expr=timestamp(a_hundred),steps=1000-8                                                                                                 6.994k ± 0%                 6.993k ± 0%       ~ (p=0.424 n=6)
geomean                                                                                                                                           3.197k                      3.197k       +0.00%
¹ all samples are equal
```

```
goos: darwin
goarch: arm64
pkg: github.com/prometheus/prometheus/promql
cpu: Apple M1
                                                                                                        │ /Users/neerajgartia/Desktop/dev/cp/before_100.txt │ /Users/neerajgartia/Desktop/dev/cp/after_100.txt │
                                                                                                        │                      sec/op                       │          sec/op            vs base               │
RangeQuery/expr=a_one,steps=100-8                                                                                                              11.02µ ± 12%                10.45µ ±  3%        ~ (p=0.221 n=6)
RangeQuery/expr=a_ten,steps=100-8                                                                                                              58.77µ ±  5%                57.13µ ±  0%   -2.80% (p=0.002 n=6)
RangeQuery/expr=a_hundred,steps=100-8                                                                                                          537.7µ ±  3%                528.2µ ±  0%   -1.77% (p=0.002 n=6)
RangeQuery/expr=rate(a_one[1m]),steps=100-8                                                                                                    18.46µ ±  4%                18.64µ ±  1%        ~ (p=0.132 n=6)
RangeQuery/expr=rate(a_ten[1m]),steps=100-8                                                                                                    115.0µ ±  2%                114.1µ ± 27%        ~ (p=0.937 n=6)
RangeQuery/expr=rate(a_hundred[1m]),steps=100-8                                                                                                1.072m ±  4%                1.072m ±  0%        ~ (p=1.000 n=6)
RangeQuery/expr=rate(a_one[1m]),steps=10000-8                                                                                                  807.1µ ± 18%                802.4µ ±  0%        ~ (p=0.180 n=6)
RangeQuery/expr=rate(a_ten[1m]),steps=10000-8                                                                                                  8.142m ±  1%                8.187m ±  1%        ~ (p=0.240 n=6)
RangeQuery/expr=rate(a_hundred[1m]),steps=10000-8                                                                                              82.60m ±  2%                81.45m ±  0%   -1.39% (p=0.002 n=6)
RangeQuery/expr=rate(sparse[1m]),steps=10000-8                                                                                                 5.382m ±  1%                5.341m ±  0%        ~ (p=0.394 n=6)
RangeQuery/expr=double_exponential_smoothing(a_one[1d],_0.3,_0.3),steps=100-8                                                                  6.228m ±  1%                6.233m ±  0%        ~ (p=0.394 n=6)
RangeQuery/expr=double_exponential_smoothing(a_ten[1d],_0.3,_0.3),steps=100-8                                                                  61.29m ±  4%                61.36m ±  0%        ~ (p=0.589 n=6)
RangeQuery/expr=double_exponential_smoothing(a_hundred[1d],_0.3,_0.3),steps=100-8                                                              609.7m ±  0%                611.5m ±  0%   +0.29% (p=0.009 n=6)
RangeQuery/expr=changes(a_one[1d]),steps=100-8                                                                                                 2.242m ±  1%                2.250m ±  0%        ~ (p=0.180 n=6)
RangeQuery/expr=changes(a_ten[1d]),steps=100-8                                                                                                 22.08m ±  2%                21.87m ±  1%        ~ (p=0.394 n=6)
RangeQuery/expr=changes(a_hundred[1d]),steps=100-8                                                                                             218.3m ±  1%                217.9m ±  0%        ~ (p=0.065 n=6)
RangeQuery/expr=rate(a_one[1d]),steps=100-8                                                                                                    881.8µ ±  1%                883.1µ ±  0%        ~ (p=0.485 n=6)
RangeQuery/expr=rate(a_ten[1d]),steps=100-8                                                                                                    8.293m ±  1%                8.312m ±  1%        ~ (p=0.394 n=6)
RangeQuery/expr=rate(a_hundred[1d]),steps=100-8                                                                                                82.85m ±  1%                81.99m ±  0%        ~ (p=0.065 n=6)
RangeQuery/expr=absent_over_time(a_one[1d]),steps=100-8                                                                                        563.5µ ±  0%                566.4µ ±  1%        ~ (p=0.310 n=6)
RangeQuery/expr=absent_over_time(a_ten[1d]),steps=100-8                                                                                        5.187m ±  2%                5.069m ±  1%   -2.28% (p=0.009 n=6)
RangeQuery/expr=absent_over_time(a_hundred[1d]),steps=100-8                                                                                    51.56m ±  2%                49.98m ±  0%   -3.06% (p=0.002 n=6)
RangeQuery/expr=-a_one,steps=100-8                                                                                                             12.13µ ±  6%                11.73µ ±  1%   -3.31% (p=0.028 n=6)
RangeQuery/expr=-a_ten,steps=100-8                                                                                                             63.40µ ±  5%                60.19µ ±  7%   -5.06% (p=0.026 n=6)
RangeQuery/expr=-a_hundred,steps=100-8                                                                                                         580.0µ ±  1%                549.0µ ±  2%   -5.34% (p=0.002 n=6)
RangeQuery/expr=a_one_-_b_one,steps=100-8                                                                                                      51.61µ ±  9%                49.80µ ±  0%   -3.50% (p=0.002 n=6)
RangeQuery/expr=a_ten_-_b_ten,steps=100-8                                                                                                      415.0µ ± 10%                399.3µ ±  0%   -3.79% (p=0.002 n=6)
RangeQuery/expr=a_hundred_-_b_hundred,steps=100-8                                                                                              4.580m ±  9%                4.341m ±  1%   -5.22% (p=0.002 n=6)
RangeQuery/expr=a_one_-_b_one,steps=10000-8                                                                                                    3.709m ±  4%                3.476m ±  0%   -6.29% (p=0.002 n=6)
RangeQuery/expr=a_ten_-_b_ten,steps=10000-8                                                                                                    36.21m ±  3%                34.50m ±  0%   -4.71% (p=0.002 n=6)
RangeQuery/expr=a_hundred_-_b_hundred,steps=10000-8                                                                                            399.6m ±  3%                385.6m ±  1%   -3.51% (p=0.002 n=6)
RangeQuery/expr=a_one_and_b_one{l=~'.*[0-4]$'},steps=100-8                                                                                     32.38µ ±  3%                31.36µ ±  5%   -3.15% (p=0.041 n=6)
RangeQuery/expr=a_ten_and_b_ten{l=~'.*[0-4]$'},steps=100-8                                                                                     179.7µ ±  2%                173.3µ ±  0%   -3.58% (p=0.002 n=6)
RangeQuery/expr=a_hundred_and_b_hundred{l=~'.*[0-4]$'},steps=100-8                                                                             1.935m ±  7%                1.879m ±  1%   -2.89% (p=0.002 n=6)
RangeQuery/expr=a_one_or_b_one{l=~'.*[0-4]$'},steps=100-8                                                                                      39.24µ ±  4%                37.86µ ±  1%   -3.51% (p=0.002 n=6)
RangeQuery/expr=a_ten_or_b_ten{l=~'.*[0-4]$'},steps=100-8                                                                                      238.5µ ±  2%                227.9µ ±  0%   -4.40% (p=0.002 n=6)
RangeQuery/expr=a_hundred_or_b_hundred{l=~'.*[0-4]$'},steps=100-8                                                                              2.508m ±  4%                2.413m ±  7%   -3.78% (p=0.041 n=6)
RangeQuery/expr=a_one_unless_b_one{l=~'.*[0-4]$'},steps=100-8                                                                                  39.34µ ±  4%                37.89µ ±  1%   -3.69% (p=0.002 n=6)
RangeQuery/expr=a_ten_unless_b_ten{l=~'.*[0-4]$'},steps=100-8                                                                                  181.3µ ±  2%                172.9µ ±  0%   -4.64% (p=0.002 n=6)
RangeQuery/expr=a_hundred_unless_b_hundred{l=~'.*[0-4]$'},steps=100-8                                                                          1.960m ±  6%                1.872m ±  0%   -4.46% (p=0.002 n=6)
RangeQuery/expr=a_one_and_b_one{l='notfound'},steps=100-8                                                                                      24.13µ ±  2%                23.14µ ±  0%   -4.11% (p=0.002 n=6)
RangeQuery/expr=a_ten_and_b_ten{l='notfound'},steps=100-8                                                                                      83.48µ ±  2%                77.93µ ±  0%   -6.65% (p=0.002 n=6)
RangeQuery/expr=a_hundred_and_b_hundred{l='notfound'},steps=100-8                                                                              662.5µ ±  1%                617.1µ ±  0%   -6.85% (p=0.002 n=6)
RangeQuery/expr=abs(a_one),steps=100-8                                                                                                         24.72µ ±  4%                23.27µ ±  1%   -5.86% (p=0.002 n=6)
RangeQuery/expr=abs(a_ten),steps=100-8                                                                                                         142.6µ ±  6%                134.0µ ± 13%        ~ (p=0.065 n=6)
RangeQuery/expr=abs(a_hundred),steps=100-8                                                                                                     1.398m ±  2%                1.335m ±  1%   -4.51% (p=0.002 n=6)
RangeQuery/expr=label_replace(a_one,_'l2',_'$1',_'l',_'(.*)'),steps=100-8                                                                      19.62µ ±  3%                18.82µ ±  1%   -4.10% (p=0.002 n=6)
RangeQuery/expr=label_replace(a_ten,_'l2',_'$1',_'l',_'(.*)'),steps=100-8                                                                      73.60µ ±  2%                68.73µ ±  0%   -6.61% (p=0.002 n=6)
RangeQuery/expr=label_replace(a_hundred,_'l2',_'$1',_'l',_'(.*)'),steps=100-8                                                                  604.9µ ±  3%                566.6µ ±  1%   -6.34% (p=0.002 n=6)
RangeQuery/expr=label_join(a_one,_'l2',_'-',_'l',_'l'),steps=100-8                                                                             17.19µ ±  2%                16.43µ ±  1%   -4.43% (p=0.002 n=6)
RangeQuery/expr=label_join(a_ten,_'l2',_'-',_'l',_'l'),steps=100-8                                                                             70.07µ ±  5%                65.44µ ±  0%   -6.62% (p=0.002 n=6)
RangeQuery/expr=label_join(a_hundred,_'l2',_'-',_'l',_'l'),steps=100-8                                                                         602.1µ ±  2%                555.0µ ±  0%   -7.82% (p=0.002 n=6)
RangeQuery/expr=sum(a_one),steps=100-8                                                                                                         16.01µ ±  2%                15.29µ ±  0%   -4.53% (p=0.002 n=6)
RangeQuery/expr=sum(a_ten),steps=100-8                                                                                                         71.35µ ±  1%                65.97µ ±  1%   -7.54% (p=0.002 n=6)
RangeQuery/expr=sum(a_hundred),steps=100-8                                                                                                     621.3µ ±  3%                571.3µ ±  0%   -8.06% (p=0.002 n=6)
RangeQuery/expr=avg(a_one),steps=100-8                                                                                                         16.16µ ±  2%                15.31µ ±  1%   -5.25% (p=0.002 n=6)
RangeQuery/expr=avg(a_ten),steps=100-8                                                                                                         71.46µ ±  2%                66.31µ ±  1%   -7.21% (p=0.002 n=6)
RangeQuery/expr=avg(a_hundred),steps=100-8                                                                                                     639.7µ ±  4%                575.6µ ±  0%  -10.01% (p=0.002 n=6)
RangeQuery/expr=sum_without_(l)(h_one),steps=100-8                                                                                             88.38µ ±  4%                81.75µ ±  1%   -7.50% (p=0.002 n=6)
RangeQuery/expr=sum_without_(l)(h_ten),steps=100-8                                                                                             703.2µ ±  9%                637.3µ ±  2%   -9.36% (p=0.002 n=6)
RangeQuery/expr=sum_without_(l)(h_hundred),steps=100-8                                                                                         6.875m ±  4%                6.592m ± 10%        ~ (p=0.093 n=6)
RangeQuery/expr=sum_without_(le)(h_one),steps=100-8                                                                                            78.12µ ±  5%                72.35µ ±  1%   -7.38% (p=0.002 n=6)
RangeQuery/expr=sum_without_(le)(h_ten),steps=100-8                                                                                            696.6µ ±  4%                639.9µ ±  1%   -8.14% (p=0.002 n=6)
RangeQuery/expr=sum_without_(le)(h_hundred),steps=100-8                                                                                       10.160m ± 55%                6.762m ±  1%  -33.44% (p=0.002 n=6)
RangeQuery/expr=sum_by_(l)(h_one),steps=100-8                                                                                                  79.87µ ±  3%                72.54µ ±  1%   -9.18% (p=0.002 n=6)
RangeQuery/expr=sum_by_(l)(h_ten),steps=100-8                                                                                                  704.9µ ±  4%                638.1µ ±  0%   -9.48% (p=0.002 n=6)
RangeQuery/expr=sum_by_(l)(h_hundred),steps=100-8                                                                                              7.401m ±  2%                6.777m ±  4%   -8.44% (p=0.002 n=6)
RangeQuery/expr=sum_by_(le)(h_one),steps=100-8                                                                                                 89.89µ ± 20%                82.61µ ±  1%   -8.09% (p=0.002 n=6)
RangeQuery/expr=sum_by_(le)(h_ten),steps=100-8                                                                                                 705.8µ ±  7%                645.0µ ±  3%   -8.61% (p=0.002 n=6)
RangeQuery/expr=sum_by_(le)(h_hundred),steps=100-8                                                                                             7.077m ±  7%                6.645m ±  2%   -6.09% (p=0.002 n=6)
RangeQuery/expr=count_values('value',_h_one),steps=100-8                                                                                       978.4µ ±  3%                922.5µ ±  0%   -5.71% (p=0.002 n=6)
RangeQuery/expr=count_values('value',_h_ten),steps=100-8                                                                                       11.36m ±  2%                10.82m ±  1%   -4.75% (p=0.002 n=6)
RangeQuery/expr=count_values('value',_h_hundred),steps=100-8                                                                                   140.0m ± 20%                132.5m ±  3%   -5.36% (p=0.015 n=6)
RangeQuery/expr=topk(1,_a_one),steps=100-8                                                                                                     40.46µ ±  4%                39.13µ ±  1%   -3.27% (p=0.002 n=6)
RangeQuery/expr=topk(1,_a_ten),steps=100-8                                                                                                     104.5µ ±  2%                100.3µ ±  1%   -3.97% (p=0.002 n=6)
RangeQuery/expr=topk(1,_a_hundred),steps=100-8                                                                                                 705.5µ ±  3%                664.2µ ±  1%   -5.84% (p=0.002 n=6)
RangeQuery/expr=topk(5,_a_one),steps=100-8                                                                                                     40.29µ ±  2%                39.10µ ±  1%   -2.96% (p=0.002 n=6)
RangeQuery/expr=topk(5,_a_ten),steps=100-8                                                                                                     169.3µ ±  4%                160.1µ ±  1%   -5.43% (p=0.002 n=6)
RangeQuery/expr=topk(5,_a_hundred),steps=100-8                                                                                                1023.5µ ±  3%                968.9µ ±  1%   -5.34% (p=0.002 n=6)
RangeQuery/expr=limitk(1,_a_one),steps=100-8                                                                                                   40.23µ ±  4%                38.11µ ±  1%   -5.28% (p=0.002 n=6)
RangeQuery/expr=limitk(1,_a_ten),steps=100-8                                                                                                   94.83µ ±  6%                90.66µ ±  1%   -4.40% (p=0.002 n=6)
RangeQuery/expr=limitk(1,_a_hundred),steps=100-8                                                                                               619.2µ ±  5%                587.2µ ±  1%   -5.16% (p=0.002 n=6)
RangeQuery/expr=limitk(5,_a_one),steps=100-8                                                                                                   39.38µ ±  2%                38.17µ ±  1%   -3.08% (p=0.002 n=6)
RangeQuery/expr=limitk(5,_a_ten),steps=100-8                                                                                                   137.4µ ±  1%                132.1µ ±  1%   -3.86% (p=0.002 n=6)
RangeQuery/expr=limitk(5,_a_hundred),steps=100-8                                                                                               649.1µ ±  3%                632.9µ ±  2%   -2.49% (p=0.026 n=6)
RangeQuery/expr=limit_ratio(0.1,_a_one),steps=100-8                                                                                            34.33µ ±  6%                33.21µ ±  1%   -3.26% (p=0.002 n=6)
RangeQuery/expr=limit_ratio(0.1,_a_ten),steps=100-8                                                                                            163.6µ ± 11%                157.3µ ±  1%   -3.84% (p=0.002 n=6)
RangeQuery/expr=limit_ratio(0.1,_a_hundred),steps=100-8                                                                                        1.312m ±  3%                1.213m ±  1%   -7.54% (p=0.002 n=6)
RangeQuery/expr=limit_ratio(0.5,_a_one),steps=100-8                                                                                            34.71µ ± 13%                33.07µ ± 25%        ~ (p=0.065 n=6)
RangeQuery/expr=limit_ratio(0.5,_a_ten),steps=100-8                                                                                            202.8µ ±  2%                197.5µ ±  0%   -2.62% (p=0.002 n=6)
RangeQuery/expr=limit_ratio(0.5,_a_hundred),steps=100-8                                                                                        1.797m ±  4%                1.681m ±  1%   -6.45% (p=0.002 n=6)
RangeQuery/expr=limit_ratio(-0.5,_a_one),steps=100-8                                                                                           44.55µ ±  4%                42.56µ ±  1%   -4.46% (p=0.002 n=6)
RangeQuery/expr=limit_ratio(-0.5,_a_ten),steps=100-8                                                                                           204.6µ ±  2%                196.8µ ±  5%        ~ (p=0.065 n=6)
RangeQuery/expr=limit_ratio(-0.5,_a_hundred),steps=100-8                                                                                       1.831m ±  3%                1.700m ± 12%        ~ (p=0.065 n=6)
RangeQuery/expr=rate(a_one[1m])_+_rate(b_one[1m]),steps=100-8                                                                                  71.23µ ±  3%                65.70µ ±  1%   -7.77% (p=0.002 n=6)
RangeQuery/expr=rate(a_ten[1m])_+_rate(b_ten[1m]),steps=100-8                                                                                  532.5µ ±  5%                499.1µ ±  1%   -6.29% (p=0.002 n=6)
RangeQuery/expr=rate(a_hundred[1m])_+_rate(b_hundred[1m]),steps=100-8                                                                          5.591m ±  3%                5.293m ±  1%   -5.35% (p=0.002 n=6)
RangeQuery/expr=sum_without_(l)(rate(a_one[1m])),steps=100-8                                                                                   26.09µ ± 19%                24.36µ ±  1%   -6.64% (p=0.002 n=6)
RangeQuery/expr=sum_without_(l)(rate(a_ten[1m])),steps=100-8                                                                                   138.1µ ±  2%                127.5µ ±  5%   -7.72% (p=0.002 n=6)
RangeQuery/expr=sum_without_(l)(rate(a_hundred[1m])),steps=100-8                                                                               1.251m ±  2%                1.153m ±  2%   -7.85% (p=0.002 n=6)
RangeQuery/expr=sum_without_(l)(rate(a_one[1m]))_/_sum_without_(l)(rate(b_one[1m])),steps=100-8                                                80.52µ ±  2%                76.33µ ±  1%   -5.20% (p=0.002 n=6)
RangeQuery/expr=sum_without_(l)(rate(a_ten[1m]))_/_sum_without_(l)(rate(b_ten[1m])),steps=100-8                                                301.7µ ±  4%                282.4µ ±  2%   -6.39% (p=0.002 n=6)
RangeQuery/expr=sum_without_(l)(rate(a_hundred[1m]))_/_sum_without_(l)(rate(b_hundred[1m])),steps=100-8                                        2.512m ±  3%                2.336m ±  1%   -7.00% (p=0.002 n=6)
RangeQuery/expr=histogram_quantile(0.9,_rate(h_one[5m])),steps=100-8                                                                           237.3µ ±  3%                225.0µ ±  1%   -5.18% (p=0.002 n=6)
RangeQuery/expr=histogram_quantile(0.9,_rate(h_ten[5m])),steps=100-8                                                                           2.442m ±  4%                2.299m ±  2%   -5.88% (p=0.002 n=6)
RangeQuery/expr=histogram_quantile(0.9,_rate(h_hundred[5m])),steps=100-8                                                                       25.04m ±  3%                23.59m ±  1%   -5.80% (p=0.002 n=6)
RangeQuery/expr=a_one_+_on(l)_group_right_a_one,steps=100-8                                                                                    63.36µ ±  4%                60.92µ ±  1%   -3.85% (p=0.004 n=6)
RangeQuery/expr=a_ten_+_on(l)_group_right_a_one,steps=100-8                                                                                    132.5µ ±  5%                123.4µ ±  1%   -6.93% (p=0.002 n=6)
RangeQuery/expr=a_hundred_+_on(l)_group_right_a_one,steps=100-8                                                                                1.244m ±  2%                1.185m ±  8%        ~ (p=0.065 n=6)
RangeQuery/expr=count({__name__!=""}),steps=1-8                                                                                                2.972m ±  2%                2.939m ±  2%        ~ (p=0.180 n=6)
RangeQuery/expr=count({__name__!="",l=""}),steps=1-8                                                                                           114.8µ ±  2%                111.4µ ±  1%   -2.97% (p=0.002 n=6)
RangeQuery/expr=timestamp(a_one),steps=100-8                                                                                                   29.60µ ±  2%                29.99µ ±  1%        ~ (p=0.394 n=6)
RangeQuery/expr=timestamp(a_ten),steps=100-8                                                                                                   149.7µ ±  2%                151.3µ ±  3%        ~ (p=0.132 n=6)
RangeQuery/expr=timestamp(a_hundred),steps=100-8                                                                                               1.444m ±  1%                1.463m ±  6%        ~ (p=0.240 n=6)
geomean                                                                                                                                        519.3µ                      494.8µ         -4.72%

                                                                                                        │ /Users/neerajgartia/Desktop/dev/cp/before_100.txt │ /Users/neerajgartia/Desktop/dev/cp/after_100.txt │
                                                                                                        │                       B/op                        │            B/op             vs base              │
RangeQuery/expr=a_one,steps=100-8                                                                                                              5.967Ki ± 0%                 5.967Ki ± 0%       ~ (p=0.182 n=6)
RangeQuery/expr=a_ten,steps=100-8                                                                                                              12.79Ki ± 0%                 12.79Ki ± 0%       ~ (p=0.632 n=6)
RangeQuery/expr=a_hundred,steps=100-8                                                                                                          78.02Ki ± 0%                 77.95Ki ± 0%       ~ (p=0.818 n=6)
RangeQuery/expr=rate(a_one[1m]),steps=100-8                                                                                                    8.563Ki ± 0%                 8.563Ki ± 0%       ~ (p=0.485 n=6)
RangeQuery/expr=rate(a_ten[1m]),steps=100-8                                                                                                    17.37Ki ± 0%                 17.37Ki ± 0%       ~ (p=0.121 n=6)
RangeQuery/expr=rate(a_hundred[1m]),steps=100-8                                                                                                102.3Ki ± 0%                 102.3Ki ± 0%       ~ (p=0.667 n=6)
RangeQuery/expr=rate(a_one[1m]),steps=10000-8                                                                                                  53.42Ki ± 1%                 53.26Ki ± 1%       ~ (p=0.855 n=6)
RangeQuery/expr=rate(a_ten[1m]),steps=10000-8                                                                                                  297.3Ki ± 0%                 297.3Ki ± 1%       ~ (p=0.699 n=6)
RangeQuery/expr=rate(a_hundred[1m]),steps=10000-8                                                                                              2.586Mi ± 1%                 2.603Mi ± 0%       ~ (p=0.240 n=6)
RangeQuery/expr=rate(sparse[1m]),steps=10000-8                                                                                                 44.59Ki ± 1%                 46.36Ki ± 8%       ~ (p=0.240 n=6)
RangeQuery/expr=double_exponential_smoothing(a_one[1d],_0.3,_0.3),steps=100-8                                                                  1.021Mi ± 0%                 1.021Mi ± 0%       ~ (p=0.699 n=6)
RangeQuery/expr=double_exponential_smoothing(a_ten[1d],_0.3,_0.3),steps=100-8                                                                  1.213Mi ± 0%                 1.213Mi ± 0%       ~ (p=0.368 n=6)
RangeQuery/expr=double_exponential_smoothing(a_hundred[1d],_0.3,_0.3),steps=100-8                                                              3.150Mi ± 0%                 3.151Mi ± 0%       ~ (p=0.660 n=6)
RangeQuery/expr=changes(a_one[1d]),steps=100-8                                                                                                 550.6Ki ± 0%                 551.5Ki ± 1%       ~ (p=0.589 n=6)
RangeQuery/expr=changes(a_ten[1d]),steps=100-8                                                                                                 764.9Ki ± 1%                 760.1Ki ± 1%       ~ (p=0.121 n=6)
RangeQuery/expr=changes(a_hundred[1d]),steps=100-8                                                                                             2.712Mi ± 2%                 2.760Mi ± 3%       ~ (p=0.093 n=6)
RangeQuery/expr=rate(a_one[1d]),steps=100-8                                                                                                    554.3Ki ± 1%                 554.4Ki ± 0%       ~ (p=0.937 n=6)
RangeQuery/expr=rate(a_ten[1d]),steps=100-8                                                                                                    758.6Ki ± 1%                 760.4Ki ± 1%       ~ (p=0.394 n=6)
RangeQuery/expr=rate(a_hundred[1d]),steps=100-8                                                                                                2.718Mi ± 0%                 2.719Mi ± 1%       ~ (p=0.260 n=6)
RangeQuery/expr=absent_over_time(a_one[1d]),steps=100-8                                                                                        562.7Ki ± 0%                 563.4Ki ± 0%       ~ (p=0.589 n=6)
RangeQuery/expr=absent_over_time(a_ten[1d]),steps=100-8                                                                                        770.6Ki ± 0%                 771.6Ki ± 0%       ~ (p=1.000 n=6)
RangeQuery/expr=absent_over_time(a_hundred[1d]),steps=100-8                                                                                    2.842Mi ± 0%                 2.853Mi ± 1%       ~ (p=0.132 n=6)
RangeQuery/expr=-a_one,steps=100-8                                                                                                             6.601Ki ± 0%                 6.600Ki ± 0%       ~ (p=0.773 n=6)
RangeQuery/expr=-a_ten,steps=100-8                                                                                                             13.58Ki ± 0%                 13.58Ki ± 0%       ~ (p=0.056 n=6)
RangeQuery/expr=-a_hundred,steps=100-8                                                                                                         80.18Ki ± 0%                 80.18Ki ± 0%       ~ (p=0.258 n=6)
RangeQuery/expr=a_one_-_b_one,steps=100-8                                                                                                      17.82Ki ± 0%                 17.82Ki ± 0%       ~ (p=0.316 n=6)
RangeQuery/expr=a_ten_-_b_ten,steps=100-8                                                                                                      42.43Ki ± 0%                 42.42Ki ± 0%       ~ (p=0.290 n=6)
RangeQuery/expr=a_hundred_-_b_hundred,steps=100-8                                                                                              389.7Ki ± 0%                 389.4Ki ± 0%       ~ (p=0.394 n=6)
RangeQuery/expr=a_one_-_b_one,steps=10000-8                                                                                                    572.3Ki ± 0%                 572.1Ki ± 0%       ~ (p=0.180 n=6)
RangeQuery/expr=a_ten_-_b_ten,steps=10000-8                                                                                                    1.221Mi ± 1%                 1.215Mi ± 1%       ~ (p=0.394 n=6)
RangeQuery/expr=a_hundred_-_b_hundred,steps=10000-8                                                                                            17.26Mi ± 1%                 17.27Mi ± 1%       ~ (p=1.000 n=6)
RangeQuery/expr=a_one_and_b_one{l=~'.*[0-4]$'},steps=100-8                                                                                     26.19Ki ± 0%                 26.19Ki ± 0%       ~ (p=0.987 n=6)
RangeQuery/expr=a_ten_and_b_ten{l=~'.*[0-4]$'},steps=100-8                                                                                     42.38Ki ± 0%                 42.38Ki ± 0%       ~ (p=0.452 n=6)
RangeQuery/expr=a_hundred_and_b_hundred{l=~'.*[0-4]$'},steps=100-8                                                                             436.7Ki ± 0%                 436.7Ki ± 0%       ~ (p=0.145 n=6)
RangeQuery/expr=a_one_or_b_one{l=~'.*[0-4]$'},steps=100-8                                                                                      26.27Ki ± 0%                 26.27Ki ± 0%       ~ (p=0.076 n=6)
RangeQuery/expr=a_ten_or_b_ten{l=~'.*[0-4]$'},steps=100-8                                                                                      71.61Ki ± 0%                 71.61Ki ± 0%       ~ (p=0.403 n=6)
RangeQuery/expr=a_hundred_or_b_hundred{l=~'.*[0-4]$'},steps=100-8                                                                              726.5Ki ± 0%                 726.3Ki ± 0%       ~ (p=0.589 n=6)
RangeQuery/expr=a_one_unless_b_one{l=~'.*[0-4]$'},steps=100-8                                                                                  26.30Ki ± 0%                 26.30Ki ± 0%       ~ (p=0.734 n=6)
RangeQuery/expr=a_ten_unless_b_ten{l=~'.*[0-4]$'},steps=100-8                                                                                  42.40Ki ± 0%                 42.40Ki ± 0%       ~ (p=0.924 n=6)
RangeQuery/expr=a_hundred_unless_b_hundred{l=~'.*[0-4]$'},steps=100-8                                                                          436.7Ki ± 0%                 436.7Ki ± 0%       ~ (p=0.394 n=6)
RangeQuery/expr=a_one_and_b_one{l='notfound'},steps=100-8                                                                                      14.89Ki ± 0%                 14.89Ki ± 0%       ~ (p=0.643 n=6)
RangeQuery/expr=a_ten_and_b_ten{l='notfound'},steps=100-8                                                                                      25.59Ki ± 0%                 25.59Ki ± 0%       ~ (p=0.481 n=6)
RangeQuery/expr=a_hundred_and_b_hundred{l='notfound'},steps=100-8                                                                              124.0Ki ± 0%                 124.0Ki ± 0%       ~ (p=0.974 n=6)
RangeQuery/expr=abs(a_one),steps=100-8                                                                                                         9.603Ki ± 0%                 9.603Ki ± 0%       ~ (p=1.000 n=6)
RangeQuery/expr=abs(a_ten),steps=100-8                                                                                                         20.79Ki ± 0%                 20.79Ki ± 0%       ~ (p=0.461 n=6)
RangeQuery/expr=abs(a_hundred),steps=100-8                                                                                                     124.2Ki ± 0%                 124.2Ki ± 0%       ~ (p=1.000 n=6)
RangeQuery/expr=label_replace(a_one,_'l2',_'$1',_'l',_'(.*)'),steps=100-8                                                                      12.65Ki ± 0%                 12.65Ki ± 0%       ~ (p=1.000 n=6)
RangeQuery/expr=label_replace(a_ten,_'l2',_'$1',_'l',_'(.*)'),steps=100-8                                                                      20.89Ki ± 0%                 20.89Ki ± 0%       ~ (p=0.632 n=6)
RangeQuery/expr=label_replace(a_hundred,_'l2',_'$1',_'l',_'(.*)'),steps=100-8                                                                  100.2Ki ± 0%                 100.2Ki ± 0%       ~ (p=0.699 n=6)
RangeQuery/expr=label_join(a_one,_'l2',_'-',_'l',_'l'),steps=100-8                                                                             9.876Ki ± 0%                 9.876Ki ± 0%       ~ (p=0.545 n=6)
RangeQuery/expr=label_join(a_ten,_'l2',_'-',_'l',_'l'),steps=100-8                                                                             17.81Ki ± 0%                 17.81Ki ± 0%       ~ (p=0.883 n=6)
RangeQuery/expr=label_join(a_hundred,_'l2',_'-',_'l',_'l'),steps=100-8                                                                         93.61Ki ± 0%                 93.58Ki ± 0%  -0.03% (p=0.002 n=6)
RangeQuery/expr=sum(a_one),steps=100-8                                                                                                         7.265Ki ± 0%                 7.265Ki ± 0%       ~ (p=1.000 n=6)
RangeQuery/expr=sum(a_ten),steps=100-8                                                                                                         14.96Ki ± 0%                 14.96Ki ± 0%       ~ (p=0.762 n=6)
RangeQuery/expr=sum(a_hundred),steps=100-8                                                                                                     88.04Ki ± 0%                 88.04Ki ± 0%       ~ (p=0.851 n=6)
RangeQuery/expr=avg(a_one),steps=100-8                                                                                                         7.266Ki ± 0%                 7.265Ki ± 0%       ~ (p=0.177 n=6)
RangeQuery/expr=avg(a_ten),steps=100-8                                                                                                         14.96Ki ± 0%                 14.96Ki ± 0%       ~ (p=0.206 n=6)
RangeQuery/expr=avg(a_hundred),steps=100-8                                                                                                     88.04Ki ± 0%                 88.04Ki ± 0%       ~ (p=0.563 n=6)
RangeQuery/expr=sum_without_(l)(h_one),steps=100-8                                                                                             19.70Ki ± 0%                 19.71Ki ± 0%  +0.02% (p=0.032 n=6)
RangeQuery/expr=sum_without_(l)(h_ten),steps=100-8                                                                                             105.0Ki ± 0%                 105.0Ki ± 0%       ~ (p=0.818 n=6)
RangeQuery/expr=sum_without_(l)(h_hundred),steps=100-8                                                                                         957.8Ki ± 0%                 958.4Ki ± 0%       ~ (p=0.485 n=6)
RangeQuery/expr=sum_without_(le)(h_one),steps=100-8                                                                                            15.78Ki ± 0%                 15.78Ki ± 0%       ~ (p=0.965 n=6)
RangeQuery/expr=sum_without_(le)(h_ten),steps=100-8                                                                                            104.9Ki ± 0%                 104.9Ki ± 0%       ~ (p=0.669 n=6)
RangeQuery/expr=sum_without_(le)(h_hundred),steps=100-8                                                                                        994.5Ki ± 0%                 993.4Ki ± 0%       ~ (p=0.485 n=6)
RangeQuery/expr=sum_by_(l)(h_one),steps=100-8                                                                                                  15.73Ki ± 0%                 15.73Ki ± 0%       ~ (p=0.076 n=6)
RangeQuery/expr=sum_by_(l)(h_ten),steps=100-8                                                                                                  104.8Ki ± 0%                 104.8Ki ± 0%       ~ (p=0.905 n=6)
RangeQuery/expr=sum_by_(l)(h_hundred),steps=100-8                                                                                              993.2Ki ± 0%                 992.6Ki ± 0%       ~ (p=0.818 n=6)
RangeQuery/expr=sum_by_(le)(h_one),steps=100-8                                                                                                 19.68Ki ± 0%                 19.68Ki ± 0%       ~ (p=0.535 n=6)
RangeQuery/expr=sum_by_(le)(h_ten),steps=100-8                                                                                                 105.0Ki ± 0%                 105.0Ki ± 0%       ~ (p=0.180 n=6)
RangeQuery/expr=sum_by_(le)(h_hundred),steps=100-8                                                                                             959.9Ki ± 0%                 957.1Ki ± 0%       ~ (p=0.132 n=6)
RangeQuery/expr=count_values('value',_h_one),steps=100-8                                                                                       832.1Ki ± 0%                 832.0Ki ± 0%       ~ (p=0.093 n=6)
RangeQuery/expr=count_values('value',_h_ten),steps=100-8                                                                                       8.306Mi ± 0%                 8.305Mi ± 1%       ~ (p=0.699 n=6)
RangeQuery/expr=count_values('value',_h_hundred),steps=100-8                                                                                   103.0Mi ± 0%                 103.1Mi ± 0%       ~ (p=0.310 n=6)
RangeQuery/expr=topk(1,_a_one),steps=100-8                                                                                                     30.21Ki ± 0%                 30.21Ki ± 0%       ~ (p=0.197 n=6)
RangeQuery/expr=topk(1,_a_ten),steps=100-8                                                                                                     39.39Ki ± 0%                 39.38Ki ± 0%       ~ (p=0.234 n=6)
RangeQuery/expr=topk(1,_a_hundred),steps=100-8                                                                                                 123.0Ki ± 0%                 123.0Ki ± 0%  +0.02% (p=0.002 n=6)
RangeQuery/expr=topk(5,_a_one),steps=100-8                                                                                                     30.21Ki ± 0%                 30.21Ki ± 0%       ~ (p=0.662 n=6)
RangeQuery/expr=topk(5,_a_ten),steps=100-8                                                                                                     65.78Ki ± 0%                 65.78Ki ± 0%       ~ (p=0.727 n=6)
RangeQuery/expr=topk(5,_a_hundred),steps=100-8                                                                                                 149.4Ki ± 0%                 149.4Ki ± 0%       ~ (p=0.331 n=6)
RangeQuery/expr=limitk(1,_a_one),steps=100-8                                                                                                   30.21Ki ± 0%                 30.21Ki ± 0%       ~ (p=0.139 n=6)
RangeQuery/expr=limitk(1,_a_ten),steps=100-8                                                                                                   39.39Ki ± 0%                 39.39Ki ± 0%       ~ (p=0.952 n=6)
RangeQuery/expr=limitk(1,_a_hundred),steps=100-8                                                                                               123.0Ki ± 0%                 123.0Ki ± 0%       ~ (p=0.732 n=6)
RangeQuery/expr=limitk(5,_a_one),steps=100-8                                                                                                   30.21Ki ± 0%                 30.21Ki ± 0%       ~ (p=0.212 n=6)
RangeQuery/expr=limitk(5,_a_ten),steps=100-8                                                                                                   61.83Ki ± 0%                 61.83Ki ± 0%       ~ (p=0.054 n=6)
RangeQuery/expr=limitk(5,_a_hundred),steps=100-8                                                                                               145.5Ki ± 0%                 145.5Ki ± 0%  -0.02% (p=0.013 n=6)
RangeQuery/expr=limit_ratio(0.1,_a_one),steps=100-8                                                                                            23.90Ki ± 0%                 23.90Ki ± 0%       ~ (p=0.305 n=6)
RangeQuery/expr=limit_ratio(0.1,_a_ten),steps=100-8                                                                                            50.62Ki ± 0%                 50.62Ki ± 0%       ~ (p=0.777 n=6)
RangeQuery/expr=limit_ratio(0.1,_a_hundred),steps=100-8                                                                                        302.4Ki ± 0%                 302.4Ki ± 0%       ~ (p=0.394 n=6)
RangeQuery/expr=limit_ratio(0.5,_a_one),steps=100-8                                                                                            23.90Ki ± 0%                 23.90Ki ± 0%  -0.01% (p=0.035 n=6)
RangeQuery/expr=limit_ratio(0.5,_a_ten),steps=100-8                                                                                            117.2Ki ± 0%                 117.2Ki ± 0%       ~ (p=0.080 n=6)
RangeQuery/expr=limit_ratio(0.5,_a_hundred),steps=100-8                                                                                        912.7Ki ± 0%                 912.6Ki ± 0%       ~ (p=0.240 n=6)
RangeQuery/expr=limit_ratio(-0.5,_a_one),steps=100-8                                                                                           30.30Ki ± 0%                 30.30Ki ± 0%       ~ (p=0.859 n=6)
RangeQuery/expr=limit_ratio(-0.5,_a_ten),steps=100-8                                                                                           117.2Ki ± 0%                 117.2Ki ± 0%       ~ (p=0.056 n=6)
RangeQuery/expr=limit_ratio(-0.5,_a_hundred),steps=100-8                                                                                       912.8Ki ± 0%                 912.7Ki ± 0%       ~ (p=0.589 n=6)
RangeQuery/expr=rate(a_one[1m])_+_rate(b_one[1m]),steps=100-8                                                                                  23.10Ki ± 0%                 23.10Ki ± 0%       ~ (p=0.184 n=6)
RangeQuery/expr=rate(a_ten[1m])_+_rate(b_ten[1m]),steps=100-8                                                                                  51.34Ki ± 0%                 51.31Ki ± 0%       ~ (p=0.169 n=6)
RangeQuery/expr=rate(a_hundred[1m])_+_rate(b_hundred[1m]),steps=100-8                                                                          435.9Ki ± 0%                 435.8Ki ± 0%       ~ (p=0.818 n=6)
RangeQuery/expr=sum_without_(l)(rate(a_one[1m])),steps=100-8                                                                                   10.33Ki ± 0%                 10.33Ki ± 0%       ~ (p=0.675 n=6)
RangeQuery/expr=sum_without_(l)(rate(a_ten[1m])),steps=100-8                                                                                   20.02Ki ± 0%                 20.01Ki ± 0%       ~ (p=0.348 n=6)
RangeQuery/expr=sum_without_(l)(rate(a_hundred[1m])),steps=100-8                                                                               112.9Ki ± 0%                 112.9Ki ± 0%       ~ (p=1.000 n=6)
RangeQuery/expr=sum_without_(l)(rate(a_one[1m]))_/_sum_without_(l)(rate(b_one[1m])),steps=100-8                                                27.66Ki ± 0%                 27.66Ki ± 0%       ~ (p=0.286 n=6)
RangeQuery/expr=sum_without_(l)(rate(a_ten[1m]))_/_sum_without_(l)(rate(b_ten[1m])),steps=100-8                                                47.02Ki ± 0%                 47.02Ki ± 0%       ~ (p=0.569 n=6)
RangeQuery/expr=sum_without_(l)(rate(a_hundred[1m]))_/_sum_without_(l)(rate(b_hundred[1m])),steps=100-8                                        232.7Ki ± 0%                 232.7Ki ± 0%       ~ (p=0.699 n=6)
RangeQuery/expr=histogram_quantile(0.9,_rate(h_one[5m])),steps=100-8                                                                           31.70Ki ± 0%                 31.70Ki ± 0%       ~ (p=0.201 n=6)
RangeQuery/expr=histogram_quantile(0.9,_rate(h_ten[5m])),steps=100-8                                                                           184.1Ki ± 0%                 184.1Ki ± 0%       ~ (p=0.121 n=6)
RangeQuery/expr=histogram_quantile(0.9,_rate(h_hundred[5m])),steps=100-8                                                                       1.610Mi ± 0%                 1.610Mi ± 0%       ~ (p=0.699 n=6)
RangeQuery/expr=a_one_+_on(l)_group_right_a_one,steps=100-8                                                                                    30.75Ki ± 0%                 30.75Ki ± 0%       ~ (p=0.123 n=6)
RangeQuery/expr=a_ten_+_on(l)_group_right_a_one,steps=100-8                                                                                    30.66Ki ± 0%                 30.66Ki ± 0%       ~ (p=0.608 n=6)
RangeQuery/expr=a_hundred_+_on(l)_group_right_a_one,steps=100-8                                                                                263.1Ki ± 0%                 263.0Ki ± 0%       ~ (p=0.485 n=6)
RangeQuery/expr=count({__name__!=""}),steps=1-8                                                                                                859.4Ki ± 0%                 859.2Ki ± 0%       ~ (p=0.589 n=6)
RangeQuery/expr=count({__name__!="",l=""}),steps=1-8                                                                                           24.28Ki ± 0%                 24.28Ki ± 0%       ~ (p=0.136 n=6)
RangeQuery/expr=timestamp(a_one),steps=100-8                                                                                                   16.91Ki ± 0%                 16.91Ki ± 0%       ~ (p=0.102 n=6)
RangeQuery/expr=timestamp(a_ten),steps=100-8                                                                                                   81.54Ki ± 0%                 81.54Ki ± 0%       ~ (p=0.909 n=6)
RangeQuery/expr=timestamp(a_hundred),steps=100-8                                                                                               774.5Ki ± 0%                 774.5Ki ± 0%       ~ (p=0.485 n=6)
geomean                                                                                                                                        107.5Ki                      107.6Ki       +0.05%

                                                                                                        │ /Users/neerajgartia/Desktop/dev/cp/before_100.txt │ /Users/neerajgartia/Desktop/dev/cp/after_100.txt │
                                                                                                        │                     allocs/op                     │        allocs/op          vs base                │
RangeQuery/expr=a_one,steps=100-8                                                                                                                116.0 ± 0%                 116.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=a_ten,steps=100-8                                                                                                                210.0 ± 0%                 210.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=a_hundred,steps=100-8                                                                                                           1.105k ± 0%                1.105k ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=rate(a_one[1m]),steps=100-8                                                                                                      169.0 ± 0%                 169.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=rate(a_ten[1m]),steps=100-8                                                                                                      300.0 ± 0%                 300.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=rate(a_hundred[1m]),steps=100-8                                                                                                 1.561k ± 0%                1.561k ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=rate(a_one[1m]),steps=10000-8                                                                                                    486.0 ± 0%                 486.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=rate(a_ten[1m]),steps=10000-8                                                                                                   3.012k ± 0%                3.012k ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=rate(a_hundred[1m]),steps=10000-8                                                                                               27.64k ± 0%                27.65k ± 0%       ~ (p=0.262 n=6)
RangeQuery/expr=rate(sparse[1m]),steps=10000-8                                                                                                   673.0 ± 0%                 673.5 ± 0%       ~ (p=0.182 n=6)
RangeQuery/expr=double_exponential_smoothing(a_one[1d],_0.3,_0.3),steps=100-8                                                                    490.0 ± 0%                 490.0 ± 0%       ~ (p=1.000 n=6)
RangeQuery/expr=double_exponential_smoothing(a_ten[1d],_0.3,_0.3),steps=100-8                                                                   2.563k ± 0%                2.564k ± 0%       ~ (p=1.000 n=6)
RangeQuery/expr=double_exponential_smoothing(a_hundred[1d],_0.3,_0.3),steps=100-8                                                               22.70k ± 0%                22.70k ± 0%       ~ (p=0.742 n=6)
RangeQuery/expr=changes(a_one[1d]),steps=100-8                                                                                                   398.0 ± 0%                 398.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=changes(a_ten[1d]),steps=100-8                                                                                                  2.474k ± 0%                2.474k ± 0%       ~ (p=0.182 n=6)
RangeQuery/expr=changes(a_hundred[1d]),steps=100-8                                                                                              22.60k ± 0%                22.60k ± 0%       ~ (p=0.115 n=6)
RangeQuery/expr=rate(a_one[1d]),steps=100-8                                                                                                      404.0 ± 0%                 404.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=rate(a_ten[1d]),steps=100-8                                                                                                     2.516k ± 0%                2.516k ± 0%       ~ (p=1.000 n=6)
RangeQuery/expr=rate(a_hundred[1d]),steps=100-8                                                                                                 23.00k ± 0%                23.00k ± 0%  +0.01% (p=0.028 n=6)
RangeQuery/expr=absent_over_time(a_one[1d]),steps=100-8                                                                                          400.0 ± 0%                 400.0 ± 0%       ~ (p=1.000 n=6)
RangeQuery/expr=absent_over_time(a_ten[1d]),steps=100-8                                                                                         2.482k ± 0%                2.482k ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=absent_over_time(a_hundred[1d]),steps=100-8                                                                                     22.69k ± 0%                22.69k ± 0%       ~ (p=0.188 n=6)
RangeQuery/expr=-a_one,steps=100-8                                                                                                               135.0 ± 0%                 135.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=-a_ten,steps=100-8                                                                                                               230.0 ± 0%                 230.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=-a_hundred,steps=100-8                                                                                                          1.131k ± 0%                1.131k ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=a_one_-_b_one,steps=100-8                                                                                                        420.0 ± 0%                 420.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=a_ten_-_b_ten,steps=100-8                                                                                                        653.0 ± 0%                 653.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=a_hundred_-_b_hundred,steps=100-8                                                                                               3.026k ± 0%                3.026k ± 0%       ~ (p=0.989 n=6)
RangeQuery/expr=a_one_-_b_one,steps=10000-8                                                                                                     20.84k ± 0%                20.84k ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=a_ten_-_b_ten,steps=10000-8                                                                                                     26.29k ± 0%                26.29k ± 0%       ~ (p=0.597 n=6)
RangeQuery/expr=a_hundred_-_b_hundred,steps=10000-8                                                                                             95.54k ± 0%                95.55k ± 0%       ~ (p=0.818 n=6)
RangeQuery/expr=a_one_and_b_one{l=~'.*[0-4]$'},steps=100-8                                                                                       476.0 ± 0%                 476.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=a_ten_and_b_ten{l=~'.*[0-4]$'},steps=100-8                                                                                       652.0 ± 0%                 652.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=a_hundred_and_b_hundred{l=~'.*[0-4]$'},steps=100-8                                                                              2.674k ± 0%                2.674k ± 0%       ~ (p=0.636 n=6)
RangeQuery/expr=a_one_or_b_one{l=~'.*[0-4]$'},steps=100-8                                                                                        477.0 ± 0%                 477.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=a_ten_or_b_ten{l=~'.*[0-4]$'},steps=100-8                                                                                        755.0 ± 0%                 755.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=a_hundred_or_b_hundred{l=~'.*[0-4]$'},steps=100-8                                                                               2.994k ± 0%                2.993k ± 0%       ~ (p=0.097 n=6)
RangeQuery/expr=a_one_unless_b_one{l=~'.*[0-4]$'},steps=100-8                                                                                    477.0 ± 0%                 477.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=a_ten_unless_b_ten{l=~'.*[0-4]$'},steps=100-8                                                                                    652.0 ± 0%                 652.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=a_hundred_unless_b_hundred{l=~'.*[0-4]$'},steps=100-8                                                                           2.674k ± 0%                2.674k ± 0%       ~ (p=0.152 n=6)
RangeQuery/expr=a_one_and_b_one{l='notfound'},steps=100-8                                                                                        396.0 ± 0%                 396.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=a_ten_and_b_ten{l='notfound'},steps=100-8                                                                                        501.0 ± 0%                 501.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=a_hundred_and_b_hundred{l='notfound'},steps=100-8                                                                               1.487k ± 0%                1.487k ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=abs(a_one),steps=100-8                                                                                                           252.0 ± 0%                 252.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=abs(a_ten),steps=100-8                                                                                                           347.0 ± 0%                 347.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=abs(a_hundred),steps=100-8                                                                                                      1.245k ± 0%                1.245k ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=label_replace(a_one,_'l2',_'$1',_'l',_'(.*)'),steps=100-8                                                                        268.0 ± 0%                 268.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=label_replace(a_ten,_'l2',_'$1',_'l',_'(.*)'),steps=100-8                                                                        391.0 ± 0%                 391.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=label_replace(a_hundred,_'l2',_'$1',_'l',_'(.*)'),steps=100-8                                                                   1.652k ± 0%                1.652k ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=label_join(a_one,_'l2',_'-',_'l',_'l'),steps=100-8                                                                               227.0 ± 0%                 227.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=label_join(a_ten,_'l2',_'-',_'l',_'l'),steps=100-8                                                                               340.0 ± 0%                 340.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=label_join(a_hundred,_'l2',_'-',_'l',_'l'),steps=100-8                                                                          1.421k ± 0%                1.421k ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=sum(a_one),steps=100-8                                                                                                           145.0 ± 0%                 145.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=sum(a_ten),steps=100-8                                                                                                           239.0 ± 0%                 239.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=sum(a_hundred),steps=100-8                                                                                                      1.134k ± 0%                1.134k ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=avg(a_one),steps=100-8                                                                                                           145.0 ± 0%                 145.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=avg(a_ten),steps=100-8                                                                                                           239.0 ± 0%                 239.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=avg(a_hundred),steps=100-8                                                                                                      1.134k ± 0%                1.134k ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=sum_without_(l)(h_one),steps=100-8                                                                                               272.0 ± 0%                 272.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=sum_without_(l)(h_ten),steps=100-8                                                                                              1.265k ± 0%                1.265k ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=sum_without_(l)(h_hundred),steps=100-8                                                                                          11.08k ± 0%                11.08k ± 0%       ~ (p=1.000 n=6)
RangeQuery/expr=sum_without_(le)(h_one),steps=100-8                                                                                              259.0 ± 0%                 259.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=sum_without_(le)(h_ten),steps=100-8                                                                                             1.266k ± 0%                1.266k ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=sum_without_(le)(h_hundred),steps=100-8                                                                                         11.19k ± 0%                11.19k ± 0%       ~ (p=0.242 n=6)
RangeQuery/expr=sum_by_(l)(h_one),steps=100-8                                                                                                    257.0 ± 0%                 257.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=sum_by_(l)(h_ten),steps=100-8                                                                                                   1.264k ± 0%                1.264k ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=sum_by_(l)(h_hundred),steps=100-8                                                                                               11.18k ± 0%                11.18k ± 0%       ~ (p=1.000 n=6)
RangeQuery/expr=sum_by_(le)(h_one),steps=100-8                                                                                                   274.0 ± 0%                 274.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=sum_by_(le)(h_ten),steps=100-8                                                                                                  1.267k ± 0%                1.267k ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=sum_by_(le)(h_hundred),steps=100-8                                                                                              11.08k ± 0%                11.08k ± 0%       ~ (p=0.054 n=6)
RangeQuery/expr=count_values('value',_h_one),steps=100-8                                                                                        6.367k ± 0%                6.367k ± 0%       ~ (p=0.182 n=6)
RangeQuery/expr=count_values('value',_h_ten),steps=100-8                                                                                        58.55k ± 0%                58.54k ± 0%       ~ (p=0.524 n=6)
RangeQuery/expr=count_values('value',_h_hundred),steps=100-8                                                                                    575.2k ± 0%                575.1k ± 0%       ~ (p=0.937 n=6)
RangeQuery/expr=topk(1,_a_one),steps=100-8                                                                                                       465.0 ± 0%                 465.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=topk(1,_a_ten),steps=100-8                                                                                                       560.0 ± 0%                 560.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=topk(1,_a_hundred),steps=100-8                                                                                                  1.456k ± 0%                1.456k ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=topk(5,_a_one),steps=100-8                                                                                                       465.0 ± 0%                 465.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=topk(5,_a_ten),steps=100-8                                                                                                       762.0 ± 0%                 762.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=topk(5,_a_hundred),steps=100-8                                                                                                  1.658k ± 0%                1.658k ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=limitk(1,_a_one),steps=100-8                                                                                                     465.0 ± 0%                 465.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=limitk(1,_a_ten),steps=100-8                                                                                                     560.0 ± 0%                 560.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=limitk(1,_a_hundred),steps=100-8                                                                                                1.456k ± 0%                1.456k ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=limitk(5,_a_one),steps=100-8                                                                                                     465.0 ± 0%                 465.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=limitk(5,_a_ten),steps=100-8                                                                                                     560.0 ± 0%                 560.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=limitk(5,_a_hundred),steps=100-8                                                                                                1.456k ± 0%                1.456k ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=limit_ratio(0.1,_a_one),steps=100-8                                                                                              367.0 ± 0%                 367.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=limit_ratio(0.1,_a_ten),steps=100-8                                                                                              665.0 ± 0%                 665.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=limit_ratio(0.1,_a_hundred),steps=100-8                                                                                         1.864k ± 0%                1.864k ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=limit_ratio(0.5,_a_one),steps=100-8                                                                                              367.0 ± 0%                 367.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=limit_ratio(0.5,_a_ten),steps=100-8                                                                                              867.0 ± 0%                 867.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=limit_ratio(0.5,_a_hundred),steps=100-8                                                                                         2.068k ± 0%                2.068k ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=limit_ratio(-0.5,_a_one),steps=100-8                                                                                             469.0 ± 0%                 469.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=limit_ratio(-0.5,_a_ten),steps=100-8                                                                                             867.0 ± 0%                 867.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=limit_ratio(-0.5,_a_hundred),steps=100-8                                                                                        2.068k ± 0%                2.068k ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=rate(a_one[1m])_+_rate(b_one[1m]),steps=100-8                                                                                    520.0 ± 0%                 520.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=rate(a_ten[1m])_+_rate(b_ten[1m]),steps=100-8                                                                                    827.0 ± 0%                 827.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=rate(a_hundred[1m])_+_rate(b_hundred[1m]),steps=100-8                                                                           3.934k ± 0%                3.935k ± 0%       ~ (p=0.448 n=6)
RangeQuery/expr=sum_without_(l)(rate(a_one[1m])),steps=100-8                                                                                     204.0 ± 0%                 204.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=sum_without_(l)(rate(a_ten[1m])),steps=100-8                                                                                     335.0 ± 0%                 335.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=sum_without_(l)(rate(a_hundred[1m])),steps=100-8                                                                                1.596k ± 0%                1.596k ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=sum_without_(l)(rate(a_one[1m]))_/_sum_without_(l)(rate(b_one[1m])),steps=100-8                                                  598.0 ± 0%                 598.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=sum_without_(l)(rate(a_ten[1m]))_/_sum_without_(l)(rate(b_ten[1m])),steps=100-8                                                  860.0 ± 0%                 860.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=sum_without_(l)(rate(a_hundred[1m]))_/_sum_without_(l)(rate(b_hundred[1m])),steps=100-8                                         3.383k ± 0%                3.383k ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=histogram_quantile(0.9,_rate(h_one[5m])),steps=100-8                                                                             602.0 ± 0%                 602.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=histogram_quantile(0.9,_rate(h_ten[5m])),steps=100-8                                                                            2.086k ± 0%                2.086k ± 0%       ~ (p=1.000 n=6)
RangeQuery/expr=histogram_quantile(0.9,_rate(h_hundred[5m])),steps=100-8                                                                        16.77k ± 0%                16.77k ± 0%       ~ (p=0.444 n=6)
RangeQuery/expr=a_one_+_on(l)_group_right_a_one,steps=100-8                                                                                      637.0 ± 0%                 637.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=a_ten_+_on(l)_group_right_a_one,steps=100-8                                                                                      533.0 ± 0%                 533.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=a_hundred_+_on(l)_group_right_a_one,steps=100-8                                                                                 1.705k ± 0%                1.705k ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=count({__name__!=""}),steps=1-8                                                                                                 10.27k ± 0%                10.27k ± 0%       ~ (p=0.455 n=6)
RangeQuery/expr=count({__name__!="",l=""}),steps=1-8                                                                                             256.0 ± 0%                 256.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=timestamp(a_one),steps=100-8                                                                                                     443.0 ± 0%                 443.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=timestamp(a_ten),steps=100-8                                                                                                     578.0 ± 0%                 578.0 ± 0%       ~ (p=1.000 n=6) ¹
RangeQuery/expr=timestamp(a_hundred),steps=100-8                                                                                                1.845k ± 0%                1.845k ± 0%       ~ (p=1.000 n=6)
geomean                                                                                                                                         1.164k                     1.164k       +0.00%
¹ all samples are equal
```

File: promql/engine.go (hunk 1 above)
Comment (NeerajGartia21) [reply promql/engine.go]: Done!

File: promql/engine.go [hunk 2]
```diff
@@ -1359,46 +1359,46 @@ func (ev *evaluator) rangeEvalAgg(ctx context.Context, aggExpr *parser.Aggregate
...
-	switch aggExpr.Op {
-	case parser.TOPK, parser.BOTTOMK, parser.LIMITK:
-		if !convertibleToInt64(param) {
-			ev.errorf("Scalar value %v overflows int64", param)
-		}
-		k = int64(param)
-		if k > int64(len(inputMatrix)) {
-			k = int64(len(inputMatrix))
+	// allParamsMatchCondition returns true if the provided condition holds for every float params.
+	allParamsMatchCondition := func(params []FPoint, constParam bool, condition func(float64) bool) bool {
```
Comment (beorn7) [inline promql/engine.go:1364]: While looking at this, I had another thought how we might want to encapsulate the param handling a bit better. Instead of this local function and some other bells and whistles, how about having an `fParams` interface like this:

```Go
type fParams interface  {
	Next(ts int64) float64
	Max() float64
	Min() float64
	HasAnyNaN() bool
}
```

There could be one implementation for the variable param series, and one for the constant parameter. The former would pre-populate internal fields to to be used for `Max`, `Min`, `HasAnyNaN`. The latter would store one float value and return it always (or just do `math.IsNaN` for the const value).

Then you could do many operations in an efficient way without using separate `if` statements everywhere.

File: promql/engine.go [hunk 3]
```diff
@@ -2937,6 +2941,10 @@ func (ev *evaluator) aggregation(e *parser.AggregateExpr, q float64, inputMatrix
 		groups[i].seen = false
 	}
 
+	if e.Op == parser.QUANTILE && (math.IsNaN(q) || q < 0 || q > 1) {
+		annos.Add(annotations.NewInvalidQuantileWarning(q, e.Param.PositionRange()))
```
Comment (beorn7) [inline promql/engine.go:2945]: Since this annotation is not specific to the affected series, we need at at most once. I think we can do this once ahead of the iteration by checking the max and min and if any is NaN. (See my idea about the interface above.)

If we have many steps, adding all those annotations, that then are promptly removed as duplicates again, could be quite some churn.

File: promql/engine.go [hunk 4]
```diff
@@ -3224,6 +3240,44 @@ seriesLoop:
...
+			}
+			switch {
+			case fParam == 0:
+				if ev.startTimestamp != ev.endTimestamp {
+					advanceRemainingSeries(enh.Ts, si+1)
+				}
+				return nil, annos
+			case fParam < -1.0:
+				r = -1.0
+				annos.Add(annotations.NewInvalidRatioWarning(fParam, r, e.Param.PositionRange()))
```
Comment (beorn7) [inline promql/engine.go:3272]: Like said before for the quantile annotation, maybe this can be done once before the iteration by checking the min of all params?

File: promql/engine.go [hunk 5]
```diff
@@ -3224,6 +3240,44 @@ seriesLoop:
...
+			case fParam > 1.0:
+				r = 1.0
+				annos.Add(annotations.NewInvalidRatioWarning(fParam, r, e.Param.PositionRange()))
```
Comment (beorn7) [inline promql/engine.go:3275]: And similarly this for the max param.

**Review by beorn7 — COMMENTED** [review]
Benchmarks look good.

I had another idea about how to make this a bit more elegant (hopefully). See comments.

Looking forward to what @machine424 thinks about this.

File: promql/engine.go (hunk 2 above)
Comment (NeerajGartia21) [reply promql/engine.go:1364]: That's a good idea. It would make the code more readable. I'll implement it as soon as possible.

File: promql/engine.go (hunk 3 above)
Comment (NeerajGartia21) [reply promql/engine.go]: Done!

**Comment by NeerajGartia21** [comment]
@beorn7, I've restructured the code for param handling with the `fParams` interface. Please have a look again.

File: promql/engine.go [hunk 6]
```diff
@@ -3229,6 +3230,42 @@ seriesLoop:
 		}
 		s = Sample{Metric: inputMatrix[si].Metric, F: f, H: h, DropName: inputMatrix[si].DropName}
 
+		var k int64
+		var r float64
+		switch op {
+		case parser.TOPK, parser.BOTTOMK, parser.LIMITK:
+			if !convertibleToInt64(fParam) {
+				ev.errorf("Scalar value %v overflows int64", fParam)
```
Comment (machine424) [inline promql/engine.go:3238]: IIUC this means if `fParam.series` has a gap somewhere, we'll get something like `Scalar value NaN overflows int64` for the whole range query instead of series with gaps.
(if we want to keep the behavior (easier), maybe we could make the message for range queries more explicit?)

**Review by machine424 — COMMENTED** [review]
thanks, didn't go through all the changes but lgtm overall.
I have a question though.

File: promql/engine.go (hunk 6 above)
Comment (NeerajGartia21) [reply promql/engine.go:3238]: Yes, if any of the `fParam` values is `NaN`, it results in an error like `Scalar value NaN overflows int64`, which doesn’t make it clear that the error occurred during a range query. We could improve this by including the timestamp and the expression that triggered the error to make it more informative.

Comment (NeerajGartia21) [reply promql/engine.go:3238]: I don’t think this will require much additional work. I’ll make the necessary changes shortly.

Comment (NeerajGartia21) [reply promql/engine.go:3238]: Or maybe I should create a separate PR for this, since there are other related issues too — for example, updating  
 ```go
 annos.Add(annotations.NewHistogramIgnoredInAggregationInfo("stdvar", e.Expr.PositionRange()))
 ```  
 to  
 ```go
 annos.Add(annotations.NewHistogramIgnoredInAggregationInfo(parser.ItemTypeStr[op], e.Expr.PositionRange()))
 ```  
I’ll also add tests to verify the expected annotation messages for these cases, which would partially address [#16367](https://github.com/prometheus/prometheus/issues/16367) too.
Since these are related but broader changes, it makes sense to handle them in a separate PR. WDYT?

Comment (machine424) [reply promql/engine.go:3238]: yes, we can have that in another PR

**Comment by NeerajGartia21** [comment]
@machine424, are there any other changes needed besides the TODO you mentioned?

**Review by machine424 — APPROVED** [review]
lgtm, thanks

File: promql/value.go [hunk 7]
```diff
@@ -533,3 +534,67 @@ func (ssi *storageSeriesIterator) Next() chunkenc.ValueType {
...
+		}
+	}
+	return fp, ws
+}
+
+func (fp *fParams) Max() float64    { return fp.maxValue }
+func (fp *fParams) Min() float64    { return fp.minValue }
+func (fp *fParams) HasAnyNaN() bool { return fp.hasAnyNaN }
+
+func (fp *fParams) Next(ts int64) float64 {
```
Comment (beorn7) [inline promql/value.go:590]: I think this is obscure enough to deserve a doc comment.

Currently, I don't understand the logic that checks `ts`. If it doesn't match, the method returns 0, but how does that help me? 0 could as well be the actual value – how do I know that the `ts` did not match?

File: promql/engine.go [hunk 8]
```diff
@@ -1359,46 +1359,43 @@ func (ev *evaluator) rangeEvalAgg(ctx context.Context, aggExpr *parser.Aggregate
...
-		case param > 1.0:
-			ratio = 1.0
-			warnings.Add(annotations.NewInvalidRatioWarning(param, ratio, aggExpr.Param.PositionRange()))
-		default:
-			ratio = param
+		if maxVal := params.Max(); maxVal > 1.0 {
+			annos.Add(annotations.NewInvalidRatioWarning(maxVal, 1.0, aggExpr.Param.PositionRange()))
+		}
+		if minVal := params.Min(); minVal < -1.0 {
+			annos.Add(annotations.NewInvalidRatioWarning(minVal, -1.0, aggExpr.Param.PositionRange()))
```
Comment (beorn7) [inline promql/engine.go:1381]: The method call should be cheap (and it's probably inlined by the compiler anyway), and the branches here are rare anyway. I wouldn't use the intermediate variables `maxVal` and `minVal` here.

File: promql/engine.go [hunk 9]
```diff
@@ -1359,46 +1359,43 @@ func (ev *evaluator) rangeEvalAgg(ctx context.Context, aggExpr *parser.Aggregate
...
+		if maxVal := params.Max(); maxVal > 1 {
+			annos.Add(annotations.NewInvalidQuantileWarning(maxVal, aggExpr.Param.PositionRange()))
+		}
+		if minVal := params.Min(); minVal < 0 {
+			annos.Add(annotations.NewInvalidQuantileWarning(minVal, aggExpr.Param.PositionRange()))
 		}
 	}
 
 	for ts := ev.startTimestamp; ts <= ev.endTimestamp; ts += ev.interval {
+		fParam := params.Next(ts)
```
Comment (beorn7) [inline promql/engine.go:1398]: As said below, I don't quite understand how passing `ts` will help here.

File: promql/engine.go [hunk 10]
```diff
@@ -1359,46 +1359,43 @@ func (ev *evaluator) rangeEvalAgg(ctx context.Context, aggExpr *parser.Aggregate
...
-		if math.IsNaN(param) || param < 0 || param > 1 {
-			warnings.Add(annotations.NewInvalidQuantileWarning(param, aggExpr.Param.PositionRange()))
+		if params.HasAnyNaN() {
+			annos.Add(annotations.NewInvalidQuantileWarning(math.NaN(), aggExpr.Param.PositionRange()))
+		}
+		if maxVal := params.Max(); maxVal > 1 {
+			annos.Add(annotations.NewInvalidQuantileWarning(maxVal, aggExpr.Param.PositionRange()))
+		}
+		if minVal := params.Min(); minVal < 0 {
+			annos.Add(annotations.NewInvalidQuantileWarning(minVal, aggExpr.Param.PositionRange()))
```
Comment (beorn7) [inline promql/engine.go:1393]: As above, I would go for brevity and just call `params.Max()` etc multiple times.

**Review by beorn7 — CHANGES_REQUESTED** [review]
Thank you very much, both @NeerajGartia21 and @machine424 . And apologies for the long wait. I only have a tiny style nit and a more serious question about the `Next` method.

File: promql/engine.go (hunk 8 above)
Comment (NeerajGartia21) [reply promql/engine.go:1381]: I'll do that.

File: promql/value.go (hunk 7 above)
Comment (NeerajGartia21) [reply promql/value.go:590]: No need to check `ts` here. I'll remove it. I initially added it for consistency with `ev.nextValues`, but there it's used differently (to distinguish between float and histogram as the next sample). I'll also add doc comments for clarity.

**Comment by NeerajGartia21** [comment]
@beorn7 , I've added your suggestions. Please have another look. Thanks!

**Review by beorn7 — APPROVED** [review]
OK, let's do it. I hope the actual PromQL experts will not be upset (but they had plenty of time to chime in).

**Comment by beorn7** [comment]
Also, @machine424 approved it. I'd consider him expert enough. :)
