### PR TITLE
promql/parser: fix UTF-8 label quoting in format_query endpoint

### LINKED ISSUE #15243: UTF-8: format_query endpoint returning invalid format
/api/v1/format_query (can be invoked on the text box in the UI) is still broken for UTF-8. At least in on(...), group_left(...) etc. clauses it returns UTF-8 label names in an unquoted way, breaking the returned expression.

### PR DESCRIPTION
**Pull request by adity-a34**
#### Which issue(s) does the PR fix:

Fixes #15243

#### Does this PR introduce a user-facing change?
```release-notes
[BUGFIX] PromQL: Fix UTF-8 label name quoting in format_query API endpoint for binary expressions and aggregations.
```

The `/api/v1/format_query` endpoint was returning invalid PromQL when UTF-8 label names appeared in `on()`, `ignoring()`, `group_left()`, `group_right()`, `by()`, and `without()` clauses. Labels like `"äää"` were rendered unquoted, breaking the expression.

### CODE REVIEW

File: promql/parser/printer.go [hunk 1]
```diff
@@ -145,6 +145,19 @@ func (node *BinaryExpr) ShortString() string {
 	return node.Op.String() + node.returnBool() + node.getMatchingStr()
 }
 
+// joinLabels joins label names, quoting them if they are not valid legacy label names.
+func joinLabels(labels []string) string {
```
Comment (juliusv) [inline promql/parser/printer.go]: This feels duplicated with `writeLabels()` in terms of functionality, even if one returns a string and the other writes directly to the buffer. Could we restructure things to use the existing `writeLabels()` everywhere instead? Or if you prefer, you could also delete the existing `writeLabels()` function and use the new `joinLabels()` function in `writeAggOpStr()` instead. Writing directly to a buffer is more efficient, but I don't think the printer is performance sensitive at all, so this should be fine.

File: promql/parser/printer_test.go [hunk 2]
```diff
@@ -394,3 +398,45 @@ func TestVectorSelector_String(t *testing.T) {
...
+		{
+			name:     "Mixed legacy and UTF-8 labels",
+			input:    `foo / on(legacy, "üüü") bar`,
+			expected: `foo / on (legacy, "üüü") bar`,
+		},
+		{
+			name:     "Legacy labels only (should not quote)",
+			input:    `foo / on(job, instance) bar`,
+			expected: `foo / on (job, instance) bar`,
+		},
```
Comment (juliusv) [inline promql/parser/printer_test.go:445]: Thanks! This addresses the `on()` / `ignoring()`, and `group_xxx()` modifiers, but not yet the label lists for aggregators (like `sum by("äää") (bar)`, `sum without("äää") (bar)`, and so on). Could you update and add tests for those as well?

**Comment by adity-a34** [comment]
Hello @juliusv 
Thanks for the review!
I've refactored the implementation to use `writeLabels()` everywhere and extended the tests as you instructed.

Please review it.

**Comment by adity-a34** [comment]
It seems [CI / fuzzing / Fuzzing (pull_request)](https://github.com/prometheus/prometheus/actions/runs/20232927953/job/58080159125?pr=17687) is failing for all the PRs since yesterday!

File: promql/parser/printer.go [hunk 3]
```diff
@@ -147,22 +147,37 @@ func (node *BinaryExpr) ShortString() string {
...
 			vmTag := "ignoring"
 			if vm.On {
 				vmTag = "on"
 			}
-			matching = fmt.Sprintf(" %s (%s)", vmTag, strings.Join(vm.MatchingLabels, ", "))
+			// Format labels with proper UTF-8 quoting using writeLabels()
+			b.Reset()
+			b.WriteString(" ")
+			b.WriteString(vmTag)
+			b.WriteString(" (")
```
Comment (juliusv) [inline promql/parser/printer.go]: I think `b.WriteString(" " + vmTag + " (")` should be sufficient here, let's not blow it up more than we need to :)

Similar below for `" group_" + vmCard + " ("`.

File: promql/parser/printer.go [hunk 4]
```diff
@@ -147,22 +147,37 @@ func (node *BinaryExpr) ShortString() string {
...
 	vm := node.VectorMatching
 	if vm != nil {
 		if len(vm.MatchingLabels) > 0 || vm.On || vm.Card == CardManyToOne || vm.Card == CardOneToMany {
 			vmTag := "ignoring"
 			if vm.On {
 				vmTag = "on"
 			}
-			matching = fmt.Sprintf(" %s (%s)", vmTag, strings.Join(vm.MatchingLabels, ", "))
+			// Format labels with proper UTF-8 quoting using writeLabels()
+			b.Reset()
```
Comment (juliusv) [inline promql/parser/printer.go]: Since the `bytes.Buffer` is new here, you do not need to call `Reset()` on it. That would only be needed if there is already something in the buffer and you want to reuse it.

Comment (juliusv) [reply promql/parser/printer.go]: And I just researched more and discovered https://github.com/prometheus/prometheus/pull/17067 by @bboreham, because I was wondering why we were using a `bytes.Buffer` rather than simpler string manipulation in the first place.

Turns out, he does care about PromQL printing performance in the context of Mimir apparently. In the other cases in this file, the `bytes.Buffer` is always created & pre-allocated as `bytes.NewBuffer(make([]byte, 0, 1024))`. Maybe @bboreham could advise what he'd prefer in this case.

**Comment by juliusv** [comment]
> It seems [CI / fuzzing / Fuzzing (pull_request)](https://github.com/prometheus/prometheus/actions/runs/20232927953/job/58080159125?pr=17687) is failing for all the PRs since yesterday!

Indeed! Arve already mentioned it on #prometheus-dev on Slack as well. We should just ignore that check until it's fixed.

**Comment by adity-a34** [comment]
@juliusv Thanks! I've simplified the buffer operations; Removed the first `b.Reset()` call, combined the three `WriteString` calls into single statement, kept the second `b.Reset()` call for buffer reuse.

Please review the changes.

File: promql/parser/printer.go (hunk 3 above)
Comment (adity-a34) [reply promql/parser/printer.go]: Combined the three `WriteString` calls into single statements with string concatenation.

**Comment by bboreham** [comment]
Please rebase on main after #17695 to fix the Fuzzing CI failure.

**Comment by adity-a34** [comment]
Hello @juliusv @bboreham 
I have tested the changes, and it is passing the requirements of issue #15243.
This PR is ready for review!


```
adityatiwari@DeathNote:~/temp/prometheus$ go test ./promql/parser -run TestBinaryExprUTF8Labels
ok      github.com/prometheus/prometheus/promql/parser  0.021s
adityatiwari@DeathNote:~/temp/prometheus$ go test ./promql/parser -run TestExprString
ok      github.com/prometheus/prometheus/promql/parser  0.021s
adityatiwari@DeathNote:~/temp/prometheus$ 
```
