### PR TITLE
Tsdb StartTime : Use a simplier way to compute StartTime

### LINKED ISSUE #3340: Consistent startup crash in storage adapter
Using Prometheus built from the
 current `master` with the attached `data` directory ([data.tar.gz](https://github.com/prometheus/prometheus/files/1409032/data.tar.gz)) (which just contains a WAL so far), Prometheus consistently crashes like this:

```
level=info ts=2017-10-23T22:57:16.067433961Z caller=main.go:215 msg="Starting Prometheus" version="(version=2.0.0-rc.1, branch=master, revision=c3d6abc8e6444c33c0071aaddbef402aa553ff68)"
level=info ts=2017-10-23T22:57:16.067475452Z caller=main.go:216 build_context="(go=go1.9, user=julius@julius-samsung, date=20171023-22:56:03)"
level=info ts=2017-10-23T22:57:16.067491611Z caller=main.go:217 host_details="(Linux 4.11.0-14-generic #20~16.04.1-Ubuntu SMP Wed Aug 9 09:06:22 UTC 2017 x86_64 julius-samsung (none))"
level=info ts=2017-10-23T22:57:16.069739337Z caller=web.go:380 component=web msg="Start listening for connections" address=0.0.0.0:9090
level=info ts=2017-10-23T22:57:16.069779637Z caller=main.go:314 msg="Starting TSDB"
level=info ts=2017-10-23T22:57:16.069784013Z caller=targetmanager.go:69 component="target manager" msg="Starting target manager..."
level=info ts=2017-10-23T22:57:16.090802158Z caller=main.go:326 msg="TSDB started"
level=info ts=2017-10-23T22:57:16.090856994Z caller=main.go:394 msg="Loading configuration file" filename=prometheus.yml
level=info ts=2017-10-23T22:57:16.091676177Z caller=main.go:371 msg="Server is ready to receive requests."
panic: runtime error: index out of range

goroutine 242 [running]:
github.com/prometheus/prometheus/storage/tsdb.adapter.StartTime(0xc4203348f0, 0x6ddd00, 0xc420064fa8, 0x42a529, 0xc400000008)
	/home/julius/gosrc/src/github.com/prometheus/prometheus/storage/tsdb/tsdb.go:193 +0x4e0
github.com/prometheus/prometheus/storage/tsdb.(*ReadyStorage).StartTime(0xc420432320, 0x196bf00, 0xc420064f01, 0x297f098)
	/home/julius/gosrc/src/github.com/prometheus/prometheus/storage/tsdb/tsdb.go:68 +0x4e
github.com/prometheus/prometheus/storage/tsdb.(*ReadyStorage).StartTime-fm(0x196bf00, 0x0, 0x0)
	/home/julius/gosrc/src/github.com/prometheus/prometheus/cmd/prometheus/main.go:227 +0x2a
github.com/prometheus/prometheus/storage/remote.(*Storage).Querier(0xc4204b9180, 0x2890c00, 0xc421898a80, 0x15f4b6fdbfa, 0x15f4b746fda, 0x0, 0x0, 0x0, 0x0)
	/home/julius/gosrc/src/github.com/prometheus/prometheus/storage/remote/read.go:33 +0x10a
github.com/prometheus/prometheus/storage.(*fanout).Querier(0xc420052600, 0x2890c00, 0xc421898a80, 0x15f4b6fdbfa, 0x15f4b746fda, 0xffffffbbc166ed07, 0x295be80, 0xa60b19d1f4a2c767, 0xc4200651a8)
	/home/julius/gosrc/src/github.com/prometheus/prometheus/storage/fanout.go:79 +0x1ed
github.com/prometheus/prometheus/promql.(*Engine).populateIterators(0xc420436690, 0x2890c00, 0xc421898a80, 0xc42189e550, 0x411bbc, 0xc4200207e0, 0xc4200652a8, 0x43c81c)
	/home/julius/gosrc/src/github.com/prometheus/prometheus/promql/engine.go:510 +0x2f5
github.com/prometheus/prometheus/promql.(*Engine).execEvalStmt(0xc420436690, 0x2890c00, 0xc421898a80, 0xc420e661c0, 0xc42189e550, 0x0, 0x0, 0x0, 0x0)
	/home/julius/gosrc/src/github.com/prometheus/prometheus/promql/engine.go:361 +0xf5
github.com/prometheus/prometheus/promql.(*Engine).exec(0xc420436690, 0x2890c00, 0xc421898a80, 0xc420e661c0, 0x0, 0x0, 0x0, 0x0)
	/home/julius/gosrc/src/github.com/prometheus/prometheus/promql/engine.go:341 +0x317
github.com/prometheus/prometheus/promql.(*query).Exec(0xc420e661c0, 0x2890b80, 0xc420052f00, 0x2890b80)
	/home/julius/gosrc/src/github.com/prometheus/prometheus/promql/engine.go:179 +0xb8
github.com/prometheus/prometheus/rules.(*AlertingRule).Eval(0xc420444c00, 0x7f05ed803ac8, 0xc420052f00, 0xbe73bad4b609b929, 0x19acba507, 0x295be80, 0xc420436690, 0xc420359700, 0x0, 0x0, ...)
	/home/julius/gosrc/src/github.com/prometheus/prometheus/rules/alerting.go:164 +0x177
github.com/prometheus/prometheus/rules.(*Group).Eval.func1(0x1ba6776, 0x8, 0xc420444d80, 0xbe73bad4b609b929, 0x19acba507, 0x295be80, 0x0, 0x2890ec0, 0xc420444c00)
	/home/julius/gosrc/src/github.com/prometheus/prometheus/rules/manager.go:307 +0x194
github.com/prometheus/prometheus/rules.(*Group).Eval(0xc420444d80, 0xbe73bad4b609b929, 0x19acba507, 0x295be80)
	/home/julius/gosrc/src/github.com/prometheus/prometheus/rules/manager.go:375 +0xbf
github.com/prometheus/prometheus/rules.(*Group).run.func1()
	/home/julius/gosrc/src/github.com/prometheus/prometheus/rules/manager.go:182 +0x81
github.com/prometheus/prometheus/rules.(*Group).run(0xc420444d80)
	/home/julius/gosrc/src/github.com/prometheus/prometheus/rules/manager.go:207 +0x23c
github.com/prometheus/prometheus/rules.(*Manager).ApplyConfig.func1.1(0xc420052f40, 0xc420444d80)
	/home/julius/gosrc/src/github.com/prometheus/prometheus/rules/manager.go:510 +0x46
created by github.com/prometheus/prometheus/rules.(*Manager).ApplyConfig.func1
	/home/julius/gosrc/src/github.com/prometheus/prometheus/rules/manager.go:505 +0x56
```

I'm not aware of anything I did to corrupt the data directory, so this seems like a Prometheus bug to me.

The code where it crashes:

```go
                        if p.Next() {
                                var lset tsdbLabels.Labels
                                var chks []tsdb.ChunkMeta
                                indexr.Series(p.At(), &lset, &chks)
                                if startTime > chks[0].MinTime {    // <--- CRASH HERE
                                        startTime = chks[0].MinTime
                                }
                        }
```

...looks like it expects there to always be a chunk, but maybe my storage doesn't have one for this case yet?

### PR DESCRIPTION
**Pull request by Thib17**
Should fix #3340 
cc @fabxc

### CODE REVIEW

File: storage/tsdb/tsdb.go [hunk 1]
```diff
@@ -151,51 +151,14 @@ func Open(path string, l log.Logger, r prometheus.Registerer, opts *Options) (*t
...
+	var startTime int64
 
-	var indexr tsdb.IndexReader
 	if len(a.db.Blocks()) > 0 {
-		var err error
-		indexr, err = a.db.Blocks()[0].Index()
-		if err != nil {
-			return startTime, err
-		}
+		startTime = a.db.Blocks()[0].Meta().MinTime
```
Comment (brian-brazil) [inline storage/tsdb/tsdb.go]: This is going to be too far back by a block

Comment (Thib17) [reply storage/tsdb/tsdb.go]: According to @fabxc in #3340 it won't because we add the safety margin (`--storage.tsdb.min-block-duration`). Then AFAIK the oldest block is the result of compaction of several smaller blocks. Therefore the difference between `blocks[0].MinTime` and the real first timestamp in the tsdb should be smaller than `min-block-duration`.
Is that right ?

Comment (fabxc) [reply storage/tsdb/tsdb.go]: Yes. Where is the safety margin being added though, or rather, where is `a.startTimeMargin` being set and to what value?

Comment (Thib17) [reply storage/tsdb/tsdb.go]: https://github.com/prometheus/prometheus/blob/master/cmd/prometheus/main.go#L329

Comment (fabxc) [reply storage/tsdb/tsdb.go]: Thanks, that makes sense AFAICS. @brian-brazil any concerns still?

Comment (brian-brazil) [reply storage/tsdb/tsdb.go]: I think we need to double the minimum then. If there's a gap of min-block-duration to the first data point then we still need another block duration to cover a Prometheus that ingests both fresh and maximally-old data.

Comment (fabxc) [reply storage/tsdb/tsdb.go]: Mh, sounds right, 1.5x would be enough but 2x seems safer.
However, it's a heuristic at best anyway. We agree on that, right?

Comment (brian-brazil) [reply storage/tsdb/tsdb.go]: It's a heuristic, but we should be choosing a conservative value to avoid weirdness around the boundary of this setting. It's better to request more data form remote storage than to miss some data due to ingestion with timestamps.

Comment (fabxc) [reply storage/tsdb/tsdb.go]: Yes, totally agreeing. All good then.

**Comment by fabxc** [comment]
Thank you @Thib17 for jumping in so quickly. I've to apologize though. Yesterday morning I read the previous code as traversing all series for a particular job. In fact, it just probed the first one. So my statement on the total cost were false.

Nonetheless, this greatly simplifies some of the logic which is always good. Thanks a lot!
