### PR TITLE
Fixed graph ui max/min logic to accommodate for toggling of stacked graph option

### LINKED ISSUE #2736: Stacked graphs are broken in /graph UI
[NOTICE]: <> (If your question is around usage and not a bug in Prometheus please use: https://groups.google.com/forum/#!forum/prometheus-users)

**What did you do?**

Ran a graph expression and activated the stacked visualization.

**What did you expect to see?**

A nicely stacked graph.

**What did you see instead? Under which circumstances?**

The max y value of the graph doesn't get updated to include the now higher maximum, therefore capping the stacked graph

**Environment**

* Prometheus version: 

	v1.6.0 but should happen in all versions since the latest js changes.

@Conorbro

### PR DESCRIPTION
**Pull request by Conorbro**
Fixes #2736

### CODE REVIEW

File: web/ui/static/js/graph.js [hunk 1]
```diff
@@ -557,24 +557,41 @@ Prometheus.Graph.prototype.updateGraph = function() {
...
 
   // Find and set graph's max/min
-  var min = Infinity;
-  var max = -Infinity;
-  self.data.forEach(function(timeSeries) {
-    timeSeries.data.forEach(function(dataPoint) {
+  if (self.isStacked() === true) {
+    // When stacked is toggled
+    var max = 0;
+    var currSeriesMax = 0;
```
Comment (brian-brazil) [inline web/ui/static/js/graph.js]: it'd be clearer to move this inside the first forEach

**Comment by brancz** [comment]
tried this out and lgtm
