### PR TITLE
Fix returned number of returned time series when scalar

### LINKED ISSUE #2744: Expression browser states two time series returned for `0/ 1000*10^6`
To reproduce, simply run `0/ 1000*10^6` in the expression browser.

It will state `Total time series: 2` when it only displays `scalar 0`

### PR DESCRIPTION
**Pull request by Conorbro**
Fixes #2744

### CODE REVIEW

File: web/ui/static/js/graph.js [hunk 1]
```diff
@@ -415,7 +415,14 @@ Prometheus.Graph.prototype.submitQuery = function() {
           return;
         }
         var duration = new Date().getTime() - startTime;
-        var totalTimeSeries = (xhr.responseJSON.data !== undefined) ? xhr.responseJSON.data.result.length : 0;
+        var totalTimeSeries = 0;
+        if (xhr.responseJSON.data !== undefined) {
+          if (xhr.responseJSON.data.resultType === "scalar") {
+            totalTimeSeries = (xhr.responseJSON.data.result.length/2);
```
Comment (brian-brazil) [inline web/ui/static/js/graph.js]: It'll always be 1.

**Comment by brian-brazil** [comment]
Can you regenerate the bindata?
