### PR TITLE
storage: Increment s.persistErrors on all persist errors

### LINKED ISSUE #2091: Metrics for local storage write failures
**What did you do?**
I ran Prometheus out of disk space

**What did you expect to see?**
An increment in `prometheus_local_storage_series_ops_errors_total` on the `/metrics` of the struggling prometheus. Alternatively, an equivalent change in the metrics which I could use to drive an alert when this happens again.

**What did you see instead? Under which circumstances?**
No clear signal appeared in the metrics. Instead, the problem was discovered when RPCs to alertmanager failed often enough that I read the stderr log of the failing prometheus and saw all the "Error while checkpointing[...] no space left on device" logs created by `MemorySeriesStorage.loop`.
- Prometheus version: 
  
  1.1.3 (plus some local mods which aren't related)
- Logs:

```
time="2016-10-17T13:49:43-04:00" level=error msg="Error while checkpointing: write /var/opt/prometheus/state/heads.db.tmp: no space left on device" source="storage.go:1158"
time="2016-10-17T13:49:43-04:00" level=info msg="Checkpointing in-memory metrics and chunks..." source="persistence.go:548"
```

### PR DESCRIPTION
**Pull request by beorn7**
Fixes #2091

@stuartnelson3 another easy fix.

### CODE REVIEW

File: storage/local/storage.go [hunk 1]
```diff
@@ -1713,14 +1714,21 @@ func (s *MemorySeriesStorage) maintainArchivedSeries(fp model.Fingerprint, befor
...
+		// TODO(beorn7): Should quarantine the series.
+		s.persistErrors.Inc()
 		log.Error("Error dropping persisted chunks: ", err)
 	}
 	if allDropped {
-		s.persistence.purgeArchivedMetric(fp) // Ignoring error. Nothing we can do.
+		if err := s.persistence.purgeArchivedMetric(fp); err != nil {
+			s.persistErrors.Inc()
+			// purgeArchivedMetric logs the error already.
+
```
Comment (brian-brazil) [inline storage/local/storage.go]: extra blank line here
