### PR TITLE
config: Remove validation GetScrapeConfigs; require using config.Load.

### LINKED ISSUE #15538: data race in TestOnlyProviderStaleTargetsAreDropped
### What did you do?

the test failed on unrelated change in https://github.com/prometheus/prometheus/pull/15529

This isn't the first occurrence of the data race

### What did you expect to see?

_No response_

### What did you see instead? Under which circumstances?

```
==================
WARNING: DATA RACE
Read at 0x00c0004fe320 by goroutine 761:
  github.com/prometheus/prometheus/scrape.(*scrapePool).sync()
      /__w/prometheus/prometheus/scrape/scrape.go:479 +0x18f
  github.com/prometheus/prometheus/scrape.(*scrapePool).Sync()
      /__w/prometheus/prometheus/scrape/scrape.go:462 +0x564
  github.com/prometheus/prometheus/scrape.(*Manager).reload.func1()
      /__w/prometheus/prometheus/scrape/manager.go:202 +0x4d
  github.com/prometheus/prometheus/scrape.(*Manager).reload.gowrap1()
      /__w/prometheus/prometheus/scrape/manager.go:204 +0x6e

Previous write at 0x00c0004fe320 by goroutine 710:
  github.com/prometheus/prometheus/config.(*ScrapeConfig).Validate()
      /__w/prometheus/prometheus/config/config.go:795 +0x1e5
  github.com/prometheus/prometheus/config.(*Config).GetScrapeConfigs()
      /__w/prometheus/prometheus/config/config.go:313 +0x204
  github.com/prometheus/prometheus/scrape.applyConfig()
      /__w/prometheus/prometheus/scrape/manager_test.go:1113 +0x14a
  github.com/prometheus/prometheus/scrape.TestOnlyProviderStaleTargetsAreDropped()
      /__w/prometheus/prometheus/scrape/manager_test.go:1339 +0x75d
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1690 +0x226
  testing.(*T).Run.gowrap1()
      /usr/local/go/src/testing/testing.go:1743 +0x44

Goroutine 761 (running) created at:
  github.com/prometheus/prometheus/scrape.(*Manager).reload()
      /__w/prometheus/prometheus/scrape/manager.go:201 +0xb93
  github.com/prometheus/prometheus/scrape.(*Manager).reloader()
      /__w/prometheus/prometheus/scrape/manager.go:161 +0x111
  github.com/prometheus/prometheus/scrape.(*Manager).Run.gowrap1()
      /__w/prometheus/prometheus/scrape/manager.go:122 +0x33

Goroutine 710 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:1743 +0x825
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:2168 +0x85
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1690 +0x226
  testing.runTests()
      /usr/local/go/src/testing/testing.go:2166 +0x8be
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:2034 +0xf17
  go.uber.org/goleak.VerifyTestMain()
      /go/pkg/mod/go.uber.org/goleak@v1.3.0/testmain.go:53 +0x64
  github.com/prometheus/prometheus/util/testutil.TolerantVerifyLeak()
      /__w/prometheus/prometheus/util/testutil/testing.go:34 +0x310
  github.com/prometheus/prometheus/scrape.TestMain()
      /__w/prometheus/prometheus/scrape/scrape_test.go:65 +0x172
  main.main()
      _testmain.go:241 +0x16d
==================
==================
WARNING: DATA RACE
Read at 0x00c0004fe328 by goroutine 761:
  github.com/prometheus/prometheus/scrape.(*scrapePool).sync()
      /__w/prometheus/prometheus/scrape/scrape.go:480 +0x1d8
  github.com/prometheus/prometheus/scrape.(*scrapePool).Sync()
      /__w/prometheus/prometheus/scrape/scrape.go:462 +0x564
  github.com/prometheus/prometheus/scrape.(*Manager).reload.func1()
      /__w/prometheus/prometheus/scrape/manager.go:202 +0x4d
  github.com/prometheus/prometheus/scrape.(*Manager).reload.gowrap1()
      /__w/prometheus/prometheus/scrape/manager.go:204 +0x6e

Previous write at 0x00c0004fe328 by goroutine 710:
  github.com/prometheus/prometheus/config.(*ScrapeConfig).Validate()
      /__w/prometheus/prometheus/config/config.go:798 +0x23c
  github.com/prometheus/prometheus/config.(*Config).GetScrapeConfigs()
      /__w/prometheus/prometheus/config/config.go:313 +0x204
  github.com/prometheus/prometheus/scrape.applyConfig()
      /__w/prometheus/prometheus/scrape/manager_test.go:1113 +0x14a
  github.com/prometheus/prometheus/scrape.TestOnlyProviderStaleTargetsAreDropped()
      /__w/prometheus/prometheus/scrape/manager_test.go:1339 +0x75d
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1690 +0x226
  testing.(*T).Run.gowrap1()
      /usr/local/go/src/testing/testing.go:1743 +0x44

Goroutine 761 (running) created at:
  github.com/prometheus/prometheus/scrape.(*Manager).reload()
      /__w/prometheus/prometheus/scrape/manager.go:201 +0xb93
  github.com/prometheus/prometheus/scrape.(*Manager).reloader()
      /__w/prometheus/prometheus/scrape/manager.go:161 +0x111
  github.com/prometheus/prometheus/scrape.(*Manager).Run.gowrap1()
      /__w/prometheus/prometheus/scrape/manager.go:122 +0x33

Goroutine 710 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:1743 +0x825
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:2168 +0x85
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1690 +0x226
  testing.runTests()
      /usr/local/go/src/testing/testing.go:2166 +0x8be
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:2034 +0xf17
  go.uber.org/goleak.VerifyTestMain()
      /go/pkg/mod/go.uber.org/goleak@v1.3.0/testmain.go:53 +0x64
  github.com/prometheus/prometheus/util/testutil.TolerantVerifyLeak()
      /__w/prometheus/prometheus/util/testutil/testing.go:34 +0x310
  github.com/prometheus/prometheus/scrape.TestMain()
      /__w/prometheus/prometheus/scrape/scrape_test.go:65 +0x172
  main.main()
      _testmain.go:241 +0x16d
==================
==================
WARNING: DATA RACE
Read at 0x00c0004fe338 by goroutine 761:
  github.com/prometheus/prometheus/scrape.(*scrapePool).sync()
      /__w/prometheus/prometheus/scrape/scrape.go:484 +0x2d1
  github.com/prometheus/prometheus/scrape.(*scrapePool).Sync()
      /__w/prometheus/prometheus/scrape/scrape.go:462 +0x564
  github.com/prometheus/prometheus/scrape.(*Manager).reload.func1()
      /__w/prometheus/prometheus/scrape/manager.go:202 +0x4d
  github.com/prometheus/prometheus/scrape.(*Manager).reload.gowrap1()
      /__w/prometheus/prometheus/scrape/manager.go:204 +0x6e

Previous write at 0x00c0004fe338 by goroutine 710:
  github.com/prometheus/prometheus/config.(*ScrapeConfig).Validate()
      /__w/prometheus/prometheus/config/config.go:804 +0x2ea
  github.com/prometheus/prometheus/config.(*Config).GetScrapeConfigs()
      /__w/prometheus/prometheus/config/config.go:313 +0x204
  github.com/prometheus/prometheus/scrape.applyConfig()
      /__w/prometheus/prometheus/scrape/manager_test.go:1113 +0x14a
  github.com/prometheus/prometheus/scrape.TestOnlyProviderStaleTargetsAreDropped()
      /__w/prometheus/prometheus/scrape/manager_test.go:1339 +0x75d
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1690 +0x226
  testing.(*T).Run.gowrap1()
      /usr/local/go/src/testing/testing.go:1743 +0x44

Goroutine 761 (running) created at:
  github.com/prometheus/prometheus/scrape.(*Manager).reload()
      /__w/prometheus/prometheus/scrape/manager.go:201 +0xb93
  github.com/prometheus/prometheus/scrape.(*Manager).reloader()
      /__w/prometheus/prometheus/scrape/manager.go:161 +0x111
  github.com/prometheus/prometheus/scrape.(*Manager).Run.gowrap1()
      /__w/prometheus/prometheus/scrape/manager.go:122 +0x33

Goroutine 710 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:1743 +0x825
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:2168 +0x85
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1690 +0x226
  testing.runTests()
      /usr/local/go/src/testing/testing.go:2166 +0x8be
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:2034 +0xf17
  go.uber.org/goleak.VerifyTestMain()
      /go/pkg/mod/go.uber.org/goleak@v1.3.0/testmain.go:53 +0x64
  github.com/prometheus/prometheus/util/testutil.TolerantVerifyLeak()
      /__w/prometheus/prometheus/util/testutil/testing.go:34 +0x310
  github.com/prometheus/prometheus/scrape.TestMain()
      /__w/prometheus/prometheus/scrape/scrape_test.go:65 +0x172
  main.main()
      _testmain.go:241 +0x16d
==================
==================
WARNING: DATA RACE
Read at 0x00c0004fe340 by goroutine 761:
  github.com/prometheus/prometheus/scrape.(*scrapePool).sync()
      /__w/prometheus/prometheus/scrape/scrape.go:485 +0x34e
  github.com/prometheus/prometheus/scrape.(*scrapePool).Sync()
      /__w/prometheus/prometheus/scrape/scrape.go:462 +0x564
  github.com/prometheus/prometheus/scrape.(*Manager).reload.func1()
      /__w/prometheus/prometheus/scrape/manager.go:202 +0x4d
  github.com/prometheus/prometheus/scrape.(*Manager).reload.gowrap1()
      /__w/prometheus/prometheus/scrape/manager.go:204 +0x6e

Previous write at 0x00c0004fe340 by goroutine 710:
  github.com/prometheus/prometheus/config.(*ScrapeConfig).Validate()
      /__w/prometheus/prometheus/config/config.go:807 +0x344
  github.com/prometheus/prometheus/config.(*Config).GetScrapeConfigs()
      /__w/prometheus/prometheus/config/config.go:313 +0x204
  github.com/prometheus/prometheus/scrape.applyConfig()
      /__w/prometheus/prometheus/scrape/manager_test.go:1113 +0x14a
  github.com/prometheus/prometheus/scrape.TestOnlyProviderStaleTargetsAreDropped()
      /__w/prometheus/prometheus/scrape/manager_test.go:1339 +0x75d
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1690 +0x226
  testing.(*T).Run.gowrap1()
      /usr/local/go/src/testing/testing.go:1743 +0x44

Goroutine 761 (running) created at:
  github.com/prometheus/prometheus/scrape.(*Manager).reload()
      /__w/prometheus/prometheus/scrape/manager.go:201 +0xb93
  github.com/prometheus/prometheus/scrape.(*Manager).reloader()
      /__w/prometheus/prometheus/scrape/manager.go:161 +0x111
  github.com/prometheus/prometheus/scrape.(*Manager).Run.gowrap1()
      /__w/prometheus/prometheus/scrape/manager.go:122 +0x33

Goroutine 710 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:1743 +0x825
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:2168 +0x85
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1690 +0x226
  testing.runTests()
      /usr/local/go/src/testing/testing.go:2166 +0x8be
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:2034 +0xf17
  go.uber.org/goleak.VerifyTestMain()
      /go/pkg/mod/go.uber.org/goleak@v1.3.0/testmain.go:53 +0x64
  github.com/prometheus/prometheus/util/testutil.TolerantVerifyLeak()
      /__w/prometheus/prometheus/util/testutil/testing.go:34 +0x310
  github.com/prometheus/prometheus/scrape.TestMain()
      /__w/prometheus/prometheus/scrape/scrape_test.go:65 +0x172
  main.main()
      _testmain.go:241 +0x16d
==================
==================
WARNING: DATA RACE
Read at 0x00c0004fe348 by goroutine 761:
  github.com/prometheus/prometheus/scrape.(*scrapePool).sync()
      /__w/prometheus/prometheus/scrape/scrape.go:486 +0x3cc
  github.com/prometheus/prometheus/scrape.(*scrapePool).Sync()
      /__w/prometheus/prometheus/scrape/scrape.go:462 +0x564
  github.com/prometheus/prometheus/scrape.(*Manager).reload.func1()
      /__w/prometheus/prometheus/scrape/manager.go:202 +0x4d
  github.com/prometheus/prometheus/scrape.(*Manager).reload.gowrap1()
      /__w/prometheus/prometheus/scrape/manager.go:204 +0x6e

Previous write at 0x00c0004fe348 by goroutine 710:
  github.com/prometheus/prometheus/config.(*ScrapeConfig).Validate()
      /__w/prometheus/prometheus/config/config.go:810 +0x39b
  github.com/prometheus/prometheus/config.(*Config).GetScrapeConfigs()
      /__w/prometheus/prometheus/config/config.go:313 +0x204
  github.com/prometheus/prometheus/scrape.applyConfig()
      /__w/prometheus/prometheus/scrape/manager_test.go:1113 +0x14a
  github.com/prometheus/prometheus/scrape.TestOnlyProviderStaleTargetsAreDropped()
      /__w/prometheus/prometheus/scrape/manager_test.go:1339 +0x75d
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1690 +0x226
  testing.(*T).Run.gowrap1()
      /usr/local/go/src/testing/testing.go:1743 +0x44

Goroutine 761 (running) created at:
  github.com/prometheus/prometheus/scrape.(*Manager).reload()
      /__w/prometheus/prometheus/scrape/manager.go:201 +0xb93
  github.com/prometheus/prometheus/scrape.(*Manager).reloader()
      /__w/prometheus/prometheus/scrape/manager.go:161 +0x111
  github.com/prometheus/prometheus/scrape.(*Manager).Run.gowrap1()
      /__w/prometheus/prometheus/scrape/manager.go:122 +0x33

Goroutine 710 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:1743 +0x825
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:2168 +0x85
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1690 +0x226
  testing.runTests()
      /usr/local/go/src/testing/testing.go:2166 +0x8be
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:2034 +0xf17
  go.uber.org/goleak.VerifyTestMain()
      /go/pkg/mod/go.uber.org/goleak@v1.3.0/testmain.go:53 +0x64
  github.com/prometheus/prometheus/util/testutil.TolerantVerifyLeak()
      /__w/prometheus/prometheus/util/testutil/testing.go:34 +0x310
  github.com/prometheus/prometheus/scrape.TestMain()
      /__w/prometheus/prometheus/scrape/scrape_test.go:65 +0x172
  main.main()
      _testmain.go:241 +0x16d
==================
==================
WARNING: DATA RACE
Read at 0x00c0004fe368 by goroutine 761:
  github.com/prometheus/prometheus/scrape.(*scrapePool).sync()
      /__w/prometheus/prometheus/scrape/scrape.go:499 +0x68d
  github.com/prometheus/prometheus/scrape.(*scrapePool).Sync()
      /__w/prometheus/prometheus/scrape/scrape.go:462 +0x564
  github.com/prometheus/prometheus/scrape.(*Manager).reload.func1()
      /__w/prometheus/prometheus/scrape/manager.go:202 +0x4d
  github.com/prometheus/prometheus/scrape.(*Manager).reload.gowrap1()
      /__w/prometheus/prometheus/scrape/manager.go:204 +0x6e

Previous write at 0x00c0004fe368 by goroutine 710:
  github.com/prometheus/prometheus/config.(*ScrapeConfig).Validate()
      /__w/prometheus/prometheus/config/config.go:842 +0x82f
  github.com/prometheus/prometheus/config.(*Config).GetScrapeConfigs()
      /__w/prometheus/prometheus/config/config.go:313 +0x204
  github.com/prometheus/prometheus/scrape.applyConfig()
      /__w/prometheus/prometheus/scrape/manager_test.go:1113 +0x14a
  github.com/prometheus/prometheus/scrape.TestOnlyProviderStaleTargetsAreDropped()
      /__w/prometheus/prometheus/scrape/manager_test.go:1339 +0x75d
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1690 +0x226
  testing.(*T).Run.gowrap1()
      /usr/local/go/src/testing/testing.go:1743 +0x44

Goroutine 761 (running) created at:
  github.com/prometheus/prometheus/scrape.(*Manager).reload()
      /__w/prometheus/prometheus/scrape/manager.go:201 +0xb93
  github.com/prometheus/prometheus/scrape.(*Manager).reloader()
      /__w/prometheus/prometheus/scrape/manager.go:161 +0x111
  github.com/prometheus/prometheus/scrape.(*Manager).Run.gowrap1()
      /__w/prometheus/prometheus/scrape/manager.go:122 +0x33

Goroutine 710 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:1743 +0x825
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:2168 +0x85
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1690 +0x226
  testing.runTests()
      /usr/local/go/src/testing/testing.go:2166 +0x8be
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:2034 +0xf17
  go.uber.org/goleak.VerifyTestMain()
      /go/pkg/mod/go.uber.org/goleak@v1.3.0/testmain.go:53 +0x64
  github.com/prometheus/prometheus/util/testutil.TolerantVerifyLeak()
      /__w/prometheus/prometheus/util/testutil/testing.go:34 +0x310
  github.com/prometheus/prometheus/scrape.TestMain()
      /__w/prometheus/prometheus/scrape/scrape_test.go:65 +0x172
  main.main()
      _testmain.go:241 +0x16d
==================
==================
WARNING: DATA RACE
Read at 0x00c0004fe330 by goroutine 761:
  github.com/prometheus/prometheus/scrape.(*scrapePool).refreshTargetLimitErr()
      /__w/prometheus/prometheus/scrape/scrape.go:599 +0x8a
  github.com/prometheus/prometheus/scrape.(*scrapePool).sync()
      /__w/prometheus/prometheus/scrape/scrape.go:580 +0x179d
  github.com/prometheus/prometheus/scrape.(*scrapePool).Sync()
      /__w/prometheus/prometheus/scrape/scrape.go:462 +0x564
  github.com/prometheus/prometheus/scrape.(*Manager).reload.func1()
      /__w/prometheus/prometheus/scrape/manager.go:202 +0x4d
  github.com/prometheus/prometheus/scrape.(*Manager).reload.gowrap1()
      /__w/prometheus/prometheus/scrape/manager.go:204 +0x6e

Previous write at 0x00c0004fe330 by goroutine 710:
  github.com/prometheus/prometheus/config.(*ScrapeConfig).Validate()
      /__w/prometheus/prometheus/config/config.go:801 +0x293
  github.com/prometheus/prometheus/config.(*Config).GetScrapeConfigs()
      /__w/prometheus/prometheus/config/config.go:313 +0x204
  github.com/prometheus/prometheus/scrape.applyConfig()
      /__w/prometheus/prometheus/scrape/manager_test.go:1113 +0x14a
  github.com/prometheus/prometheus/scrape.TestOnlyProviderStaleTargetsAreDropped()
      /__w/prometheus/prometheus/scrape/manager_test.go:1339 +0x75d
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1690 +0x226
  testing.(*T).Run.gowrap1()
      /usr/local/go/src/testing/testing.go:1743 +0x44

Goroutine 761 (running) created at:
  github.com/prometheus/prometheus/scrape.(*Manager).reload()
      /__w/prometheus/prometheus/scrape/manager.go:201 +0xb93
  github.com/prometheus/prometheus/scrape.(*Manager).reloader()
      /__w/prometheus/prometheus/scrape/manager.go:161 +0x111
  github.com/prometheus/prometheus/scrape.(*Manager).Run.gowrap1()
      /__w/prometheus/prometheus/scrape/manager.go:122 +0x33

Goroutine 710 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:1743 +0x825
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:2168 +0x85
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1690 +0x226
  testing.runTests()
      /usr/local/go/src/testing/testing.go:2166 +0x8be
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:2034 +0xf17
  go.uber.org/goleak.VerifyTestMain()
      /go/pkg/mod/go.uber.org/goleak@v1.3.0/testmain.go:53 +0x64
  github.com/prometheus/prometheus/util/testutil.TolerantVerifyLeak()
      /__w/prometheus/prometheus/util/testutil/testing.go:34 +0x310
  github.com/prometheus/prometheus/scrape.TestMain()
      /__w/prometheus/prometheus/scrape/scrape_test.go:65 +0x172
  main.main()
      _testmain.go:241 +0x16d
==================
--- FAIL: TestOnlyProviderStaleTargetsAreDropped (0.30s)
    testing.go:1399: race detected during execution of test
2024/12/04 16:25:33 http: TLS handshake error from 127.0.0.1:55474: remote error: tls: bad certificate
FAIL
FAIL	github.com/prometheus/prometheus/scrape	24.160s
```

### System information

_No response_

### Prometheus version

_No response_

### Prometheus configuration file

_No response_

### Alertmanager version

_No response_

### Alertmanager configuration file

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by bwplotka**
We should never modify (or even shallow copy) Config after config.Load; added comments and modified GetScrapeConfigs to do so. For GetScrapeConfigs the validation (even repeated) was likely doing writes (because global fields was 0). We GetScrapeConfigs concurrently in tests and ApplyConfig causing test races. In prod there were races but likelyt only to replace 0 with 0, so not too severe.

I removed validation since I don't see anyone using our config.Config without Load. I had to refactor one test that was doing it, all others use yaml config.

Fixes #15538
Previous attempt: https://github.com/prometheus/prometheus/pull/15634

### CODE REVIEW

File: config/config.go [hunk 1]
```diff
@@ -302,24 +306,24 @@ func (c Config) String() string {
 	return string(b)
 }
 
-// GetScrapeConfigs returns the scrape configurations.
+// GetScrapeConfigs returns the read-only, validated scrape configurations including
+// the ones from the scrape_config_files.
+// This method does not write to config, and it's concurrency safe (the pointer receiver is for efficiency).
+// This method also assumes the Config was created by Load, due to races,
+// read mode https://github.com/prometheus/prometheus/issues/15538.
```
Comment (ArthurSens) [inline config/config.go:313]:
```suggestion
// read more https://github.com/prometheus/prometheus/issues/15538.
```

File: config/config.go [hunk 2]
```diff
@@ -355,6 +359,7 @@ func (c *Config) GetScrapeConfigs() ([]*ScrapeConfig, error) {
 }
 
 // UnmarshalYAML implements the yaml.Unmarshaler interface.
+// NOTE: This method should not be used outside of this package. Use Load or LoadFile instead.
 func (c *Config) UnmarshalYAML(unmarshal func(interface{}) error) error {
```
Comment (ArthurSens) [inline config/config.go:363]: Why is this public then? To fulfill an interface?

File: config/config.go [hunk 3]
```diff
@@ -302,24 +306,24 @@ func (c Config) String() string {
...
-// GetScrapeConfigs returns the scrape configurations.
+// GetScrapeConfigs returns the read-only, validated scrape configurations including
+// the ones from the scrape_config_files.
+// This method does not write to config, and it's concurrency safe (the pointer receiver is for efficiency).
+// This method also assumes the Config was created by Load, due to races,
+// read mode https://github.com/prometheus/prometheus/issues/15538.
 func (c *Config) GetScrapeConfigs() ([]*ScrapeConfig, error) {
-	scfgs := make([]*ScrapeConfig, len(c.ScrapeConfigs))
+	if !c.loaded {
+		return nil, errors.New("main config scrape configs was not validated and loaded; GetScrapeConfigs method can only be used on configuration from the config.Load or config.LoadFile")
```
Comment (ArthurSens) [inline config/config.go:316]: Is there any chance we can log this error to a user? Sounds very developer-focused

**Review by ArthurSens — COMMENTED** [review]
overall LGTM, just some questions/comments

**Review by machine424 — COMMENTED** [review]
lgtm as well, thanks for this.
(I'll look tomorrow at the tests changes when I have some time)

File: config/config.go (hunk 2 above)
Comment (bwplotka) [reply config/config.go:363]: Correct.

File: config/config.go (hunk 3 above)
Comment (bwplotka) [reply config/config.go:316]: There is, but should be caught by the error. What's the alternative you suggest? (:

Comment (bwplotka) [reply config/config.go]: Would we prefer panic here? I would ok with that.

Otherwise I think we could indeed make it obvious and say "config was not validated and loaded; programmatic error, should never happened").

If we don't check here, there will be more confusing error later on (e.g. "interval should be 0" because globals were not updated). Revalidation risk races (:

Comment (machine424) [reply config/config.go]: Yes, a panic seems better as this would be a misuse and it's better to fail earlier.

Comment (bwplotka) [reply config/config.go]: One way to avoid this is to make `config.Config` private, so no one can create it and `Load` will have to be used. This will be no go idiomatic, but might work. Otherwise the best long term solution is to split config into type that's parsed and validated and then to type that's actually used in code (without global section etc).

Comment (bwplotka) [reply config/config.go]: Improved the message and commentary.

**Review by ArthurSens — APPROVED** [review]
LGTM

**Comment by juliusv** [comment]
This was merged on Dec 12, but I just got the same error again on Dec 14 unfortunately.
