### PR TITLE
relabeling: Fix labelmap action validation with legacy metric name scheme

### LINKED ISSUE #17370: prometheus v3.7.0 fails to start with relabeling config
### What did you do?

i upgraded prometheus on GKE via prometheus-operator from version 3.6.0 to 3.7.0

### What did you expect to see?

prometheus starts up successfully 

### What did you see instead? Under which circumstances?

prometheus fails to start with the error `parsing YAML file /etc/prometheus/config_out/prometheus.env.yaml: \"$1\" is invalid 'replacement' for labelmap action` 

### System information

Kuberentes 1.32

### Prometheus version

```text
Prometheus 3.7.0
```

### Prometheus configuration file

```yaml
- job_name: podMonitor/com-dev-kafka-cluster/entity-operator-resources-metrics/0
  honor_labels: false
  kubernetes_sd_configs:
  - role: pod
    namespaces:
      names:
      - com-dev-kafka-cluster
  metrics_path: /metrics
  relabel_configs:
  - source_labels:
    - job
    target_label: __tmp_prometheus_job_name
  - action: drop
    source_labels:
    - __meta_kubernetes_pod_phase
    regex: (Failed|Succeeded)
  - action: keep
    source_labels:
    - __meta_kubernetes_pod_label_strimzi_io_component_type
    - __meta_kubernetes_pod_labelpresent_strimzi_io_component_type
    regex: (entity-operator);true
  - action: keep
    source_labels:
    - __meta_kubernetes_pod_container_port_name
    regex: healthcheck
  - source_labels:
    - __meta_kubernetes_namespace
    target_label: namespace
  - source_labels:
    - __meta_kubernetes_pod_container_name
    target_label: container
  - source_labels:
    - __meta_kubernetes_pod_name
    target_label: pod
  - target_label: job
    replacement: com-dev-kafka-cluster/entity-operator-resources-metrics
  - target_label: endpoint
    replacement: healthcheck
  - regex: __meta_kubernetes_pod_label_(strimzi_io_.+)
    action: labelmap
  - source_labels:
    - __meta_kubernetes_namespace
    separator: ;
    target_label: namespace
    regex: (.*)
    replacement: $1
    action: replace
```

### Alertmanager version

```text

```

### Alertmanager configuration file

```yaml

```

### Logs

```text
{
  "time": "2025-10-20T07:08:18.575139903Z",
  "level": "ERROR",
  "source": "main.go:642",
  "msg": "Error loading config (--config.file=/etc/prometheus/config_out/prometheus.env.yaml)",
  "file": "/etc/prometheus/config_out/prometheus.env.yaml",
  "err": "parsing YAML file /etc/prometheus/config_out/prometheus.env.yaml: \"$1\" is invalid 'replacement' for labelmap action"
}
```

### PR DESCRIPTION
**Pull request by roidelapluie**
Fixes #17370

In Prometheus v3.7.0, using labelmap actions with replacement patterns containing regex variables (e.g., `$1`, `${1}`) would fail validation when `metric_name_validation_scheme` was set to `legacy`, causing Prometheus to fail at startup with:
  "$1" is invalid 'replacement' for labelmap action

This was a regression as the same configuration worked in v3.6.0.

The issue was in the validation logic: while UTF-8 validation correctly allowed `$` characters, legacy validation incorrectly used `IsValidLabelName` which rejects `$` characters. The fix ensures legacy validation uses `relabelTargetLegacy` regex which explicitly supports regex template variables.

Added test cases to verify labelmap validation works with both `$1` and `${1}` replacement patterns under legacy validation scheme.

#### Does this PR introduce a user-facing change?

```release-notes
[BUGFIX] relabeling: Fix labelmap action validation with legacy metric name scheme
```

### CODE REVIEW

File: model/relabel/relabel.go [hunk 1]
```diff
@@ -145,7 +145,13 @@ func (c *Config) Validate(nameValidationScheme model.ValidationScheme) error {
 		// UTF-8 allows ${} characters, so standard validation allow $variables by default.
 		// TODO(bwplotka): Relabelling users cannot put $ and ${<...>} characters in metric names or values.
 		// Design escaping mechanism to allow that, once valid use case appears.
-		return c.NameValidationScheme.IsValidLabelName(value)
+		switch c.NameValidationScheme {
+		case model.UTF8Validation:
+			return c.NameValidationScheme.IsValidLabelName(value)
+		default:
+			// For legacy validation, use the legacy regex that allows $variables.
+			return relabelTargetLegacy.Match([]byte(value))
```
Comment (aknuds1) [inline model/relabel/relabel.go]: [Nit]
```suggestion
			return relabelTargetLegacy.MatchString(value)
```

**Review by aknuds1 — APPROVED** [review]
LGTM modulo nit.

**Comment by KyriosGN0** [comment]
@roidelapluie Thanks!
