### PR TITLE
storage: Sanity-check number of loaded chunk descs

### LINKED ISSUE #2249: runtime error: index out of range
**What did you do?**
Nothing, abrupt service panic
**What did you expect to see?**
That it continued working.
**What did you see instead? Under which circumstances?**
Last night at 22:48 our Prometheus service stopped ingesting data and serving requests
**Environment**
* System information:
	Docker v.1.12.1
	Linux 3.13.0-96-generic x86_64
* Prometheus version: 
	v1.3.1
* Logs:
```
time="2016-12-04T21:48:01Z" level=warning msg="Storage has entered rushed mode." chunksToPersist=149515 maxChunksToPersist=524288 maxMemoryChunks=500000 memoryChunks=544659 source="storage.go:1607" urgencyScore=0.8931800000000001
time="2016-12-04T21:48:01Z" level=info msg="Storage has left rushed mode." chunksToPersist=149466 maxChunksToPersist=524288 maxMemoryChunks=500000 memoryChunks=469612 source="storage.go:1594" urgencyScore=0.2850837707519531
time="2016-12-04T21:48:14Z" level=warning msg="Storage has entered rushed mode." chunksToPersist=149372 maxChunksToPersist=524288 maxMemoryChunks=500000 memoryChunks=541605 source="storage.go:1607" urgencyScore=0.8321000000000001
time="2016-12-04T21:48:15Z" level=error msg="Storage needs throttling. Scrapes and rule evaluations will be skipped." chunksToPersist=149017 maxChunksToPersist=524288 maxToleratedMemChunks=550000 memoryChunks=584381 source="storage.go:908"
time="2016-12-04T21:48:15Z" level=info msg="Storage has left rushed mode." chunksToPersist=148975 maxChunksToPersist=524288 maxMemoryChunks=500000 memoryChunks=529466 source="storage.go:1594" urgencyScore=0.5893199999999998
time="2016-12-04T21:48:15Z" level=warning msg="Storage has entered rushed mode." chunksToPersist=148957 maxChunksToPersist=524288 maxMemoryChunks=500000 memoryChunks=540245 source="storage.go:1607" urgencyScore=0.8048999999999995
time="2016-12-04T21:48:19Z" level=error msg="
http: panic serving 172.16.5.1:58461: runtime error: index out of range
goroutine 49313231 [running]:
net/http.(*conn).serve.func1(0xc4852efb00)
	/usr/local/go/src/net/http/server.go:1491 +0x12a
panic(0x1785e00, 0xc4200140c0)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/prometheus/prometheus/storage/local.(*memorySeries).preloadChunksForRange(0xc4c84b6af0, 0xe6f63760970a017f, 0x158314b8270, 0x158cbcede50, 0xc420266140, 0x2469c40, 0xc48f9a46c0, 0x0, 0x0)
	/go/src/github.com/prometheus/prometheus/storage/local/series.go:468 +0x73d
github.com/prometheus/prometheus/storage/local.(*MemorySeriesStorage).preloadChunksForRange(0xc420266140, 0xe6f63760970a017f, 0xc4c84b6af0, 0x158314b8270, 0x158cbcede50, 0x0, 0x0)
	/go/src/github.com/prometheus/prometheus/storage/local/storage.go:992 +0xd1
github.com/prometheus/prometheus/storage/local.(*MemorySeriesStorage).QueryRange(0xc420266140, 0x7fc433d230d0, 0xc4903f0c60, 0x158314b8270, 0x158cbcede50, 0xc4a1e71fa0, 0x2, 0x2, 0x6, 0x6, ...)
	/go/src/github.com/prometheus/prometheus/storage/local/storage.go:506 +0x154
github.com/prometheus/prometheus/storage/local.memorySeriesStorageQuerier.QueryRange(0xc420266140, 0x7fc433d230d0, 0xc4903f0c60, 0x158314b8270, 0x158cbcede50, 0xc4a1e71fa0, 0x2, 0x2, 0x50, 0x48, ...)
	<autogenerated>:66 +0xa0
github.com/prometheus/prometheus/promql.(*Engine).populateIterators.func1(0x7fc435d3eb90, 0xc443e31f90, 0x4125ff)
	/go/src/github.com/prometheus/prometheus/promql/engine.go:494 +0x41f
github.com/prometheus/prometheus/promql.inspector.Visit(0xc43e3a46c0, 0x7fc435d3eb90, 0xc443e31f90, 0xeee5679e69, 0x0)
	/go/src/github.com/prometheus/prometheus/promql/ast.go:306 +0x3a
github.com/prometheus/prometheus/promql.Walk(0x245b040, 0xc43e3a46c0, 0x7fc435d3eb90, 0xc443e31f90)
	/go/src/github.com/prometheus/prometheus/promql/ast.go:255 +0x7b
github.com/prometheus/prometheus/promql.Walk(0x245b040, 0xc43e3a46c0, 0x7fc435d3ecf0, 0xc4433bc050)
	/go/src/github.com/prometheus/prometheus/promql/ast.go:278 +0x51d
github.com/prometheus/prometheus/promql.Walk(0x245b040, 0xc43e3a46c0, 0x245afc0, 0xc4a4406140)
	/go/src/github.com/prometheus/prometheus/promql/ast.go:275 +0x234
github.com/prometheus/prometheus/promql.Walk(0x245b040, 0xc43e3a46c0, 0x7fc435d3ec98, 0xc4a4406120)
	/go/src/github.com/prometheus/prometheus/promql/ast.go:285 +0x74a
github.com/prometheus/prometheus/promql.Inspect(0x7fc435d3ec98, 0xc4a4406120, 0xc43e3a46c0)
	/go/src/github.com/prometheus/prometheus/promql/ast.go:316 +0x4b
github.com/prometheus/prometheus/promql.(*Engine).populateIterators(0xc420461a40, 0x7fc433d230d0, 0xc4903f0c60, 0x246e080, 0xc420266140, 0xc490b244e0, 0x0, 0x2)
	/go/src/github.com/prometheus/prometheus/promql/engine.go:511 +0x123
github.com/prometheus/prometheus/promql.(*Engine).execEvalStmt(0xc420461a40, 0x7fc433d230d0, 0xc4903f0c60, 0xc43e3a4240, 0xc490b244e0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/prometheus/prometheus/promql/engine.go:366 +0x1b6
github.com/prometheus/prometheus/promql.(*Engine).exec(0xc420461a40, 0x7fc433d230d0, 0xc4903f0c60, 0xc43e3a4240, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/prometheus/prometheus/promql/engine.go:349 +0x3a9
github.com/prometheus/prometheus/promql.(*query).Exec(0xc43e3a4240, 0x7fc435b7cb38, 0xc43e3be740, 0x15831501650)
	/go/src/github.com/prometheus/prometheus/promql/engine.go:196 +0x52
github.com/prometheus/prometheus/web/api/v1.(*API).queryRange(0xc4203f3b30, 0xc4a3f7f680, 0x8000104, 0x0, 0xffffffffffffffff)
	/go/src/github.com/prometheus/prometheus/web/api/v1/api.go:212 +0x601
github.com/prometheus/prometheus/web/api/v1.(*API).(github.com/prometheus/prometheus/web/api/v1.queryRange)-fm(0xc4a3f7f680, 0xc4a44060c0, 0x4, 0x0)
	/go/src/github.com/prometheus/prometheus/web/api/v1/api.go:126 +0x34
github.com/prometheus/prometheus/web/api/v1.(*API).Register.func1.1(0x24620c0, 0xc4a44060c0, 0xc4a3f7f680)
	/go/src/github.com/prometheus/prometheus/web/api/v1/api.go:110 +0x55
net/http.HandlerFunc.ServeHTTP(0xc42033ddd0, 0x24620c0, 0xc4a44060c0, 0xc4a3f7f680)
	/usr/local/go/src/net/http/server.go:1726 +0x44
github.com/prometheus/prometheus/util/httputil.CompressionHandler.ServeHTTP(0x245c440, 0xc42033ddd0, 0x2462480, 0xc4758b3720, 0xc4a3f7f680)
	/go/src/github.com/prometheus/prometheus/util/httputil/compression.go:90 +0x7c
github.com/prometheus/prometheus/util/httputil.(*CompressionHandler).ServeHTTP(0xc42033dde0, 0x2462480, 0xc4758b3720, 0xc4a3f7f680)
	<autogenerated>:5 +0x79
net/http.(Handler).ServeHTTP-fm(0x2462480, 0xc4758b3720, 0xc4a3f7f680)
	/go/src/github.com/prometheus/prometheus/web/web.go:173 +0x4d
github.com/prometheus/prometheus/vendor/github.com/prometheus/client_golang/prometheus.InstrumentHandlerFuncWithOpts.func1(0x2468240, 0xc42160a270, 0xc4a3f7f680)
	/go/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/client_golang/prometheus/http.go:287 +0x2ab
github.com/prometheus/prometheus/vendor/github.com/prometheus/common/route.(*Router).handle.func1(0x2468240, 0xc42160a270, 0xc4a3f7f680, 0x0, 0x0, 0x0)
	/go/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/common/route/route.go:83 +0x2ba
github.com/prometheus/prometheus/vendor/github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc420391140, 0x2468240, 0xc42160a270, 0xc4a3f7f680)
	/go/src/github.com/prometheus/prometheus/vendor/github.com/julienschmidt/httprouter/router.go:299 +0x7ec
github.com/prometheus/prometheus/vendor/github.com/prometheus/common/route.(*Router).ServeHTTP(0xc420461b00, 0x2468240, 0xc42160a270, 0xc4a3f7f680)
	/go/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/common/route/route.go:125 +0x4c
net/http.serverHandler.ServeHTTP(0xc462c61700, 0x2468240, 0xc42160a270, 0xc4a3f7f680)
	/usr/local/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc4852efb00, 0x2469940, 0xc43e699ec0)
	/usr/local/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2293 +0x44d
" source="<autogenerated>:38"
```

### PR DESCRIPTION
**Pull request by beorn7**
Two cases:

- An unarchived metric must have at least one chunk desc loaded upon
  unarchival. Otherwise, the file is gone or has size 0, which is an
  inconsistency (because the series is still indexed in the archive
  index). Hence, quarantining is triggered.

- If loading the chunk descs of a series with a known chunkDescsOffset
  (i.e. != -1), the number of chunks loaded must be equal to
  chunkDescsOffset. If not, there is a data corruption. An error is
  returned, which leads to qurantining.

In any case, there is a guard added to not access the 1st element of
an empty chunkDescs slice. (That's what triggered the crashes in #2249.)  A time series with unknown chunkDescsOffset and no chunks in
memory and no chunks on disk either could trigger that case.
I would assume such a "null series" doesn't exist, but it's not
entirely unthinkable to happen (perhaps in future uses of the
storage). (Create a series, and then something tries to preload chunks
before the first sample is added.)

Fixes #2249. 

@brancz perhaps you are getting into storage reviews...
@juliusv is probably the most qualified person (but might be on vacation).
@rtreffer is very interested in this.

Sorry for not adding a specific test case. It needed quite a contraption: Creating a time series that has chunk _descs_ evicted, then corrupt the series file in the right way, and then trigger a query that loads it.

### CODE REVIEW

File: storage/local/series.go [hunk 1]
```diff
@@ -459,13 +459,21 @@ func (s *memorySeries) preloadChunksForRange(
 	}
 	if s.chunkDescsOffset != 0 && from.Before(firstChunkDescTime) {
 		cds, err := mss.loadChunkDescs(fp, s.persistWatermark)
+		if s.chunkDescsOffset != -1 && len(cds) != s.chunkDescsOffset {
```
Comment (juliusv) [inline storage/local/series.go]: Sorry. I'm still jet-lagged and recovering from vacation - all good :)

Comment (juliusv) [inline storage/local/series.go]: Though actually, it would still be good if there's already an error to not overwrite it, since we wouldn't expect the length to match here then anyways?

**Comment by juliusv** [comment]
:+1: otherwise

File: storage/local/series.go (hunk 1 above)
Comment (juliusv) [inline storage/local/series.go]: If there is an error already returned by `mss.loadChunkDescs` it seems more that that should be the only relevant error and this one here would just be a red herring.

**Comment by beorn7** [comment]
Changed the error handling at both occasions.

**Comment by brancz** [comment]
lgtm
