### PR TITLE
Convert tsdb.ErrOutOfBounds to a storage error

### LINKED ISSUE #2894: Prom2: 'Out of bounds' tsdb error drops target entirely
[NOTICE]: <> (If your question is around usage and not a bug in Prometheus please use: https://groups.google.com/forum/#!forum/prometheus-users)

**What did you do?**
I'm scraping NetData targets that give the timestamp with the metric in the response as seen below. Sometimes some metrics are not often updated (or ever after they're created) leading to out of bounds errors. 

Here's an example, I've added the comment to the out of bounds metric for the purpose of this ticket.
```
apps_vmem_tc_qos_helper{instance="host"} 402 1499115245472
apps_vmem_email{instance="host"} 0 1498781084668                 # this metric is out of bounds
apps_vmem_logs{instance="host"} 111669 1499115245472
apps_vmem_ssh{instance="host} 10027 1499115245472
```

My settings for block durations seem to be very reasonable.
storage.tsdb.max-block-duration 	17h48m0s
storage.tsdb.min-block-duration 	2h0m0s

**What did you expect to see?**
I would expect that only the time series' that are out of bounds be dropped, not the target entirely. Logs only indicate this is a warning.  I assume the expected behaviour is to drop **only** the erroneous time series' during ingestion and append the rest that are correctly within the bounds.  

So for example if a target has 3 metrics which are out of bounds, I should ingest all except those three. 

**What did you see instead? Under which circumstances?**
All time series' from a target with _any_ metrics that are 'out of bounds' are being dropped. So even if 1 out of 1,000 is out of bounds, **all** 1,000 get dropped and the target is considered 'down' due to the out of bounds errors. 

* Prometheus version: 
I'm a little bit ahead of the 2.0.0-alpha.2 release but behind the current branch. 
```
prometheus, version 2.0.0-alpha.2a (branch: dev-2.0, revision: dfef6cf2345465285e27802fcd24219ccbab1523)
  build user:       jeff@localhost.localdomain
  build date:       20170616-16:54:53
  go version:       go1.8
```
**Logs**
Jul 03 21:15:21 ip prometheus[1829]: time="2017-07-03T21:15:21Z" level=warning msg="append failed" err="out of bounds" source="scrape.go:606" target=....

### PR DESCRIPTION
**Pull request by Gouthamve**
storage.Err* cannot be compared to tsdb.Err* as errors.New() returns
pointers

Fixes #2894 for good. Tested on a target which failed previously but now works.

/cc @johrstrom

---
This change is [Reviewable](https://reviewable.io/reviews/prometheus/prometheus/2906)

### CODE REVIEW

**Comment by brian-brazil** [comment]
:+1:

File: retrieval/scrape_test.go [hunk 1]
```diff
@@ -875,11 +876,11 @@ type errorAppender struct {
...
 	switch lset.Get(model.MetricNameLabel) {
 	case "out_of_order":
-		return "", storage.ErrOutOfOrderSample
+		return "", tsdb.ErrOutOfOrderSample
 	case "amend":
-		return "", storage.ErrDuplicateSampleForTimestamp
+		return "", tsdb.ErrAmendSample
 	case "out_of_bounds":
-		return "", storage.ErrOutOfBounds
+		return "", tsdb.ErrOutOfBounds
```
Comment (fabxc) [inline retrieval/scrape_test.go]: Are these changes necessary after the changes to the error vars in itnerface.go?

Comment (Gouthamve) [inline retrieval/scrape_test.go]: Yes, because the actual appender throws `tsdb.Err*` instead of those in the storage.

Comment (fabxc) [inline retrieval/scrape_test.go]: But they are literally defined as the equality. This appender simulates a `storage.Appender` and not a `tsdb.Appender`.

Thinking about it. The change to `interface.go` actually makes package storage depend on tsdb and thereby all packages using a storage depend on tsdb.
This kind of breaks the entire purpose of the shim layer. So either we keep it separated as before and do explicit conversion in the shim layers or we move away from it and make dependencies to tsdb tighter.

Comment (Gouthamve) [inline retrieval/scrape_test.go]: Fair point. I see what you mean, will make the conversion at the shim layer.

Comment (Gouthamve) [inline retrieval/scrape_test.go]: Oh wow, sorry. I missed this. We do make the conversion at the shim layer already: https://github.com/prometheus/prometheus/blob/dev-2.0/storage/tsdb/tsdb.go#L136-L141

**Comment by Gouthamve** [comment]
Sorry for the previous change, I did not notice the conversion in the shim layer. Thanks @fabxc for catching this.

**Comment by fabxc** [comment]
:+1:
