### PR TITLE
UI: Fix starting screen flash before showing page

### LINKED ISSUE #9522: React UI: Starting Screen flashes before going to requested page
**What did you do?**

I opened the Prometheus web UI on a version that has the starting screen (for example https://prometheus-react.netlify.app).

**What did you expect to see?**

I expected to be taken right to the graph page.

**What did you see instead? Under which circumstances?**

The starting screen flashed for a second before forwarding me to the graph page.

* Prometheus version:

	main (1270b87)

This happens because the UI starts out on the starting screen and only moves off it once a request to `/ready` responds with a `200` status. I wonder if we could have the request happen in the background instead and just delay all requests on other pages until it responds (and if the server isn't ready _then_ go to the starting screen).

### PR DESCRIPTION
**Pull request by LeviHarrison**
This PR changes the logic of the starting screen so that the requested page is shown at first and then after that the instance's status is checked and the starting screen is shown if necessary. Previously the starting screen was shown first even if it wasn't needed, causing that flash before the application figures out the instance is ready.

Fixes #9522

### CODE REVIEW

**Comment by juliusv** [comment]
Hmmm, the only issue I see with this is that it initially renders various pages with an error (if the TSDB is still loading).

For example, the graph page will initially render this until the status is fetched:

image

And the TSDB page will show:

image

Or just the status page:

image

I provoked this by making both the TSDB startup and the status fetch really slow in a local checkout. Now normally the status fetch should be fast at least, but it still seems a bit unclean to first attempt a broken render...

**Comment by LeviHarrison** [comment]
Maybe show nothing (just a blank screen and the navigation bar) before we determine if the server is ready or not?

**Comment by roidelapluie** [comment]
> Maybe show nothing (just a blank screen and the navigation bar) before we determine if the server is ready or not?

That would be more or less the same as the loading screen :)

**Comment by LeviHarrison** [comment]
You mean the starting screen? A would think a bit different because the starting screen indicates the instance is still starting up, while a loading screen doesn't imply that.

**Comment by LeviHarrison** [comment]
> Maybe show nothing (just a blank screen and the navigation bar) before we determine if the server is ready or not?

But if this doesn't sound good to you I think rendering a possibly broken page at first is fine. That's what happened before the starting screen existed and is arguably the more correct behavior (as opposed to what happens now which is rendering the starting screen first even if the instance isn't actually starting).

**Comment by juliusv** [comment]
> But if this doesn't sound good to you I think rendering a possibly broken page at first is fine. That's what happened before the starting screen existed and is arguably the more correct behavior (as opposed to what happens now which is rendering the starting screen first even if the instance isn't actually starting).

I think it'd be a little worse than what we did before, since we flicker in something broken, but then remove it again once we know it isn't supposed to work yet. Seems more confusing/unclean to me.

So I'd prefer showing either a blank screen or better yet, a notice saying what is actually happening, like "Loading server state..." (rather than the TSDB startup message). If we *really* want to get rid of any startup flicker, we could even inject the current readiness state into the page to begin with, like we do for other values at https://github.com/prometheus/prometheus/blob/main/web/web.go#L400-L402. But I don't expect that :)

**Comment by LeviHarrison** [comment]
> If we really want to get rid of any startup flicker, we could even inject the current readiness state into the page to begin with, like we do for other values at https://github.com/prometheus/prometheus/blob/main/web/web.go#L400-L402.

Hmm, this sounds interesting, I'll look into it. I like the idea of avoiding a loading screen because the only reason for having it is when the server is starting up which is probably like 0.001% of the time.

**Comment by LeviHarrison** [comment]
Ok, that should work

File: web/ui/react-app/src/App.tsx [hunk 1]
```diff
@@ -82,34 +83,34 @@ const App: FC<AppProps> = ({ consolesLink, agentMode }) => {
               React-handled router paths ("reactRouterPaths") in /web/web.go.
             */}
               <Route path="/agent">
-                <AgentPage />
+                <AgentPage staticReady={ready} />
```
Comment (juliusv) [inline web/ui/react-app/src/App.tsx:86]: I'd try to avoid threading through such a minor setting to all pages... how about doing it like we do for the path prefix, which is also injected. We have a context for it here: https://github.com/prometheus/prometheus/blob/fa0f04bbc6f41708782d4e259fd1fb38896bb904/web/ui/react-app/src/contexts/PathPrefixContext.tsx#L4, which is wrapped around the whole App here: https://github.com/prometheus/prometheus/blob/fa0f04bbc6f41708782d4e259fd1fb38896bb904/web/ui/react-app/src/App.tsx#L74

And then any place that needs it can do `usePathPrefix()`.

Maybe at some point it can even make sense to combine it all into one big injected settings config context object, rather than multiple small ones.

Comment (LeviHarrison) [reply web/ui/react-app/src/App.tsx]: Done

**Comment by juliusv** [comment]
:+1: Thanks!
