### PR TITLE
histograms: Fix parsing of float histograms without zero bucket

### LINKED ISSUE #12305: Native histogram federation not working
### What did you do?

I've added native histograms to some code of mine. The code is running on 40 servers, each one is running a prometheus instance which is scraped by a master server. "--enable-feature" native-histograms is enabled on all instances.

On each instance, I can see the values of the native histogram being properly ingested by prometheus. However on the master instance I can only see the values ingested locally, the entire series are missing for all servers being scraped. All other series from these servers is present.

### What did you expect to see?

Full time series from all servers being scrapped.

### What did you see instead? Under which circumstances?

Only locally ingested data present.

### System information

Linux 6.1.12-zen1+ #19 ZEN SMP PREEMPT Wed Mar 15 19:32:47 CET 2023 x86_64 x86_64 x86_64 GNU/Linux

### Prometheus version

```text
prometheus, version 2.44.0-rc.0 (branch: HEAD, revision: d70688038e5d444ab8beac53722df15d244038e4)
  build user:       root@c3e52c6dd464
  build date:       20230426-09:46:54
  go version:       go1.20.3
  platform:         linux/amd64
  tags:             netgo,builtinassets,stringlabels
```

### Prometheus configuration file

```yaml
This is from the master server. As mentioned, each target node does have the data available, so I assume the problem is not on their side. 

  - job_name: 'federate'
    scrape_interval: 15s

    honor_labels: true
    metrics_path: '/federate'

    params:
      'match[]':
        - '{job=~".*"}'

    static_configs:
      - targets:
        [...]
```

### Alertmanager version

_No response_

### Alertmanager configuration file

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by beorn7**
Fixes #12305

### CODE REVIEW

**Comment by beorn7** [comment]
@zenador & @krajorama , this should be an easy review (especially given that @krajorama has done a protobuf parser review recently). Could you have a look?

See the bug and the individual commit description for the full context.

File: web/federate_test.go [hunk 1]
```diff
@@ -335,18 +335,41 @@ func TestFederationWithNativeHistograms(t *testing.T) {
...
+		},
+		NegativeBuckets: []int64{2, 2, -2, 0},
+	}
 	app := db.Appender(context.Background())
 	for i := 0; i < 6; i++ {
 		l := labels.FromStrings("__name__", "test_metric", "foo", fmt.Sprintf("%d", i))
 		expL := labels.FromStrings("__name__", "test_metric", "instance", "", "foo", fmt.Sprintf("%d", i))
-		if i%3 == 0 {
+		switch {
+		case i%3 == 0:
```
Comment (krajorama) [inline web/federate_test.go:358]: nitpick: this seems a bit convoluted , with 6 items it might be worth to just list them by hand or make AI do it

File: web/federate_test.go [hunk 2]
```diff
@@ -335,18 +335,41 @@ func TestFederationWithNativeHistograms(t *testing.T) {
...
 			})
-		} else {
+		case i == 4:
+			_, err = app.AppendHistogram(0, l, 100*60*1000, histWithoutZeroBucket.Copy(), nil)
+			expVec = append(expVec, promql.Sample{
+				T:      100 * 60 * 1000,
+				H:      histWithoutZeroBucket.ToFloat(),
+				Metric: expL,
+			})
+		default:
```
Comment (krajorama) [inline web/federate_test.go:372]: I noticed @codesome 's comment bellow, does PromQL return the header now? At least for Gauges? Could we add a test case?

**Review by krajorama — APPROVED** [review]
Approved with some nitpick/questions
