### PR TITLE
Fixed wrongly handled not ready TSDB on web and API.

### LINKED ISSUE #7181: Panic when trying to use /federate endpoint in v2.18.0-rc.0
**What did you do?**
Tried to use `/federate` endpoint on the v2.18.0 release candidate

**What did you expect to see?**
Appropriate results coming back

**What did you see instead? Under which circumstances?**
Panic inside of Prometheus

**Environment**
* Prometheus version: v2.18.0-rc.0
* Prometheus configuration file: Reproducible using `documentation/examples/prometheus.yml`

**Stacktrace**
```
runtime error: invalid memory address or nil pointer dereference" stack="goroutine 388463 [running]:
github.com/prometheus/prometheus/web.withStackTracer.func1.1(0x2e92de0, 0xc000247e90, 0xc097834800)
    /app/web/web.go:98 +0xb5
panic(0x22b7e80, 0x41f4180)
    /usr/local/go/src/runtime/panic.go:969 +0x166
github.com/prometheus/prometheus/tsdb.(*DB).Querier(0x0, 0x2ee3c20, 0xc09c2d3c80, 0x171c30cc6f1, 0x171c3115ad1, 0x0, 0x0, 0x0, 0x0)
    /app/tsdb/db.go:1283 +0x5d
github.com/prometheus/prometheus/web.(*Handler).federation(0xc0008b2b40, 0x2ece520, 0xc09c2a9680, 0xc097834b00)
    /app/web/federate.go:78 +0x758
net/http.HandlerFunc.ServeHTTP(0xc0002054f0, 0x2ece520, 0xc09c2a9680, 0xc097834b00)
    /usr/local/go/src/net/http/server.go:2012 +0x44
github.com/prometheus/prometheus/util/httputil.CompressionHandler.ServeHTTP(0x2e97c00, 0xc0002054f0, 0x7f570c507a58, 0xc09be56cd0, 0xc097834b00)
    /app/util/httputil/compression.go:90 +0x7c
github.com/prometheus/prometheus/web.(*Handler).testReady.func1(0x7f570c507a58, 0xc09be56cd0, 0xc097834b00)
    /app/web/web.go:495 +0x55
net/http.HandlerFunc.ServeHTTP(0xc000209600, 0x7f570c507a58, 0xc09be56cd0, 0xc097834b00)
    /usr/local/go/src/net/http/server.go:2012 +0x44
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerResponseSize.func1(0x7f570c507a58, 0xc09be56c80, 0xc097834b00)
    /app/vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go:196 +0xea
net/http.HandlerFunc.ServeHTTP(0xc00073ff20, 0x7f570c507a58, 0xc09be56c80, 0xc097834b00)
    /usr/local/go/src/net/http/server.go:2012 +0x44
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerDuration.func2(0x7f570c507a58, 0xc09be56c80, 0xc097834b00)
    /app/vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go:76 +0xb2
net/http.HandlerFunc.ServeHTTP(0xc0008f4030, 0x7f570c507a58, 0xc09be56c80, 0xc097834b00)
    /usr/local/go/src/net/http/server.go:2012 +0x44
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1(0x2edc360, 0xc09be56c30, 0xc097834b00)
    /app/vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go:100 +0xda
github.com/prometheus/prometheus/web.setPathWithPrefix.func1.1(0x2edc360, 0xc09be56c30, 0xc097834a00)
    /app/web/web.go:1128 +0x1c6
github.com/prometheus/common/route.(*Router).handle.func1(0x2edc360, 0xc09be56c30, 0xc097834900, 0x0, 0x0, 0x0)
    /app/vendor/github.com/prometheus/common/route/route.go:83 +0x27f
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc000201e60, 0x2edc360, 0xc09be56c30, 0xc097834900)
    /app/vendor/github.com/julienschmidt/httprouter/router.go:387 +0xc37
github.com/prometheus/common/route.(*Router).ServeHTTP(0xc00000d2e0, 0x2edc360, 0xc09be56c30, 0xc097834900)
    /app/vendor/github.com/prometheus/common/route/route.go:121 +0x4c
net/http.(*ServeMux).ServeHTTP(0xc0000d5240, 0x2edc360, 0xc09be56c30, 0xc097834900)
    /usr/local/go/src/net/http/server.go:2387 +0x1a5
github.com/opentracing-contrib/go-stdlib/nethttp.MiddlewareFunc.func5(0x2eda920, 0xc0861cb6c0, 0xc097834800)
    /app/vendor/github.com/opentracing-contrib/go-stdlib/nethttp/server.go:140 +0x5f6
net/http.HandlerFunc.ServeHTTP(0xc000537d40, 0x2eda920, 0xc0861cb6c0, 0xc097834800)
    /usr/local/go/src/net/http/server.go:2012 +0x44
github.com/prometheus/prometheus/web.withStackTracer.func1(0x2eda920, 0xc0861cb6c0, 0xc097834800)
    /app/web/web.go:103 +0x8b
net/http.HandlerFunc.ServeHTTP(0xc000537d70, 0x2eda920, 0xc0861cb6c0, 0xc097834800)
    /usr/local/go/src/net/http/server.go:2012 +0x44
net/http.serverHandler.ServeHTTP(0xc0005be000, 0x2eda920, 0xc0861cb6c0, 0xc097834800)
    /usr/local/go/src/net/http/server.go:2807 +0xa3
net/http.(*conn).serve(0xc09be17720, 0x2ee3b60, 0xc0835db840)
    /usr/local/go/src/net/http/server.go:1895 +0x86c
created by net/http.(*Server).Serve
    /usr/local/go/src/net/http/server.go:2933 +0x35c
```

cc: @bwplotka as this is blocking for the release.

### PR DESCRIPTION
**Pull request by yeya24**
Two commits: 

1. Fixed federation.
   Signed-off-by: yeya24 <yb532204897@gmail.com>

EDIT by @bwplotka: 

2. Fixed all cases of not ready TSDB being wrongly handled.

* Fixed issue for federation.
* Ensured this will never happen again thanks to interfaces
* Fixes same issue for stats.
* Fixed bug in stats. It was:
   status.MaxTime = db.Head().MaxTime()
   status.MinTime = db.Head().MaxTime()
* Added tests for readiness.

Signed-off-by: Bartlomiej Plotka <bwplotka@gmail.com>

Fixes #7181

### CODE REVIEW

File: promql/test.go [hunk 1]
```diff
@@ -25,10 +25,10 @@ import (
 
 	"github.com/pkg/errors"
 	"github.com/prometheus/common/model"
-
```
Comment (roidelapluie) [inline promql/test.go:28]: that space could stay

**Comment by roidelapluie** [comment]
did you test this, especially early in prometheus start?

File: promql/test.go [hunk 2]
```diff
@@ -101,6 +101,11 @@ func (t *Test) Storage() storage.Storage {
 	return t.storage
 }
 
+// Storage returns the test's TSDB
```
Comment (bwplotka) [inline promql/test.go:104]:
```suggestion
// Storage returns the test's TSDB.
```

File: web/federate_test.go [hunk 3]
```diff
@@ -199,7 +199,7 @@ func TestFederation(t *testing.T) {
 	}
 
 	h := &Handler{
-		localStorage:  suite.Storage(),
+		tsdb:          suite.GetDB,
```
Comment (bwplotka) [inline web/federate_test.go:202]: Not sure why all of those tests changes, would this reproduce it?

**Comment by bwplotka** [comment]
Let me fix it, will push commit to your PR, hope that's ok :hugs:

**Comment by bwplotka** [comment]
Ok, this should be ready for review @roidelapluie @yeya24 @beorn7 @brancz @brian-brazil :hugs: 

I think it makes sense to move to interfaces only, so we don't leak raw DB pointer anymore and ensure we can properly check the readiness and return meaningful errors. We happen to have an issue in more places than just one.

Also fixed undiscovered bug with status page: 

```
* Fixed bug in stats. It was:
   status.MaxTime = db.Head().MaxTime()
   status.MinTime = db.Head().MaxTime()
```

After this is merged I will cut rc.1

**Comment by bwplotka** [comment]
cc @csmarchbanks

File: tsdb/head.go [hunk 4]
```diff
@@ -751,6 +751,23 @@ func (h *Head) initTime(t int64) (initialized bool) {
...
+	MinTime, MaxTime       int64
+	NameMetricPostingStats *index.PostingsStats
+}
+
+// Stats returns important current HEAD statistics. Note that it is expensive to
+// calculate those.
+func (h *Head) Stats() *Stats {
+	return &Stats{
+		NumSeries:              h.NumSeries(),
+		MinTime:                h.MaxTime(),
```
Comment (brian-brazil) [inline tsdb/head.go:765]: MaxTime?

File: tsdb/head.go [hunk 5]
```diff
@@ -751,6 +751,23 @@ func (h *Head) initTime(t int64) (initialized bool) {
...
+		MaxTime:                h.MaxTime(),
+		NameMetricPostingStats: h.PostingsCardinalityStats("__name__"),
```
Comment (brian-brazil) [inline tsdb/head.go:767]: The tsdb shouldn't know about the existence of `__name__`

Comment (bwplotka) [reply tsdb/head.go:767]: sure

File: tsdb/head.go (hunk 4 above)
Comment (bwplotka) [reply tsdb/head.go:765]: good catch!

**Comment by bwplotka** [comment]
Addressed @brian-brazil

File: web/api/v1/api.go [hunk 6]
```diff
@@ -37,6 +37,7 @@ import (
 	"github.com/prometheus/client_golang/prometheus"
 	"github.com/prometheus/common/model"
 	"github.com/prometheus/common/route"
+	"github.com/prometheus/prometheus/tsdb"
```
Comment (roidelapluie) [inline web/api/v1/api.go:40]: why this move?

File: web/api/v1/api.go [hunk 7]
```diff
@@ -159,13 +159,13 @@ type apiFuncResult struct {
 
 type apiFunc func(r *http.Request) apiFuncResult
 
-// TSDBAdmin defines the tsdb interfaces used by the v1 API for admin operations.
-type TSDBAdmin interface {
+// TSDBAdmin defines the tsdb interfaces used by the v1 API for admin operations as well as statistics.
+type TSDBAdminStats interface {
```
Comment (roidelapluie) [inline web/api/v1/api.go:163]: if that rename is really needed, comment should be updated too

Comment (bwplotka) [reply web/api/v1/api.go:163]: Yea, it's no longer just admin.

Comment (bwplotka) [reply web/api/v1/api.go:163]: Thanks!

File: web/api/v1/api.go (hunk 6 above)
Comment (bwplotka) [reply web/api/v1/api.go:40]: I did not just formatting

Comment (bwplotka) [reply web/api/v1/api.go]: ah got it - should be fixed now

File: tsdb/head.go [hunk 8]
```diff
@@ -751,6 +751,23 @@ func (h *Head) initTime(t int64) (initialized bool) {
...
 }
 
+type Stats struct {
+	NumSeries         uint64
+	MinTime, MaxTime  int64
+	IndexPostingStats *index.PostingsStats
+}
+
+// Stats returns important current HEAD statistics. Note that it is expensive to
+// calculate those.
```
Comment (brian-brazil) [inline tsdb/head.go:761]: these

File: web/api/v1/api.go [hunk 9]
```diff
@@ -1124,29 +1126,30 @@ type tsdbStatus struct {
...
-	posting := db.Head().PostingsCardinalityStats(model.MetricNameLabel)
-	response := tsdbStatus{
-		SeriesCountByMetricName:     convert(posting.CardinalityMetricsStats),
-		LabelValueCountByLabelName:  convert(posting.CardinalityLabelStats),
-		MemoryInBytesByLabelName:    convert(posting.LabelValueStats),
-		SeriesCountByLabelValuePair: convert(posting.LabelValuePairsStats),
+func (api *API) serveTSDBStatus(*http.Request) apiFuncResult {
+	s, err := api.db.Stats("__name__")
+	if err != nil {
+		if errors.Cause(err) == tsdb.ErrNotReady {
```
Comment (brian-brazil) [inline web/api/v1/api.go:1141]: This is repeated a lot, could we do it in wrap instead?

Comment (bwplotka) [reply web/api/v1/api.go:1141]: :+1:

**Comment by bwplotka** [comment]
Nice comments, thanks for quick review :+1:

**Comment by bwplotka** [comment]
Merging on green (~2h) to unblock release if no objections.
