### PR TITLE
Fix target group foreach nil bug.

### LINKED ISSUE #3074: [ BUG ] nil target item cause prometheus exit
**What did you do?**
using a file sd to define the target groups.

**What did you expect to see?**
wrong discovery data should be skipped or warning, not panic.

**What did you see instead? Under which circumstances?**
panic, and the details is:
```
INFO[0000] Starting target manager...                    source="targetmanager.go:63"

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x166053a]

goroutine 52 [running]:
github.com/prometheus/prometheus/discovery/file.readFile(0xc42015e2a0, 0x1b, 0x1, 0x1, 0xc420b4a270, 0x3, 0x3)
	/Users/Jacky/Jacky.Wu/MyProjects/Go/src/github.com/prometheus/prometheus/discovery/file/file.go:259 +0x1ea
github.com/prometheus/prometheus/discovery/file.(*Discovery).refresh(0xc420b28080, 0x3ea2080, 0xc420b28100, 0xc42001d620)
	/Users/Jacky/Jacky.Wu/MyProjects/Go/src/github.com/prometheus/prometheus/discovery/file/file.go:196 +0xfe
github.com/prometheus/prometheus/discovery/file.(*Discovery).Run(0xc420b28080, 0x3ea2080, 0xc420b28100, 0xc42001d620)
	/Users/Jacky/Jacky.Wu/MyProjects/Go/src/github.com/prometheus/prometheus/discovery/file/file.go:121 +0x198
created by github.com/prometheus/prometheus/discovery.(*TargetSet).updateProviders
	/Users/Jacky/Jacky.Wu/MyProjects/Go/src/github.com/prometheus/prometheus/discovery/discovery.go:249 +0x283
```

**Environment**

* System information:

	Linux 3.16.0-4-amd64 x86_64

* Prometheus version: 

```
 prometheus, version 1.6.0 (branch: master, revision: 10f645382988add09c8e3420d0d7ff2dc4d36a29)
  build user:       root@0816a56aa81c
  build date:       20170414-18:36:18
  go version:       go1.8.1
```

* Alertmanager version:

* Prometheus configuration file:
```
...
  - job_name: 'nil-item-array-json-job'
    metrics_path: /metrics
    file_sd_configs:
      - files:
         - "invalid_nil_item_array.json"
```

```
# invalid_nil_item_array.json
# !!! the last null line caused panic!

[
    {
        "labels": {
            "env": "prod"
        },
        "targets": [
            "localhost:9090"
        ]
    },
    null
]
```

### PR DESCRIPTION
**Pull request by Colstuwjx**
Fix #3074

### CODE REVIEW

**Comment by fabxc** [comment]
Thanks! Can you add a test to catch that case?

File: discovery/file/file.go [hunk 1]
```diff
@@ -256,6 +256,11 @@ func readFile(filename string) ([]*config.TargetGroup, error) {
 	}
 
 	for i, tg := range targetGroups {
+		if tg == nil {
+			log.Errorf("nil target group item found from: %s", filename)
+			continue
```
Comment (grobie) [inline discovery/file/file.go]: I don't think we should accept a broken file. This also doesn't increment `fileSDReadErrorsCount`. IMHO we should just return an error here, the caller will take care of updating the metric and logging the error using the correct logger (instead of using the package logger).

**Comment by Colstuwjx** [comment]
Sorry about the delay, I have already added testcases, and directly return error while there is a nil item in the json/yml fsd.

Thanks!

File: discovery/file/file.go [hunk 2]
```diff
@@ -256,6 +256,11 @@ func readFile(filename string) ([]*config.TargetGroup, error) {
 	}
 
 	for i, tg := range targetGroups {
+		if tg == nil {
+			err = fmt.Errorf("nil target group item found from: %s", filename)
```
Comment (grobie) [inline discovery/file/file.go]: We already include the file name in the error log in the caller. Something like `errors.New("nil target group item found")` would be enough.

**Comment by Colstuwjx** [comment]
Aha，all things cleared!
