### PR TITLE
discovery/file: restore atomic file writes in tests

### LINKED ISSUE #18237: `TestInvalidFileUpdate` file_sd test failed on CI with unexpected file contents
Just got this `TestInvalidFileUpdate` file_sd test failure in CI on a PR.

I don't know if this is just related to the general Go test brokenness in CI at the moment or specific to this test, but since it's not about a timeout but about unexpected file contents, I thought I'd file an issue for it just in case.

```
--- FAIL: TestInvalidFileUpdate (1.10s)
    file_test.go:400: 
        	Error Trace:	/__w/prometheus/prometheus/discovery/file/file_test.go:227
        	            				/__w/prometheus/prometheus/discovery/file/file_test.go:400
        	Error:      	Not equal: 
        	            	expected: "[{\"targets\":[\"localhost:9090\",\"example.org:443\"],\"labels\":{\"__meta_filepath\":\"/tmp/TestInvalidFileUpdate2130356920/001/valid.yml\",\"foo\":\"bar\"}},{\"targets\":[\"my.domain\"],\"labels\":{\"__meta_filepath\":\"/tmp/TestInvalidFileUpdate2130356920/001/valid.yml\"}}]"
        	            	actual  : "[{\"targets\":[]},{\"targets\":[]}]"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-[{"targets":["localhost:9090","example.org:443"],"labels":{"__meta_filepath":"/tmp/TestInvalidFileUpdate2130356920/001/valid.yml","foo":"bar"}},{"targets":["my.domain"],"labels":{"__meta_filepath":"/tmp/TestInvalidFileUpdate2130356920/001/valid.yml"}}]
        	            	+[{"targets":[]},{"targets":[]}]
        	Test:       	TestInvalidFileUpdate
FAIL
FAIL	github.com/prometheus/prometheus/discovery/file	2.521s
```

### PR DESCRIPTION
**Pull request by MunemHashmi**
#### Which issue(s) does the PR fix:

Fixes #18237

#### Does this PR introduce a user-facing change?

```release-notes
NONE
```

---

**Root cause:**

PR #17269 replaced atomic `os.Rename`-based file writes in the test helpers with `os.WriteFile` to fix a Windows flake. However, `os.WriteFile` is not atomic (it truncates then writes), and `fsnotify` can fire between the truncate and write, causing the watcher to read an empty file. Since `yaml.UnmarshalStrict` returns no error for empty content, `readFile()` succeeds with 0 target groups, and `refresh()` sends empty target groups that replace the previously valid ones.

This matches the CI failure output exactly: `[{"targets":[]},{"targets":[]}]`.

**Fix:**

Restore atomic file writes in the test helpers using temp file + `os.Rename`. The temp file is created in `os.TempDir()` (outside the watched directory) to avoid triggering spurious `fsnotify` events that could cause `readFile` to hold an open handle on the destination file (which would make `os.Rename` fail on Windows). A small retry loop on `os.Rename` is included as a safety net for the rare case where a previous refresh cycle hasn't released the file handle yet. On Linux/macOS, `os.Rename` succeeds regardless of open handles, so the retry never triggers.

### CODE REVIEW

**Comment by juliusv** [comment]
Thanks. I looked a bit deeper into the history and found https://github.com/prometheus/prometheus/pull/17269, which removed the file write atomicity in the tests.

I think the assumption has always been that writes for file_sd files have to happen atomically, and prior to https://github.com/prometheus/prometheus/pull/17269, that also happened via an atomic `os.Rename`. I think the correct solution would be to fix the test in such a way that it writes out files atomically again. It just also needs to work on Windows, which that PR tried to fix (but which made it non-atomic). I haven't looked yet at how to do that in the best way.

**Comment by MunemHashmi** [comment]
Thanks for the context @juliusv! You're right — the fix belongs in the test, not the production code.

I've updated the PR to restore atomic file writes (temp file + `os.Rename`) in the test helpers. To handle Windows reliably:

1. The temp file is created in `os.TempDir()` (outside the watched directory) so it doesn't trigger spurious `fsnotify` events that would cause `readFile` to hold `valid.yml` open.
2. A small retry loop on `os.Rename` is included as a safety net for the rare case where a previous refresh cycle hasn't released the file handle yet. On Linux/macOS this never triggers since `os.Rename` succeeds regardless of open handles.

**Comment by juliusv** [comment]
@HankStat Could you confirm whether the proposed fix here still works reliably under Windows? Is simply retrying sufficient, or will the Windows version always fail?

**Comment by bwplotka** [comment]
Looks like this is related to https://github.com/prometheus/prometheus/issues/18269

File: discovery/file/file_test.go [hunk 1]
```diff
@@ -69,25 +69,55 @@ func (t *testRunner) copyFile(src string) string {
...
+// and renaming it. The temp file is created outside the watched directory to
+// avoid triggering spurious fsnotify events that could cause readFile to hold
+// an open handle on dst (which would make os.Rename fail on Windows).
+func (t *testRunner) atomicWrite(dst string, data []byte) {
+	t.Helper()
+
+	// Create the temp file in os.TempDir rather than t.dir (the watched
+	// directory). Both reside on the same filesystem since t.dir is created
+	// via t.TempDir(), so os.Rename works across them.
+	tmp, err := os.CreateTemp("", ".sd-test-*")
```
Comment (krajorama) [inline discovery/file/file_test.go]: If we fail the move 5 times, we give up, but the `tmp` file will not be removed.
Since `t.TempDir()` returns a new directory every time, it could be the place for the temp file.
Also I feel like using `t.TempDir()` is more sure to be on the same filesystem , than `os.CreateTmp("",...` as it's the same call that we used for setting up `t.dir`.

```suggestion
	tmp, err := os.CreateTemp(t.TempDir(), ".sd-test-*")
```

Comment (MunemHashmi) [reply discovery/file/file_test.go]: Good catch, thanks! Updated to use `t.TempDir()` — this ensures the temp file is on the same filesystem and gets auto-cleaned by the test framework.

**Comment by krajorama** [comment]
> @HankStat Could you confirm whether the proposed fix here still works reliably under Windows? Is simply retrying sufficient, or will the Windows version always fail?

@HankStat  doesn't seemed to be very active, but his PR #17269 removed the guard around the tests, so they are currently running on windows test runner (see the logs). We can re-run the test a couple of times in CI to see how flaky it is.

**Comment by HankStat** [comment]
> > @HankStat Could you confirm whether the proposed fix here still works reliably under Windows? Is simply retrying sufficient, or will the Windows version always fail?
> 
> @HankStat doesn't seemed to be very active, but his PR #17269 removed the guard around the tests, so they are currently running on windows test runner (see the logs). We can re-run the test a couple of times in CI to see how flaky it is.

Hi, sorry for the late response. I have switched my laptop to a non-Windows OS, so I can no longer do the local verification (go test -count=100) on my own.

If the current PR author or anyone reviewing has a Windows machine, it would be ideal to test this locally to prevent running it on CI too many times.

**Comment by krajorama** [comment]
I fired up an old laptop and ran all tests in discovery/file 100 times. Took 233s. Windows 10, go 1.26.1.
