### PR TITLE
PromQL: Fix string and parentheses handling in engine

### LINKED ISSUE #6610: PromQL: Allow engine to return strings
## Problem
`promql.ParseExpr` will parse expressions of all types without syntax errors, but the engine can only evaluate expressions of type `vector` and `matrix`.

## Proposal

Add a `ParseQuery` func that will behave like `ParseExpr` but will panic if the type of the AST root has a type that can not be evaluated by the engine, i.e. is a scalar or string.

This would also solve part of the problem pointed out in https://github.com/prometheus/prometheus/issues/6598#issuecomment-573624531.

### PR DESCRIPTION
**Pull request by slrtbtfs**
Will fix #6610.

There are still problems at the font end side.

The old UI handles string returns on queries like `"foo"` or `("bar")` just fine, however the react UI claims the return type is a scalar.

Could someone who is more familiar with the React UI look into this, maybe @juliusv or @boyskila ?

Signed-off-by: Tobias Guggenmos <tguggenm@redhat.com>

### CODE REVIEW

**Comment by roidelapluie** [comment]
Can you please add tests?

```diff
diff --git a/promql/testdata/aggregators.test b/promql/testdata/aggregators.test
index 0da80576..7b3ba45b 100644
--- a/promql/testdata/aggregators.test
+++ b/promql/testdata/aggregators.test
@@ -233,6 +233,11 @@ eval instant at 5m count_values("version", version)
 	{version="7"} 2
 	{version="8"} 2
 
+eval instant at 5m count_values(((("version"))), version)
+	{version="6"} 5
+	{version="7"} 2
+	{version="8"} 2
+
 eval instant at 5m count_values without (instance)("version", version)
 	{job="api-server", group="production", version="6"} 3
 	{job="api-server", group="canary", version="8"} 2
```

```
    promql_test.go:32: unexpected error: error evaluating query "count_values((((\"version\"))), version)" (line 236): unexpected error: runtime error: index out of range [0] with length 0
```

**Comment by slrtbtfs** [comment]
Thanks!

So I guess we should get to consensus about how to deal with these parentheses in #6598 first, i.e. figure out whether we should fix that kind of bug in the engine or let it already fail during parse time.

**Comment by juliusv** [comment]
> The old UI handles string returns on queries like "foo" or ("bar") just fine, however the react UI claims the return type is a scalar.
>
> Could someone who is more familiar with the React UI look into this, maybe @juliusv or @boyskila ?

I think it's just a typo in the string handling case: https://github.com/prometheus/prometheus/blob/8cb2ab6a9913d7735c729a03964bf485053aca35/web/ui/react-app/src/DataTable.tsx#L106

Ironically we already even support strings as a root-level type in the UI (except for this typo), probably because the new UI code was partially adapted from the old UI code, and 1.x Prometheus once supported root-level strings already.

**Comment by slrtbtfs** [comment]
Thanks, that fixed it.

**Comment by brian-brazil** [comment]
> 1.x Prometheus once supported root-level strings already.

I don't think we ever did, though some of the code that'd be needed to support it was there.

**Comment by juliusv** [comment]
@brian-brazil We did, I tried.

foostring

**Comment by roidelapluie** [comment]
Can we please have negative tests? rate((foo)[5m]).

**Comment by slrtbtfs** [comment]
Still working on another PR, this one will come after.

**Comment by slrtbtfs** [comment]
This PR now (hopefully) fixes #6598, fixes #6610  and is ready for review.

File: promql/engine.go [hunk 1]
```diff
@@ -1013,6 +1021,7 @@ func (ev *evaluator) eval(expr Expr) Value {
 
 	switch e := expr.(type) {
 	case *AggregateExpr:
+		unwrapParenExpr(&e.Param)
```
Comment (juliusv) [inline promql/engine.go]: I'd prefer not to mutate the main (non-cache etc.) fields of the AST during the query. E.g. a user might want to serialize or otherwise use it again after executing.

Could we make this functional?

```suggestion
		param := unwrapParenExpr(&e.Param)
```

**Comment by juliusv** [comment]
:+1: besides the nit

File: promql/engine.go (hunk 1 above)
Comment (slrtbtfs) [reply promql/engine.go]: I agree that functional execution would be nicer.

However, evaluation already mutates the AST in other places, so actually making this functional would be a larger effort.

https://github.com/prometheus/prometheus/blob/master/promql/engine.go#L1056

Comment (slrtbtfs) [reply promql/engine.go]: Re-evaluation might still produce correct results, but I wouldn't rely on it.

Comment (juliusv) [reply promql/engine.go]: Damn. My worst fears are confirmed ;) I think in this case it'd be really easy to avoid a mutation though, and fewer mutations cause fewer confusions.

Comment (slrtbtfs) [reply promql/engine.go]: I quickly skimmed the code and found a couple places where evaluation has side effects on (non-cache) AST contents.

All of them look relatively fixable.

If functional execution is desired, I'd prefer to fix all of them in a separate PR and leave this one as is.

Comment (juliusv) [reply promql/engine.go]: Ok, I'd say let's put that on hold for now then and keep things as is here.

Comment (slrtbtfs) [reply promql/engine.go]: I've made an issue for this #6627

**Comment by slrtbtfs** [comment]
Merge conflicts are resolved now.

**Comment by juliusv** [comment]
:+1:
