### PR TITLE
remote-write: Add type and unit labels to receiver when feature flag enabled

### LINKED ISSUE #17319: [RW2] Type and unit labels not propagated to Prometheus receiver
### Description
Hi! In the recent Prometheus release [v3.7.0-rc.0](https://github.com/prometheus/prometheus/releases/tag/v3.7.0-rc.0), a new feature was added:
* [FEATURE] Remote-write: Add type and unit labels to outgoing time series in remote-write 2.0 when the type-and-unit-labels feature flag is enabled. ([#17033](https://github.com/prometheus/prometheus/pull/17033))

I tried enabling this feature, but the type and unit labels don’t appear in Prometheus after being sent via remote-write v2.
I’d appreciate any help to figure out what I might be doing wrong.

### Setup

Both Prometheus and Prometheus Agent are running on the same host.
The agent scrapes metrics from node-exporter and sends them to Prometheus via remote-write v2.
```mermaid
flowchart LR
    subgraph test-monitoring-host
        pa("prometheus-agent</br>[version 3.7.0-rc.0]")
        ne("node-exporter</br>[version 1.9.1]")
        prometheus("Prometheus</br>[version 3.7.0-rc.0]")        
    end

    pa <-->|scrape| ne
    pa -->|Remote Write| prometheus
```

### Prometheus Agent configuration
```yaml
global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'node-exporter'
    scrape_interval: 15s
    file_sd_configs:
    - files:
      - '/opt/prometheus-agent/test/node-exporter.yaml'
      refresh_interval: 1m
    relabel_configs:
      - source_labels: [__address__]
        regex: '(.*):(.*)'
        target_label: instance
        replacement: '${1}'
      - source_labels: [__address__]
        regex: '(.*):(.*)'
        target_label: port
        replacement: '${2}'
    tls_config:
      insecure_skip_verify: true

remote_write:
  - url: "http://127.0.0.1:9090/api/v1/write"
    name: "Remote write to prometheus"
    protobuf_message: io.prometheus.write.v2.Request
    metadata_config:
      send: true
    write_relabel_configs:
      - source_labels: ['__name__']
        regex: 'prometheus_.*|go_.*'
        action: drop
```
###  Prometheus agent startup flags:
```bash
--config.file=/opt/prometheus-agent/prometheus-agent.yml
--web.listen-address=0.0.0.0:9091
--agent
--storage.agent.path=/mnt/tsdb/prometheus-agent
--storage.agent.retention.max-time=1d
--enable-feature=metadata-wal-records,type-and-unit-labels
--log.level=debug
```
----
### Prometheus configuration
```yaml
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.0.1:9090']
```

### Prometheus startup flags:
```bash
--config.file=/opt/prometheus/prometheus.yml
--storage.tsdb.path=/mnt/tsdb/prometheus
--web.listen-address=0.0.0.0:9090
--storage.tsdb.retention.time=1d
--web.enable-remote-write-receiver
--web.remote-write-receiver.accepted-protobuf-messages=io.prometheus.write.v2.Request
--enable-feature=metadata-wal-records,type-and-unit-labels
--log.level=debug
```

### Steps to Reproduce
* Start Prometheus and Prometheus Agent (both v3.7.0-rc.0) with the configs and feature flags above
* Let the agent scrape metrics from node-exporter
* Check metrics received by Prometheus (i'm using [Promlens](https://github.com/prometheus/promlens))

### Expected Behavior

Metrics received by Prometheus should include type and unit labels, as described in [#17033](https://github.com/prometheus/prometheus/pull/17033)

### Problem
Type and unit labels don’t appear in Prometheus after being sent via remote-write v2

Image

### Environment
```bash
[root@exp-01 tmp]# cat /etc/os-release
NAME="AlmaLinux"
VERSION="9.6 (Sage Margay)"
```

Would you please confirm whether this feature is already fully implemented in the v2 remote-write receiver, or if additional flags/config are required on the receiving side?
Let me know if you’d like me to provide full debug logs or a test environment to reproduce the issue.

### PR DESCRIPTION
**Pull request by hxrshxz**
#### Which issue(s) does the PR fix:
Fixes #17319

#### Does this PR introduce a user-facing change?
```release-notes
[FEATURE] Remote-write: Type and unit labels are now correctly propagated to the Prometheus receiver when using Remote Write v2 with the `type-and-unit-labels` feature flag enabled.

### CODE REVIEW

File: storage/remote/write_handler.go [hunk 1]
```diff
@@ -417,6 +419,26 @@ func (h *writeHandler) appendV2(app storage.Appender, req *writev2.Request, rs *
 			samplesWithInvalidLabels += len(ts.Samples) + len(ts.Histograms)
 			continue
 		}
+
+		// Convert metadata once for both label addition and later UpdateMetadata call.
+		// ToMetadata() safely handles nil Metadata by returning default values (MetricTypeUnknown, empty strings).
+		// This avoids nil pointer dereference and redundant conversion work.
+		m := ts.ToMetadata(req.Symbols)
```
Comment (bwplotka) [inline storage/remote/write_handler.go:424]: should we use `AddToLabels` in some way for readability and consistency? https://github.com/prometheus/prometheus/blob/edbc5cfa06e1e199861474a8ab1d8f7753efbf61/schema/labels.go#L115

File: storage/remote/write_handler.go [hunk 2]
```diff
@@ -417,6 +419,26 @@ func (h *writeHandler) appendV2(app storage.Appender, req *writev2.Request, rs *
 			samplesWithInvalidLabels += len(ts.Samples) + len(ts.Histograms)
 			continue
 		}
+
+		// Convert metadata once for both label addition and later UpdateMetadata call.
+		// ToMetadata() safely handles nil Metadata by returning default values (MetricTypeUnknown, empty strings).
+		// This avoids nil pointer dereference and redundant conversion work.
```
Comment (bwplotka) [inline storage/remote/write_handler.go]: Perhaps too obvious code to comment, to skip?

```suggestion
```

File: storage/remote/write_handler.go [hunk 3]
```diff
@@ -535,7 +557,7 @@ func (h *writeHandler) appendV2(app storage.Appender, req *writev2.Request, rs *
 			h.logger.Error("failed to ingest exemplar, emitting error log, but no error for PRW caller", "err", err.Error(), "series", ls.String(), "exemplar", fmt.Sprintf("%+v", e))
 		}
 
-		m := ts.ToMetadata(req.Symbols)
+		// Metadata is converted once above and reused here for both label addition and UpdateMetadata to avoid redundant work.
```
Comment (bwplotka) [inline storage/remote/write_handler.go]: Self explanatory?
```suggestion
```

File: storage/remote/write_handler_type_unit_test.go [hunk 4]
```diff
@@ -0,0 +1,251 @@
...
+			handler.ServeHTTP(recorder, httpReq)
+
+			resp := recorder.Result()
+			body, err := io.ReadAll(resp.Body)
+			require.NoError(t, err)
+			require.Equal(t, http.StatusNoContent, resp.StatusCode, "response body: %s", string(body))
+
+			// Verify the labels
+			require.Len(t, appendable.samples, 1)
+			require.Equal(t, tc.expectedLabels, appendable.samples[0].l)
```
Comment (bwplotka) [inline storage/remote/write_handler_type_unit_test.go]: label comparisons require using [`testutil.RequireEqual`](https://github.com/prometheus/prometheus/blob/edbc5cfa06e1e199861474a8ab1d8f7753efbf61/util/testutil/cmp.go#L28)

File: storage/remote/write_handler_type_unit_test.go [hunk 5]
```diff
@@ -0,0 +1,251 @@
...
+
+	"github.com/prometheus/prometheus/config"
+	"github.com/prometheus/prometheus/model/labels"
+	"github.com/prometheus/prometheus/prompb"
+	writev2 "github.com/prometheus/prometheus/prompb/io/prometheus/write/v2"
+)
+
+// buildExpectedLabels constructs labels the same way as the write handler implementation
+// to ensure consistency across different labels implementations (stringlabels, dedupelabels).
+func buildExpectedLabels(metricName, labelName, labelValue string, metricType writev2.Metadata_MetricType, unit string) labels.Labels {
```
Comment (bwplotka) [inline storage/remote/write_handler_type_unit_test.go]: This is not ideal for testing -- complex expectation building can have bugs, so when things fail (or give false positive) it might be equally likely the expectation is broken. We generally prefer static expectations (e.g. hardcoded labels.FromString(....) evaluation).

See `TestRemoteWriteHandler_V2Message` (which we could expand instead of this file).

File: storage/remote/write_handler_type_unit_test.go [hunk 6]
```diff
@@ -0,0 +1,251 @@
...
+			lb.Set("__type__", typeStr)
+		}
+	}
+	if unit != "" {
+		lb.Set("__unit__", unit)
+	}
+	return lb.Labels()
+}
+
+func TestRemoteWriteHandler_TypeAndUnitLabels(t *testing.T) {
```
Comment (bwplotka) [inline storage/remote/write_handler_type_unit_test.go]: Why not expanding `TestRemoteWriteHandler_V2Message` instead?

File: storage/remote/write_handler.go (hunk 1 above)
Comment (bwplotka) [reply storage/remote/write_handler.go:424]: I hate to complain - it's better now with `AddToLabels` but honestly the better solution would be to add type and unit (optional) support (using `AddToLabels`) inside the `writev2` codec utils e.g `ts.ToLabels(&b, req.Symbols, h.typeAndUnitLabels)`

We could add TODO for this and add later, but otherwise this might be a bit expensive to use. WDYT?

**Comment by hxrshxz** [comment]
@bwplotka I  agree this adds some overhead Maybe we can merge this with the TODO for now and optimize ts.ToLabels() in a follow up. If that sounds good then I can raise a new issue for this and make the changes there?

**Comment by bwplotka** [comment]
👍🏽
