### PR TITLE
fix: add response closures to web_test.go

### LINKED ISSUE #9711: TestAgentAPIEndPoints test is broken
**What did you do?**

Executed `go test -short -failfast -count 10 ./web/` on revision 9fae120f2a6daa420530e44559c67ce27cb6e7eb.

**What did you expect to see?**

Test to pass.

**What did you see instead? Under which circumstances?**

```
$ go test -short -failfast -count 10 ./web/
http://localhost:9090/targets
--- FAIL: TestAgentAPIEndPoints (0.00s)
    web_test.go:602:
                Error Trace:    web_test.go:602
                Error:          Not equal:
                                expected: 200
                                actual  : 500
                Test:           TestAgentAPIEndPoints
FAIL
FAIL    github.com/prometheus/prometheus/web    15.060s
FAIL
```

Running built prometheus binary in agent mode and curl-ing gives the following:
```
$ curl -v localhost:9090/status; echo
*   Trying 127.0.0.1:9090...
* Connected to localhost (127.0.0.1) port 9090 (#0)
> GET /status HTTP/1.1
> Host: localhost:9090
> User-Agent: curl/7.79.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< Date: Wed, 10 Nov 2021 11:30:40 GMT
< Content-Length: 94
< Content-Type: text/plain; charset=utf-8
<
* Connection #0 to host localhost left intact
Error opening React index.html: open web/ui/static/react/index.html: no such file or directory
```

Same when adding some verbosity to tests:
```
$ go test -short -failfast -count 10 ./web/
--- FAIL: TestAgentAPIEndPoints (0.01s)
    --- FAIL: TestAgentAPIEndPoints//status (0.00s)
        web_test.go:613: for url: "http://localhost:39825/status"
        web_test.go:621: Error opening React index.html: open ui/static/react/index.html: no such file or directory
        web_test.go:613: for url: "http://localhost:39825/status"
        web_test.go:621: Error opening React index.html: open ui/static/react/index.html: no such file or directory
        web_test.go:613: for url: "http://localhost:39825/status"
        web_test.go:621: Error opening React index.html: open ui/static/react/index.html: no such file or directory
        web_test.go:613: for url: "http://localhost:39825/status"
        web_test.go:621: Error opening React index.html: open ui/static/react/index.html: no such file or directory
        web_test.go:613: for url: "http://localhost:39825/status"
        web_test.go:621: Error opening React index.html: open ui/static/react/index.html: no such file or directory
        web_test.go:613: for url: "http://localhost:39825/status"
        web_test.go:621: Error opening React index.html: open ui/static/react/index.html: no such file or directory
        web_test.go:613: for url: "http://localhost:39825/status"
        web_test.go:621: Error opening React index.html: open ui/static/react/index.html: no such file or directory
        web_test.go:613: for url: "http://localhost:39825/status"
        web_test.go:621: Error opening React index.html: open ui/static/react/index.html: no such file or directory
        web_test.go:613: for url: "http://localhost:39825/status"
        web_test.go:621: Error opening React index.html: open ui/static/react/index.html: no such file or directory
        web_test.go:613: for url: "http://localhost:39825/status"
        web_test.go:621: Error opening React index.html: open ui/static/react/index.html: no such file or directory
        web_test.go:624:
                Error Trace:    web_test.go:624
                Error:          Should be true
                Test:           TestAgentAPIEndPoints//status
    --- FAIL: TestAgentAPIEndPoints//targets (0.00s)
        web_test.go:613: for url: "http://localhost:39825/targets"
        web_test.go:621: Error opening React index.html: open ui/static/react/index.html: no such file or directory
        web_test.go:613: for url: "http://localhost:39825/targets"
        web_test.go:621: Error opening React index.html: open ui/static/react/index.html: no such file or directory
        web_test.go:613: for url: "http://localhost:39825/targets"
        web_test.go:621: Error opening React index.html: open ui/static/react/index.html: no such file or directory
        web_test.go:613: for url: "http://localhost:39825/targets"
        web_test.go:621: Error opening React index.html: open ui/static/react/index.html: no such file or directory
        web_test.go:613: for url: "http://localhost:39825/targets"
        web_test.go:621: Error opening React index.html: open ui/static/react/index.html: no such file or directory
        web_test.go:613: for url: "http://localhost:39825/targets"
        web_test.go:621: Error opening React index.html: open ui/static/react/index.html: no such file or directory
        web_test.go:613: for url: "http://localhost:39825/targets"
        web_test.go:621: Error opening React index.html: open ui/static/react/index.html: no such file or directory
        web_test.go:613: for url: "http://localhost:39825/targets"
        web_test.go:621: Error opening React index.html: open ui/static/react/index.html: no such file or directory
        web_test.go:613: for url: "http://localhost:39825/targets"
        web_test.go:621: Error opening React index.html: open ui/static/react/index.html: no such file or directory
        web_test.go:613: for url: "http://localhost:39825/targets"
        web_test.go:621: Error opening React index.html: open ui/static/react/index.html: no such file or directory
        web_test.go:624:
                Error Trace:    web_test.go:624
                Error:          Should be true
                Test:           TestAgentAPIEndPoints//targets
FAIL
FAIL    github.com/prometheus/prometheus/web    15.094s
FAIL
```

### PR DESCRIPTION
**Pull request by mtfoley**
I believe This PR resolves #9711.
When running `go test -short -failfast -count 10 ./web/`, I encountered an error about TCP dialing.  This was the original reproduction step in the issue.
```
--- FAIL: TestAgentAPIEndPoints (5.04s)
    web_test.go:555: 
        	Error Trace:	web_test.go:555
        	Error:      	Received unexpected error:
        	            	Get "http://localhost:65296/api/v1/label/:name/values": dial tcp: lookup localhost: no such host
        	Test:       	TestAgentAPIEndPoints
FAIL
FAIL	github.com/prometheus/prometheus/web	108.291s
FAIL
```
Reading up about this error on https://stackoverflow.com/questions/26228163/localhost-no-such-host-after-250-connections-in-go-when-using-responsewriter, I tried adding `resp.Body.Close()` to a few of the loops where the utility function `cleanupTestResponse()` wasn't used.

I also ran this test on the main branch: `go test -short -failfast -count 10 -test.v  -run TestAgentAPIEndPoints ./web/`, and I got errors like this one.  This tests case was a secondary reproduction mentioned in the issue.
```
=== RUN   TestAgentAPIEndPoints
=== PAUSE TestAgentAPIEndPoints
=== CONT  TestAgentAPIEndPoints
    web_test.go:573: 
        	Error Trace:	web_test.go:573
        	Error:      	Received unexpected error:
        	            	Get "http://localhost:49220/api/v1/targets/metadata": EOF
        	Test:       	TestAgentAPIEndPoints
--- FAIL: TestAgentAPIEndPoints (5.05s)
```
When I run the same on the feature branch, the tests pass.

### CODE REVIEW

File: web/web_test.go [hunk 1]
```diff
@@ -554,6 +554,7 @@ func TestAgentAPIEndPoints(t *testing.T) {
 			resp, err := http.DefaultClient.Do(req)
 			require.NoError(t, err)
```
Comment (roidelapluie) [inline web/web_test.go:555]:
```suggestion
			require.NoError(t, err)
			t.Cleanup(resp.Body.Close)
```

**Comment by mtfoley** [comment]
@roidelapluie i think I’ve got your suggested changes implemented.

**Comment by roidelapluie** [comment]
Thanks!
