### PR TITLE
web/ui: avoid truncated Y-axis values

### LINKED ISSUE #6013: Y-axis tick labels are truncated for very small/large values
## Bug Report
**What did you do?**
Graph a single timeseries with a high value (eg `prometheus_tsdb_lowest_timestamp{pod="prometheus-k8s-0"}`)

**What did you expect to see?**

Y-axis values not being truncated.

**What did you see instead? Under which circumstances?**

image

**Environment**

* System information:

Linux 5.2.9-200.fc30.x86_64 x86_64

* Prometheus version:

prometheus, version 2.12.0 (branch: master, revision: 58866f083d640b382df0c003d9e14156a12b2e09)
  build user:       simon@simon-laptop
  build date:       20190911-09:44:58
  go version:       go1.13

* Alertmanager version:

n/a

* Prometheus configuration file:

n/a

* Alertmanager configuration file:

n/a

* Logs:

n/a

### PR DESCRIPTION
**Pull request by simonpasquier**
Closes #6013 

image

### CODE REVIEW

File: web/ui/static/js/graph/index.js [hunk 1]
```diff
@@ -738,13 +738,9 @@ Prometheus.Graph.prototype.updateGraph = function() {
...
       });
     });
-    if (min === max) {
-      self.rickshawGraph.max = max + 1;
-      self.rickshawGraph.min = min - 1;
-    } else {
-      self.rickshawGraph.max = max + (0.1*(Math.abs(max - min)));
-      self.rickshawGraph.min = min - (0.1*(Math.abs(max - min)));
-    }
+    var offset = 0.1 * (min === max ? max : Math.abs(max-min))
```
Comment (brian-brazil) [inline web/ui/static/js/graph/index.js]: Missing semicolon

Comment (simonpasquier) [reply web/ui/static/js/graph/index.js]: this shows my Javascript skills ;-)
